#!/usr/bin/env node
// 012_ccus_ontology.mjs — populates the ontology layer with the
// Industrial CCUS worked example for Shell.
//
// Per /docs/methodology/ontology_population_procedure.md:
//   Step 1 — pair identification from Shell CCUS components
//   Step 2 — source classification (evidence per pair)
//   Step 3 — horizon classification per rubric
//   Step 4 — adjacency identification (>=2 per pair)
//   Step 5 — linkage to client components
//   Step 6 — confidence band + analyst-review flagging
//   Step 7 — self-marking output
//
// Idempotent against re-runs. Transactional. --commit --confirm-yes to persist.

import { readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const __dirname = dirname(fileURLToPath(import.meta.url));
async function loadEnv(p) {
  if (!existsSync(p)) return;
  const raw = await readFile(p, 'utf8');
  for (const line of raw.split(/\r?\n/)) {
    const t = line.trim(); if (!t || t.startsWith('#')) continue;
    const eq = t.indexOf('='); if (eq < 0) continue;
    const k = t.slice(0, eq).trim();
    const v = t.slice(eq + 1).trim().replace(/^["']|["']$/g, '');
    if (!process.env[k]) process.env[k] = v;
  }
}
await loadEnv(join(__dirname, '..', '.env'));
await loadEnv(join(__dirname, '..', '..', 'n8n', '.env'));

const args = process.argv.slice(2);
const COMMIT = args.includes('--commit');
const CONFIRM = args.includes('--confirm-yes');
const WILL_COMMIT = COMMIT && CONFIRM;
if (COMMIT && !CONFIRM) { console.error('--commit requires --confirm-yes'); process.exit(1); }

const client = new pg.Client({ connectionString: process.env.DATABASE_URL });
await client.connect();
console.log(`=== Population — CCUS ontology ===  Mode: ${WILL_COMMIT ? 'COMMIT' : 'DRY-RUN'}`);

// ============================================================================
// Data definitions
// ============================================================================

// 7 technologies covering the CCUS domain
const TECHNOLOGIES = [
  {
    name: 'post_combustion_amine_capture',
    label: 'Post-combustion amine capture',
    tech_function: 'industrial_post_combustion_co2_capture',
    description: 'CO2 absorbed from flue gas by amine solvent (MEA, MDEA, sterically hindered amines, CANSOLV DC-103); regenerated by heat to release concentrated CO2 stream. Mature commercial technology with multiple FOAK and 1.0+ Mtpa industrial deployments.',
    current_trl: 9,
    trl_as_of_date: '2024-12-31',
    cost_trajectory_pct_yoy: -3,
    cost_trajectory_unit: 'pct_per_year_capex',
    substitution_risk: 'emerging',
    source_citation: 'IEAGHG CCS Cost Network 2024; Global CCS Institute Status Report 2024',
  },
  {
    name: 'post_combustion_solvent_next_gen',
    label: 'Post-combustion next-gen solvent capture',
    tech_function: 'industrial_post_combustion_co2_capture',
    description: 'Advanced solvent capture systems beyond first-generation amines: water-lean solvents, phase-change solvents, encapsulated liquid sorbents, KM-CDR (Mitsubishi), CANSOLV S5 (Shell). Aim is 30-50% energy penalty reduction vs MEA at equivalent capture rate. Pilot to FOAK commercial.',
    current_trl: 7,
    trl_as_of_date: '2024-12-31',
    cost_trajectory_pct_yoy: -8,
    cost_trajectory_unit: 'pct_per_year_capex',
    substitution_risk: 'none',
    source_citation: 'IEAGHG technology readiness review 2024; DOE NETL Solvent Capture Program 2024',
  },
  {
    name: 'pre_combustion_capture',
    label: 'Pre-combustion CO2 capture',
    tech_function: 'smr_with_ccs_blue_hydrogen',
    description: 'CO2 separated upstream of combustion via gasification or steam reforming + water-gas shift, producing high-pressure CO2 stream and H2-rich syngas. Mature in industrial gas processing (LNG sweetening, ammonia production for decades) and emerging at commercial scale for blue H2 industrial decarbonisation.',
    current_trl: 9,
    trl_as_of_date: '2024-12-31',
    cost_trajectory_pct_yoy: -2,
    cost_trajectory_unit: 'pct_per_year_capex',
    substitution_risk: 'emerging',
    source_citation: 'IEA Hydrogen Roadmap 2024; IEAGHG pre-combustion review 2024',
  },
  {
    name: 'oxyfuel_combustion',
    label: 'Oxyfuel combustion capture',
    tech_function: 'industrial_post_combustion_co2_capture',
    description: 'Combustion with pure oxygen rather than air, producing flue gas of mostly CO2 and H2O — water condensation yields concentrated CO2 stream without solvent. Allam cycle (NET Power) for power; pilot scale for cement and industrial.',
    current_trl: 7,
    trl_as_of_date: '2024-12-31',
    cost_trajectory_pct_yoy: -5,
    cost_trajectory_unit: 'pct_per_year_capex',
    substitution_risk: 'none',
    source_citation: 'NET Power Allam cycle disclosures 2024; IEAGHG oxyfuel review 2023',
  },
  {
    name: 'direct_air_capture',
    label: 'Direct air capture',
    tech_function: null,
    description: 'CO2 removed from ambient air using sorbents (solid amine on porous structure, e.g. Climeworks; aqueous KOH followed by Ca-cycle, e.g. Carbon Engineering) at ~400ppm intake. Pilot to FOAK commercial. Cost trajectory contested: operators claim aggressive trajectory; peer-reviewed analysis shows slower decline.',
    current_trl: 7,
    trl_as_of_date: '2024-12-31',
    cost_trajectory_pct_yoy: -10,
    cost_trajectory_unit: 'pct_per_year_capex_operator_claimed',
    substitution_risk: 'none',
    source_citation: 'Climeworks operator disclosures 2024; Carbon Engineering Stratos progress reports 2024; IEA CCUS Roadmap 2024',
  },
  {
    name: 'mineral_carbonation',
    label: 'Mineral carbonation',
    tech_function: null,
    description: 'CO2 reacted with metal oxides (Mg, Ca silicates) to form stable carbonate minerals. Permanent storage but slow kinetics; pilot scale only. Examples: Carbfix (Iceland, basalt injection — at the boundary between in-situ mineralisation and conventional storage), 44.01 (Oman), Heirloom-Carbfix integration.',
    current_trl: 5,
    trl_as_of_date: '2024-12-31',
    cost_trajectory_pct_yoy: null,
    cost_trajectory_unit: null,
    substitution_risk: 'none',
    source_citation: 'Carbfix project disclosures 2024; 44.01 operator updates 2024; IEAGHG mineralisation review 2023',
  },
  {
    name: 'biological_capture',
    label: 'Biological CO2 capture',
    tech_function: null,
    description: 'Algae bioreactors, engineered microorganisms, ocean alkalinity enhancement, BECCS (bioenergy with CCS). Mostly research-to-demonstration scale; BECCS the most commercial-adjacent variant via existing biomass plants.',
    current_trl: 4,
    trl_as_of_date: '2024-12-31',
    cost_trajectory_pct_yoy: null,
    cost_trajectory_unit: null,
    substitution_risk: 'none',
    source_citation: 'IEA Bioenergy Task 41 2023; DOE Office of Fossil Energy biological CCS portfolio 2024',
  },
];

// 5 applications
const APPLICATIONS = [
  {
    name: 'industrial_point_source_decarbonisation',
    label: 'Industrial point-source decarbonisation',
    domain: 'industrial',
    description: 'Capture of CO2 from industrial flue stacks of cement, steel, refining, chemicals, and high-purity gas streams — followed by transport and permanent geological storage. Subsidy-dependent in current price environment; FOAK commercial deployments operating.',
    market_maturity: 'emerging',
    source_citation: 'Global CCS Institute Status Report 2024; IEA CCUS Roadmap 2024',
  },
  {
    name: 'power_sector_decarbonisation',
    label: 'Power-sector decarbonisation',
    domain: 'power',
    description: 'Capture of CO2 from coal- or gas-fired electricity generation. Largely uncommercial against renewables-plus-storage at current carbon prices; Boundary Dam (SK) operating, Petra Nova (TX) mothballed. Allam cycle (NET Power) is the active novel-technology variant.',
    market_maturity: 'frontier',
    source_citation: 'IEA World Energy Outlook 2024; SaskPower Boundary Dam annual disclosures 2024',
  },
  {
    name: 'cdr_voluntary_market',
    label: 'Carbon dioxide removal — voluntary market',
    domain: 'cross_domain',
    description: 'Removal of CO2 from atmosphere or ocean for voluntary corporate net-zero compliance, sold via CDR purchase agreements at $300-1000+/t. Demand contingent on continued voluntary market deepening; Microsoft, Google, Stripe, Frontier as principal anchor buyers.',
    market_maturity: 'emerging',
    source_citation: 'CDR.fyi market tracker 2024; Frontier Climate purchase commitments disclosure 2024',
  },
  {
    name: 'enhanced_oil_recovery',
    label: 'Enhanced oil recovery (EOR)',
    domain: 'industrial',
    description: 'Injection of CO2 into mature oil reservoirs to mobilise residual oil. Long-running commercial application (US Permian, Gulf Coast since 1970s); subsidy-supported in US (45Q EOR rate $60/t). Increasingly de-coupled from "decarbonisation" framing as analyst frameworks separate EOR from removal.',
    market_maturity: 'mature',
    source_citation: 'EIA US EOR Statistics 2024; IRS 45Q EOR provisions',
  },
  {
    name: 'industrial_gas_processing',
    label: 'Industrial gas processing (sweetening, separation, ammonia)',
    domain: 'industrial',
    description: 'CO2 separation as part of natural gas sweetening for LNG export, ammonia synthesis, hydrogen production for refining. Decades of commercial operation at scale; CO2 typically vented but increasingly captured for storage or use as input. Mature commercial technology.',
    market_maturity: 'mature',
    source_citation: 'IEA Natural Gas Information 2024; IFA ammonia production statistics 2024',
  },
];

// 9 pairs covering meaningful CCUS technology x application combinations
const PAIRS = [
  {
    label: 'Post-combustion amine capture × industrial point-source decarbonisation',
    technology: 'post_combustion_amine_capture',
    application: 'industrial_point_source_decarbonisation',
    horizon: 'H2',
    horizon_reasoning: 'FOAK commercial operating (Quest 2015 1.0 Mtpa, Northern Lights phase 1 2024 1.5 Mtpa, multiple FIDs 2026-2030 in UK CCS clusters). Cost trajectory clear (capex declining ~3% YoY per IEAGHG; capture cost $60-90/t industrial). Subsidy-dependent (45Q $85/t US, UK CCS CfD, Norwegian Longship state backing). Regulatory frameworks (ETS, 45Q, CCS CfD) in force or late-stage development. H2 markers: FOAK operational, FIDs being considered, subsidy material but expected to remain through commercial transition.',
    confidence: 'high',
    confidence_reasoning: '4 evidence rows (IEAGHG industry_body high; Global CCS Institute industry_body high; Quest annual disclosure company_filing high; Northern Lights operator_disclosure high). Cross-source agreement on cost, scale, and trajectory.',
    trajectory: 'improving',
    trajectory_reasoning: 'Capacity coming online accelerating (UK clusters HyNet, East Coast, Acorn FID 2024-2026); cost declining; cross-border CO2 transport rules clarifying.',
    flag: false,
  },
  {
    label: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    technology: 'post_combustion_solvent_next_gen',
    application: 'industrial_point_source_decarbonisation',
    horizon: 'H3',
    horizon_reasoning: 'KM-CDR (Mitsubishi) and CANSOLV S5 (Shell) at FOAK commercial demonstration; energy-penalty reduction promising but field validation incomplete. Cost trajectory aspirational; commercial parity beyond 5-year window because incumbents (first-gen amines) maintain operational learning advantage. H3 markers: technology demonstrated but not at commercial scale; cost trajectory unclear at current price points.',
    confidence: 'medium',
    confidence_reasoning: '3 evidence rows (IEAGHG industry_body medium; DOE NETL government_data high; Mitsubishi KM-CDR operator_disclosure medium). Operator claims of cost-trajectory not yet field-validated; supports the H3 placement but not a high-confidence call.',
    trajectory: 'improving',
    trajectory_reasoning: 'DOE NETL programme funding and KM-CDR/CANSOLV deployments expanding; expect material trajectory improvement next 24-36 months.',
    flag: false,
  },
  {
    label: 'Pre-combustion capture × industrial gas processing',
    technology: 'pre_combustion_capture',
    application: 'industrial_gas_processing',
    horizon: 'H1',
    horizon_reasoning: 'Standard practice in LNG sweetening and ammonia production for 40+ years; commercial deployments globally at scale (Sleipner 1996 onwards, every LNG export terminal, every ammonia plant). Capital flows without subsidy gating — this is base industrial economics. H1 markers: ≥3 independent commercial-scale deployments; capital flowing without subsidy; standardised contracts; regulatory frameworks in force.',
    confidence: 'high',
    confidence_reasoning: '3 evidence rows (IEA Natural Gas Information government_data high; IFA ammonia statistics industry_body high; Equinor Sleipner historical operator_disclosure high). Hard data confirms scale and longevity.',
    trajectory: 'holding',
    trajectory_reasoning: 'Mature application; new growth at the margin from CO2-utilisation rather than expansion of base practice.',
    flag: false,
  },
  {
    label: 'Pre-combustion capture × industrial point-source decarbonisation',
    technology: 'pre_combustion_capture',
    application: 'industrial_point_source_decarbonisation',
    horizon: 'H2',
    horizon_reasoning: 'Blue hydrogen industrial decarbonisation pathway: SMR + WGS + CCS for H2 supplied to refining, chemicals, steel. HyNet (UK), H21 North of England, Equinor H2H Saltend at FID or near-FID 2024-2026. Cost competitiveness vs green H2 dependent on gas prices and 45V/EU Hydrogen Bank treatment. H2 markers: FOAK at FID stage; regulatory frameworks (45V, EU Hydrogen Bank) in force; subsidy material and expected to remain.',
    confidence: 'medium',
    confidence_reasoning: '3 evidence rows (IEA Hydrogen Roadmap industry_body high; UK DESNZ HyNet government_data high; Equinor H2H Saltend operator_disclosure medium). Some uncertainty on lifecycle methane emissions accounting which can flip 45V eligibility.',
    trajectory: 'volatile',
    trajectory_reasoning: 'IRA 45V final guidance March 2024 narrowed eligibility, partial reversal. EU Hydrogen Bank pricing variable. Trajectory volatile until regulatory accounting stabilises.',
    flag: false,
  },
  {
    label: 'Direct air capture × CDR voluntary market',
    technology: 'direct_air_capture',
    application: 'cdr_voluntary_market',
    horizon: 'H3',
    horizon_reasoning: 'Pilot to FOAK commercial (Climeworks Orca 4 ktpa, Mammoth 36 ktpa; Carbon Engineering Stratos pre-commissioning 500 ktpa). Demand structurally contingent on voluntary CDR market deepening; cost ~$600-1000/t with operator-claimed trajectory toward $200-400/t contested by peer-reviewed analysis. H3 markers: technology demonstrated but not at commercial scale; cost trajectory unclear; demand contingent on conditions not yet materialised.',
    confidence: 'medium',
    confidence_reasoning: '4 evidence rows (Climeworks operator_disclosure medium; Carbon Engineering operator_disclosure medium; IEA CCUS Roadmap industry_body high; Frontier Climate purchase commitments operator_disclosure high). Conflict on cost trajectory between operator-claimed and IEA/peer-reviewed; flagging discipline applied below.',
    trajectory: 'improving',
    trajectory_reasoning: 'Frontier $1bn+ commitment locking in offtake; Microsoft and Google as anchor buyers; FOAK commercial scale-up underway. But trajectory could weaken if voluntary CDR demand softens.',
    flag: false,
  },
  {
    label: 'Mineral carbonation × CDR voluntary market',
    technology: 'mineral_carbonation',
    application: 'cdr_voluntary_market',
    horizon: 'H3',
    horizon_reasoning: 'Pilot scale only — Carbfix (Iceland) at 12 ktpa, 44.01 (Oman) at pilot, Heirloom-Carbfix integration emerging. Permanent storage credentials very strong but throughput and cost barriers material. H3 markers: technology demonstrated but not at commercial scale; cost trajectory unclear; market structure contingent on voluntary CDR demand.',
    confidence: 'low',
    confidence_reasoning: 'Only 2 evidence rows from operator_disclosure and industry_body categories; no peer-reviewed cost analysis at the pair level; no government_data or company_filing rows. Insufficient evidence diversity for medium confidence.',
    trajectory: 'improving',
    trajectory_reasoning: 'Capacity expansions announced at Carbfix and 44.01; Heirloom integrating mineralisation as permanence path; trajectory improving but from very low base.',
    flag: true,
    flag_reason: 'low confidence: only operator-disclosure and industry-body evidence; no peer-reviewed or government data; cost claims not independently validated. Re-run Step 2 with peer-reviewed cost analysis (DOE NETL mineralisation review or equivalent).',
  },
  {
    label: 'Post-combustion amine capture × power-sector decarbonisation',
    technology: 'post_combustion_amine_capture',
    application: 'power_sector_decarbonisation',
    horizon: 'H3',
    horizon_reasoning: 'Boundary Dam (SK) operating since 2014 but persistent capture-rate underperformance (~65% vs 90% design); Petra Nova (TX) mothballed 2020 due to oil-price-linked economics. No new FIDs against retrofit or new-build coal-CCS at commercial scale. Renewables-plus-storage outcompetes at current carbon prices. H3 markers: applications speculative or pre-FID at scale; cost trajectory unfavourable at current price points; market demand contingent on conditions not materialised (high carbon price).',
    confidence: 'medium',
    confidence_reasoning: '3 evidence rows (SaskPower Boundary Dam company_filing high; IEA WEO 2024 industry_body high; Petra Nova mothballing news/operator high). Hard data on poor outcomes; horizon assignment defensible.',
    trajectory: 'weakening',
    trajectory_reasoning: 'No new commercial FIDs in development; renewables-plus-storage cost trajectory making power-sector CCS structurally uncompetitive; outlook for revival contingent on $150+/t carbon prices not currently in play.',
    flag: false,
  },
  {
    label: 'Post-combustion amine capture × enhanced oil recovery',
    technology: 'post_combustion_amine_capture',
    application: 'enhanced_oil_recovery',
    horizon: 'H1',
    horizon_reasoning: 'Long-running commercial application (Permian, Gulf Coast since 1970s); standardised contracts; capital flowing without subsidy gating (45Q EOR rate is $60/t but EOR economics work without it at appropriate oil prices). H1 markers: ≥3 independent commercial-scale deployments; FIDs operating; capital flowing; regulatory frameworks (45Q EOR) in force.',
    confidence: 'high',
    confidence_reasoning: '3 evidence rows (EIA US EOR Statistics government_data high; IRS 45Q EOR provisions government_data high; ExxonMobil LaBarge operator_disclosure high).',
    trajectory: 'volatile',
    trajectory_reasoning: 'Activity tracks oil price and 45Q political durability; recent IRA-repeal scenarios introduce material political volatility. H1 with volatile trajectory triggers Step 6 flagging rule.',
    flag: true,
    flag_reason: 'H1 with volatile trajectory — re-classify against horizon rubric within 90 days. Political-durability concerns on 45Q + oil-price linkage make trajectory genuinely volatile but the pair remains commercially in operation (true H1). Worth checking whether the volatility actually warrants H2 demotion or whether trajectory captures it.',
  },
  {
    label: 'Oxyfuel combustion × industrial point-source decarbonisation',
    technology: 'oxyfuel_combustion',
    application: 'industrial_point_source_decarbonisation',
    horizon: 'H3',
    horizon_reasoning: 'NET Power Allam cycle La Porte demonstration ~50 MW (gas); cement-sector oxyfuel at pilot (Heidelberg Brevik post-combustion not oxyfuel; oxyfuel cement at FEED stage). FOAK commercial-scale industrial oxyfuel pre-FID. H3 markers: technology demonstrated but not at commercial scale; FOAK projects struggling to FID; cost trajectory unclear.',
    confidence: 'medium',
    confidence_reasoning: '2 evidence rows (NET Power operator_disclosure medium; IEAGHG oxyfuel review industry_body medium). Limited peer-reviewed at the application-pair level.',
    trajectory: 'holding',
    trajectory_reasoning: 'NET Power scaling commercial demonstration but no broad industrial uptake; outlook depends on FOAK commercial commissioning by 2027.',
    flag: false,
  },
];

// Evidence per pair
const EVIDENCE = [
  // post_combustion_amine × industrial_point_source
  { pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'industry_body', strength: 'high', supports: 'H2',
    text: 'CCUS services market growing 20-30% CAGR through 2030 if current pipeline converts; 50+ projects with 45Q elections; FOAK commercial scale-up underway with capture capex declining ~2-5% YoY for amine technology.',
    citation: 'Global CCS Institute Status Report 2024',
    url: 'https://www.globalccsinstitute.com/resources/global-status-of-ccs-report-2024/',
    publication_date: '2024-11-01' },
  { pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'industry_body', strength: 'high', supports: 'H2',
    text: 'IEAGHG cost network: capture capex ~$60-90/t CO2 for industrial-scale; capture-as-a-service pricing $80-120/t; declining ~3% YoY for first-gen amine.',
    citation: 'IEAGHG CCS Cost Network 2024',
    url: 'https://ieaghg.org/publications/technical-reports',
    publication_date: '2024-09-01' },
  { pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'company_filing', strength: 'high', supports: 'H2',
    text: 'Quest CCS (Shell, Alberta) operational since 2015 at 1.0 Mtpa; cumulative >9 Mt CO2 stored; commercial-scale FOAK confirming amine capture at industrial point-source.',
    citation: 'Shell Quest annual disclosures 2015-2024',
    url: 'https://www.shell.ca/en_ca/about-us/projects-and-sites/quest-carbon-capture-and-storage-project.html',
    publication_date: '2024-12-01' },
  { pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'operator_disclosure', strength: 'high', supports: 'H2',
    text: 'Northern Lights phase 1 (Equinor + Shell + TotalEnergies) commenced operations 2024 at 1.5 Mtpa industrial-scale capture-and-store; phase 2 expansion to 5 Mtpa at FID stage 2025.',
    citation: 'Northern Lights consortium technical disclosures 2024',
    url: 'https://norlights.com/news-and-media/',
    publication_date: '2024-09-01' },

  // post_combustion_solvent_next_gen × industrial_point_source
  { pair: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    type: 'industry_body', strength: 'medium', supports: 'H3',
    text: 'IEAGHG technology readiness: water-lean solvents and phase-change solvents at TRL 6-7; commercial demonstration pending; energy-penalty reduction 30-50% claimed but field-validated only at pilot scale.',
    citation: 'IEAGHG technology readiness review 2024',
    url: 'https://ieaghg.org/publications/technical-reports',
    publication_date: '2024-06-01' },
  { pair: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    type: 'government_data', strength: 'high', supports: 'H3',
    text: 'DOE NETL Solvent Capture Program 2024 portfolio: 8 active solvent development projects funded $300m+ across 2022-2024; commercial parity target 2030+.',
    citation: 'DOE NETL Carbon Capture Solvent Program 2024',
    url: 'https://netl.doe.gov/carbon-capture',
    publication_date: '2024-08-01' },
  { pair: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    type: 'operator_disclosure', strength: 'medium', supports: 'H3',
    text: 'Mitsubishi KM-CDR Process at FOAK commercial deployment (Petra Nova revival, Linde-Mitsubishi Heavy Industries partnerships); CANSOLV (Shell) S5 next-gen at SaskPower BD3 retrofit study.',
    citation: 'Mitsubishi Heavy Industries KM-CDR product brochure 2024',
    url: 'https://power.mhi.com/products/kmcdr',
    publication_date: '2024-04-01' },

  // pre_combustion × industrial_gas_processing
  { pair: 'Pre-combustion capture × industrial gas processing',
    type: 'government_data', strength: 'high', supports: 'H1',
    text: 'IEA: every operating LNG export facility uses amine sweetening with CO2 separation; ammonia production globally requires CO2 separation post-WGS — base practice at >180 Mt NH3/yr scale.',
    citation: 'IEA Natural Gas Information 2024',
    url: 'https://www.iea.org/reports/natural-gas-information-overview',
    publication_date: '2024-07-01' },
  { pair: 'Pre-combustion capture × industrial gas processing',
    type: 'industry_body', strength: 'high', supports: 'H1',
    text: 'IFA: 180+ Mt/yr ammonia production globally with CO2 stripping at every facility; commercial since 1913 (Haber-Bosch).',
    citation: 'IFA Ammonia Production Statistics 2024',
    url: 'https://www.ifastat.org/',
    publication_date: '2024-06-01' },
  { pair: 'Pre-combustion capture × industrial gas processing',
    type: 'operator_disclosure', strength: 'high', supports: 'H1',
    text: 'Equinor Sleipner gas sweetening + CO2 storage in Utsira formation since 1996 — 28 years continuous operation captures >20 Mt CO2 from base LNG processing.',
    citation: 'Equinor Sleipner historical disclosure 2024',
    url: 'https://www.equinor.com/energy/carbon-capture-utilisation-and-storage',
    publication_date: '2024-09-01' },

  // pre_combustion × industrial_point_source
  { pair: 'Pre-combustion capture × industrial point-source decarbonisation',
    type: 'industry_body', strength: 'high', supports: 'H2',
    text: 'IEA Hydrogen Roadmap: blue H2 production 1-2 Mt/yr operating today via SMR+CCS (mostly North America Quest, ATR-CCS pilot Saudi); 8-12 Mt/yr expected operational by 2030 driven by industrial decarbonisation demand.',
    citation: 'IEA Hydrogen Roadmap 2024',
    url: 'https://www.iea.org/reports/global-hydrogen-review-2024',
    publication_date: '2024-10-01' },
  { pair: 'Pre-combustion capture × industrial point-source decarbonisation',
    type: 'government_data', strength: 'high', supports: 'H2',
    text: 'UK DESNZ HyNet North West cluster: 4.5 Mtpa CO2 capture from blue H2 production for refining, chemicals, glass; FID 2024-2025 with operations 2027-2028.',
    citation: 'UK DESNZ Cluster Sequencing Update 2024',
    url: 'https://www.gov.uk/government/publications/cluster-sequencing-for-carbon-capture-usage-and-storage',
    publication_date: '2024-08-01' },
  { pair: 'Pre-combustion capture × industrial point-source decarbonisation',
    type: 'operator_disclosure', strength: 'medium', supports: 'H2',
    text: 'Equinor H2H Saltend (Humber UK): 0.6 Mtpa CO2 capture from ATR + CCS for industrial H2; pre-FID 2024 awaiting 45V-equivalent UK CCUS support frameworks.',
    citation: 'Equinor H2H Saltend project page 2024',
    url: 'https://www.equinor.com/energy/h2h-saltend',
    publication_date: '2024-10-01' },

  // dac × cdr_voluntary
  { pair: 'Direct air capture × CDR voluntary market',
    type: 'operator_disclosure', strength: 'medium', supports: 'H3',
    text: 'Climeworks: Orca (Iceland 4 ktpa) operational 2021; Mammoth (Iceland 36 ktpa) operational 2024; cost ~$600-1000/t with stated path to $300-400/t by 2030 contingent on Generation 3 sorbent and scale.',
    citation: 'Climeworks operator disclosures 2024',
    url: 'https://climeworks.com/news',
    publication_date: '2024-05-01' },
  { pair: 'Direct air capture × CDR voluntary market',
    type: 'operator_disclosure', strength: 'medium', supports: 'H3',
    text: 'Carbon Engineering Stratos (Texas) pre-commissioning 2025 at 500 ktpa nameplate; Occidental partnership; FOAK commercial scale-up against contested cost claims.',
    citation: 'Carbon Engineering Stratos project updates 2024',
    url: 'https://carbonengineering.com/news/',
    publication_date: '2024-08-01' },
  { pair: 'Direct air capture × CDR voluntary market',
    type: 'industry_body', strength: 'high', supports: 'H3',
    text: 'IEA: DAC global capacity ~10 ktpa operational 2024; cumulative committed capacity ~5 Mtpa by 2030 if all announced projects deliver. Cost trajectory: IEA models slower decline than operators claim — $400-600/t commercial floor 2030 vs operator $200-400/t.',
    citation: 'IEA CCUS Roadmap 2024',
    url: 'https://www.iea.org/reports/ccus-projects-explorer',
    publication_date: '2024-09-01' },
  { pair: 'Direct air capture × CDR voluntary market',
    type: 'operator_disclosure', strength: 'high', supports: 'H3',
    text: 'Frontier Climate (Stripe-led $1bn+ CDR purchase commitment) signing offtake at $300-1000/t for DAC; demand-side anchoring durable for the H3 horizon though contingent on continued voluntary market.',
    citation: 'Frontier Climate purchase commitments disclosure 2024',
    url: 'https://frontierclimate.com/portfolio',
    publication_date: '2024-10-01' },

  // mineral_carbonation × cdr_voluntary
  { pair: 'Mineral carbonation × CDR voluntary market',
    type: 'operator_disclosure', strength: 'medium', supports: 'H3',
    text: 'Carbfix (Iceland) operational mineralisation in basalt: 12 ktpa current; expansion to 100+ ktpa announced via Coda Terminal; cost claimed $25-50/t CO2 for mineralisation step (excludes capture).',
    citation: 'Carbfix project disclosures 2024',
    url: 'https://www.carbfix.com/about-us',
    publication_date: '2024-06-01' },
  { pair: 'Mineral carbonation × CDR voluntary market',
    type: 'industry_body', strength: 'medium', supports: 'H3',
    text: 'IEAGHG mineralisation review: ex-situ mineralisation TRL 4-6 globally; permanence credentials very strong; throughput and cost barriers material at scale.',
    citation: 'IEAGHG mineralisation review 2023',
    url: 'https://ieaghg.org/publications/technical-reports',
    publication_date: '2023-11-01' },

  // post_combustion_amine × power_sector
  { pair: 'Post-combustion amine capture × power-sector decarbonisation',
    type: 'company_filing', strength: 'high', supports: 'H3',
    text: 'SaskPower Boundary Dam Unit 3: 1.0 Mtpa nameplate capture, operational 2014; persistent underperformance (~65% capture rate vs 90% design). No new commercial-scale coal-CCS power FIDs since.',
    citation: 'SaskPower Boundary Dam annual disclosure 2024',
    url: 'https://www.saskpower.com/our-power-future/our-electricity/electrical-system/system-map/boundary-dam-power-station',
    publication_date: '2024-08-01' },
  { pair: 'Post-combustion amine capture × power-sector decarbonisation',
    type: 'industry_body', strength: 'high', supports: 'H3',
    text: 'IEA WEO 2024: power-sector CCS cost-uncompetitive against renewables-plus-storage at <$150/t carbon prices; no new FIDs in pipeline for retrofit or new-build coal-CCS in OECD.',
    citation: 'IEA World Energy Outlook 2024',
    url: 'https://www.iea.org/reports/world-energy-outlook-2024',
    publication_date: '2024-10-01' },
  { pair: 'Post-combustion amine capture × power-sector decarbonisation',
    type: 'operator_disclosure', strength: 'high', supports: 'H3',
    text: 'Petra Nova (NRG-JX Nippon, Texas): mothballed 2020 after oil-price-linked CO2-EOR economics collapsed; restart explored 2023-2024 with KM-CDR retrofit study but pre-FID.',
    citation: 'NRG Energy Petra Nova disclosures 2020-2024',
    url: 'https://www.nrg.com/sustainability/highlights/petra-nova.html',
    publication_date: '2024-04-01' },

  // post_combustion_amine × eor
  { pair: 'Post-combustion amine capture × enhanced oil recovery',
    type: 'government_data', strength: 'high', supports: 'H1',
    text: 'EIA: US CO2-EOR production ~280 kbpd from ~140 fields, 80%+ Permian + Gulf Coast; cumulative CO2 utilisation 60+ Mt/yr; long-running commercial application since 1972.',
    citation: 'EIA US EOR Statistics 2024',
    url: 'https://www.eia.gov/dnav/pet/pet_crd_pres_dcu_NUS_a.htm',
    publication_date: '2024-07-01' },
  { pair: 'Post-combustion amine capture × enhanced oil recovery',
    type: 'government_data', strength: 'high', supports: 'H1',
    text: 'IRS 45Q EOR provisions: $60/t for CO2 used in EOR; bonus depreciation; standardised tax-credit treatment for EOR capture-utilisation. Pre-IRA grandfathered rates apply to legacy projects.',
    citation: 'IRC §45Q text + IRS guidance 2024',
    url: 'https://www.irs.gov/credits-deductions/credit-for-carbon-oxide-sequestration',
    publication_date: '2024-03-01' },
  { pair: 'Post-combustion amine capture × enhanced oil recovery',
    type: 'operator_disclosure', strength: 'high', supports: 'H1',
    text: 'ExxonMobil LaBarge (Wyoming): 6+ Mtpa CO2 separation from natural gas processing, supplied to EOR markets and storage; operating since 1986; one of the largest commercial CCS operations globally.',
    citation: 'ExxonMobil LaBarge facility disclosures 2024',
    url: 'https://corporate.exxonmobil.com/locations/united-states/labarge-facility',
    publication_date: '2024-05-01' },

  // oxyfuel × industrial_point_source
  { pair: 'Oxyfuel combustion × industrial point-source decarbonisation',
    type: 'operator_disclosure', strength: 'medium', supports: 'H3',
    text: 'NET Power La Porte 50 MW Allam cycle gas demonstration; first commercial-scale 280 MW project Project Permian under development; industrial oxyfuel for cement at FEED via Heidelberg Brevik (post-combustion not oxyfuel for the operating unit).',
    citation: 'NET Power Allam cycle disclosures 2024',
    url: 'https://netpower.com/projects/',
    publication_date: '2024-09-01' },
  { pair: 'Oxyfuel combustion × industrial point-source decarbonisation',
    type: 'industry_body', strength: 'medium', supports: 'H3',
    text: 'IEAGHG oxyfuel review: oxyfuel cement at TRL 7 (pilot to FOAK); oxyfuel power at TRL 7-8 via Allam cycle; broad industrial-sector commercial uptake structurally beyond 5-year window.',
    citation: 'IEAGHG oxyfuel review 2023',
    url: 'https://ieaghg.org/publications/technical-reports',
    publication_date: '2023-09-01' },
];

// Adjacencies (>=2 per pair)
const ADJACENCIES = [
  // post_combustion_amine × industrial_point_source — 4 adj
  { from: 'Post-combustion amine capture × industrial point-source decarbonisation',
    to:   'Post-combustion amine capture × power-sector decarbonisation',
    type: 'same_technology_different_application', strength: 'strong',
    reason: 'Same physical capture process; different flue-gas characteristics (concentration, scale, contaminants) shift economics. Power-sector application is H3 against industrial H2 because of competitive pressure from renewables-plus-storage.' },
  { from: 'Post-combustion amine capture × industrial point-source decarbonisation',
    to:   'Pre-combustion capture × industrial point-source decarbonisation',
    type: 'same_application_different_technology', strength: 'moderate',
    reason: 'Same end goal (industrial decarbonisation) but different upstream choice (post- vs pre-combustion). Pre-combustion via blue H2 is the principal alternative for new-build industrial decarbonisation; post-combustion suits retrofit.' },
  { from: 'Post-combustion amine capture × industrial point-source decarbonisation',
    to:   'Direct air capture × CDR voluntary market',
    type: 'substitute', strength: 'weak',
    reason: 'DAC offers a substitute decarbonisation pathway for emitters that purchase removals rather than capture at source. Substitution risk is weak in current price environment but rises if voluntary CDR pricing crosses point-source-capture cost.' },
  { from: 'Post-combustion amine capture × industrial point-source decarbonisation',
    to:   'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    type: 'predecessor_successor', strength: 'strong',
    reason: 'First-generation amine capture is the predecessor; next-gen solvents (KM-CDR, CANSOLV S5, water-lean) are the temporal heir for the same application. Successor expected to retrofit incumbents over 2027-2032 as energy-penalty reductions field-validate.' },

  // post_combustion_solvent_next_gen × industrial_point_source — 2 adj
  { from: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    to:   'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'predecessor_successor', strength: 'strong',
    reason: 'Mirror of above — next-gen succeeds first-gen for same application.' },
  { from: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    to:   'Pre-combustion capture × industrial point-source decarbonisation',
    type: 'same_application_different_technology', strength: 'moderate',
    reason: 'Both serve industrial point-source decarbonisation; pre-combustion competes structurally on energy-penalty terms that next-gen solvent is closing.' },

  // pre_combustion × industrial_gas_processing — 2 adj
  { from: 'Pre-combustion capture × industrial gas processing',
    to:   'Pre-combustion capture × industrial point-source decarbonisation',
    type: 'same_technology_different_application', strength: 'strong',
    reason: 'Same SMR + WGS + CCS process; different end use (gas sweetening vs blue H2 for industrial decarbonisation). Industrial gas processing is the H1 base; industrial point-source application is the H2 derivative.' },
  { from: 'Pre-combustion capture × industrial gas processing',
    to:   'Post-combustion amine capture × enhanced oil recovery',
    type: 'complement', strength: 'moderate',
    reason: 'Industrial gas processing supplies CO2 streams for EOR utilisation in many cases (LaBarge → Permian); the two pairs operate as complementary nodes in mature US carbon-management infrastructure.' },

  // pre_combustion × industrial_point_source — 2 adj
  { from: 'Pre-combustion capture × industrial point-source decarbonisation',
    to:   'Pre-combustion capture × industrial gas processing',
    type: 'same_technology_different_application', strength: 'strong',
    reason: 'Mirror of above — industrial decarbonisation is the H2 derivative of the H1 base practice in gas processing.' },
  { from: 'Pre-combustion capture × industrial point-source decarbonisation',
    to:   'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'same_application_different_technology', strength: 'moderate',
    reason: 'Mirror of above — pre- and post-combustion compete for the same industrial decarbonisation application.' },

  // dac × cdr_voluntary — 3 adj
  { from: 'Direct air capture × CDR voluntary market',
    to:   'Mineral carbonation × CDR voluntary market',
    type: 'same_application_different_technology', strength: 'moderate',
    reason: 'Both target CDR voluntary market; different removal pathway (atmospheric capture vs mineralisation). Increasingly integrated (Heirloom-Carbfix) where DAC supplies CO2 to mineralisation for permanence.' },
  { from: 'Direct air capture × CDR voluntary market',
    to:   'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'substitute', strength: 'weak',
    reason: 'Mirror of above — substitution surface between point-source capture and atmospheric removal.' },
  { from: 'Direct air capture × CDR voluntary market',
    to:   'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    type: 'substitute', strength: 'weak',
    reason: 'Same substitution dynamic as first-gen amine; next-gen solvent reduces the industrial-capture cost which raises the bar for DAC competitiveness.' },

  // mineral_carbonation × cdr_voluntary — 2 adj
  { from: 'Mineral carbonation × CDR voluntary market',
    to:   'Direct air capture × CDR voluntary market',
    type: 'same_application_different_technology', strength: 'moderate',
    reason: 'Mirror of DAC entry — both serve voluntary CDR with different physical pathway.' },
  { from: 'Mineral carbonation × CDR voluntary market',
    to:   'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'complement', strength: 'weak',
    reason: 'Mineralisation can serve as a permanence path for industrial-captured CO2 (Carbfix-Coda); the two pairs are increasingly composed in cluster designs.' },

  // post_combustion_amine × power_sector — 2 adj
  { from: 'Post-combustion amine capture × power-sector decarbonisation',
    to:   'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'same_technology_different_application', strength: 'strong',
    reason: 'Mirror of first entry — same tech, industrial application is H2 vs power sector H3.' },
  { from: 'Post-combustion amine capture × power-sector decarbonisation',
    to:   'Oxyfuel combustion × industrial point-source decarbonisation',
    type: 'substitute', strength: 'weak',
    reason: 'Allam cycle (NET Power) offers an oxyfuel substitute for power-sector decarbonisation; same end goal of low-carbon dispatchable power, very different physical approach.' },

  // post_combustion_amine × eor — 2 adj
  { from: 'Post-combustion amine capture × enhanced oil recovery',
    to:   'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'same_technology_different_application', strength: 'strong',
    reason: 'Same physical capture process; different end use (EOR utilisation vs storage). EOR is the H1 commercial base; industrial point-source storage is the H2 derivative being scaled by 45Q $85/t industrial vs $60/t EOR.' },
  { from: 'Post-combustion amine capture × enhanced oil recovery',
    to:   'Pre-combustion capture × industrial gas processing',
    type: 'complement', strength: 'moderate',
    reason: 'Industrial gas-processing CO2 streams supply EOR markets (LaBarge → Permian; Sleipner-style streams in Norwegian context). Complementary nodes in mature US carbon-utilisation infrastructure.' },

  // oxyfuel × industrial_point_source — 2 adj
  { from: 'Oxyfuel combustion × industrial point-source decarbonisation',
    to:   'Post-combustion amine capture × industrial point-source decarbonisation',
    type: 'same_application_different_technology', strength: 'moderate',
    reason: 'Both target industrial decarbonisation; oxyfuel offers a different physical approach (no solvent needed) but at the cost of pure-O2 supply.' },
  { from: 'Oxyfuel combustion × industrial point-source decarbonisation',
    to:   'Post-combustion amine capture × power-sector decarbonisation',
    type: 'substitute', strength: 'weak',
    reason: 'Mirror of earlier entry — Allam cycle as substitute for amine in power sector; same end goal.' },
];

// Component linkage (Shell CCUS components -> pair labels)
const COMPONENT_LINKS = [
  // INDUSTRIAL_CCUS_CAPTURE_TECH (id=8) — primary to multiple operating capture pairs
  { component: 'INDUSTRIAL_CCUS_CAPTURE_TECH',
    pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    role: 'primary',
    reason: 'Quest is a primary instance of post-combustion amine for industrial point-source — Shell\'s flagship operating CCUS asset. Component vector=tech with tech_function=industrial_post_combustion_co2_capture.' },
  { component: 'INDUSTRIAL_CCUS_CAPTURE_TECH',
    pair: 'Pre-combustion capture × industrial point-source decarbonisation',
    role: 'secondary',
    reason: 'Shell H2H Saltend (Equinor partnership) and Polaris-adjacent blue H2 work depend on pre-combustion industrial decarbonisation. Component is a tech-anchor for both first- and pre-combustion pathways.' },
  { component: 'INDUSTRIAL_CCUS_CAPTURE_TECH',
    pair: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    role: 'secondary',
    reason: 'Shell CANSOLV S5 next-gen solvent is the technology Shell is positioning for retrofit and new-build; component carries the next-gen capture pathway through Shell\'s CANSOLV ownership.' },

  // US_45Q_TAX_CREDIT (id=9) — secondary to all 45Q-eligible pairs
  { component: 'US_45Q_TAX_CREDIT',
    pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    role: 'secondary',
    reason: '45Q industrial rate $85/t is the principal subsidy gating Quest-style and US industrial point-source decarbonisation economics. Regulation gates pair viability.' },
  { component: 'US_45Q_TAX_CREDIT',
    pair: 'Pre-combustion capture × industrial point-source decarbonisation',
    role: 'secondary',
    reason: '45Q industrial rate $85/t plus 45V hydrogen production credit interaction gates blue H2 industrial decarbonisation economics for US projects.' },
  { component: 'US_45Q_TAX_CREDIT',
    pair: 'Direct air capture × CDR voluntary market',
    role: 'secondary',
    reason: '45Q DAC rate $180/t is the principal subsidy stacking on top of voluntary CDR pricing for US-based DAC projects (Stratos, future builds).' },
  { component: 'US_45Q_TAX_CREDIT',
    pair: 'Post-combustion amine capture × enhanced oil recovery',
    role: 'secondary',
    reason: '45Q EOR rate $60/t is the principal subsidy on US EOR-utilisation pathway; long-running commercial pair gated by 45Q political durability.' },
  { component: 'US_45Q_TAX_CREDIT',
    pair: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    role: 'secondary',
    reason: 'Same 45Q $85/t industrial framework applies to next-gen solvent retrofits; gating is identical to first-gen pair.' },

  // NORTH_SEA_CO2_STORAGE_CAPACITY (id=10) — secondary to North Sea storage-side pairs
  { component: 'NORTH_SEA_CO2_STORAGE_CAPACITY',
    pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    role: 'secondary',
    reason: 'North Sea storage (Northern Lights, Endurance, Acorn) is the principal storage destination for European industrial-point-source captured CO2; component is the storage-side anchor that operating pairs depend on.' },
  { component: 'NORTH_SEA_CO2_STORAGE_CAPACITY',
    pair: 'Pre-combustion capture × industrial point-source decarbonisation',
    role: 'secondary',
    reason: 'HyNet, H21, Acorn blue H2 industrial decarbonisation projects depend on UK Continental Shelf storage; storage-side anchor for the pair in NW Europe.' },
  { component: 'NORTH_SEA_CO2_STORAGE_CAPACITY',
    pair: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    role: 'secondary',
    reason: 'Next-gen solvent retrofits in European industrial sites would similarly depend on North Sea storage cluster.' },

  // INDUSTRIAL_DECARBONISATION_SERVICES_DEMAND (id=11) — exposure_only to capture-and-store pairs
  { component: 'INDUSTRIAL_DECARBONISATION_SERVICES_DEMAND',
    pair: 'Post-combustion amine capture × industrial point-source decarbonisation',
    role: 'exposure_only',
    reason: 'Demand-side market component — services market sizes and pricing depend on horizon trajectory of this pair. Movement in the pair changes market component\'s subsidy_dependency, demand_certainty, and CAGR.' },
  { component: 'INDUSTRIAL_DECARBONISATION_SERVICES_DEMAND',
    pair: 'Pre-combustion capture × industrial point-source decarbonisation',
    role: 'exposure_only',
    reason: 'Demand for industrial decarbonisation services includes blue H2 supply contracts; market component carries exposure to pair viability.' },
  { component: 'INDUSTRIAL_DECARBONISATION_SERVICES_DEMAND',
    pair: 'Post-combustion next-gen solvent × industrial point-source decarbonisation',
    role: 'exposure_only',
    reason: 'Next-gen solvent reduces the cost-per-tonne in services market; substantial driver of services market expansion if technology converts.' },
  { component: 'INDUSTRIAL_DECARBONISATION_SERVICES_DEMAND',
    pair: 'Direct air capture × CDR voluntary market',
    role: 'exposure_only',
    reason: 'Services market exposed to substitution from voluntary CDR — DAC offtake at $300-1000/t draws demand from industrial-captured CO2 services. Cross-pair exposure surface.' },
];

// ============================================================================
// Execution
// ============================================================================
try {
  await client.query('BEGIN');

  // 1. Insert technologies
  const techIds = {};
  for (const t of TECHNOLOGIES) {
    let funcId = null;
    if (t.tech_function) {
      const r = await client.query(`SELECT id FROM tech_functions WHERE function_name = $1`, [t.tech_function]);
      funcId = r.rows[0]?.id ?? null;
    }
    const r = await client.query(`
      INSERT INTO technologies (technology_name, technology_label, tech_function_id, description,
        current_trl, trl_as_of_date, cost_trajectory_pct_yoy, cost_trajectory_unit, substitution_risk, source_citation)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
      ON CONFLICT (technology_name) DO UPDATE SET
        technology_label = EXCLUDED.technology_label,
        tech_function_id = EXCLUDED.tech_function_id,
        description = EXCLUDED.description,
        current_trl = EXCLUDED.current_trl,
        trl_as_of_date = EXCLUDED.trl_as_of_date,
        cost_trajectory_pct_yoy = EXCLUDED.cost_trajectory_pct_yoy,
        cost_trajectory_unit = EXCLUDED.cost_trajectory_unit,
        substitution_risk = EXCLUDED.substitution_risk,
        source_citation = EXCLUDED.source_citation,
        last_updated_at = NOW()
      RETURNING id
    `, [t.name, t.label, funcId, t.description, t.current_trl, t.trl_as_of_date, t.cost_trajectory_pct_yoy,
        t.cost_trajectory_unit, t.substitution_risk, t.source_citation]);
    techIds[t.name] = r.rows[0].id;
  }
  console.log(`  technologies inserted/updated: ${TECHNOLOGIES.length}`);

  // 2. Insert applications
  const appIds = {};
  for (const a of APPLICATIONS) {
    const r = await client.query(`
      INSERT INTO applications (application_name, application_label, application_domain,
        description, market_maturity, source_citation)
      VALUES ($1,$2,$3,$4,$5,$6)
      ON CONFLICT (application_name) DO UPDATE SET
        application_label = EXCLUDED.application_label,
        application_domain = EXCLUDED.application_domain,
        description = EXCLUDED.description,
        market_maturity = EXCLUDED.market_maturity,
        source_citation = EXCLUDED.source_citation,
        last_updated_at = NOW()
      RETURNING id
    `, [a.name, a.label, a.domain, a.description, a.market_maturity, a.source_citation]);
    appIds[a.name] = r.rows[0].id;
  }
  console.log(`  applications inserted/updated: ${APPLICATIONS.length}`);

  // 3. Insert pairs
  const pairIds = {};
  for (const p of PAIRS) {
    const tid = techIds[p.technology];
    const aid = appIds[p.application];
    if (!tid || !aid) throw new Error(`Missing FK ids for pair ${p.label}: tech=${p.technology}, app=${p.application}`);
    const r = await client.query(`
      INSERT INTO technology_application_pairs
        (technology_id, application_id, pair_label, horizon, horizon_reasoning,
         confidence_band, confidence_reasoning, trajectory, trajectory_reasoning,
         is_flagged_for_review, flag_reason, last_reclassified_at)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11, NOW())
      ON CONFLICT (technology_id, application_id) DO UPDATE SET
        pair_label = EXCLUDED.pair_label,
        horizon = EXCLUDED.horizon,
        horizon_reasoning = EXCLUDED.horizon_reasoning,
        confidence_band = EXCLUDED.confidence_band,
        confidence_reasoning = EXCLUDED.confidence_reasoning,
        trajectory = EXCLUDED.trajectory,
        trajectory_reasoning = EXCLUDED.trajectory_reasoning,
        is_flagged_for_review = EXCLUDED.is_flagged_for_review,
        flag_reason = EXCLUDED.flag_reason,
        last_reclassified_at = NOW(),
        last_updated_at = NOW()
      RETURNING id
    `, [tid, aid, p.label, p.horizon, p.horizon_reasoning, p.confidence,
        p.confidence_reasoning, p.trajectory, p.trajectory_reasoning,
        p.flag, p.flag_reason ?? null]);
    pairIds[p.label] = r.rows[0].id;
  }
  console.log(`  pairs inserted/updated: ${PAIRS.length}`);

  // 4. Insert evidence (clear existing for these pairs first to keep idempotent)
  const pairIdList = Object.values(pairIds);
  await client.query(`DELETE FROM pair_evidence WHERE pair_id = ANY($1::int[])`, [pairIdList]);
  for (const e of EVIDENCE) {
    const pid = pairIds[e.pair];
    if (!pid) throw new Error(`Missing pair_id for evidence on ${e.pair}`);
    await client.query(`
      INSERT INTO pair_evidence (pair_id, evidence_type, evidence_strength, evidence_text,
        source_citation, source_url, publication_date, supports_horizon, recorded_by)
      VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
    `, [pid, e.type, e.strength, e.text, e.citation, e.url ?? null, e.publication_date ?? null,
        e.supports ?? null, '012_ccus_ontology']);
  }
  console.log(`  evidence rows inserted: ${EVIDENCE.length}`);

  // 5. Insert adjacencies (clear existing for these pairs first)
  await client.query(`
    DELETE FROM pair_adjacencies
    WHERE source_pair_id = ANY($1::int[]) OR target_pair_id = ANY($1::int[])
  `, [pairIdList]);
  for (const a of ADJACENCIES) {
    const sid = pairIds[a.from];
    const tid = pairIds[a.to];
    if (!sid || !tid) throw new Error(`Missing pair_id for adjacency ${a.from} -> ${a.to}`);
    await client.query(`
      INSERT INTO pair_adjacencies (source_pair_id, target_pair_id, adjacency_type,
        adjacency_strength, reasoning_text)
      VALUES ($1,$2,$3,$4,$5)
      ON CONFLICT (source_pair_id, target_pair_id, adjacency_type) DO NOTHING
    `, [sid, tid, a.type, a.strength, a.reason]);
  }
  console.log(`  adjacencies inserted: ${ADJACENCIES.length}`);

  // 6. Insert component_pair_links
  const componentIds = {};
  for (const cname of new Set(COMPONENT_LINKS.map(l => l.component))) {
    const r = await client.query(`SELECT id FROM components WHERE name = $1 AND initiative_id = 6`, [cname]);
    if (!r.rows[0]) throw new Error(`Component not found: ${cname}`);
    componentIds[cname] = r.rows[0].id;
  }
  // clear existing links from these components
  const compIdList = Object.values(componentIds);
  await client.query(`DELETE FROM component_pair_links WHERE component_id = ANY($1::int[])`, [compIdList]);
  for (const l of COMPONENT_LINKS) {
    const cid = componentIds[l.component];
    const pid = pairIds[l.pair];
    if (!pid) throw new Error(`Missing pair_id for link ${l.component} -> ${l.pair}`);
    await client.query(`
      INSERT INTO component_pair_links (component_id, pair_id, link_role, reasoning_text, source_citation)
      VALUES ($1,$2,$3,$4,$5)
      ON CONFLICT (component_id, pair_id) DO UPDATE SET
        link_role = EXCLUDED.link_role,
        reasoning_text = EXCLUDED.reasoning_text,
        source_citation = EXCLUDED.source_citation
    `, [cid, pid, l.role, l.reason, '012_ccus_ontology']);
  }
  console.log(`  component_pair_links inserted: ${COMPONENT_LINKS.length}`);

  // ============================================================================
  // Self-marking output (Step 7)
  // ============================================================================
  console.log('\n=== Self-marking output ===');

  const r1 = await client.query(`SELECT COUNT(*) AS n FROM technology_application_pairs WHERE id = ANY($1::int[])`, [pairIdList]);
  console.log(`  pairs populated: ${r1.rows[0].n}`);

  const r2 = await client.query(`
    SELECT confidence_band, COUNT(*) AS n
    FROM technology_application_pairs WHERE id = ANY($1::int[])
    GROUP BY confidence_band ORDER BY confidence_band
  `, [pairIdList]);
  console.log(`  confidence distribution:`); for (const row of r2.rows) console.log(`    ${row.confidence_band}: ${row.n}`);

  const r3 = await client.query(`
    SELECT pair_label, flag_reason FROM technology_application_pairs
    WHERE id = ANY($1::int[]) AND is_flagged_for_review = TRUE
  `, [pairIdList]);
  console.log(`  flagged for review: ${r3.rows.length}`);
  for (const row of r3.rows) console.log(`    - ${row.pair_label} :: ${row.flag_reason}`);

  const r4 = await client.query(`
    SELECT COUNT(DISTINCT cpl.component_id) AS linked,
           (SELECT COUNT(*) FROM components WHERE initiative_id = 6) AS total
    FROM component_pair_links cpl
    WHERE cpl.pair_id = ANY($1::int[])
  `, [pairIdList]);
  console.log(`  components linked: ${r4.rows[0].linked} / ${r4.rows[0].total} in initiative 6`);

  const r5 = await client.query(`
    SELECT tap.pair_label,
           COUNT(*) FILTER (WHERE pa.source_pair_id = tap.id OR pa.target_pair_id = tap.id) AS adj_count
    FROM technology_application_pairs tap
    LEFT JOIN pair_adjacencies pa ON pa.source_pair_id = tap.id OR pa.target_pair_id = tap.id
    WHERE tap.id = ANY($1::int[])
    GROUP BY tap.id, tap.pair_label
    ORDER BY adj_count, tap.pair_label
  `, [pairIdList]);
  console.log(`  adjacencies per pair (target >= 2):`);
  for (const row of r5.rows) console.log(`    ${row.adj_count} -- ${row.pair_label}`);

  const r6 = await client.query(`
    SELECT tap.pair_label,
           COUNT(pe.id) AS evidence_count,
           COUNT(pe.id) FILTER (WHERE pe.source_url IS NOT NULL) AS evidence_with_url,
           COUNT(pe.id) FILTER (WHERE pe.evidence_type IN ('peer_reviewed','company_filing','government_data')) AS hard_evidence
    FROM technology_application_pairs tap
    LEFT JOIN pair_evidence pe ON pe.pair_id = tap.id
    WHERE tap.id = ANY($1::int[])
    GROUP BY tap.id, tap.pair_label
    ORDER BY evidence_count DESC
  `, [pairIdList]);
  console.log(`  source citation quality:`);
  for (const row of r6.rows) console.log(`    ${row.evidence_count} (url=${row.evidence_with_url}, hard=${row.hard_evidence}) -- ${row.pair_label}`);

  // Check for placeholder citations
  const r7 = await client.query(`
    SELECT pe.id, pe.pair_id, pe.source_citation FROM pair_evidence pe
    WHERE pe.pair_id = ANY($1::int[])
      AND LOWER(pe.source_citation) IN ('industry knowledge','general knowledge','common knowledge')
  `, [pairIdList]);
  console.log(`  placeholder citations: ${r7.rows.length} (must be 0)`);
  if (r7.rows.length > 0) throw new Error(`Placeholder citations detected — discipline violation`);

  // ============================================================================
  // Acceptance queries (Q1-Q5)
  // ============================================================================
  console.log('\n=== Acceptance queries ===');

  const t1 = Date.now();
  const Q1 = await client.query(`
    SELECT horizon, confidence_band, COUNT(*) AS pair_count
    FROM technology_application_pairs
    GROUP BY horizon, confidence_band
    ORDER BY horizon, confidence_band
  `);
  console.log(`  Q1 (pair count by horizon × confidence) : ${Q1.rows.length} rows in ${Date.now()-t1}ms`);
  for (const r of Q1.rows) console.log(`    ${r.horizon} / ${r.confidence_band} -> ${r.pair_count}`);

  const t2 = Date.now();
  const Q2 = await client.query(`
    SELECT tap.pair_label, tap.horizon, tap.confidence_band, tap.flag_reason,
           COUNT(pe.id) AS evidence_count
    FROM technology_application_pairs tap
    LEFT JOIN pair_evidence pe ON pe.pair_id = tap.id
    WHERE tap.is_flagged_for_review = TRUE
    GROUP BY tap.id, tap.pair_label, tap.horizon, tap.confidence_band, tap.flag_reason
    ORDER BY tap.confidence_band, tap.pair_label
  `);
  console.log(`  Q2 (flagged review queue) : ${Q2.rows.length} rows in ${Date.now()-t2}ms`);
  for (const r of Q2.rows) console.log(`    [${r.confidence_band}/${r.horizon}] ${r.pair_label}`);

  const t3 = Date.now();
  const Q3 = await client.query(`
    SELECT i.name AS initiative,
           c.name AS component,
           tap.pair_label,
           tap.horizon,
           tap.confidence_band,
           tap.trajectory,
           cpl.link_role
    FROM components c
    JOIN initiatives_v2 i ON i.id = c.initiative_id
    JOIN companies co ON co.id = i.company_id
    JOIN component_pair_links cpl ON cpl.component_id = c.id
    JOIN technology_application_pairs tap ON tap.id = cpl.pair_id
    WHERE co.name = 'Shell' AND i.id = 6
    ORDER BY i.name, c.name, tap.horizon
  `);
  console.log(`  Q3 (Shell × ontology heat map) : ${Q3.rows.length} rows in ${Date.now()-t3}ms`);
  console.log(`    sample: ${JSON.stringify(Q3.rows[0])}`);

  const t4 = Date.now();
  const Q4 = await client.query(`
    WITH anchor AS (
      SELECT id FROM technology_application_pairs
      WHERE pair_label ILIKE 'Post-combustion amine%industrial point-source%'
    )
    SELECT a.adjacency_type, a.adjacency_strength,
           neighbour.pair_label AS neighbour_pair,
           neighbour.horizon AS neighbour_horizon
    FROM pair_adjacencies a
    JOIN technology_application_pairs neighbour ON neighbour.id = a.target_pair_id
    WHERE a.source_pair_id = (SELECT id FROM anchor)
    UNION ALL
    SELECT a.adjacency_type, a.adjacency_strength,
           neighbour.pair_label AS neighbour_pair,
           neighbour.horizon AS neighbour_horizon
    FROM pair_adjacencies a
    JOIN technology_application_pairs neighbour ON neighbour.id = a.source_pair_id
    WHERE a.target_pair_id = (SELECT id FROM anchor)
    ORDER BY adjacency_type, adjacency_strength
  `);
  console.log(`  Q4 (adjacency walk from anchor pair) : ${Q4.rows.length} rows in ${Date.now()-t4}ms`);
  for (const r of Q4.rows) console.log(`    [${r.adjacency_type}/${r.adjacency_strength}] -> ${r.neighbour_pair} (${r.neighbour_horizon})`);

  const t5 = Date.now();
  const Q5 = await client.query(`
    SELECT tap.pair_label, tap.confidence_band,
           COUNT(pe.id) AS evidence_count,
           COUNT(pe.id) FILTER (WHERE pe.evidence_type IN ('peer_reviewed','company_filing','government_data')) AS hard_evidence_count,
           COUNT(pe.id) FILTER (WHERE pe.evidence_strength = 'high') AS high_strength_count,
           COUNT(pe.id) FILTER (WHERE pe.source_url IS NOT NULL) AS evidence_with_url
    FROM technology_application_pairs tap
    LEFT JOIN pair_evidence pe ON pe.pair_id = tap.id
    GROUP BY tap.id, tap.pair_label, tap.confidence_band
    ORDER BY tap.confidence_band, tap.pair_label
  `);
  console.log(`  Q5 (evidence quality audit) : ${Q5.rows.length} rows in ${Date.now()-t5}ms`);

  // ============================================================================
  // Commit / rollback
  // ============================================================================
  if (WILL_COMMIT) {
    await client.query('COMMIT');
    console.log('\n[pg] COMMIT — CCUS ontology persisted');
  } else {
    await client.query('ROLLBACK');
    console.log('\n[pg] ROLLBACK (dry-run; pass --commit --confirm-yes to persist)');
  }
} catch (err) {
  await client.query('ROLLBACK').catch(() => {});
  console.error(`\n[pg] ROLLBACK due to error: ${err.message}`);
  console.error(err.stack);
  await client.end();
  process.exit(1);
}
await client.end();
