// db/population/P2_VWG_hypotheses.mjs
// Path A — VW Group hypotheses (group + Skoda + Porsche brand level)
// populated from the corresponding intelligence brief HTMLs:
//   - vw_intelligence_brief__4_.html (March 2026, posture: TRANSFORM)
//   - skoda_intelligence_brief__3_.html (March 2026)
//   - porsche_intelligence_brief__4_.html (March 2026)
//
// Nine hypotheses transcribed from the briefs' HYP registers:
//
//   VW-01  Group       — German factory closure blocked by IG Metall,
//                        €2-3B extra restructuring cost (H1, High, 72%)
//   VW-02  Group       — ID. platform SDV revision required before 2028
//                        (H2, Medium, 66%)
//   VW-03  Group       — China share below 12% by 2027 (H2, Medium, 61%)
//   SKD-01 Skoda Auto  — India dedicated platform >200k units/yr by 2028
//                        (H2, Medium, 69%)
//   SKD-02 Skoda Auto  — Enyaq+Elroq top-3 European affordable EV
//                        through 2028 (H2, Medium, 64%)
//   SKD-03 Skoda Auto  — Czech manufacturing as structural VWG advantage
//                        (H1, Medium, 58%)
//   PAG-01 Porsche AG  — eFuels EU carve-out by 2026 preserves 911 ICE
//                        beyond 2035 (H2, High, 72%)
//   PAG-02 Porsche AG  — Taycan 15-25% premium over Tesla Model S Plaid
//                        and BYD Han through 2028 (H1, High, 69%)
//   PAG-03 Porsche AG  — Motorsport + experiential becomes primary brand
//                        investment by 2028 (H2, Medium, 60%)
//
// MAN_001 (fleet customer BEV charging co-investment) was on the original
// brief but is dropped from this run — no MAN intelligence brief is in the
// repo, so a population pass would violate the "do not invent positions"
// discipline. Flagged in sessions/_next.md for a future pass once the brief
// is generated.
//
// Run:
//   node db/population/P2_VWG_hypotheses.mjs           # dry-run
//   node db/population/P2_VWG_hypotheses.mjs --commit  # write to PG
//
// Three runPopulation() calls — one per company. Each is its own transaction.
// Idempotent.

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const VW_BRIEF      = 'vw_intelligence_brief__4_.html (March 2026)';
const SKODA_BRIEF   = 'skoda_intelligence_brief__3_.html (March 2026)';
const PORSCHE_BRIEF = 'porsche_intelligence_brief__4_.html (March 2026)';

// ============================================================================
// VOLKSWAGEN GROUP (parent — existing companies row id=11 "Volkswagen Group")
// ============================================================================

const vwgCompany = {
  name: 'Volkswagen Group',
  sector: 'mobility',
  notes: 'Volkswagen AG group level. v2 catalogue first-cut hypotheses sourced from March 2026 brief. Brand-level (Skoda, Porsche, MAN, Audi etc.) tracked as separate companies.',
};

const vwgInitiatives = [
  // VW-01 ----------------------------------------------------------------
  {
    name: 'VW German factory closure programme blocked by IG Metall, €2-3B extra restructuring cost',
    strategy_context: `VW launched a German restructuring programme in 2024 targeting factory closures and headcount reduction in Wolfsburg / Zwickau / Osnabrück / Dresden. IG Metall and works council have publicly opposed every closure. The 2026 labour agreement renegotiation gates the closure timetable. Brief assesses High confidence on the blocking scenario.`,
    brief_description: 'Whether IG Metall and works council action substantially blocks VW German factory closures, forcing absorption of €2-3B additional restructuring cost.',
    hypothesis_statement: `VW's German factory closure programme will be substantially blocked by IG Metall and works council action, forcing VW to absorb €2-3B in additional restructuring costs. Source: ${VW_BRIEF}, HYP VW-01.`,
    why_it_matters: 'The restructuring timeline directly determines VW\'s technology procurement budget and scouting capacity through 2027. Larger cost absorption tightens R&D budget — narrowing the procurement window for SDV, battery, autonomous technology vendors.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${VW_BRIEF} HYP VW-01 (H1 · 1–2yr)`,
    decision_threshold: [
      'IG Metall secures binding employment guarantee covering 90%+ of German headcount through end-2028;',
      'VW 2026 labour agreement requires 24+ months additional consultation before any closure;',
      'German federal or state government provides financial instrument in exchange for closure moratorium;',
      'VW Supervisory Board votes to modify original restructuring plan by Q2 2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP VW-01.)',
    ].join(' '),
    baseline_confidence: 0.72,
    current_confidence: 0.72,
    state: 'strengthening',
    trajectory: 'deteriorating',
    state_reasoning: 'IG Metall public statements actively opposing closures; brief flags Market driver as live SIGNAL.',
    trajectory_reasoning: `BP's restructuring economics deteriorating relative to original plan as concessions accumulate. Source: ${VW_BRIEF} HYP VW-01 system drivers.`,
    components: [
      {
        name: 'IG_METALL_NEGOTIATING_POSITION',
        description: 'IG Metall negotiating position and works council stance on VW German plant closures. Market system driver SIGNAL per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-01 (System Driver: Market — IG Metall negotiating position SIGNAL); live source: IG Metall public statements`,
        state: 'strengthening', trajectory: 'deteriorating',
        state_reasoning: 'IG Metall consistently opposing closures since 2024; brief notes their stance is the operative blocker.',
        trajectory_reasoning: 'Bargaining position hardening as 2026 labour agreement approaches.',
      },
      {
        name: 'VW_2026_LABOUR_AGREEMENT_TERMS',
        description: 'VW 2026 labour agreement terms and closure moratorium provisions. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-01 (System Driver: Policy — VW 2026 labour agreement terms SIGNAL); WNTBT bullet 2`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'Agreement under negotiation as of brief date; outcome WNTBT condition.',
        trajectory_reasoning: 'Will resolve in 2026 — directional indicator pending.',
      },
      {
        name: 'VW_RESTRUCTURING_COST_VS_PLAN',
        description: 'VW restructuring cost realisation vs original plan target. Economics driver per brief — currently NOT signalled but tracked as the financial impact register.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-01 (System Driver: Economics — VW restructuring cost vs original plan target)`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Brief\'s €2-3B additional cost framing implies original plan economics already eroded.',
        trajectory_reasoning: 'Accumulating concessions imply continued erosion.',
      },
      {
        name: 'GERMAN_FEDERAL_STATE_INTERVENTION',
        description: 'German federal or Niedersachsen / Sachsen state government financial-instrument intervention conditional on closure moratorium. WNTBT condition 3.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-01 WNTBT bullet 3`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'No instrument announced as of March 2026 brief; conditional on negotiation outcome.',
        trajectory_reasoning: 'Pending — will become directional once announced or refused.',
      },
    ],
    claims: [
      { component_name: 'IG_METALL_NEGOTIATING_POSITION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'IG Metall and works council secure a binding employment guarantee covering >90% of German VW headcount through end-2028.',
        claim_basis: `Brief HYP VW-01 WNTBT condition 1. Source: ${VW_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 90, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Employment guarantee is the principal observable confirmation that closures are blocked.',
        impact_reasoning: 'Headcount lock-in directly forces additional restructuring cost into VW\'s P&L.' },
      { component_name: 'VW_2026_LABOUR_AGREEMENT_TERMS', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW 2026 labour agreement requires 24+ months additional consultation before any closure can be effected.',
        claim_basis: `Brief HYP VW-01 WNTBT condition 2. Source: ${VW_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 24, threshold_unit: 'months',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Consultation lock-in extends the closure timetable beyond the strategic relevance horizon.',
        impact_reasoning: 'Procedural delay is structurally equivalent to closure block in this brief\'s assessment.' },
      { component_name: 'VW_RESTRUCTURING_COST_VS_PLAN', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW Supervisory Board votes to modify the original restructuring plan by Q2 2026, accepting €2-3B additional cost vs. original.',
        claim_basis: `Brief HYP VW-01 WNTBT condition 4. Source: ${VW_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Supervisory Board acceptance is the boardroom confirmation of the cost absorption.',
        impact_reasoning: 'Public modification establishes the cost as recurring — not a one-off concession.' },
      { component_name: 'GERMAN_FEDERAL_STATE_INTERVENTION', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'German federal or state government provides a financial instrument (subsidy, tax relief, supported loan) in exchange for the closure moratorium.',
        claim_basis: `Brief HYP VW-01 WNTBT condition 3. Source: ${VW_BRIEF}.`,
        criticality_reasoning: 'State intervention partially offsets the €2-3B cost absorption, dampening the hypothesis confidence even if the closure block holds.',
        impact_reasoning: 'Subsidy reduces the net cost VW absorbs but does not invalidate the structural closure block.' },
    ],
  },

  // VW-02 ----------------------------------------------------------------
  {
    name: 'VW ID. platform requires fundamental SDV+E/E architecture revision before 2028',
    strategy_context: `CARIAD (VW Group software unit) has undergone repeated reorganisations. The current MEB platform underpinning ID. vehicles is judged uncompetitive vs Tesla and Chinese SDV platforms (BYD, Li Auto, Xiaomi). The SSP next-gen platform is the strategic answer; brief assesses 18+ month delay risk.`,
    brief_description: 'Whether VW must fundamentally revise its ID. platform software and electrical architecture before 2028 to remain competitive.',
    hypothesis_statement: `VW's ID. platform will require a fundamental software and electrical architecture revision before 2028 — the current generation will not be competitive with next-generation Chinese or Tesla SDV platforms. Source: ${VW_BRIEF}, HYP VW-02.`,
    why_it_matters: 'SDV architecture, OTA software economics, and zonal E/E architecture transition are the technology intelligence categories VW R&D scouting team is most urgently seeking. FutureBridge engagement window is broad and immediate.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${VW_BRIEF} HYP VW-02 (H2 · 3–5yr)`,
    decision_threshold: [
      'VW announces revised SSP timeline showing 18+ month delay from original 2026 target;',
      'At least two major software reviews show VW trailing Chinese and Tesla benchmarks by 20%+;',
      'VW CARIAD undergoes a second major management reorganisation before end-2025;',
      'Strategic software partner formally announced for next-gen VW SDV architecture.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP VW-02.)',
    ].join(' '),
    baseline_confidence: 0.66,
    current_confidence: 0.66,
    state: 'ambiguous',
    trajectory: 'volatile',
    state_reasoning: 'CARIAD reorganisations and SSP timeline uncertainty make state ambiguous; SDV competitive pressure rising but VW response unsettled.',
    trajectory_reasoning: `Trajectory volatile — dependent on whether SSP delays compound or VW takes a strategic-partner shortcut. Source: ${VW_BRIEF} HYP VW-02.`,
    components: [
      {
        name: 'CARIAD_SOFTWARE_RD_COST_VS_REVENUE',
        description: 'CARIAD software R&D cost vs platform revenue contribution. Economics SIGNAL driver.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-02 (System Driver: Economics — CARIAD software R&D cost vs platform revenue SIGNAL)`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Brief implies CARIAD spend running ahead of platform revenue contribution.',
        trajectory_reasoning: 'Cost overruns and management churn worsen the ratio.',
      },
      {
        name: 'VW_ID_DIGITAL_EXPERIENCE_VS_PEERS',
        description: 'VW ID. digital experience benchmarks vs Tesla and Chinese OEMs. Market SIGNAL driver — digital experience is the consumer-visible measure.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-02 (System Driver: Market — VW ID. digital experience vs Tesla and Chinese OEM benchmarks SIGNAL)`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'WNTBT condition 2 implies independent reviews show VW trailing 20%+ — already approaching threshold.',
        trajectory_reasoning: 'Chinese OEM SDV cadence accelerating year-on-year per brief.',
      },
      {
        name: 'SSP_ZONAL_ARCHITECTURE_AND_OTA',
        description: 'SSP zonal E/E architecture and OTA software delivery. Tech driver per brief — currently NOT signalled but the underlying technical question.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${VW_BRIEF} HYP VW-02 (System Driver: Technology — SSP zonal architecture and OTA software delivery)`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'SSP under development; not yet operational at production volume.',
        trajectory_reasoning: 'Brief flags potential 18+ month delay — directional indicator pending.',
      },
      {
        name: 'EU_CONNECTED_VEHICLE_CYBER_REGS',
        description: 'EU connected vehicle cybersecurity (UNECE R155/R156) and software regulations. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${VW_BRIEF} HYP VW-02 (System Driver: Policy — EU connected vehicle cybersecurity and software regulations)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'UNECE regulations in force; no near-term policy shift in brief.',
        trajectory_reasoning: 'Regulatory framework stable.',
      },
    ],
    claims: [
      { component_name: 'SSP_ZONAL_ARCHITECTURE_AND_OTA', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VW announces revised SSP platform timeline showing 18+ month delay from original 2026 target.',
        claim_basis: `Brief HYP VW-02 WNTBT condition 1. Source: ${VW_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 18, threshold_unit: 'months',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'SSP delay is the principal observable confirmation that ID. revision is structurally required.',
        impact_reasoning: 'Each month of delay extends the competitive gap relative to Chinese / Tesla cadence.' },
      { component_name: 'VW_ID_DIGITAL_EXPERIENCE_VS_PEERS', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'At least two major independent software reviews show VW trailing Chinese and Tesla benchmarks by 20%+.',
        claim_basis: `Brief HYP VW-02 WNTBT condition 2. Source: ${VW_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 20, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Independent benchmark gap >20% is the operational evidence the hypothesis demands.',
        impact_reasoning: 'Public benchmarks force the architectural revision conversation onto the supervisory board agenda.' },
      { component_name: 'CARIAD_SOFTWARE_RD_COST_VS_REVENUE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW CARIAD undergoes a second major management reorganisation before end-2025.',
        claim_basis: `Brief HYP VW-02 WNTBT condition 3. Source: ${VW_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Repeat management reorganisation is the structural symptom of architectural failure.',
        impact_reasoning: 'Each reorganisation cycle delays delivery and burns goodwill.' },
      { component_name: 'EU_CONNECTED_VEHICLE_CYBER_REGS', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'EU connected-vehicle cybersecurity tightening forces VW to harden current MEB software faster than SSP migration timetable, locking in legacy architecture investments.',
        claim_basis: `Brief HYP VW-02 (Policy driver). Source: ${VW_BRIEF}.`,
        criticality_reasoning: 'Regulatory hardening could entrench MEB rather than force replacement, dampening the revision hypothesis.',
        impact_reasoning: 'Compliance-driven legacy investment dilutes the case for fundamental revision.' },
    ],
  },

  // VW-03 ----------------------------------------------------------------
  {
    name: 'VW China market share falls below 12% by 2027 as BYD / Li Auto / Huawei consolidate mid-market',
    strategy_context: `VW China deliveries have declined from 3.2M units (2023) toward 2.5M as BYD, Li Auto, Xiaomi, and Huawei-backed brands consolidate the mid-market. SAIC-VW and FAW-VW JV royalty terms are under renegotiation pressure. Brief identifies this as the most commercially sensitive intelligence gap in VW\'s scouting portfolio.`,
    brief_description: 'Whether VW China market share drops below 12% by 2027 as Chinese OEMs consolidate the mid-market.',
    hypothesis_statement: `VW's China market share will fall below 12% by 2027 as BYD, Li Auto, and Huawei-backed brands consolidate the mid-market. Source: ${VW_BRIEF}, HYP VW-03.`,
    why_it_matters: 'China localisation intelligence is the most commercially sensitive gap in VW\'s current scouting portfolio. Without it, VW\'s defensive measures (China-only EV platform) risk being launched without market-fit validation.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${VW_BRIEF} HYP VW-03 (H2 · 3–6yr)`,
    decision_threshold: [
      'VW China deliveries fall below 2.5M units in 2025 (from 3.2M in 2023);',
      'BYD surpasses VW as China\'s number one passenger car brand by volume before end-2025;',
      'VW China JV partners publicly seek to renegotiate technology royalty terms before 2026;',
      'VW announces a dedicated China-only EV platform by end-2025 as a defensive measure.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP VW-03.)',
    ].join(' '),
    baseline_confidence: 0.61,
    current_confidence: 0.61,
    state: 'strengthening',
    trajectory: 'deteriorating',
    state_reasoning: 'Multiple WNTBT conditions already confirmed: BYD surpassed VW in 2024 and 2.5M unit threshold approaching.',
    trajectory_reasoning: `Brief signals BYD and local brand share growth in core VW segments — trajectory consistent with hypothesis. Source: ${VW_BRIEF} HYP VW-03.`,
    components: [
      {
        name: 'BYD_LOCAL_BRAND_SHARE_VW_CORE_SEGMENTS',
        description: 'BYD and local Chinese brand share of VW\'s core China segments (mid-market sedans, mid-size SUVs). Market SIGNAL driver.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-03 (System Driver: Market — BYD and local brand share of VW core China segments SIGNAL); live source: BYD monthly China sales vs VW`,
        state: 'strengthening', trajectory: 'deteriorating',
        state_reasoning: 'BYD overtook VW as #1 passenger car brand in China in 2024 per brief WNTBT condition 2.',
        trajectory_reasoning: 'Mid-market consolidation continuing — Li Auto and Xiaomi expanding model lines.',
      },
      {
        name: 'VW_CHINA_DELIVERIES_VOLUME_TRAJECTORY',
        description: 'VW China total deliveries volume trajectory. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-03 (System Driver: Economics — VW China average transaction price and JV profitability)`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: '3.2M (2023) → trending toward 2.5M (2025 WNTBT condition 1) — declining trajectory clear.',
        trajectory_reasoning: 'Brief LIVE NOW: VW China monthly delivery data continuing to weaken.',
      },
      {
        name: 'CHINA_LOCAL_EV_PLATFORM_LOCALISATION',
        description: 'VW China-specific EV platform localisation pace and investment. Tech driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-03 (System Driver: Technology — China-only EV platform localisation pace and investment); WNTBT bullet 4`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'Defensive China-only EV platform under consideration but not announced as of brief.',
        trajectory_reasoning: 'WNTBT condition 4 awaits resolution.',
      },
      {
        name: 'SAIC_VW_FAW_VW_JV_ROYALTY_TERMS',
        description: 'SAIC-VW and FAW-VW joint venture technology royalty term renegotiation. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${VW_BRIEF} HYP VW-03 (System Driver: Policy — SAIC-VW and FAW-VW JV royalty renegotiation terms); WNTBT bullet 3`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'JV partners publicly seeking renegotiation per brief WNTBT condition 3.',
        trajectory_reasoning: 'Volatile — outcome depends on Chinese government and individual JV partner positions.',
      },
    ],
    claims: [
      { component_name: 'VW_CHINA_DELIVERIES_VOLUME_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VW China deliveries fall below 2.5M units in 2025, on trajectory to <12% market share by 2027.',
        claim_basis: `Brief HYP VW-03 WNTBT condition 1; hypothesis statement. Source: ${VW_BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 2.5, threshold_unit: 'million_units',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Volume threshold is the principal numeric anchor of the hypothesis.',
        impact_reasoning: 'Each unit below threshold accelerates share loss in absolute and relative terms.' },
      { component_name: 'BYD_LOCAL_BRAND_SHARE_VW_CORE_SEGMENTS', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'BYD surpasses VW as China\'s number one passenger car brand by volume before end-2025.',
        claim_basis: `Brief HYP VW-03 WNTBT condition 2. Source: ${VW_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Brand-rank crossover is the structural confirmation that local consolidation has succeeded.',
        impact_reasoning: 'BYD #1 status reshapes consumer purchasing decisions and dealer network economics.' },
      { component_name: 'SAIC_VW_FAW_VW_JV_ROYALTY_TERMS', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW China JV partners (SAIC, FAW) publicly seek to renegotiate technology royalty terms before 2026.',
        claim_basis: `Brief HYP VW-03 WNTBT condition 3. Source: ${VW_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'JV royalty renegotiation directly compresses VW China earnings power and the strategic value of remaining presence.',
        impact_reasoning: 'Public renegotiation indicates JV partners view VW IP as commoditising.' },
      { component_name: 'CHINA_LOCAL_EV_PLATFORM_LOCALISATION', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'VW announces a dedicated China-only EV platform by end-2025 as a defensive measure that succeeds in stabilising share above 12%.',
        claim_basis: `Brief HYP VW-03 WNTBT condition 4 (inverse — successful platform launch dampens hypothesis). Source: ${VW_BRIEF}.`,
        criticality_reasoning: 'A successful defensive platform launch is the primary path to hypothesis falsification.',
        impact_reasoning: 'China-only platform addressing local consumer preferences could re-rate VW positioning.' },
    ],
  },
];

// ============================================================================
// SKODA AUTO (brand-level — companies row may not yet exist in PG)
// ============================================================================

const skodaCompany = {
  name: 'Skoda Auto',
  sector: 'mobility',
  notes: 'Skoda Auto a.s. — VW Group subsidiary, headquartered in Mlada Boleslav, Czech Republic. Brand-level hypotheses sourced from March 2026 brief.',
};

const skodaInitiatives = [
  // SKD-01 ---------------------------------------------------------------
  {
    name: 'Skoda India dedicated platform >200k units annually by 2028',
    strategy_context: `Skoda Auto Volkswagen India has been the VW Group's lead India entity. The MQB-A0-IN platform (co-developed for India) underpins Slavia and Kushaq. The hypothesis tests whether India scales to >200k units/yr by 2028, establishing the sub-continent as primary volume growth engine.`,
    brief_description: 'Whether Skoda\'s India dedicated platform exceeds 200k units annually by 2028.',
    hypothesis_statement: `Skoda's India dedicated platform will generate more than 200,000 units annually by 2028, establishing the sub-continent as the primary volume growth engine. Source: ${SKODA_BRIEF}, HYP SKD-01.`,
    why_it_matters: 'India automotive supply chain intelligence is the planning input Skoda\'s emerging market team most needs. FutureBridge engagement priority is the supply chain + regulatory landscape.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${SKODA_BRIEF} HYP SKD-01 (H2 · 4–7yr)`,
    decision_threshold: [
      'Skoda Slavia and Kushaq India platform reaches 120,000 units in 2025;',
      'Volkswagen India secures local battery supply agreement for India-specific EV before end-2026;',
      'Indian government EV incentive scheme extends beyond 2025;',
      'Skoda establishes 3+ additional local suppliers for India platform components by end-2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP SKD-01.)',
    ].join(' '),
    baseline_confidence: 0.69,
    current_confidence: 0.69,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief signals Indian EV incentive (Market) AND India-specific platform (Tech) as live SIGNAL drivers — both reinforcing.',
    trajectory_reasoning: `India EV market expansion sustained per brief. Source: ${SKODA_BRIEF}.`,
    components: [
      {
        name: 'SKODA_INDIA_PLATFORM_VOLUME',
        description: 'Skoda Slavia + Kushaq India platform unit volume. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${SKODA_BRIEF} HYP SKD-01 (Economics driver — Skoda India platform unit volume and contribution margin); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'WNTBT 120k (2025) approaching trajectory to 200k (2028).',
        trajectory_reasoning: 'India auto market growth sustained.',
      },
      {
        name: 'INDIA_GOVT_EV_INCENTIVE_FRAMEWORK',
        description: 'Indian government EV incentive scheme continuation. Market SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${SKODA_BRIEF} HYP SKD-01 (Market driver SIGNAL — Indian government EV incentive scheme continuation); WNTBT bullet 3`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'EV incentive scheme in force; brief flags continuation as WNTBT.',
        trajectory_reasoning: 'Brief shows scheme as live policy without imminent reversal indicator.',
      },
      {
        name: 'INDIA_SPECIFIC_EV_PLATFORM_AND_LOCAL_SOURCING',
        description: 'India-specific EV platform and local component sourcing. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${SKODA_BRIEF} HYP SKD-01 (Technology driver SIGNAL — India-specific EV platform and local component sourcing); WNTBT bullets 2 + 4`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'India-specific EV platform under development; local sourcing expanding per brief.',
        trajectory_reasoning: 'WNTBT 4 requires 3+ additional local suppliers — directional indicator.',
      },
      {
        name: 'INDIA_EV_MANDATE_IMPORT_DUTY_REGIME',
        description: 'India EV mandate timeline and import duty framework. Policy driver per brief — currently NOT signalled.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${SKODA_BRIEF} HYP SKD-01 (Policy driver — India EV mandate timeline and import duty framework)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'Import duty framework stable; no near-term shift in brief.',
        trajectory_reasoning: 'Stable.',
      },
    ],
    claims: [
      { component_name: 'SKODA_INDIA_PLATFORM_VOLUME', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Skoda Slavia + Kushaq India platform reaches 120,000 units in 2025 — on trajectory to >200,000 by 2028.',
        claim_basis: `Brief HYP SKD-01 WNTBT condition 1 + hypothesis statement. Source: ${SKODA_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 120000, threshold_unit: 'units',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: '2025 volume is the leading indicator for the 2028 200k threshold.',
        impact_reasoning: 'Each unit above 120k strengthens the trajectory case.' },
      { component_name: 'INDIA_SPECIFIC_EV_PLATFORM_AND_LOCAL_SOURCING', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW India secures local battery supply agreement for India-specific EV before end-2026; Skoda establishes 3+ additional local suppliers.',
        claim_basis: `Brief HYP SKD-01 WNTBT conditions 2 + 4. Source: ${SKODA_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 3, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Local sourcing depth is the structural enabler of the volume scale-up.',
        impact_reasoning: 'Each new local supplier improves cost competitiveness vs imported alternatives.' },
      { component_name: 'INDIA_GOVT_EV_INCENTIVE_FRAMEWORK', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Indian government EV incentive scheme extends beyond 2025.',
        claim_basis: `Brief HYP SKD-01 WNTBT condition 3. Source: ${SKODA_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Incentive continuity is the precondition for accelerated EV uptake at the price points India volume requires.',
        impact_reasoning: 'Scheme continuity holds the consumer demand curve in place.' },
    ],
  },

  // SKD-02 ---------------------------------------------------------------
  {
    name: 'Skoda Enyaq + next-gen Elroq hold top-3 European affordable EV through 2028',
    strategy_context: `Skoda Enyaq is established in the European affordable EV segment. Elroq (smaller, lower price point) launched. EU-China BEV tariff regime (17%+ duties on Chinese imports) is the structural insulator. Brief assesses confidence Medium.`,
    brief_description: 'Whether Skoda Enyaq + Elroq sustain a top-3 position in the European affordable EV segment through 2028.',
    hypothesis_statement: `Skoda's Enyaq and next-generation Elroq will hold top-3 position in the European affordable EV segment through 2028 as Chinese competitors face tariff headwinds. Source: ${SKODA_BRIEF}, HYP SKD-02.`,
    why_it_matters: 'Affordable EV technology is where Skoda\'s technology scouting is most active. Battery cost reduction, charging interoperability, MEB platform competitive intelligence are live engagement opportunities.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${SKODA_BRIEF} HYP SKD-02 (H2 · 3–5yr)`,
    decision_threshold: [
      'EU tariffs on Chinese BEV imports maintained at 17%+ through 2027 following WTO review;',
      'Enyaq and Elroq combined achieve 150,000+ annual European sales by 2026;',
      'VW Group MEB cost reductions deliver 15%+ BOM reduction on Skoda EV models by 2027;',
      'No Chinese EV brand establishes local European assembly bypassing tariffs before 2028.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP SKD-02.)',
    ].join(' '),
    baseline_confidence: 0.64,
    current_confidence: 0.64,
    state: 'holding',
    trajectory: 'stable',
    state_reasoning: 'Tariff regime in force; Enyaq position established in segment; Elroq launched.',
    trajectory_reasoning: `Outcome depends on tariff durability and BOM cost trajectory — both currently aligned. Source: ${SKODA_BRIEF}.`,
    components: [
      {
        name: 'MEB_PLATFORM_BOM_COST_REDUCTION',
        description: 'MEB platform bill-of-materials cost reduction trajectory on Skoda EV models. Economics SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${SKODA_BRIEF} HYP SKD-02 (Economics driver SIGNAL — MEB platform BOM cost reduction trajectory); WNTBT bullet 3`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'BOM reduction in flight per VW Group capital reallocation; brief assesses 15% target by 2027.',
        trajectory_reasoning: 'Battery cell cost trajectory improving generally; PowerCo gigafactory ramp aligns with SKD-02 timeline.',
      },
      {
        name: 'EU_CHINA_BEV_TARIFF_REGIME_AND_WTO',
        description: 'EU China BEV tariff regime and WTO dispute timeline. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${SKODA_BRIEF} HYP SKD-02 (Policy driver SIGNAL — EU China BEV tariff regime and WTO dispute timeline); WNTBT bullets 1 + 4`,
        state: 'holding', trajectory: 'volatile',
        state_reasoning: 'Tariff regime in force at 17%+ as of brief; WTO review pending.',
        trajectory_reasoning: 'WTO outcome uncertain — directional indicator pending.',
      },
      {
        name: 'CHINESE_BEV_LOCAL_EU_ASSEMBLY',
        description: 'Chinese BEV local European assembly investments (BYD Hungary plant et al.) that would bypass tariffs.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${SKODA_BRIEF} HYP SKD-02 WNTBT bullet 4`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'BYD Hungary in construction; first cars 2026-2027.',
        trajectory_reasoning: 'Pace of local-assembly ramp is volatile — depends on individual OEM commitment.',
      },
      {
        name: 'AFFORDABLE_EV_BATTERY_AND_SOFTWARE_VALUE',
        description: 'Affordable EV battery cost and software value stacking. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${SKODA_BRIEF} HYP SKD-02 (Technology driver — Affordable EV battery cost and software value stacking)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Battery cost trajectory continuing to fall; software differentiation strengthening as a value-add.',
        trajectory_reasoning: 'Industry-wide trajectory positive.',
      },
    ],
    claims: [
      { component_name: 'EU_CHINA_BEV_TARIFF_REGIME_AND_WTO', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'EU tariffs on Chinese BEV imports maintained at 17%+ through 2027 following WTO review.',
        claim_basis: `Brief HYP SKD-02 WNTBT condition 1. Source: ${SKODA_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 17, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Tariff durability is the principal structural insulator for Skoda position; without it the hypothesis collapses.',
        impact_reasoning: 'Each percentage point of tariff sustained holds Chinese OEM landed prices above Skoda BOM.' },
      { component_name: 'MEB_PLATFORM_BOM_COST_REDUCTION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW Group MEB cost reductions deliver 15%+ BOM reduction on Skoda EV models by 2027.',
        claim_basis: `Brief HYP SKD-02 WNTBT condition 3. Source: ${SKODA_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 15, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cost reduction is the operational lever — without it Skoda cannot match Chinese pricing within tariff envelope.',
        impact_reasoning: 'Each percentage point of BOM reduction widens the price-competitiveness gap vs imports.' },
      { component_name: 'AFFORDABLE_EV_BATTERY_AND_SOFTWARE_VALUE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Enyaq and Elroq combined achieve 150,000+ annual European sales by 2026.',
        claim_basis: `Brief HYP SKD-02 WNTBT condition 2. Source: ${SKODA_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 150000, threshold_unit: 'units',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Volume threshold is the operational confirmation that affordable EV positioning works.',
        impact_reasoning: 'Volume scale amortises BOM reductions and reinforces top-3 position.' },
      { component_name: 'CHINESE_BEV_LOCAL_EU_ASSEMBLY', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'No Chinese EV brand establishes meaningful local European assembly bypassing tariffs before 2028 (>50k unit annual capacity).',
        claim_basis: `Brief HYP SKD-02 WNTBT condition 4. Source: ${SKODA_BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Successful Chinese local-assembly ramp is the structural threat to the tariff insulator.',
        impact_reasoning: 'BYD Hungary, Chery Spain, Geely Slovakia — collective ramp determines hypothesis falsification timeline.' },
    ],
  },

  // SKD-03 ---------------------------------------------------------------
  {
    name: 'Skoda Czech manufacturing as structural VW Group advantage in CEE consolidation',
    strategy_context: `Skoda Mlada Boleslav HQ + Czech assembly base. German production cost disadvantage widening per brief; CEE manufacturing cost benchmarks favour Czech sites. EU Battery Regulation local production criteria align with Czech production rather than German.`,
    brief_description: 'Whether Skoda\'s Czech manufacturing base becomes a structural advantage as VW Group consolidates production in CEE.',
    hypothesis_statement: `Skoda's Czech manufacturing base will become a structural VW Group advantage as EU localisation incentives tighten and German production costs accelerate CEE consolidation. Source: ${SKODA_BRIEF}, HYP SKD-03.`,
    why_it_matters: 'CEE manufacturing cost benchmarking, supply chain localisation modelling, and Czech regulatory intelligence are inputs Skoda\'s operations strategy team would act on directly.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${SKODA_BRIEF} HYP SKD-03 (H1 · 1–3yr)`,
    decision_threshold: [
      'VW Group designates Mlada Boleslav as strategic MEB production hub in 2026–2030 plan;',
      'Czech Republic secures EU Battery Regulation approved battery production within 100km of Skoda HQ by 2027;',
      'German factory cost disadvantage widens above 35% vs Czech equivalent by end-2025;',
      'No VW Group capacity closure affects Czech Republic through end-2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP SKD-03.)',
    ].join(' '),
    baseline_confidence: 0.58,
    current_confidence: 0.58,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags VW Group CEE investment plan AND EU Battery Regulation local production criteria as live SIGNAL drivers.',
    trajectory_reasoning: `Czech cost advantage widening per brief; localisation pressure increasing. Source: ${SKODA_BRIEF}.`,
    components: [
      {
        name: 'VW_GROUP_CEE_INVESTMENT_PLAN',
        description: 'VW Group CEE investment plan and production allocation. Market SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${SKODA_BRIEF} HYP SKD-03 (Market driver SIGNAL — VW Group CEE investment plan and production allocation); WNTBT bullets 1 + 4`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: VW Group investment plan announcements directionally favourable for Czech production.',
        trajectory_reasoning: 'CEE allocation increasing as German closures deferred.',
      },
      {
        name: 'EU_BATTERY_REGULATION_LOCAL_PRODUCTION',
        description: 'EU Battery Regulation local production criteria. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${SKODA_BRIEF} HYP SKD-03 (Policy driver SIGNAL — EU Battery Regulation local production criteria); WNTBT bullet 2`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'EU Battery Regulation in force; local production criteria tightening.',
        trajectory_reasoning: 'Trajectory favourable for Czech battery production within 100km of Skoda HQ.',
      },
      {
        name: 'GERMAN_VS_CZECH_FACTORY_COST_GAP',
        description: 'German vs Czech factory all-in cost per vehicle. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${SKODA_BRIEF} HYP SKD-03 (Economics driver — German vs Czech factory all-in cost per vehicle); WNTBT bullet 3`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Cost gap widening above 35% per WNTBT condition 3.',
        trajectory_reasoning: 'German energy + labour cost pressure sustained.',
      },
      {
        name: 'MLADA_BOLESLAV_MEB_SSP_READINESS',
        description: 'MEB and SSP platform readiness at Mlada Boleslav. Tech driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${SKODA_BRIEF} HYP SKD-03 (Technology driver — MEB and SSP platform readiness at Mlada Boleslav)`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'MEB operational at Mlada Boleslav; SSP migration planned.',
        trajectory_reasoning: 'Platform technology trajectory broadly aligned with VW Group SSP timeline.',
      },
    ],
    claims: [
      { component_name: 'VW_GROUP_CEE_INVESTMENT_PLAN', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VW Group designates Mlada Boleslav as strategic MEB production hub in the 2026–2030 plan.',
        claim_basis: `Brief HYP SKD-03 WNTBT condition 1. Source: ${SKODA_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Hub designation is the boardroom-level confirmation of the structural advantage.',
        impact_reasoning: 'Strategic hub status concentrates VW capital + technology investment in Czech production.' },
      { component_name: 'GERMAN_VS_CZECH_FACTORY_COST_GAP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'German factory cost disadvantage widens above 35% vs Czech equivalent by end-2025.',
        claim_basis: `Brief HYP SKD-03 WNTBT condition 3. Source: ${SKODA_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 35, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cost differential is the operational lever forcing CEE consolidation.',
        impact_reasoning: 'Each percentage point of widening cost gap accelerates capacity allocation toward Czech.' },
      { component_name: 'EU_BATTERY_REGULATION_LOCAL_PRODUCTION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Czech Republic secures EU Battery Regulation approved battery production within 100km of Skoda HQ by 2027.',
        claim_basis: `Brief HYP SKD-03 WNTBT condition 2. Source: ${SKODA_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Battery production proximity is the structural enabler of fully local Skoda EV value chain.',
        impact_reasoning: 'Local battery supply removes the most material remaining import dependency.' },
      { component_name: 'MLADA_BOLESLAV_MEB_SSP_READINESS', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A VW Group capacity closure affects Czech Republic before end-2026, falsifying the structural advantage thesis.',
        claim_basis: `Brief HYP SKD-03 WNTBT condition 4 (inverse). Source: ${SKODA_BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Czech capacity reduction would undermine the structural-advantage framing entirely.',
        impact_reasoning: 'Any closure signals VW Group does not view Czech as the consolidation winner.' },
    ],
  },
];

// ============================================================================
// PORSCHE AG (brand-level — companies row id=99 "Porsche AG")
// ============================================================================

const porscheCompany = {
  name: 'Porsche AG',
  sector: 'mobility',
  notes: 'Dr. Ing. h.c. F. Porsche AG. Brand-level hypotheses sourced from March 2026 brief.',
};

const porscheInitiatives = [
  // PAG-01 ---------------------------------------------------------------
  {
    name: 'Porsche eFuels EU carve-out by 2026 preserves 911 ICE beyond 2035',
    strategy_context: `Porsche operates Haru Oni eFuels plant (Chile) at demonstration scale. EU 2026 ICE ban review is the legislative gate. Brief assesses High confidence on the carve-out scenario — Porsche has politically secured initial carve-out language but commercial production economics need to validate.`,
    brief_description: 'Whether Porsche\'s eFuels programme secures formal EU legislative carve-out for high-performance combustion vehicles by 2026.',
    hypothesis_statement: `Porsche's eFuels programme will secure a formal EU legislative carve-out for high-performance combustion vehicles by 2026, preserving the 911 ICE beyond 2035. Source: ${PORSCHE_BRIEF}, HYP PAG-01.`,
    why_it_matters: 'eFuels regulatory trajectory and production economics are the intelligence inputs Porsche\'s strategy team is most reliant on external validation for. FutureBridge engagement is on the regulatory + production economics intersection.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2026,
    time_horizon_source: `${PORSCHE_BRIEF} HYP PAG-01 (H2 · 4–7yr)`,
    decision_threshold: [
      'EU 2026 review includes a binding eFuels exemption for vehicles above €80,000;',
      'Porsche\'s Haru Oni plant reaches 55ML/yr commercial production by end-2026;',
      'eFuel production cost falls below €1.80/litre at project scale;',
      'No major EU member state pre-empts the 2035 rule with an earlier ICE ban.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP PAG-01.)',
    ].join(' '),
    baseline_confidence: 0.72,
    current_confidence: 0.72,
    state: 'ambiguous',
    trajectory: 'volatile',
    state_reasoning: 'Brief flags Tech (electrolyser efficiency + e-methanol synthesis) AND Policy (eFuels exemption) as live SIGNAL drivers — both load-bearing.',
    trajectory_reasoning: `Outcome volatile until 2026 EU review concludes. Source: ${PORSCHE_BRIEF} HYP PAG-01.`,
    components: [
      {
        name: 'EU_EFUELS_VEHICLE_EXEMPTION_CATEGORY',
        description: 'EU eFuels vehicle exemption category definition in 2026 review legislative language. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-01 (Policy driver SIGNAL — EU eFuels vehicle exemption category definition); WNTBT bullet 1`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'EU 2026 review consultation underway; category definition pending.',
        trajectory_reasoning: 'Outcome depends on member-state alignment.',
      },
      {
        name: 'HARU_ONI_ELECTROLYSER_AND_E_METHANOL',
        description: 'Haru Oni electrolyser efficiency and e-methanol synthesis. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-01 (Technology driver SIGNAL — Electrolyser efficiency and e-methanol synthesis); WNTBT bullet 2`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Plant in commissioning phase; production milestones tracked.',
        trajectory_reasoning: 'Brief LIVE NOW: Haru Oni production milestone updates indicate scale-up advancing.',
      },
      {
        name: 'EFUELS_PRODUCTION_COST_PER_LITRE',
        description: 'eFuel production cost per litre at Haru Oni scale. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-01 (Economics driver — eFuel production cost per litre at Haru Oni scale); WNTBT bullet 3`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'Commercial cost data emerging; threshold €1.80/litre per WNTBT.',
        trajectory_reasoning: 'Cost trajectory depends on electrolyser ramp + electricity price at site.',
      },
      {
        name: 'EU_2026_ICE_REVIEW_LEGISLATIVE_LANGUAGE',
        description: 'EU 2026 ICE ban review legislative language and member-state pre-emption risk. Market driver per brief — currently NOT signalled but tracked.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-01 (Market driver — EU 2026 ICE ban review legislative language); WNTBT bullet 4`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Member-state pre-emption (e.g. national earlier-ban moves) would bypass the carve-out.',
        trajectory_reasoning: 'Volatile — depends on individual member-state legislative cycles.',
      },
    ],
    claims: [
      { component_name: 'EU_EFUELS_VEHICLE_EXEMPTION_CATEGORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'EU 2026 review includes a binding eFuels exemption for vehicles above €80,000.',
        claim_basis: `Brief HYP PAG-01 WNTBT condition 1. Source: ${PORSCHE_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 80000, threshold_unit: 'EUR',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Carve-out language is the principal legislative hook — without it the hypothesis fails by definition.',
        impact_reasoning: 'Binding exemption preserves the 911 ICE beyond 2035 directly.' },
      { component_name: 'HARU_ONI_ELECTROLYSER_AND_E_METHANOL', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Porsche\'s Haru Oni plant reaches 55ML/yr commercial production by end-2026.',
        claim_basis: `Brief HYP PAG-01 WNTBT condition 2. Source: ${PORSCHE_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 55, threshold_unit: 'ML_per_year',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Commercial scale demonstrates eFuels are technically viable at the volume the carve-out implies.',
        impact_reasoning: 'Production milestone validates the policy framework.' },
      { component_name: 'EFUELS_PRODUCTION_COST_PER_LITRE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'eFuel production cost falls below €1.80/litre at project scale.',
        claim_basis: `Brief HYP PAG-01 WNTBT condition 3. Source: ${PORSCHE_BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 1.80, threshold_unit: 'EUR_per_litre',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cost threshold establishes commercial-economic viability for premium ICE customers.',
        impact_reasoning: 'Below threshold, eFuels pencil for the 911 customer at pump-equivalent supplement.' },
      { component_name: 'EU_2026_ICE_REVIEW_LEGISLATIVE_LANGUAGE', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'A major EU member state pre-empts the 2035 rule with an earlier national ICE ban, bypassing the eFuels carve-out.',
        claim_basis: `Brief HYP PAG-01 WNTBT condition 4 (inverse). Source: ${PORSCHE_BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A single Western European member state with an earlier ban materially shrinks Porsche\'s addressable ICE market.',
        impact_reasoning: 'Pre-emption defeats the EU-level carve-out at member-state level.' },
    ],
  },

  // PAG-02 ---------------------------------------------------------------
  {
    name: 'Porsche Taycan sustains 15-25% premium over Tesla Model S Plaid and BYD Han through 2028',
    strategy_context: `Taycan refresh in market. 800V architecture and porsche-specific charging experience. BYD Han European launch and Tesla repositioning are the competitive challenges. Brief assesses High confidence on premium sustainability.`,
    brief_description: 'Whether Taycan sustains 15-25% price premium over Tesla Model S Plaid and BYD Han through 2028.',
    hypothesis_statement: `Porsche's Taycan will sustain a 15–25% price premium over Tesla Model S Plaid and comparable BYD Han performance EVs through 2028. Source: ${PORSCHE_BRIEF}, HYP PAG-02.`,
    why_it_matters: 'Performance EV battery technology and high-voltage fast charging experience are where Porsche\'s technology scouting is focused. Active engagement opportunity on these technologies.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${PORSCHE_BRIEF} HYP PAG-02 (H1 · 2–4yr)`,
    decision_threshold: [
      'Taycan refresh receives top-tier critical reception with no quality regression;',
      'Porsche customer satisfaction scores remain above 85% in core markets through 2026;',
      'BYD Han does not achieve meaningful European premium penetration above 3% in €80k+ segment;',
      'Tesla premium repositioning does not materially erode Porsche brand equity in JD Power surveys.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP PAG-02.)',
    ].join(' '),
    baseline_confidence: 0.69,
    current_confidence: 0.69,
    state: 'holding',
    trajectory: 'stable',
    state_reasoning: 'Brief assesses High confidence — Taycan position established, BYD Han European entry pending.',
    trajectory_reasoning: `Trajectory stable; hypothesis depends on durability of Porsche brand equity. Source: ${PORSCHE_BRIEF}.`,
    components: [
      {
        name: 'BYD_HAN_TESLA_MS_EUROPEAN_PREMIUM_SHARE',
        description: 'BYD Han and Tesla Model S European premium segment share. Market SIGNAL driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-02 (Market driver SIGNAL — BYD Han and Tesla Model S European premium share); WNTBT bullets 3 + 4`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'BYD Han European launch in progress; Tesla repositioning ongoing.',
        trajectory_reasoning: 'Volatile — depends on BYD pricing and Tesla brand strategy.',
      },
      {
        name: 'PORSCHE_800V_FAST_CHARGING_TECH',
        description: '800V charging and battery performance benchmarks. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-02 (Technology driver SIGNAL — 800V charging and battery performance benchmarks)`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'Porsche 800V architecture in market; performance benchmarks competitive.',
        trajectory_reasoning: 'Battery performance improving generation-on-generation.',
      },
      {
        name: 'TAYCAN_AVG_TRANSACTION_PRICE_VS_PEERS',
        description: 'Taycan average transaction price vs Tesla Model S Plaid and BYD Han. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-02 (Economics driver — Taycan average transaction price vs Tesla and BYD)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'Taycan ATP holding 15-25% premium per hypothesis.',
        trajectory_reasoning: 'Stable absent BYD Han pricing aggression.',
      },
      {
        name: 'EU_PREMIUM_EV_PURCHASE_INCENTIVE',
        description: 'EU premium EV purchase incentive eligibility. Policy driver per brief — currently NOT signalled.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-02 (Policy driver — EU premium EV purchase incentive eligibility)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'EU incentive eligibility largely excludes premium segment; framework stable.',
        trajectory_reasoning: 'Premium incentive policy unlikely to shift materially.',
      },
    ],
    claims: [
      { component_name: 'TAYCAN_AVG_TRANSACTION_PRICE_VS_PEERS', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Taycan refresh receives top-tier critical reception with no quality regression, sustaining the 15-25% price premium.',
        claim_basis: `Brief HYP PAG-02 WNTBT condition 1. Source: ${PORSCHE_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Critical reception is the principal validator of the premium position.',
        impact_reasoning: 'Quality regression would directly justify peer pricing parity, breaking the premium.' },
      { component_name: 'PORSCHE_800V_FAST_CHARGING_TECH', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Porsche customer satisfaction scores remain above 85% in core markets through 2026.',
        claim_basis: `Brief HYP PAG-02 WNTBT condition 2. Source: ${PORSCHE_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 85, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Customer satisfaction proxies for the full Porsche experience including charging.',
        impact_reasoning: 'Sustained satisfaction reinforces brand equity supporting premium.' },
      { component_name: 'BYD_HAN_TESLA_MS_EUROPEAN_PREMIUM_SHARE', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'BYD Han achieves meaningful European premium penetration above 3% in the €80k+ segment, eroding Porsche premium positioning.',
        claim_basis: `Brief HYP PAG-02 WNTBT condition 3 (inverse). Source: ${PORSCHE_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 3, threshold_unit: 'pct',
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'BYD Han breakthrough is the structural threat to premium pricing.',
        impact_reasoning: 'Each percentage point of BYD share at €80k+ compresses Porsche pricing power.' },
      { component_name: 'EU_PREMIUM_EV_PURCHASE_INCENTIVE', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'Tesla premium repositioning materially erodes Porsche brand equity in JD Power surveys.',
        claim_basis: `Brief HYP PAG-02 WNTBT condition 4 (inverse). Source: ${PORSCHE_BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Tesla premium move is a parallel threat — different customer pool, but equity erosion via comparison.',
        impact_reasoning: 'Brand equity erosion shows in survey data 6-12 months before pricing follows.' },
    ],
  },

  // PAG-03 ---------------------------------------------------------------
  {
    name: 'Porsche motorsport + experiential business as primary brand investment by 2028',
    strategy_context: `Porsche Cup, Carrera Cup, Formula E, WEC programmes. Porsche Experience Centres expanding. Brief argues digital channels commoditise traditional automotive advertising — motorsport + experiential becomes the differentiating brand investment.`,
    brief_description: 'Whether Porsche\'s motorsport + experiential business becomes the primary brand investment by 2028.',
    hypothesis_statement: `Porsche's motorsport and experiential business will become the primary brand building investment by 2028 as digital channels commoditise traditional automotive advertising. Source: ${PORSCHE_BRIEF}, HYP PAG-03.`,
    why_it_matters: 'Motorsport technology — electric racing powertrain, tyre telemetry, energy recovery — maps directly to Porsche\'s experiential brand agenda and is the active scouting category.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${PORSCHE_BRIEF} HYP PAG-03 (H2 · 3–6yr)`,
    decision_threshold: [
      'Porsche Cup and Carrera Cup expand to 5+ new markets by end-2027;',
      'Porsche Experience Centres generate €500M+ cumulative revenue from 2025–2028;',
      'At least two Formula E or WEC manufacturers exit, increasing Porsche motorsport visibility premium;',
      'Porsche brand value outperforms Ferrari and Lamborghini in 2025 and 2026 rankings.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP PAG-03.)',
    ].join(' '),
    baseline_confidence: 0.60,
    current_confidence: 0.60,
    state: 'new',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Tech (electric racing powertrain) AND Market (premium brand value) as live SIGNALs. Hypothesis is gaining structural support but is not yet fully confirmed.',
    trajectory_reasoning: `Brief signals Porsche motorsport expansion and Experience Centre revenue ramp. Source: ${PORSCHE_BRIEF}.`,
    components: [
      {
        name: 'PORSCHE_PREMIUM_BRAND_VALUE_VS_FERRARI_LAMBO',
        description: 'Premium automotive brand value vs Ferrari and Lamborghini. Market SIGNAL driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-03 (Market driver SIGNAL — Premium automotive brand value vs Ferrari and Lamborghini); WNTBT bullet 4`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'Brand value rankings show Porsche competitive with Italian premium peers.',
        trajectory_reasoning: 'Brand value trajectory improving on motorsport + experiential investment.',
      },
      {
        name: 'ELECTRIC_RACING_POWERTRAIN_AND_RECOVERY',
        description: 'Electric racing powertrain and energy recovery systems. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-03 (Technology driver SIGNAL — Electric racing powertrain and energy recovery systems)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Formula E + WEC programmes drive technology development; Porsche actively investing.',
        trajectory_reasoning: 'Each season raises performance benchmarks.',
      },
      {
        name: 'PORSCHE_EXPERIENCE_CENTRE_AND_MOTORSPORT_REVENUE',
        description: 'Porsche Experience Centre and motorsport revenue. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-03 (Economics driver — Porsche Experience Centre and motorsport revenue); WNTBT bullets 1 + 2`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Experience Centre revenue ramp consistent with €500M cumulative target.',
        trajectory_reasoning: 'Brief LIVE NOW: Porsche motorsport series expansion announcements.',
      },
      {
        name: 'FORMULA_E_WEC_MANUFACTURER_COMMITMENT',
        description: 'Formula E and WEC manufacturer commitment rules. Policy driver per brief — currently NOT signalled.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${PORSCHE_BRIEF} HYP PAG-03 (Policy driver — Formula E and WEC manufacturer commitment rules); WNTBT bullet 3`,
        state: 'holding', trajectory: 'volatile',
        state_reasoning: 'Manufacturer commitment rules stable but exits possible; framework otherwise stable.',
        trajectory_reasoning: 'Volatile — depends on individual manufacturer cost calculus.',
      },
    ],
    claims: [
      { component_name: 'PORSCHE_EXPERIENCE_CENTRE_AND_MOTORSPORT_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Porsche Experience Centres generate €500M+ cumulative revenue from 2025–2028 AND Cup / Carrera Cup expand to 5+ new markets by end-2027.',
        claim_basis: `Brief HYP PAG-03 WNTBT conditions 1 + 2. Source: ${PORSCHE_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 500, threshold_unit: 'EUR_million_cumulative',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Combined revenue + market expansion is the principal commercial confirmation.',
        impact_reasoning: 'Revenue scale validates investment thesis at boardroom level.' },
      { component_name: 'PORSCHE_PREMIUM_BRAND_VALUE_VS_FERRARI_LAMBO', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Porsche brand value outperforms Ferrari and Lamborghini in 2025 and 2026 rankings.',
        claim_basis: `Brief HYP PAG-03 WNTBT condition 4. Source: ${PORSCHE_BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Brand value relative ranking is the cross-segment validation.',
        impact_reasoning: 'Outperformance vs Italian premium peers signals motorsport + experiential investment paying out.' },
      { component_name: 'FORMULA_E_WEC_MANUFACTURER_COMMITMENT', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'At least two Formula E or WEC manufacturers exit, increasing Porsche motorsport visibility premium.',
        claim_basis: `Brief HYP PAG-03 WNTBT condition 3. Source: ${PORSCHE_BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Manufacturer attrition concentrates motorsport visibility on remaining participants.',
        impact_reasoning: 'Each manufacturer exit raises Porsche\'s share of total motorsport mind-share.' },
    ],
  },
];

// ============================================================================
// EXECUTE — three sequential populations (one transaction each)
// ============================================================================

console.log('=================== VW Group ===================');
await runPopulation({ company: vwgCompany, initiatives: vwgInitiatives, dryRun: !COMMIT });
console.log('\n=================== Skoda Auto ===================');
await runPopulation({ company: skodaCompany, initiatives: skodaInitiatives, dryRun: !COMMIT });
console.log('\n=================== Porsche AG ===================');
await runPopulation({ company: porscheCompany, initiatives: porscheInitiatives, dryRun: !COMMIT });
