// db/population/P4_audi_hypotheses.mjs
// Source: audi_intelligence_brief__3_.html (March 2026 brief).
// Three hypotheses: AUD-01 second restructuring round, AUD-02 PPE platform decisive, AUD-03 China retreat to ultra-premium.
// PG company: id=101 (Audi AG).
//
// Run:
//   node db/population/P4_audi_hypotheses.mjs           # dry-run
//   node db/population/P4_audi_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'audi_intelligence_brief__3_.html (March 2026)';

const company = {
  name: 'Audi AG',
  sector: 'mobility',
  notes: 'Audi AG — VW Group premium subsidiary. HQ: Ingolstadt, Germany. CARIAD software dependency, PPE platform launch (Q6/A6 e-tron), China JV restructuring all live. v2 catalogue first-cut hypotheses sourced from March 2026 brief.',
};

const initiatives = [
  // AUD-01 ----------------------------------------------------------------
  {
    name: 'Audi 18,000 job cut programme insufficient — second restructuring round before 2028',
    strategy_context: `Audi announced 18,000-job cost programme in 2024-2025. Group margin target 10% by 2026. Brief assesses High confidence that the programme will not restore margin, forcing a second restructuring round before 2028. China share decline + PPE platform commercial uncertainty compound the cost pressure.`,
    brief_description: 'Whether Audi\'s 18k job cut programme fails to restore group margin above 10% by 2027, requiring a second round.',
    hypothesis_statement: `Audi's 18,000 job cut programme will not restore group margin above 10% by 2027 — a second restructuring round is likely before 2028. Source: ${BRIEF}, HYP AUD-01.`,
    why_it_matters: 'The restructuring window opens a technology partnership opportunity — Audi will rationalise internal R&D and seek external innovation at lower commitment thresholds. Engagement entry at reduced commitment threshold.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP AUD-01 (H1 · 1-2yr)`,
    decision_threshold: [
      'Audi EBIT margin fails to recover above 8% in both 2025 and 2026;',
      'VW Group formally announces second round of Audi cost targets before end-2026;',
      'PPE platform vehicle launches miss first-year sales targets by more than 15%;',
      'Audi China market share falls below 8% in 2025.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP AUD-01.)',
    ].join(' '),
    baseline_confidence: 0.70,
    current_confidence: 0.70,
    state: 'strengthening',
    trajectory: 'deteriorating',
    state_reasoning: 'Brief flags Economics (Audi EBIT recovery vs target) AND Market (China premium EV brand share shift) as live SIGNAL drivers. Multiple WNTBT conditions tracking toward confirmation.',
    trajectory_reasoning: `Audi China share decline + PPE launch performance + IG Metall labour pressure all compound restructuring inadequacy. Source: ${BRIEF}.`,
    components: [
      {
        name: 'AUDI_EBIT_MARGIN_RECOVERY',
        description: 'Audi EBIT margin recovery vs 10% target. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-01 (Economics SIGNAL — Audi EBIT margin recovery vs 10% target); WNTBT bullet 1`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Audi EBIT margin under 8% in 2024; recovery toward 10% target uncertain.',
        trajectory_reasoning: 'Brief LIVE NOW: Audi quarterly earnings releases trending below target.',
      },
      {
        name: 'CHINA_PREMIUM_EV_SHARE_SHIFT',
        description: 'China premium EV brand market share shift. Market SIGNAL driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-01 (Market SIGNAL — China premium EV brand market share shift); WNTBT bullet 4`,
        state: 'strengthening', trajectory: 'deteriorating',
        state_reasoning: 'NIO, Li Auto, Huawei-backed brands eroding Audi China premium share.',
        trajectory_reasoning: 'Audi China share trajectory consistent with sub-8% by 2025.',
      },
      {
        name: 'PPE_PLATFORM_LAUNCH_PERFORMANCE',
        description: 'PPE platform commercial launch performance. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-01 (Technology — PPE commercial launch performance); WNTBT bullet 3`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'PPE Q6 e-tron + A6 e-tron in early commercial; first-year sales pending.',
        trajectory_reasoning: 'Brief LIVE NOW: PPE vehicle review scores and sales data.',
      },
      {
        name: 'VWG_AUDI_RESTRUCTURING_GOVERNANCE',
        description: 'VW Group governance and IG Metall labour agreement. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-01 (Policy — VW Group governance and IG Metall agreement); WNTBT bullet 2`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Second cost round pending VWG board decision; IG Metall opposition likely (per VW-01 hypothesis).',
        trajectory_reasoning: 'Volatile — depends on 2026 labour agreement outcome.',
      },
    ],
    claims: [
      { component_name: 'AUDI_EBIT_MARGIN_RECOVERY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Audi EBIT margin fails to recover above 8% in both 2025 and 2026.',
        claim_basis: `Brief HYP AUD-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 8, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'EBIT margin is the principal financial confirmation that current restructuring is insufficient.',
        impact_reasoning: 'Each percentage point below 8% strengthens the second-round case.' },
      { component_name: 'VWG_AUDI_RESTRUCTURING_GOVERNANCE', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VW Group formally announces second round of Audi cost targets before end-2026.',
        claim_basis: `Brief HYP AUD-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Public announcement of second round is the boardroom-level confirmation.',
        impact_reasoning: 'Public framing forces accelerated cost-cut execution.' },
      { component_name: 'PPE_PLATFORM_LAUNCH_PERFORMANCE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'PPE platform vehicle launches miss first-year sales targets by more than 15%.',
        claim_basis: `Brief HYP AUD-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 15, threshold_unit: 'pct_miss',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'PPE underperformance compounds revenue pressure on top of cost issues.',
        impact_reasoning: 'Each percentage point miss adds to inadequate-restructuring case.' },
      { component_name: 'CHINA_PREMIUM_EV_SHARE_SHIFT', role: 'external_threat', impact: 'amplifying', criticality: 'high',
        claim_text: 'Audi China market share falls below 8% in 2025.',
        claim_basis: `Brief HYP AUD-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 8, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'China share collapse is the external threat that amplifies restructuring inadequacy.',
        impact_reasoning: 'Each percentage point of China share loss reduces revenue base for cost amortisation.' },
    ],
  },

  // AUD-02 ----------------------------------------------------------------
  {
    name: 'PPE Premium Platform Electric determines Audi BEV competitive position through 2030',
    strategy_context: `PPE = Audi/Porsche premium electric platform. Q6 e-tron + A6 e-tron + Q8 e-tron + Macan EV (Porsche). 800V charging architecture. Brief assesses Medium confidence — commercial success or failure of PPE dictates the next-architecture decision (SSP successor or alternative).`,
    brief_description: 'Whether PPE commercial performance determines Audi\'s competitive BEV position through 2030.',
    hypothesis_statement: `The PPE Premium Platform Electric will determine Audi's competitive BEV position through 2030 — its commercial success or failure dictates the next architecture decision. Source: ${BRIEF}, HYP AUD-02.`,
    why_it_matters: 'PPE battery integration, thermal management, and software stack are the technology vectors Audi R&D scouting is most active on right now.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP AUD-02 (H2 · 3-5yr)`,
    decision_threshold: [
      'A6 e-tron and Q6 e-tron achieve combined European sales above 80,000 units in first full year;',
      'PPE 800V fast-charging remains best-in-class vs Mercedes EQ and BMW i through 2026;',
      'VW Group confirms SSP successor to PPE will enter production before 2030;',
      'Audi PPE gross margin exceeds equivalent ICE platform margin by end-2027.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP AUD-02.)',
    ].join(' '),
    baseline_confidence: 0.67,
    current_confidence: 0.67,
    state: 'new',
    trajectory: 'volatile',
    state_reasoning: 'Brief flags Economics (PPE gross margin) AND Technology (800V charging) as live SIGNAL drivers. Commercial outcome pending PPE first-full-year results.',
    trajectory_reasoning: `Q6 e-tron + A6 e-tron review reception positive but volume vs targets uncertain. Source: ${BRIEF}.`,
    components: [
      {
        name: 'PPE_GROSS_MARGIN_VS_ICE',
        description: 'PPE gross margin vs equivalent ICE platform. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-02 (Economics SIGNAL — PPE gross margin vs ICE); WNTBT bullet 4`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'PPE gross margin emerging; ICE-parity by end-2027 is WNTBT.',
        trajectory_reasoning: 'Volatile — depends on volume + BOM cost reductions.',
      },
      {
        name: 'PPE_800V_CHARGING_PERFORMANCE',
        description: 'PPE 800V charging performance vs Mercedes EQ and BMW i. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-02 (Technology SIGNAL — 800V charging performance vs Tesla and Mercedes); WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Audi PPE 800V architecture currently best-in-class among German premium BEVs.',
        trajectory_reasoning: 'Mercedes 800V (MMA + AMG.EA) catching up; competition tightening.',
      },
      {
        name: 'A6_Q6_ETRON_FIRST_YEAR_SALES',
        description: 'A6 + Q6 e-tron first-year European sales. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-02 (Market — A6 + Q6 e-tron first-year sales); WNTBT bullet 1`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'Brief LIVE NOW: Q6 e-tron European sales data Q1 2026 emerging.',
        trajectory_reasoning: '80k+ first-full-year combined target ambitious; pending Q3 2026 results.',
      },
      {
        name: 'VWG_SSP_SUCCESSOR_TIMELINE',
        description: 'VW Group SSP platform timeline and investment. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-02 (Policy — VWG SSP platform timeline); WNTBT bullet 3`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'SSP successor timeline confirmed by VWG (per VW-02 hypothesis); 2026 → potential 18+ month delay.',
        trajectory_reasoning: 'Volatile — VWG SSP delivery risk + Audi PPE bridge dependency.',
      },
    ],
    claims: [
      { component_name: 'A6_Q6_ETRON_FIRST_YEAR_SALES', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'A6 e-tron and Q6 e-tron achieve combined European sales above 80,000 units in first full year.',
        claim_basis: `Brief HYP AUD-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 80000, threshold_unit: 'units_first_full_year',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'First-year sales are the principal commercial confirmation of PPE viability.',
        impact_reasoning: 'Each unit above 80k strengthens the platform-as-decisive thesis.' },
      { component_name: 'PPE_GROSS_MARGIN_VS_ICE', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Audi PPE gross margin exceeds equivalent ICE platform margin by end-2027.',
        claim_basis: `Brief HYP AUD-02 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Gross margin parity is the financial threshold for platform commitment.',
        impact_reasoning: 'PPE > ICE margin justifies SSP successor investment.' },
      { component_name: 'PPE_800V_CHARGING_PERFORMANCE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'PPE 800V fast-charging remains best-in-class vs Mercedes EQ and BMW i through 2026.',
        claim_basis: `Brief HYP AUD-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Technical leadership underwrites the premium pricing case.',
        impact_reasoning: 'Lost charging-speed leadership compresses pricing power.' },
      { component_name: 'VWG_SSP_SUCCESSOR_TIMELINE', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'VW Group confirms SSP successor to PPE will enter production before 2030.',
        claim_basis: `Brief HYP AUD-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Without SSP successor confirmation, PPE becomes orphaned rather than transitional.',
        impact_reasoning: 'SSP delay (per VW-02) extends PPE service life and amortisation window.' },
    ],
  },

  // AUD-03 ----------------------------------------------------------------
  {
    name: 'Audi China sales stabilise <500k by 2027 through deliberate ultra-premium retreat',
    strategy_context: `Audi China sales declining since 2023 peak. Local premium EVs (NIO, Li Auto, Huawei Aito, Xiaomi SU7 Ultra) eroding share at CNY 400k+. Brief assesses Medium confidence on a deliberate strategic retreat to ultra-premium-only positioning, abandoning volume competition.`,
    brief_description: 'Whether Audi deliberately retreats to ultra-premium China positioning, stabilising sales below 500k by 2027.',
    hypothesis_statement: `Audi's China sales will stabilise below 500,000 units by 2027 through deliberate retreat to ultra-premium, abandoning volume competition with local EV brands. Source: ${BRIEF}, HYP AUD-03.`,
    why_it_matters: 'China luxury consumer intelligence and premium EV competitive benchmarking are inputs Audi\'s Asia-Pacific strategy team cannot build internally at speed.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP AUD-03 (H2 · 4-7yr)`,
    decision_threshold: [
      'Audi China publicly repositions as top-end premium only brand by end-2025;',
      'SAIC-VW and FAW-VW JV renegotiation delivers new equity structure before end-2026;',
      'Audi launches China-specific technology feature developed locally without VW Group delay;',
      'Audi China average transaction price increases more than 15% by end-2026 as volumes decline.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP AUD-03.)',
    ].join(' '),
    baseline_confidence: 0.58,
    current_confidence: 0.58,
    state: 'strengthening',
    trajectory: 'volatile',
    state_reasoning: 'Brief flags Market (NIO/Li Auto/Huawei share) as live SIGNAL driver. Audi China repositioning under consideration.',
    trajectory_reasoning: `Volatile — depends on whether VWG/Audi formally adopts retreat strategy or attempts volume defence. Source: ${BRIEF}.`,
    components: [
      {
        name: 'AUDI_CHINA_REPOSITIONING_TO_PREMIUM_ONLY',
        description: 'Audi China public repositioning to top-end premium only. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-03 (Market — Audi China repositioning); WNTBT bullet 1`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'No public repositioning announcement as of brief; pending VWG board decision.',
        trajectory_reasoning: 'Volatile — depends on Q3-Q4 2025 announcements.',
      },
      {
        name: 'NIO_LI_AUTO_HUAWEI_400K_SHARE',
        description: 'NIO, Li Auto, Huawei share of CNY 400k+ segment. Market SIGNAL driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-03 (Market SIGNAL — NIO/Li Auto/Huawei share)`,
        state: 'strengthening', trajectory: 'deteriorating',
        state_reasoning: 'Brief LIVE NOW: Local premium EV brand quarterly deliveries rising at CNY 400k+.',
        trajectory_reasoning: 'Trajectory unfavourable for Audi volume in this segment.',
      },
      {
        name: 'AUDI_CHINA_ATP_TRAJECTORY',
        description: 'Audi China average transaction price trend. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-03 (Economics — Audi China ATP); WNTBT bullet 4`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'ATP rising as Audi tilts mix toward higher trim; volume falling.',
        trajectory_reasoning: '+15% by end-2026 directionally consistent with mix shift.',
      },
      {
        name: 'SAIC_FAW_VW_AUDI_JV_RENEGOTIATION',
        description: 'SAIC-VW and FAW-VW JV renegotiation terms. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP AUD-03 (Policy — SAIC-VW + FAW-VW JV renegotiation); WNTBT bullet 2`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'JV renegotiation pressure consistent with VW-03 hypothesis context.',
        trajectory_reasoning: 'Volatile — outcome depends on multilateral negotiation.',
      },
    ],
    claims: [
      { component_name: 'AUDI_CHINA_REPOSITIONING_TO_PREMIUM_ONLY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Audi China publicly repositions as top-end premium only brand by end-2025.',
        claim_basis: `Brief HYP AUD-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Public repositioning is the strategic confirmation of the deliberate retreat.',
        impact_reasoning: 'Without public framing, retreat looks like decline rather than strategy.' },
      { component_name: 'AUDI_CHINA_ATP_TRAJECTORY', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Audi China average transaction price increases more than 15% by end-2026 as volumes decline.',
        claim_basis: `Brief HYP AUD-03 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 15, threshold_unit: 'pct_increase',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'ATP rise + volume decline is the operational signature of deliberate retreat.',
        impact_reasoning: 'Each percentage point of ATP rise validates the premium-only thesis.' },
      { component_name: 'SAIC_FAW_VW_AUDI_JV_RENEGOTIATION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'SAIC-VW and FAW-VW JV renegotiation delivers new equity structure before end-2026.',
        claim_basis: `Brief HYP AUD-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'JV restructuring enables China-specific product autonomy.',
        impact_reasoning: 'New equity structure reduces VWG-imposed delay on China-specific features.' },
      { component_name: 'NIO_LI_AUTO_HUAWEI_400K_SHARE', role: 'external_threat', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Audi launches China-specific technology feature developed locally without VW Group delay.',
        claim_basis: `Brief HYP AUD-03 WNTBT condition 3 (mapped to local-tech response to local competition). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Local-tech autonomy is the operational requirement for ultra-premium positioning vs NIO/Li Auto/Huawei.',
        impact_reasoning: 'Each China-specific feature reduces VWG-induced execution lag.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
