// db/population/P4_infineon_hypotheses.mjs
// Source: infineon_intelligence_brief__4_.html (March 2026 brief).
// Three hypotheses: IFX-01 SiC margin compression, IFX-02 inventory recovery, IFX-03 data centre AI power.
// PG company: id=12 (Infineon Technologies AG).
//
// Run:
//   node db/population/P4_infineon_hypotheses.mjs           # dry-run
//   node db/population/P4_infineon_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'infineon_intelligence_brief__4_.html (March 2026)';

const company = {
  name: 'Infineon Technologies AG',
  sector: 'mobility',
  notes: 'Infineon Technologies AG — German power semiconductor and automotive SoC supplier. v2 catalogue first-cut hypotheses sourced from March 2026 brief.',
};

const initiatives = [
  // IFX-01 ----------------------------------------------------------------
  {
    name: 'Infineon SiC margin compression from Chinese IDM and STMicro pressure by 2027',
    strategy_context: `Infineon is the global #1 SiC power semiconductor supplier with ~45% automotive segment margins. Chinese IDMs (BYD Semiconductor, CRRC) and STMicroelectronics (Catania fab) are scaling SiC capacity into 2025-2027. Pricing pressure is the SIGNAL driver as wafer costs decline and OEM dual-sourcing strategies emerge.`,
    brief_description: 'Whether sustained competitive pressure compresses Infineon automotive SiC margins from ~45% to <35% by 2027.',
    hypothesis_statement: `Infineon's SiC power semiconductor market share will face sustained pressure from Chinese IDMs and STMicro by 2027, compressing automotive SiC margins from around 45% to below 35%. Source: ${BRIEF}, HYP IFX-01.`,
    why_it_matters: 'Margin compression in Infineon\'s flagship growth segment forces strategic choices on capacity, pricing, and customer mix. Engagement entry on competitor capability mapping and customer dual-sourcing intelligence.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP IFX-01 (H2 · 3-5yr)`,
    decision_threshold: [
      'BYD Semiconductor or CRRC ships SiC modules at volume to Tier-1 automotive outside China before 2027;',
      'STMicro Catania SiC fab reaches 100,000 wafer starts per month by end-2026;',
      'Average SiC MOSFET wafer price falls below $300 at 200mm equivalent by end-2026;',
      'At least one European OEM dual-sources SiC inverters with a non-Infineon supplier by 2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP IFX-01.)',
    ].join(' '),
    baseline_confidence: 0.70,
    current_confidence: 0.70,
    state: 'strengthening',
    trajectory: 'deteriorating',
    state_reasoning: 'Brief flags Economics (wafer price) AND Market (Chinese IDM share) as live SIGNAL drivers — both reinforcing the margin compression case.',
    trajectory_reasoning: `SiC capacity additions across STMicro Catania, Wolfspeed Mohawk Valley, BYD Semiconductor accelerating into 2025-2027 — supply growth ahead of demand recovery. Source: ${BRIEF} HYP IFX-01.`,
    components: [
      {
        name: 'CHINESE_IDM_SIC_QUALIFICATION',
        description: 'Chinese SiC IDM (BYD Semiconductor, CRRC) automotive qualification status and yield rates. Market SIGNAL driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP IFX-01 (Market driver SIGNAL — Chinese IDM and STMicro automotive SiC share); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'volatile',
        state_reasoning: 'Brief LIVE NOW: BYD Semiconductor customer qualification news ongoing.',
        trajectory_reasoning: 'Pace volatile — depends on Tier-1 qualification timelines and yield achievement.',
      },
      {
        name: 'STMICRO_CATANIA_SIC_FAB_RAMP',
        description: 'STMicroelectronics Catania SiC fab capacity ramp. WNTBT condition 2: 100k wafer starts per month by end-2026.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP IFX-01 WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'STMicro Catania fab in active ramp; Bosch SiC partnership announced 2025 production.',
        trajectory_reasoning: 'Yole Group confirms STMicro entering production 2025; trajectory improving for capacity but pressuring incumbents.',
      },
      {
        name: 'SIC_WAFER_PRICE_TRAJECTORY',
        description: 'SiC MOSFET wafer price per 200mm equivalent. Economics SIGNAL driver and WNTBT condition 3.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP IFX-01 (Economics driver SIGNAL — SiC MOSFET wafer price); WNTBT bullet 3`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Wafer prices declining as capacity additions outpace BEV demand recovery 2024-2025.',
        trajectory_reasoning: 'Brief LIVE NOW: SiC wafer spot price quarterly data — trajectory clearly downward.',
      },
      {
        name: 'EUROPEAN_OEM_SIC_DUAL_SOURCING',
        description: 'European OEM dual-sourcing SiC inverters with non-Infineon suppliers. WNTBT condition 4.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP IFX-01 WNTBT bullet 4`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'No European OEM dual-source publicly announced as of brief; WNTBT condition pending.',
        trajectory_reasoning: 'Will resolve in 2026 — directional indicator pending.',
      },
    ],
    claims: [
      { component_name: 'CHINESE_IDM_SIC_QUALIFICATION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'BYD Semiconductor or CRRC ships SiC modules at volume to Tier-1 automotive outside China before 2027.',
        claim_basis: `Brief HYP IFX-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Chinese IDM breakout from China-only to global Tier-1 supply is the principal structural shift behind the margin compression case.',
        impact_reasoning: 'Each Tier-1 win for a Chinese SiC supplier compresses Infineon pricing power.' },
      { component_name: 'STMICRO_CATANIA_SIC_FAB_RAMP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'STMicro Catania SiC fab reaches 100,000 wafer starts per month by end-2026.',
        claim_basis: `Brief HYP IFX-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 100000, threshold_unit: 'wafer_starts_per_month',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'STMicro at scale is the European-tier supply alternative that breaks Infineon\'s default-supplier position.',
        impact_reasoning: 'Each step of capacity ramp pulls share from Infineon at constant or lower price.' },
      { component_name: 'SIC_WAFER_PRICE_TRAJECTORY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Average SiC MOSFET wafer price falls below $300 at 200mm equivalent by end-2026.',
        claim_basis: `Brief HYP IFX-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 300, threshold_unit: 'USD_per_200mm_eq',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Price floor breaking is the operational force behind margin compression.',
        impact_reasoning: 'Each $50 wafer price decline compresses contribution margin proportionally.' },
      { component_name: 'EUROPEAN_OEM_SIC_DUAL_SOURCING', role: 'external_threat', impact: 'amplifying', criticality: 'medium',
        claim_text: 'At least one European OEM (VW, BMW, Mercedes, Stellantis) dual-sources SiC inverters with a non-Infineon supplier by 2026.',
        claim_basis: `Brief HYP IFX-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'OEM dual-sourcing decisions are the structural break in Infineon\'s historic single-source incumbency.',
        impact_reasoning: 'First dual-source confirmation triggers cascade across other OEMs.' },
    ],
  },

  // IFX-02 ----------------------------------------------------------------
  {
    name: 'Automotive semiconductor inventory correction clears Q3 2026, Infineon record auto revenue end-2026',
    strategy_context: `2024-2025 saw a deep automotive semiconductor inventory correction as OEMs and Tier-1s drew down stockpiles built during the 2021-2022 shortage. Infineon Q4 2024 revenue down 23% YoY. Brief assesses High confidence on a clean recovery by Q3 2026.`,
    brief_description: 'Whether the auto semi inventory correction clears by Q3 2026 with Infineon returning to record automotive revenue by end-2026.',
    hypothesis_statement: `The automotive semiconductor inventory correction of 2024-2025 will fully clear by Q3 2026, with Infineon returning to record automotive revenue by end of 2026. Source: ${BRIEF}, HYP IFX-02.`,
    why_it_matters: 'Recovery timing determines Infineon CAPEX sequencing and technology partnership appetite. EV production schedules at Tier-1 level are the most commercially valuable input.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP IFX-02 (H1 · 1-2yr)`,
    decision_threshold: [
      'Global EV production reaches 12M+ units in 2026;',
      'Infineon automotive book-to-bill returns above 1.0 for two consecutive quarters by mid-2026;',
      'Continental, Bosch, and ZF reduce inventory weeks of supply below 12 weeks by Q2 2026;',
      'No further automotive production curtailment events in Europe or US in 2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP IFX-02.)',
    ].join(' '),
    baseline_confidence: 0.75,
    current_confidence: 0.75,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Market (EV production volume) AND Technology (Tier-1 inventory) as live SIGNAL drivers. Demand-side picking up.',
    trajectory_reasoning: `Industry-wide pattern: inventory destocking complete by H1 2026, restocking + organic demand recovery thereafter. Source: ${BRIEF} HYP IFX-02.`,
    components: [
      {
        name: 'GLOBAL_EV_PRODUCTION_VOLUME_2026',
        description: 'Global EV production volume trajectory in 2026. Market SIGNAL driver and WNTBT condition 1.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP IFX-02 (Market driver SIGNAL — Global EV production volume); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Global EV sales 17.6M (BNEF 2024) → 39M (BNEF 2030 forecast) trajectory. 2026 production target 12M+ aligns.',
        trajectory_reasoning: 'BNEF + IEA EVO 2024 confirm sustained EV production growth despite 2024-2025 slowdown.',
      },
      {
        name: 'INFINEON_AUTO_BOOK_TO_BILL',
        description: 'Infineon automotive segment book-to-bill ratio. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP IFX-02 (Economics driver — Infineon automotive book-to-bill ratio); WNTBT bullet 2`,
        state: 'weakening', trajectory: 'improving',
        state_reasoning: 'Q4 2024 revenue down 23%; book-to-bill below 1.0 throughout 2024-2025.',
        trajectory_reasoning: 'WNTBT requires book-to-bill >1.0 for two consecutive quarters by mid-2026 — directional improvement signal.',
      },
      {
        name: 'TIER1_INVENTORY_WEEKS_OF_SUPPLY',
        description: 'Continental, Bosch, ZF inventory weeks of supply. Technology SIGNAL driver per brief.',
        component_type: 'ecosystem', vector: 'ecosystem', cross_industry: false,
        source_citation: `${BRIEF} HYP IFX-02 (Technology driver SIGNAL — Tier-1 supplier inventory weeks of supply); WNTBT bullet 3`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Tier-1 inventory drawdown active through 2025; Bosch + Continental guidance signals approaching normal levels.',
        trajectory_reasoning: 'Below 12 weeks of supply target by Q2 2026 indicates restocking inflection.',
      },
      {
        name: 'OEM_PRODUCTION_CURTAILMENT_RISK',
        description: 'OEM production curtailment events in Europe and US. WNTBT condition 4 (inverse — no further curtailments).',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP IFX-02 WNTBT bullet 4`,
        state: 'holding', trajectory: 'volatile',
        state_reasoning: 'Curtailment events in 2024-2025 (VW, Stellantis idle weeks) tapering; risk remains if BEV demand softens further.',
        trajectory_reasoning: 'Volatile — depends on Q1-Q3 2026 sales pace.',
      },
    ],
    claims: [
      { component_name: 'GLOBAL_EV_PRODUCTION_VOLUME_2026', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Global EV production reaches 12M+ units in 2026.',
        claim_basis: `Brief HYP IFX-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 12, threshold_unit: 'million_units',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Volume threshold is the principal demand-side anchor for the recovery hypothesis.',
        impact_reasoning: 'Each unit above threshold strengthens Infineon order book recovery.' },
      { component_name: 'INFINEON_AUTO_BOOK_TO_BILL', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Infineon automotive book-to-bill returns above 1.0 for two consecutive quarters by mid-2026.',
        claim_basis: `Brief HYP IFX-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1.0, threshold_unit: 'ratio',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Book-to-bill crossing is the operational confirmation of demand recovery.',
        impact_reasoning: 'Two consecutive quarters above 1.0 establish trajectory rather than spike.' },
      { component_name: 'TIER1_INVENTORY_WEEKS_OF_SUPPLY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Continental, Bosch, and ZF reduce inventory weeks of supply below 12 weeks by Q2 2026.',
        claim_basis: `Brief HYP IFX-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 12, threshold_unit: 'weeks',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Tier-1 normalisation gates the restocking cycle that drives Infineon revenue rebound.',
        impact_reasoning: 'Inventory normalisation triggers fresh orders.' },
      { component_name: 'OEM_PRODUCTION_CURTAILMENT_RISK', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A material OEM production curtailment event (>2 weeks idle at major plant) occurs in Europe or US in 2026.',
        claim_basis: `Brief HYP IFX-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A new curtailment event would re-trigger destocking and dampen the recovery hypothesis.',
        impact_reasoning: 'Each curtailment month adds inventory back into the chain.' },
    ],
  },

  // IFX-03 ----------------------------------------------------------------
  {
    name: 'Data centre AI power management as Infineon second-largest segment by 2030',
    strategy_context: `Hyperscaler AI server rack power density is rising past 100kW. GaN and SiC wide-bandgap power semiconductors are required to maintain efficiency at 48V bus. Infineon, ST, ON Semi all positioning. Brief assesses Medium confidence — large opportunity but pre-FOAK at scale.`,
    brief_description: 'Whether data centre AI power management becomes Infineon\'s second-largest revenue segment by 2030.',
    hypothesis_statement: `Data centre AI power management will become Infineon's second-largest revenue segment by 2030 as hyperscalers demand wide-bandgap power conversion for racks above 100kW. Source: ${BRIEF}, HYP IFX-03.`,
    why_it_matters: 'AI infrastructure × power semiconductors is the fastest-moving technology story in Infineon\'s portfolio. Engagement window for hyperscaler PSU specification roadmaps and GaN vs SiC competitive intelligence.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP IFX-03 (H2 · 4-7yr)`,
    decision_threshold: [
      'AI server rack power density exceeds 100kW in mainstream hyperscaler deployments by 2027;',
      'GaN-based power conversion achieves 98%+ efficiency at 48V bus at commercial scale;',
      'At least two top-5 hyperscalers mandate GaN or SiC in next-generation PSU specifications;',
      'Infineon industrial and IoT segment grows 15%+ CAGR 2025-2027 with data centre as primary driver.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP IFX-03.)',
    ].join(' '),
    baseline_confidence: 0.62,
    current_confidence: 0.62,
    state: 'new',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Market (hyperscaler PSU specs) AND Technology (GaN efficiency) as live SIGNAL drivers — both reinforcing.',
    trajectory_reasoning: `AI training cluster power density doubling every 18 months; wide-bandgap adoption from niche to mainstream. Source: ${BRIEF} HYP IFX-03.`,
    components: [
      {
        name: 'HYPERSCALER_GAN_SIC_PSU_SPEC',
        description: 'Hyperscaler GaN and SiC PSU specification adoption. Market SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP IFX-03 (Market driver SIGNAL — Hyperscaler GaN and SiC PSU specification adoption)`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: Hyperscaler PSU specification releases ongoing.',
        trajectory_reasoning: 'NVIDIA + AMD AI rack architectures driving 48V bus + wide-bandgap.',
      },
      {
        name: 'GAN_48V_BUS_EFFICIENCY',
        description: 'GaN power conversion efficiency at 48V bus at commercial scale. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP IFX-03 (Technology driver SIGNAL — GaN efficiency at 48V bus); WNTBT bullet 2`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'GaN suppliers (Navitas, EPC, Innoscience) approaching 98% efficiency target.',
        trajectory_reasoning: 'Commercial scale crossover expected 2026-2027.',
      },
      {
        name: 'AI_SERVER_RACK_POWER_DENSITY',
        description: 'AI server rack power density kW per rack trend. Economics driver per brief — currently NOT signalled but the underlying market force.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP IFX-03 (Economics driver — AI server rack power density); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Power density rising past 100kW in NVIDIA H100 + B200 deployments.',
        trajectory_reasoning: 'Industry-wide trajectory positive; B200 / B300 racks projected >150kW.',
      },
      {
        name: 'DATA_CENTRE_POWER_REGULATION',
        description: 'Data centre power efficiency regulation and targets. Policy driver per brief — currently NOT signalled.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP IFX-03 (Policy driver — Data centre power efficiency regulation)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'EU + US data centre energy efficiency regulations in force; no near-term tightening flagged.',
        trajectory_reasoning: 'Regulatory framework stable but supports wide-bandgap adoption.',
      },
    ],
    claims: [
      { component_name: 'AI_SERVER_RACK_POWER_DENSITY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'AI server rack power density exceeds 100kW in mainstream hyperscaler deployments by 2027.',
        claim_basis: `Brief HYP IFX-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 100, threshold_unit: 'kW_per_rack',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Power density crossing 100kW is the structural force creating the wide-bandgap opportunity.',
        impact_reasoning: 'Each step of density growth raises wide-bandgap content per rack.' },
      { component_name: 'GAN_48V_BUS_EFFICIENCY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'GaN-based power conversion achieves 98%+ efficiency at 48V bus at commercial scale.',
        claim_basis: `Brief HYP IFX-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 98, threshold_unit: 'pct_efficiency',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Efficiency threshold crossing is the technical confirmation that GaN scales.',
        impact_reasoning: 'Above 98% efficiency, GaN replaces silicon at 48V bus by default.' },
      { component_name: 'HYPERSCALER_GAN_SIC_PSU_SPEC', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'At least two top-5 hyperscalers mandate GaN or SiC in next-generation PSU specifications.',
        claim_basis: `Brief HYP IFX-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Hyperscaler specification mandates are the operational confirmation of the demand pull.',
        impact_reasoning: 'Each hyperscaler mandate locks in volume across multiple generations.' },
      { component_name: 'DATA_CENTRE_POWER_REGULATION', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'Infineon industrial and IoT segment grows 15%+ CAGR 2025-2027 with data centre as primary driver.',
        claim_basis: `Brief HYP IFX-03 WNTBT condition 4 (mapped to regulation/segment driver). Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 15, threshold_unit: 'pct_CAGR',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Segment growth is the financial confirmation that data centre is becoming structural.',
        impact_reasoning: 'CAGR above 15% positions data centre to overtake automotive as #2 segment.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
