// db/population/P4_mercedes_hypotheses.mjs
// Source: daimler_intelligence_brief__4_.html (March 2026 brief — title: "Mercedes-Benz Group AG").
// Filename historically reads "daimler" — content is the post-2022-split Mercedes-Benz parent, NOT
// Daimler Truck AG (id=6). This script targets PG companies.id=9 (Mercedes-Benz).
//
// Three hypotheses: MBG-01 ICE-delay margin defence, MBG-02 MB.OS platform, MBG-03 China JV renegotiation.
//
// Run:
//   node db/population/P4_mercedes_hypotheses.mjs           # dry-run
//   node db/population/P4_mercedes_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'daimler_intelligence_brief__4_.html (March 2026; subject: Mercedes-Benz Group AG)';

const company = {
  name: 'Mercedes-Benz',
  sector: 'mobility',
  notes: 'Mercedes-Benz Group AG (formerly Daimler AG; renamed 2022 post Daimler Truck split). Premium passenger automotive. v2 catalogue first-cut hypotheses sourced from March 2026 brief. Note: brief filename uses legacy "daimler" prefix; PG row id=9 (NOT id=6 Daimler Truck AG).',
};

const initiatives = [
  // MBG-01 ----------------------------------------------------------------
  {
    name: 'Mercedes-Benz electrification delay sustains EBIT >10% through 2028 via premium ICE/PHEV',
    strategy_context: `Mercedes-Benz publicly recalibrated full electrification beyond 2030 in 2024. Premium ICE + PHEV demand persists in €80k+ segment. EBIT margin target 10%+ through cycle. Brief assesses High confidence on commercial vindication of the delay decision.`,
    brief_description: 'Whether Mercedes\' delay of full electrification proves commercially correct via sustained premium ICE/hybrid demand.',
    hypothesis_statement: `Mercedes-Benz's decision to delay full electrification beyond 2030 will prove commercially correct — premium ICE and hybrid demand will sustain EBIT margin above 10% through 2028. Source: ${BRIEF}, HYP MBG-01.`,
    why_it_matters: 'Engagement window on combustion efficiency, advanced transmission, and e-fuel compatibility — Mercedes R&D scouting agenda for the technology roadmap beyond 2030 is live and under-served.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP MBG-01 (H2 · 3-5yr)`,
    decision_threshold: [
      'European premium BEV penetration in €80k+ segment stays below 55% by end-2027;',
      'Mercedes S-Class and E-Class PHEV variants maintain more than 15% price premium over direct BEV;',
      'No major European market bans PHEV sales in the 2025-2028 legislative window;',
      'Mercedes EBIT margin holds above 10% in both 2026 and 2027 annual results.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP MBG-01.)',
    ].join(' '),
    baseline_confidence: 0.69,
    current_confidence: 0.69,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (EBIT margin) AND Technology (combustion + e-fuel) as live SIGNAL drivers. Mercedes 2024 strategy reset already realised in financials.',
    trajectory_reasoning: `EU 2026 ICE review opens potential PHEV / eFuel carve-outs (see Porsche PAG-01). Trajectory positive for premium ICE/hybrid retention. Source: ${BRIEF}.`,
    components: [
      {
        name: 'MERCEDES_EBIT_MARGIN_TRAJECTORY',
        description: 'Mercedes EBIT margin and PHEV price premium hold. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-01 (Economics driver SIGNAL); WNTBT bullets 2 + 4`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Mercedes 2024 reset towards retained ICE/PHEV portfolio; margin defence a stated boardroom priority.',
        trajectory_reasoning: 'Premium pricing power on S-Class/E-Class PHEV holding through 2025; trajectory consistent with 10% target.',
      },
      {
        name: 'EUROPEAN_PREMIUM_BEV_PENETRATION',
        description: 'European premium BEV penetration above €80k segment. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP MBG-01 (Market driver — European premium BEV penetration); WNTBT bullet 1`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'Premium BEV penetration €80k+ segment growing but not yet majority; Mercedes EQ + BMW i + Porsche Taycan + Tesla Model S split.',
        trajectory_reasoning: 'Below 55% threshold through 2027 protects ICE/PHEV revenue base.',
      },
      {
        name: 'COMBUSTION_EFFICIENCY_AND_EFUEL',
        description: 'Combustion efficiency and e-fuel compatibility. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP MBG-01 (Technology driver SIGNAL — Combustion efficiency and e-fuel)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'EU 2026 review eFuels carve-out path live; Porsche Haru Oni leading; Mercedes adjacent.',
        trajectory_reasoning: 'Trajectory positive — eFuel scale approaching commercial, premium ICE economics holding.',
      },
      {
        name: 'EU_PHEV_LEGISLATIVE_WINDOW',
        description: 'EU PHEV eligibility in 2025-2028 legislative window. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP MBG-01 (Policy driver — EU PHEV eligibility); WNTBT bullet 3`,
        state: 'holding', trajectory: 'volatile',
        state_reasoning: 'No major EU member state banning PHEV sales; framework holding.',
        trajectory_reasoning: 'Volatile — depends on individual member-state legislative cycles.',
      },
    ],
    claims: [
      { component_name: 'MERCEDES_EBIT_MARGIN_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Mercedes EBIT margin holds above 10% in both 2026 and 2027 annual results.',
        claim_basis: `Brief HYP MBG-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'EBIT margin is the principal financial confirmation of the hypothesis.',
        impact_reasoning: 'Each percentage point above 10% strengthens the strategic delay rationale.' },
      { component_name: 'EUROPEAN_PREMIUM_BEV_PENETRATION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'European premium BEV penetration in €80k+ segment stays below 55% by end-2027.',
        claim_basis: `Brief HYP MBG-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 55, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Premium BEV penetration is the demand-side anchor for the ICE/PHEV revenue retention.',
        impact_reasoning: 'Each percentage point below 55% protects Mercedes ICE/PHEV portfolio share.' },
      { component_name: 'COMBUSTION_EFFICIENCY_AND_EFUEL', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Mercedes S-Class and E-Class PHEV variants maintain more than 15% price premium over direct BEV equivalents.',
        claim_basis: `Brief HYP MBG-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 15, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'PHEV price premium captures the customer value Mercedes places on combustion-hybrid retention.',
        impact_reasoning: 'Premium pricing flows directly to EBIT margin.' },
      { component_name: 'EU_PHEV_LEGISLATIVE_WINDOW', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'A major European market (Germany, France, UK, Netherlands) bans PHEV sales in the 2025-2028 legislative window.',
        claim_basis: `Brief HYP MBG-01 WNTBT condition 3 (inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A national PHEV ban materially shrinks the addressable market and breaks the hypothesis.',
        impact_reasoning: 'Each major-market ban removes 5-10% of premium PHEV addressable demand.' },
    ],
  },

  // MBG-02 ----------------------------------------------------------------
  {
    name: 'MB.OS platform captures >15% in-vehicle software revenue by 2028',
    strategy_context: `MB.OS is Mercedes\' bet on owning its in-vehicle operating system. Tesla, BYD, NIO are the SDV-native benchmarks; CARIAD struggles in VW comparison. Brief assesses Medium confidence — large opportunity but execution-dependent.`,
    brief_description: 'Whether MB.OS becomes a genuine platform competitive advantage capturing >15% of in-vehicle software revenue.',
    hypothesis_statement: `The MB.OS in-vehicle operating system will become a genuine platform competitive advantage by 2028, enabling Mercedes to capture more than 15% of in-vehicle software revenue. Source: ${BRIEF}, HYP MBG-02.`,
    why_it_matters: 'FutureBridge SDV intelligence maps directly to the gap between Mercedes\' software ambitions and current delivery capability. Active scouting window.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP MBG-02 (H2 · 3-6yr)`,
    decision_threshold: [
      'MB.OS rolls out to at least 500,000 vehicles in production spec by end-2026;',
      'At least two third-party developers sign commercial MB.OS integration agreements by 2027;',
      'Mercedes achieves OTA revenue above €500M annually by 2028;',
      'No major MB.OS cybersecurity incident disrupts the platform launch.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP MBG-02.)',
    ].join(' '),
    baseline_confidence: 0.55,
    current_confidence: 0.55,
    state: 'ambiguous',
    trajectory: 'volatile',
    state_reasoning: 'Brief flags Technology (MB.OS rollout) AND Policy (EU cybersecurity) as live SIGNAL drivers. State ambiguous — execution heterogeneity.',
    trajectory_reasoning: `MB.OS rollout pace will resolve in 2026 — directional indicator pending. Source: ${BRIEF}.`,
    components: [
      {
        name: 'MB_OS_PRODUCTION_ROLLOUT',
        description: 'MB.OS production rollout vehicle count. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-02 (Technology driver SIGNAL — MB.OS production rollout vehicle count); WNTBT bullet 1`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'MB.OS launch on MMA platform 2025; rollout to 500k+ vehicles by end-2026 is WNTBT.',
        trajectory_reasoning: 'Brief LIVE NOW: MB.OS production rollout announcements ongoing.',
      },
      {
        name: 'MERCEDES_OTA_SOFTWARE_REVENUE',
        description: 'Mercedes OTA and software subscription revenue trajectory. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-02 (Economics driver — OTA and software subscription revenue); WNTBT bullet 3`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'OTA revenue developing post MB.OS launch; €500M annual target by 2028 aspirational.',
        trajectory_reasoning: 'Trajectory directionally positive but pace gated by MB.OS production scale.',
      },
      {
        name: 'MB_OS_THIRD_PARTY_DEVELOPER_PIPELINE',
        description: 'Third-party developer MB.OS adoption pipeline. Market driver per brief.',
        component_type: 'ecosystem', vector: 'ecosystem', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-02 (Market driver — Third-party developer MB.OS adoption); WNTBT bullet 2`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'No major third-party commercial integration agreement publicly announced as of brief.',
        trajectory_reasoning: 'WNTBT requires 2 commercial agreements by 2027 — directional indicator pending.',
      },
      {
        name: 'EU_CYBERSEC_TYPE_APPROVAL',
        description: 'EU cybersecurity and software update type approval (UNECE R155/R156). Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP MBG-02 (Policy driver SIGNAL — EU cybersecurity and software update type approval)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'UNECE R155/R156 in force in EU + Japan. Framework stable but enforcing.',
        trajectory_reasoning: 'No material new tightening flagged in brief.',
      },
    ],
    claims: [
      { component_name: 'MB_OS_PRODUCTION_ROLLOUT', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'MB.OS rolls out to at least 500,000 vehicles in production spec by end-2026.',
        claim_basis: `Brief HYP MBG-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 500000, threshold_unit: 'vehicles',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Production scale is the principal observable confirmation that MB.OS is operational not aspirational.',
        impact_reasoning: 'Each step of vehicle rollout grows the addressable software-revenue base.' },
      { component_name: 'MERCEDES_OTA_SOFTWARE_REVENUE', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Mercedes achieves OTA revenue above €500M annually by 2028.',
        claim_basis: `Brief HYP MBG-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 500, threshold_unit: 'EUR_million_annual',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Revenue threshold is the financial confirmation that MB.OS captures share.',
        impact_reasoning: 'Above €500M, software contributes meaningfully to group EBIT.' },
      { component_name: 'MB_OS_THIRD_PARTY_DEVELOPER_PIPELINE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'At least two third-party developers sign commercial MB.OS integration agreements by 2027.',
        claim_basis: `Brief HYP MBG-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Third-party adoption is the structural validation that MB.OS is a platform not a closed system.',
        impact_reasoning: 'Each commercial integration legitimises the platform thesis.' },
      { component_name: 'EU_CYBERSEC_TYPE_APPROVAL', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A major MB.OS cybersecurity incident disrupts the platform launch (forcing recall, fleet update, or regulatory intervention).',
        claim_basis: `Brief HYP MBG-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A material incident damages platform credibility and slows third-party adoption.',
        impact_reasoning: 'Each disclosed vulnerability erodes consumer + developer trust.' },
    ],
  },

  // MBG-03 ----------------------------------------------------------------
  {
    name: 'Mercedes BAIC China JV requires fundamental renegotiation before 2027 as share falls',
    strategy_context: `Mercedes Beijing Benz JV with BAIC under structural pressure as NIO, Li Auto, Huawei-backed brands erode CNY 400k+ premium share. Royalty flow to Mercedes core business at risk; localisation demands rising.`,
    brief_description: 'Whether Mercedes BAIC JV faces fundamental renegotiation before 2027 as Beijing Benz market share falls below 15%.',
    hypothesis_statement: `Mercedes' China JV with BAIC will require fundamental renegotiation before 2027 as local premium EV brands erode Beijing Benz's market share below 15%. Source: ${BRIEF}, HYP MBG-03.`,
    why_it_matters: 'China localisation of battery chemistry, autonomous features, and digital UX is the immediate scouting priority for Mercedes Asia-Pacific.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP MBG-03 (H1 · 1-3yr)`,
    decision_threshold: [
      'Mercedes China market share falls below 18% by end-2025;',
      'NIO, Li Auto, or Huawei brands capture more than 20% of CNY 400k+ segment by 2026;',
      'BAIC publicly raises localisation demands or seeks a revised royalty structure before mid-2026.',
      'All three conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP MBG-03.)',
    ].join(' '),
    baseline_confidence: 0.63,
    current_confidence: 0.63,
    state: 'strengthening',
    trajectory: 'deteriorating',
    state_reasoning: 'Brief flags Market (Mercedes China share trajectory) as live SIGNAL driver. WNTBT conditions tracking toward confirmation.',
    trajectory_reasoning: `Mercedes China share trajectory deteriorating since 2024; local premium EV brands gaining structurally. Source: ${BRIEF} HYP MBG-03.`,
    components: [
      {
        name: 'MERCEDES_CHINA_MARKET_SHARE',
        description: 'Mercedes China market share trajectory. Market SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-03 (Market driver SIGNAL — Mercedes China market share trajectory); WNTBT bullet 1`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Brief LIVE NOW: Mercedes China monthly sales data trending down.',
        trajectory_reasoning: 'Below 18% share by end-2025 directionally consistent.',
      },
      {
        name: 'CHINA_PREMIUM_EV_LOCAL_BRANDS',
        description: 'NIO, Li Auto, Huawei-backed brands share of CNY 400k+ segment. Market driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-03 (Market driver — China premium EV brand share); WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'NIO ET-series, Li Auto MEGA, Huawei Aito pulling share from German premium incumbents.',
        trajectory_reasoning: 'Trajectory accelerating; >20% capture by 2026 directionally indicated.',
      },
      {
        name: 'BEIJING_BENZ_JV_PROFITABILITY',
        description: 'Beijing Benz JV profitability and royalty flow. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-03 (Economics driver — Beijing Benz JV profitability)`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'JV profitability under pressure as China share declines.',
        trajectory_reasoning: 'Royalty flow to Mercedes core declining commensurate with share loss.',
      },
      {
        name: 'BAIC_LOCALISATION_DEMANDS',
        description: 'BAIC localisation demands and JV renegotiation. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP MBG-03 (Policy driver — BAIC localisation demands and JV renegotiation); WNTBT bullet 3`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'BAIC public statements on JV terms emerging; framework under negotiation pressure.',
        trajectory_reasoning: 'Volatile — outcome depends on Chinese government and individual JV partner positions.',
      },
    ],
    claims: [
      { component_name: 'MERCEDES_CHINA_MARKET_SHARE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Mercedes China market share falls below 18% by end-2025.',
        claim_basis: `Brief HYP MBG-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 18, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Share threshold is the principal numeric anchor of the hypothesis.',
        impact_reasoning: 'Each percentage point of share loss accelerates BAIC renegotiation pressure.' },
      { component_name: 'CHINA_PREMIUM_EV_LOCAL_BRANDS', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'NIO, Li Auto, or Huawei-backed brands capture more than 20% of CNY 400k+ segment by 2026.',
        claim_basis: `Brief HYP MBG-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 20, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Local premium EV breakthrough is the structural force driving Mercedes share loss.',
        impact_reasoning: 'Each percentage point of local premium share comes directly from German incumbents.' },
      { component_name: 'BAIC_LOCALISATION_DEMANDS', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'BAIC publicly raises localisation demands or seeks a revised royalty structure before mid-2026.',
        claim_basis: `Brief HYP MBG-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Public renegotiation pressure is the operational confirmation of the hypothesis.',
        impact_reasoning: 'Each escalation step compresses Mercedes China earnings power.' },
      { component_name: 'BEIJING_BENZ_JV_PROFITABILITY', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'Mercedes successfully launches a China-specific premium EV product re-stabilising share above 18% before mid-2026.',
        claim_basis: `Brief HYP MBG-03 (inverse — successful product re-launch). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Successful China-specific product would dampen the renegotiation hypothesis.',
        impact_reasoning: 'Each percentage point of share regained reduces JV renegotiation urgency.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
