// db/population/P4_mol_hypotheses.mjs
// Source: mol_intelligence_brief__4_.html (March 2026 brief).
// Three hypotheses: MOL-01 CEE retail durability, MOL-02 polyolefins compression, MOL-03 EV charging leadership.
// PG company: NOT yet present — script creates 'MOL Group' via runPopulation's getOrCreateCompany.
//
// Run:
//   node db/population/P4_mol_hypotheses.mjs           # dry-run
//   node db/population/P4_mol_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'mol_intelligence_brief__4_.html (March 2026)';

const company = {
  name: 'MOL Group',
  sector: 'energy',
  notes: 'MOL Plc — Hungarian integrated oil & gas + downstream + retail. HQ: Budapest, Hungary. CEE-anchored regional player; Lotos acquisition consolidated regional refining position. v2 catalogue first-cut hypotheses sourced from March 2026 brief.',
};

const initiatives = [
  // MOL-01 ----------------------------------------------------------------
  {
    name: 'MOL CEE fuel retail network structurally profitable through 2030 as CEE EV adoption lags',
    strategy_context: `MOL operates 2,000+ retail sites across Hungary, Slovakia, Czech Republic, Poland (post-Lotos). CEE EV adoption lags Western Europe by 5-8 years per IEA: Hungary, Slovakia, Czech Republic EV penetration <10% in 2024 vs Germany ~18%. Brief assesses Medium confidence.`,
    brief_description: 'Whether MOL\'s CEE retail network sustains profitability through 2030 as CEE EV transition lags.',
    hypothesis_statement: `MOL's Central and Eastern European fuel retail network will remain structurally profitable through 2030 as CEE EV adoption lags Western Europe by 5-8 years. Source: ${BRIEF}, HYP MOL-01.`,
    why_it_matters: 'CEE energy transition timing intelligence is MOL\'s most time-sensitive planning input. EV adoption modelling and regulatory forecasting is a direct fit.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP MOL-01 (H2 · 3-6yr)`,
    decision_threshold: [
      'EV penetration in Hungary, Slovakia, and Czech Republic stays below 20% through end-2027;',
      'MOL deploys EV charging at 30%+ of CEE fuel stations by end-2026 without EBITDA dilution;',
      'CEE governments maintain fuel duty structures preserving downstream retail margins through 2026;',
      'No major Chinese EV brand establishes a dominant CEE market position before 2027.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP MOL-01.)',
    ].join(' '),
    baseline_confidence: 0.71,
    current_confidence: 0.71,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (CEE retail EBITDA) AND Policy (EU AFIR mandate) as live SIGNAL drivers. CEE EV penetration trajectory consistent with WNTBT.',
    trajectory_reasoning: `IEA EV Outlook 2024 confirms CEE EV penetration lag; AFIR compliance creating structural retail-EV-charging integration window. Source: ${BRIEF}.`,
    components: [
      {
        name: 'CEE_FUEL_RETAIL_EBITDA_MARGIN',
        description: 'CEE fuel retail EBITDA margin stability. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MOL-01 (Economics driver SIGNAL — CEE fuel retail EBITDA margin stability)`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'CEE retail EBITDA margins holding above western European norms; Lotos integration completing.',
        trajectory_reasoning: 'AFIR co-deployment of EV charging at fuel sites supports site-EBITDA via through-traffic.',
      },
      {
        name: 'CEE_EV_PENETRATION_TRAJECTORY',
        description: 'EV penetration of new sales in Hungary, Slovakia, Czech Republic. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP MOL-01 (Market driver — EV penetration of CEE new sales); WNTBT bullet 1`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'CEE EV penetration <10% in 2024; below 20% threshold through 2027 directionally consistent.',
        trajectory_reasoning: 'Trajectory rising but lag vs Western Europe sustained — protects MOL retail base.',
      },
      {
        name: 'EV_CHARGING_FUEL_STATION_DEPLOYMENT',
        description: 'EV charging deployment economics at fuel station sites. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP MOL-01 (Technology driver — EV charging at fuel station economics); WNTBT bullet 2`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'MOL EV charging rollout active; AFIR mandate accelerating.',
        trajectory_reasoning: 'Brief LIVE NOW: CEE EV registration data + EU AFIR compliance deadline confirmation.',
      },
      {
        name: 'EU_AFIR_CEE_TENT_MANDATE',
        description: 'EU AFIR mandate for CEE TEN-T corridors. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP MOL-01 (Policy driver SIGNAL — EU AFIR mandate for CEE TEN-T corridors)`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'AFIR in force; CEE compliance deadlines upcoming 2025-2026.',
        trajectory_reasoning: 'Mandate accelerating CEE charging deployment, protecting MOL site value.',
      },
    ],
    claims: [
      { component_name: 'CEE_EV_PENETRATION_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'EV penetration in Hungary, Slovakia, and Czech Republic stays below 20% through end-2027.',
        claim_basis: `Brief HYP MOL-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 20, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'CEE EV penetration is the principal demand-side anchor for sustained ICE fuel retail.',
        impact_reasoning: 'Each percentage point below 20% protects ICE volume base.' },
      { component_name: 'EV_CHARGING_FUEL_STATION_DEPLOYMENT', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'MOL deploys EV charging at 30%+ of CEE fuel stations by end-2026 without EBITDA dilution.',
        claim_basis: `Brief HYP MOL-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 30, threshold_unit: 'pct_of_sites',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Co-deployment is the operational hedge — captures EV-driver revenue without forfeiting fuel margins.',
        impact_reasoning: 'Each step of EV-charger rollout adds revenue at constant site overhead.' },
      { component_name: 'EU_AFIR_CEE_TENT_MANDATE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'CEE governments maintain fuel duty structures preserving downstream retail margins through 2026.',
        claim_basis: `Brief HYP MOL-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Fuel duty structures protect retail margin against accelerated transition.',
        impact_reasoning: 'Each year of stable fuel duty extends profitability window.' },
      { component_name: 'CEE_FUEL_RETAIL_EBITDA_MARGIN', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A major Chinese EV brand (BYD, Geely, Chery) establishes a dominant CEE market position before 2027.',
        claim_basis: `Brief HYP MOL-01 WNTBT condition 4 (inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Chinese EV breakthrough into CEE accelerates the transition timeline that MOL is hedging against.',
        impact_reasoning: 'BYD Hungary plant and Chery/Geely CEE distribution add aggression to local EV adoption.' },
    ],
  },

  // MOL-02 ----------------------------------------------------------------
  {
    name: 'MOL polyolefins / chemicals 30%+ EBITDA compression by 2030',
    strategy_context: `European chemical industry under structural pressure: capacity utilisation declining, Chinese polyolefin imports rising, EU CBAM Phase 2 expanding to petrochemical intermediates. MOL Downstream chemicals position vulnerable. Brief assesses Low confidence — high uncertainty range.`,
    brief_description: 'Whether MOL polyolefins / chemicals faces 30%+ EBITDA compression by 2030.',
    hypothesis_statement: `MOL's polyolefins and chemicals business will face structural EBITDA compression of 30%+ by 2030 as European demand restructuring and Asian competition erode premium positions. Source: ${BRIEF}, HYP MOL-02.`,
    why_it_matters: 'Circular chemistry, plastic recycling technology, and chemical feedstock alternatives are areas where MOL\'s innovation agenda is underdeveloped.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP MOL-02 (H2 · 4-7yr)`,
    decision_threshold: [
      'European chemical industry capacity utilisation falls below 72% for 3+ consecutive quarters by end-2026;',
      'Chinese polyolefin exports to Central Europe increase 40%+ between 2024 and 2027;',
      'EU CBAM Phase 2 covers petrochemical intermediates by 2028;',
      'MOL fails to achieve planned €200M cost reduction in Downstream by end-2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP MOL-02.)',
    ].join(' '),
    baseline_confidence: 0.45,
    current_confidence: 0.45,
    state: 'weakening',
    trajectory: 'deteriorating',
    state_reasoning: 'Brief flags Economics (capacity utilisation) AND Policy (CBAM Phase 2) as live SIGNAL drivers. Hypothesis confidence Low per brief — flagged for review per methodology Step 6 (low confidence triggers automatic flag).',
    trajectory_reasoning: `European petrochemical capacity utilisation in structural decline; Chinese imports rising. Source: ${BRIEF}.`,
    components: [
      {
        name: 'EUROPEAN_POLYOLEFIN_CAPACITY_UTILISATION',
        description: 'European polyolefin capacity utilisation rate. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MOL-02 (Economics driver SIGNAL — European polyolefin capacity utilisation); WNTBT bullet 1`,
        state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'European chemical capacity utilisation around 72-78% as of 2024; trajectory declining.',
        trajectory_reasoning: 'Below 72% for 3+ quarters by end-2026 directionally consistent with brief.',
      },
      {
        name: 'CHINESE_POLYOLEFIN_EUROPEAN_EXPORTS',
        description: 'Chinese polyolefin export volume to Central Europe. Market driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP MOL-02 (Market driver — Chinese polyolefin export volume); WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'deteriorating',
        state_reasoning: 'Brief LIVE NOW: Chinese polyolefin export volume data rising.',
        trajectory_reasoning: '40%+ increase 2024-2027 directionally consistent.',
      },
      {
        name: 'EU_CBAM_PHASE2_PETROCHEMICALS',
        description: 'EU CBAM Phase 2 petrochemical intermediates scope. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP MOL-02 (Policy driver SIGNAL — EU CBAM Phase 2 petrochemical intermediates scope); WNTBT bullet 3`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: EU CBAM Phase 2 consultation progress. Petrochemical intermediates scope under review.',
        trajectory_reasoning: 'Phase 2 expansion expected by 2028 — would shift competitive dynamics in MOL\'s favour.',
      },
      {
        name: 'PLASTIC_RECYCLING_FEEDSTOCK_TECH',
        description: 'Plastic recycling and circular feedstock technology. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP MOL-02 (Technology driver — Plastic recycling and circular feedstock)`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'MOL circular chemistry investments emerging but not yet at scale.',
        trajectory_reasoning: 'Pace depends on regulatory + cost trajectory.',
      },
    ],
    claims: [
      { component_name: 'EUROPEAN_POLYOLEFIN_CAPACITY_UTILISATION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'European chemical industry capacity utilisation falls below 72% for 3+ consecutive quarters by end-2026.',
        claim_basis: `Brief HYP MOL-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 72, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Capacity utilisation is the principal financial-pressure indicator for MOL chemicals.',
        impact_reasoning: 'Each percentage point below 72% raises fixed-cost dilution and EBITDA pressure.' },
      { component_name: 'CHINESE_POLYOLEFIN_EUROPEAN_EXPORTS', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Chinese polyolefin exports to Central Europe increase 40%+ between 2024 and 2027.',
        claim_basis: `Brief HYP MOL-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40, threshold_unit: 'pct_increase',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Chinese imports are the structural force driving European margin compression.',
        impact_reasoning: 'Each percentage point of import growth displaces MOL volume.' },
      { component_name: 'EU_CBAM_PHASE2_PETROCHEMICALS', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'EU CBAM Phase 2 covers petrochemical intermediates by 2028.',
        claim_basis: `Brief HYP MOL-02 WNTBT condition 3 (note: CBAM expansion DAMPENS the compression hypothesis by penalising imports). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'CBAM expansion is the regulatory hedge — penalties Chinese imports and protects MOL.',
        impact_reasoning: 'Each scope expansion of CBAM Phase 2 raises Chinese import landed costs.' },
      { component_name: 'PLASTIC_RECYCLING_FEEDSTOCK_TECH', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'MOL fails to achieve planned €200M cost reduction in Downstream by end-2026.',
        claim_basis: `Brief HYP MOL-02 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cost-reduction failure compounds the structural compression.',
        impact_reasoning: 'Without the €200M target, EBITDA compression accelerates.' },
    ],
    flag: true,
    flag_reason: 'Confidence band Low per brief assessment (Low/Medium/High range explicit). Methodology Step 6 requires automatic flag for low confidence.',
  },

  // MOL-03 ----------------------------------------------------------------
  {
    name: 'MOL leading EV charging operator in CEE by 2027 (15%+ regional share)',
    strategy_context: `MOL leveraging 2,000+ retail site footprint to scale EV charging across CEE. EU AFIR mandates fast-charging at fuel stations on TEN-T corridors. Brief assesses High confidence — site footprint is structural advantage if execution sustained.`,
    brief_description: 'Whether MOL captures 15%+ regional CEE EV charging market share by 2027.',
    hypothesis_statement: `MOL will establish itself as a leading EV charging operator in CEE by 2027, leveraging its 2,000+ site network to capture 15%+ regional charging market share. Source: ${BRIEF}, HYP MOL-03.`,
    why_it_matters: 'EV charging technology — ultra-fast hardware, payment/roaming interoperability, demand management software — is where MOL\'s procurement team is most active.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP MOL-03 (H1 · 2-3yr)`,
    decision_threshold: [
      'EU AFIR mandates fast-charging at fuel stations on core network routes in CEE by end-2025;',
      'MOL deploys 150+ high-power charging locations above 150kW by end-2026;',
      'MOL EV charging generates €50M+ annual revenue by 2027 with clear path to profitability;',
      'No third-party aggregator captures dominant CEE position before MOL scales.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP MOL-03.)',
    ].join(' '),
    baseline_confidence: 0.71,
    current_confidence: 0.71,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (ultra-fast charging hardware) AND Policy (EU AFIR enforcement) as live SIGNAL drivers.',
    trajectory_reasoning: `AFIR mandate + MOL site footprint + brand presence give structural advantage. Source: ${BRIEF}.`,
    components: [
      {
        name: 'MOL_HIGH_POWER_CHARGER_DEPLOYMENT',
        description: 'MOL high-power charging deployment locations. Market + tech driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP MOL-03 (Tech/Market — MOL HPC deployment); WNTBT bullets 2 + 3`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: MOL EV charging deployment announcements ongoing.',
        trajectory_reasoning: 'On track for 150+ locations target by end-2026.',
      },
      {
        name: 'EU_AFIR_HPC_DENSITY_ENFORCEMENT',
        description: 'EU AFIR compliance enforcement and HPC density mandate. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP MOL-03 (Policy SIGNAL — EU AFIR enforcement and HPC density); WNTBT bullet 1`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'AFIR in force; CEE TEN-T compliance deadlines upcoming.',
        trajectory_reasoning: 'Mandate enforcement strengthening — aligned with MOL deployment timeline.',
      },
      {
        name: 'CEE_HPC_MARKET_SHARE',
        description: 'CEE high-power charging market share by operator. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MOL-03 (Market driver — CEE HPC market share by operator)`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'CEE HPC market emerging; Ionity + EnBW + ChargePoint entering.',
        trajectory_reasoning: 'Brief LIVE NOW: Ionity and EnBW CEE network expansion. MOL share defensible if scaled fast.',
      },
      {
        name: 'ULTRA_FAST_CHARGING_TECH_AND_DEMAND_MGMT',
        description: 'Ultra-fast charging hardware and demand management. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP MOL-03 (Technology SIGNAL — Ultra-fast charging hardware and demand management)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: '350kW+ HPC technology + demand management software maturing.',
        trajectory_reasoning: 'SiC + GaN power electronics enabling 350kW+ at lower BOM cost.',
      },
    ],
    claims: [
      { component_name: 'MOL_HIGH_POWER_CHARGER_DEPLOYMENT', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'MOL deploys 150+ high-power charging locations above 150kW by end-2026.',
        claim_basis: `Brief HYP MOL-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 150, threshold_unit: 'locations',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Network scale is the principal observable confirmation of operator-status hypothesis.',
        impact_reasoning: 'Each location adds CEE coverage and revenue.' },
      { component_name: 'CEE_HPC_MARKET_SHARE', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'MOL EV charging generates €50M+ annual revenue by 2027 with clear path to profitability.',
        claim_basis: `Brief HYP MOL-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 50, threshold_unit: 'EUR_million_annual',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Revenue threshold is the financial confirmation of operator-status.',
        impact_reasoning: 'Above €50M, EV charging is a meaningful business unit.' },
      { component_name: 'EU_AFIR_HPC_DENSITY_ENFORCEMENT', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'EU AFIR mandates fast-charging at fuel stations on core network routes in CEE by end-2025.',
        claim_basis: `Brief HYP MOL-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'AFIR mandate is the policy force creating the deployment window.',
        impact_reasoning: 'Mandate compels co-location of charging at fuel sites — favours MOL incumbency.' },
      { component_name: 'ULTRA_FAST_CHARGING_TECH_AND_DEMAND_MGMT', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'A third-party aggregator (Ionity, EnBW, ChargePoint, BP Pulse) captures dominant CEE position before MOL scales.',
        claim_basis: `Brief HYP MOL-03 WNTBT condition 4 (inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Aggregator dominance would undermine MOL\'s incumbent-network advantage.',
        impact_reasoning: 'Each Ionity site at scale erodes MOL\'s geographic-monopoly value.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
