// db/population/P4_michelin_hypotheses.mjs
// Source: michelin_intelligence_brief__4_.html (March 2026 brief).
// Three hypotheses: ML-01 EV tyre price premium, ML-02 EU EPR + circular rubber, ML-03 specialty EBIT anchor.
// PG company: id=51 (Michelin Group).
//
// Run:
//   node db/population/P4_michelin_hypotheses.mjs           # dry-run
//   node db/population/P4_michelin_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'michelin_intelligence_brief__4_.html (March 2026)';

const company = {
  name: 'Michelin Group',
  sector: 'mobility',
  notes: 'Compagnie Générale des Établissements Michelin — global tyre and mobility-services company. v2 catalogue first-cut hypotheses sourced from March 2026 brief.',
};

const initiatives = [
  // ML-01 ----------------------------------------------------------------
  {
    name: 'EV-specific tyre demand drives Michelin premium mix improvement through 2029',
    strategy_context: `EV tyres carry a 20-35% price premium over equivalent ICE tyres due to higher load, rolling resistance optimisation, thermal management, road noise reduction. Global EV fleet projected >80M units by end-2027. Michelin EV-specific range targeting 40%+ European OEM EV fitment share.`,
    brief_description: 'Whether EV-specific tyre demand sustains 20-35% price premium over ICE equivalents through 2029.',
    hypothesis_statement: `EV-specific tyre demand will drive Michelin's premium mix improvement through 2029, with EV tires sustaining a 20-35% price premium over equivalent ICE tires. Source: ${BRIEF}, HYP ML-01.`,
    why_it_matters: 'EV tyre performance chemistry, thermal management compounds, and road noise materials are the R&D areas where Michelin\'s technology scouting is most active.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2029,
    time_horizon_source: `${BRIEF} HYP ML-01 (H2 · 3-5yr)`,
    decision_threshold: [
      'Global EV fleet exceeds 80M vehicles by end-2027;',
      'OEM EV tire specifications diverge sufficiently from ICE to prevent commodity substitution;',
      'Michelin EV tire range achieves 40%+ share of European OEM EV fitment by 2027;',
      'No disruptive new tire material achieves OEM homologation before 2030.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP ML-01.)',
    ].join(' '),
    baseline_confidence: 0.74,
    current_confidence: 0.74,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (EV tire price premium) AND Technology (rolling resistance + thermal) as live SIGNAL drivers. Both reinforcing.',
    trajectory_reasoning: `IEA + BNEF EV adoption forecasts confirm fleet >80M by 2027; OEM EV-specific homologation diverging from ICE. Source: ${BRIEF}.`,
    components: [
      {
        name: 'EV_TIRE_PRICE_PREMIUM',
        description: 'EV tire price premium over ICE equivalent. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ML-01 (Economics driver SIGNAL — EV tire price premium); hypothesis statement`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: '20-35% premium currently observed across Michelin Pilot Sport EV, Primacy EV, etc.',
        trajectory_reasoning: 'Premium widening as OEM-specific homologation requirements grow.',
      },
      {
        name: 'GLOBAL_EV_FLEET_TRAJECTORY',
        description: 'Global EV fleet and OEM EV tire fitment share. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP ML-01 (Market driver — Global EV fleet); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Global EV fleet on path to 80M+ by 2027 per IEA/BNEF forecasts.',
        trajectory_reasoning: 'Replacement-tyre demand follows fleet with 18-24 month lag — accelerating.',
      },
      {
        name: 'ROLLING_RESISTANCE_AND_THERMAL_TECH',
        description: 'Rolling resistance compound and thermal management technology. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP ML-01 (Technology driver SIGNAL — Rolling resistance compound and thermal management)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: Michelin EV fitment share data + OEM EV tire spec releases.',
        trajectory_reasoning: 'OEM-specific EV homologation widening separation from generic ICE tyres.',
      },
      {
        name: 'EU_TIRE_LABELLING_EV_STANDARDS',
        description: 'EU tire labelling and EV-specific standards. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP ML-01 (Policy driver — EU tire labelling and EV-specific standards)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'EU tire labelling regulation in force; EV-specific labelling provisions stable.',
        trajectory_reasoning: 'No imminent policy shift in brief.',
      },
    ],
    claims: [
      { component_name: 'GLOBAL_EV_FLEET_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Global EV fleet exceeds 80M vehicles by end-2027.',
        claim_basis: `Brief HYP ML-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 80, threshold_unit: 'million_vehicles',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Fleet size is the principal demand-side anchor for the EV-tyre premium thesis.',
        impact_reasoning: 'Each million units in fleet drives replacement tyre demand at premium pricing.' },
      { component_name: 'EV_TIRE_PRICE_PREMIUM', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'EV tires sustain 20-35% price premium over equivalent ICE tires through 2029.',
        claim_basis: `Brief HYP ML-01 hypothesis statement. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 20, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Price premium is the financial confirmation of differentiation.',
        impact_reasoning: 'Each premium percentage point flows to gross margin.' },
      { component_name: 'ROLLING_RESISTANCE_AND_THERMAL_TECH', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Michelin EV tire range achieves 40%+ share of European OEM EV fitment by 2027 AND no disruptive new tire material achieves OEM homologation before 2030.',
        claim_basis: `Brief HYP ML-01 WNTBT conditions 3 + 4 (combined market + technology). Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'OEM fitment share + technology stability protects the premium-mix thesis.',
        impact_reasoning: 'Fitment share locks in volume; absence of disruption preserves pricing power.' },
      { component_name: 'EU_TIRE_LABELLING_EV_STANDARDS', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'OEM EV tire specifications diverge sufficiently from ICE specifications to prevent commodity substitution.',
        claim_basis: `Brief HYP ML-01 WNTBT condition 2 (technical/regulatory bridge). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Specification divergence is the structural defence against commoditisation.',
        impact_reasoning: 'If specs converge with ICE, premium pricing erodes.' },
    ],
  },

  // ML-02 ----------------------------------------------------------------
  {
    name: 'EU end-of-life tire EPR drives Michelin €1B+ circular rubber investment by 2030',
    strategy_context: `EU EPR (Extended Producer Responsibility) framework consultation underway with recycled-content mandates >20% by 2028. PFAS restriction expanding. Michelin Symbio (hydrogen) JV + bio-sourced silica programmes scaling. Brief assesses Medium confidence.`,
    brief_description: 'Whether EU end-of-life tire EPR + PFAS rules become Michelin\'s primary compliance cost driver.',
    hypothesis_statement: `EU end-of-life tire regulations and EPR rules will become Michelin's primary compliance cost driver by 2030, spurring €1B+ investment in circular rubber. Source: ${BRIEF}, HYP ML-02.`,
    why_it_matters: 'Regulatory foresight on tire EPR and raw material provenance is a gap Michelin\'s sustainability team does not fully cover.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP ML-02 (H2 · 4-7yr)`,
    decision_threshold: [
      'EU EPR framework enters force with recycled content mandates above 20% by 2028;',
      'Sustainable natural rubber supply chains achieve certified volume for 15%+ of Michelin needs by 2027;',
      'Michelin Symbio and bio-sourced silica reach commercial scale above 100,000 tires/yr by 2027;',
      'No cost gap above 10% between sustainable compounds and current formulations at volume.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP ML-02.)',
    ].join(' '),
    baseline_confidence: 0.58,
    current_confidence: 0.58,
    state: 'new',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (bio-sourced silica) AND Policy (EU EPR + PFAS) as live SIGNAL drivers.',
    trajectory_reasoning: `EU EPR consultation advancing; PFAS restriction in force; trajectory toward tighter standards. Source: ${BRIEF}.`,
    components: [
      {
        name: 'EU_TIRE_EPR_PFAS_FRAMEWORK',
        description: 'EU tire EPR framework and PFAS restriction. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP ML-02 (Policy driver SIGNAL — EU tire EPR framework and PFAS restriction); WNTBT bullet 1`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'EU EPR consultation outcomes pending. PFAS restriction expanding scope.',
        trajectory_reasoning: 'Brief LIVE NOW: EU EPR framework consultation outcomes.',
      },
      {
        name: 'BIO_SOURCED_SILICA_AND_RUBBER',
        description: 'Bio-sourced silica and sustainable rubber at scale. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP ML-02 (Technology driver SIGNAL — Bio-sourced silica and sustainable rubber); WNTBT bullets 2 + 3`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Michelin Symbio + bio-sourced silica at pilot to FOAK commercial scale. Sustainable natural rubber certified supply emerging.',
        trajectory_reasoning: 'Brief LIVE NOW: Michelin Symbio programme milestone updates.',
      },
      {
        name: 'SUSTAINABLE_COMPOUND_COST_GAP',
        description: 'Sustainable compound cost vs conventional at volume. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ML-02 (Economics driver — Sustainable compound cost); WNTBT bullet 4`,
        state: 'weakening', trajectory: 'improving',
        state_reasoning: 'Sustainable compound cost gap currently >15%; target <10% at volume.',
        trajectory_reasoning: 'Cost gap closing as bio-sourced supply scales — directional indicator positive.',
      },
      {
        name: 'EPR_RECYCLED_CONTENT_MANDATE',
        description: 'EU EPR recycled content mandate scope and timeline. Market driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP ML-02 (Market driver — EU EPR recycled content mandate scope and timeline)`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'Mandate >20% by 2028 directionally indicated but legislative process pending.',
        trajectory_reasoning: 'Volatile — depends on Council/Parliament negotiation outcome.',
      },
    ],
    claims: [
      { component_name: 'EU_TIRE_EPR_PFAS_FRAMEWORK', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'EU EPR framework enters force with recycled content mandates above 20% by 2028.',
        claim_basis: `Brief HYP ML-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 20, threshold_unit: 'pct_recycled_content',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'EPR mandate is the principal regulatory force creating the compliance cost driver.',
        impact_reasoning: 'Each percentage point of recycled content mandate raises Michelin compliance investment.' },
      { component_name: 'BIO_SOURCED_SILICA_AND_RUBBER', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Sustainable natural rubber + Symbio bio-sourced silica reach commercial scale: certified rubber for 15%+ of Michelin needs by 2027 AND silica >100,000 tires/yr by 2027.',
        claim_basis: `Brief HYP ML-02 WNTBT conditions 2 + 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 100000, threshold_unit: 'tires_per_year',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Sustainable feedstock at scale is the operational lever for compliance.',
        impact_reasoning: 'Volume scale drives down the cost gap.' },
      { component_name: 'SUSTAINABLE_COMPOUND_COST_GAP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'No cost gap above 10% between sustainable compounds and current formulations at volume.',
        claim_basis: `Brief HYP ML-02 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 10, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cost gap is the operational threshold for transition without margin sacrifice.',
        impact_reasoning: 'Each step of cost-gap closure makes sustainable transition self-funding.' },
      { component_name: 'EPR_RECYCLED_CONTENT_MANDATE', role: 'external_threat', impact: 'amplifying', criticality: 'medium',
        claim_text: 'EU EPR recycled-content mandate scope expands beyond passenger to include heavy-duty + specialty tyre segments before 2030.',
        claim_basis: `Brief HYP ML-02 (broader EPR scope risk). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Scope expansion accelerates the €1B+ investment trajectory.',
        impact_reasoning: 'Each segment added to EPR scope adds compliance investment.' },
    ],
  },

  // ML-03 ----------------------------------------------------------------
  {
    name: 'Michelin specialty + high-performance segments as primary EBIT margin anchor by 2028',
    strategy_context: `Volume passenger tyre margins under pressure from Chinese imports (BYD-tyres, GiTi, Sailun) capturing European mid-tier replacement share. Specialty tyres (aircraft, mining, motorsport) hold structural margin advantage; aircraft tyre demand recovering post-COVID.`,
    brief_description: 'Whether specialty + high-performance segments become Michelin\'s primary EBIT margin anchor by 2028.',
    hypothesis_statement: `Michelin's specialty and high-performance segments will become the primary EBIT margin anchor by 2028 as volume passenger tire margins compress under Chinese competitive pressure. Source: ${BRIEF}, HYP ML-03.`,
    why_it_matters: 'Aircraft and mining tyre materials, wear analytics, and remote performance monitoring are product innovation areas where FutureBridge\'s technology intelligence adds direct value.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP ML-03 (H1 · 2-4yr)`,
    decision_threshold: [
      'Michelin specialty tire EBIT margin exceeds 18% in both 2025 and 2026;',
      'Chinese tires capture 25%+ of the European mid-tier replacement market by 2027;',
      'Global aircraft tire demand recovers to 110%+ of 2019 volumes by end-2026;',
      'Michelin wins at least 2 significant mining tire OEM contracts before end-2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP ML-03.)',
    ].join(' '),
    baseline_confidence: 0.67,
    current_confidence: 0.67,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Market (Chinese tire export share) AND Technology (aircraft tire wear analytics) as live SIGNAL drivers.',
    trajectory_reasoning: `Specialty tyre margin trajectory positive; aircraft fleet recovery sustained. Source: ${BRIEF}.`,
    components: [
      {
        name: 'CHINESE_TIRE_EUROPEAN_SHARE',
        description: 'Chinese tire export share of European mid-tier. Market SIGNAL driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP ML-03 (Market driver SIGNAL — Chinese tire export share); WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'deteriorating',
        state_reasoning: 'Brief LIVE NOW: Chinese tire export volume data quarterly. Share rising in mid-tier.',
        trajectory_reasoning: 'BYD-tyres + GiTi + Sailun expanding European distribution; trajectory consistent with 25%+ by 2027.',
      },
      {
        name: 'AIRCRAFT_TIRE_DEMAND_RECOVERY',
        description: 'Global aircraft widebody fleet utilisation and tire demand. Policy driver per brief — currently NOT signalled but the underlying demand force.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP ML-03 (Policy driver — Aircraft fleet recovery); WNTBT bullet 3`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: Global aircraft widebody utilisation rates approaching pre-COVID levels.',
        trajectory_reasoning: 'IATA + Boeing + Airbus 2024-2025 traffic data confirm sustained recovery.',
      },
      {
        name: 'AIRCRAFT_TIRE_MATERIALS_AND_ANALYTICS',
        description: 'Aircraft tire materials and wear analytics. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP ML-03 (Technology driver SIGNAL — Aircraft tire materials and wear analytics)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Aircraft tyre advanced materials + remote monitoring deployment ongoing.',
        trajectory_reasoning: 'Trajectory positive — connected aircraft tyre programmes expanding.',
      },
      {
        name: 'MICHELIN_SPECIALTY_VS_PASSENGER_EBIT',
        description: 'Michelin specialty vs passenger tire EBIT margin. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ML-03 (Economics driver — Specialty vs passenger EBIT margin); WNTBT bullets 1 + 4`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Specialty EBIT margin >18% target in both 2025 + 2026 directionally indicated.',
        trajectory_reasoning: 'Specialty mining + aircraft contracts pipeline supports trajectory.',
      },
    ],
    claims: [
      { component_name: 'MICHELIN_SPECIALTY_VS_PASSENGER_EBIT', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Michelin specialty tire EBIT margin exceeds 18% in both 2025 and 2026.',
        claim_basis: `Brief HYP ML-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 18, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Specialty margin is the principal financial confirmation of the segment shift.',
        impact_reasoning: 'Each percentage point above 18% strengthens the EBIT-anchor thesis.' },
      { component_name: 'CHINESE_TIRE_EUROPEAN_SHARE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Chinese tires capture 25%+ of the European mid-tier replacement market by 2027.',
        claim_basis: `Brief HYP ML-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 25, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Chinese share is the operational force compressing volume passenger margins.',
        impact_reasoning: 'Each percentage point of Chinese mid-tier share forces Michelin defensive moves.' },
      { component_name: 'AIRCRAFT_TIRE_DEMAND_RECOVERY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Global aircraft tire demand recovers to 110%+ of 2019 volumes by end-2026.',
        claim_basis: `Brief HYP ML-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 110, threshold_unit: 'pct_of_2019',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Aircraft demand recovery is the structural growth driver for specialty.',
        impact_reasoning: 'Above 110% of 2019, aircraft tyre business sets new revenue records.' },
      { component_name: 'AIRCRAFT_TIRE_MATERIALS_AND_ANALYTICS', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'Michelin wins at least 2 significant mining tire OEM contracts before end-2026.',
        claim_basis: `Brief HYP ML-03 WNTBT condition 4 (mapped to specialty technology component). Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Mining contracts are structural OEM lock-ins for specialty.',
        impact_reasoning: 'Each contract anchors multi-year specialty revenue.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
