// db/population/P4_seat_cupra_hypotheses.mjs
// Source: seat_cupra_intelligence_brief__4_.html (March 2026 brief).
// Three hypotheses: CUP-01 CUPRA volume, CUP-02 brand drift toward Audi, CUP-03 Spain manufacturing hub.
// PG company: id=92 (SEAT / CUPRA).
//
// Run:
//   node db/population/P4_seat_cupra_hypotheses.mjs           # dry-run
//   node db/population/P4_seat_cupra_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'seat_cupra_intelligence_brief__4_.html (March 2026)';

const company = {
  name: 'SEAT / CUPRA',
  sector: 'mobility',
  notes: 'SEAT S.A. (parent) and CUPRA (performance brand). VW Group subsidiary. HQ: Martorell, Spain. CUPRA is the volume growth engine. v2 catalogue first-cut hypotheses sourced from March 2026 brief.',
};

const initiatives = [
  // CUP-01 ----------------------------------------------------------------
  {
    name: 'CUPRA exceeds 300k annual units by 2026, Spain becomes VWG strategic EV manufacturing hub',
    strategy_context: `CUPRA launched 2018 as performance/youth brand. 2024 deliveries ~230k units; 300k+ target by 2026 implies sustained growth. Spanish government co-investment €3B+ in Martorell electrification. PowerCo Sagunt gigafactory under construction supplies cells. Brief assesses High confidence.`,
    brief_description: 'Whether CUPRA exceeds 300k annual units by 2026, with Spain confirmed as VWG strategic EV manufacturing hub.',
    hypothesis_statement: `CUPRA will exceed 300,000 annual units by 2026, cementing its position as VW Group's fastest-growing brand and establishing Spain as a strategic EV manufacturing hub. Source: ${BRIEF}, HYP CUP-01.`,
    why_it_matters: 'CUPRA growth creates an immediate technology partnership window. Battery performance software, digital UX, and performance tuning are the scouting categories.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP CUP-01 (H1 · 1-3yr)`,
    decision_threshold: [
      'CUPRA Born and Tavascan combined European sales reach 120,000+ units in 2025;',
      'VW Group allocates one or more additional MEB-based models to CUPRA production in Spain by end-2025;',
      'Spanish government co-investment in Martorell electrification remains fully committed at €3B+;',
      'CUPRA Tavascan achieves top-3 position in its segment across 3+ major European markets.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP CUP-01.)',
    ].join(' '),
    baseline_confidence: 0.77,
    current_confidence: 0.77,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Market (VWG MEB allocation) AND Technology (battery performance + UX) as live SIGNAL drivers. CUPRA growth accelerating since 2022.',
    trajectory_reasoning: `CUPRA Born + Tavascan ramping; MEB cost reductions widening accessible price points. Source: ${BRIEF}.`,
    components: [
      {
        name: 'CUPRA_BORN_TAVASCAN_VOLUME',
        description: 'CUPRA Born + Tavascan combined European sales. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-01 (Economics — CUPRA volume); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: CUPRA monthly European sales data trending up. 120k+ in 2025 directionally consistent.',
        trajectory_reasoning: 'Tavascan ramp + Born facelift + new model pipeline.',
      },
      {
        name: 'VWG_MEB_SPAIN_MODEL_ALLOCATION',
        description: 'VW Group MEB model allocation to Spanish production. Market SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-01 (Market SIGNAL — VWG MEB allocation to Spain); WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: VW Group model allocation announcements ongoing.',
        trajectory_reasoning: 'Additional MEB allocation by end-2025 directionally consistent with VWG CEE consolidation pattern.',
      },
      {
        name: 'CUPRA_BATTERY_SOFTWARE_AND_UX',
        description: 'Battery performance software and digital UX features. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-01 (Technology SIGNAL — Battery performance software and digital UX)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'CUPRA leveraging VW.OS + CARIAD tech with performance-focused UX overlay.',
        trajectory_reasoning: 'Differentiated UX + battery tuning is the brand-building lever.',
      },
      {
        name: 'SPANISH_GOVT_MARTORELL_INVESTMENT',
        description: 'Spanish government Martorell electrification co-investment. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-01 (Policy — Spanish Martorell co-investment); WNTBT bullet 3`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: '€3B+ commitment in place; PERTE VEC programme active.',
        trajectory_reasoning: 'Stable through 2026 absent political shift.',
      },
    ],
    claims: [
      { component_name: 'CUPRA_BORN_TAVASCAN_VOLUME', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'CUPRA Born and Tavascan combined European sales reach 120,000+ units in 2025.',
        claim_basis: `Brief HYP CUP-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 120000, threshold_unit: 'units',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Volume threshold is the principal numeric anchor.',
        impact_reasoning: 'Each unit above 120k strengthens trajectory to 300k by 2026.' },
      { component_name: 'VWG_MEB_SPAIN_MODEL_ALLOCATION', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VW Group allocates one or more additional MEB-based models to CUPRA production in Spain by end-2025.',
        claim_basis: `Brief HYP CUP-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Model allocation is the structural confirmation of Spain-as-hub thesis.',
        impact_reasoning: 'Each additional model adds capacity utilisation + margin contribution.' },
      { component_name: 'CUPRA_BATTERY_SOFTWARE_AND_UX', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'CUPRA Tavascan achieves top-3 position in its segment across 3+ major European markets.',
        claim_basis: `Brief HYP CUP-01 WNTBT condition 4 (mapped to brand differentiation tech). Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 3, threshold_unit: 'markets',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Top-3 segment position is the structural validation of brand strength.',
        impact_reasoning: 'Each market with top-3 position locks in dealer + customer mind-share.' },
      { component_name: 'SPANISH_GOVT_MARTORELL_INVESTMENT', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'Spanish government co-investment in Martorell electrification holds fully committed at €3B+ through 2026 (no PERTE VEC retrenchment).',
        claim_basis: `Brief HYP CUP-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 3, threshold_unit: 'EUR_billion',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Government co-investment is the political precondition for the manufacturing hub thesis.',
        impact_reasoning: 'Withdrawal would shift allocation back to Wolfsburg / Mlada Boleslav.' },
    ],
  },

  // CUP-02 ----------------------------------------------------------------
  {
    name: 'CUPRA brand drifts toward Audi territory by 2028 — internal VWG competition risk',
    strategy_context: `CUPRA average transaction price rising; Born + Tavascan + Formentor pricing approaches Audi entry-level. Brand drift creates internal VWG competition with Audi Q4 e-tron in segment + price. Brief assesses Medium confidence.`,
    brief_description: 'Whether CUPRA brand drift toward Audi territory creates VWG internal competition requiring resolution by 2028.',
    hypothesis_statement: `CUPRA's brand will begin to drift toward Audi territory by 2028 — performance positioning and higher transaction prices will create internal VW Group competition requiring resolution. Source: ${BRIEF}, HYP CUP-02.`,
    why_it_matters: 'Brand differentiation intelligence is the strategic input CUPRA\'s marketing function most visibly lacks as it scales.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP CUP-02 (H2 · 3-5yr)`,
    decision_threshold: [
      'CUPRA average transaction price exceeds €40,000 by end-2026 overlapping entry-level Audi EQ;',
      'VW Group publicly debates CUPRA long-term brand architecture role by 2026;',
      'CUPRA launches a model directly competing with Audi Q4 e-tron in segment and price by 2027;',
      'CUPRA brand awareness in Northern Europe exceeds 60% unaided recall by end-2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP CUP-02.)',
    ].join(' '),
    baseline_confidence: 0.62,
    current_confidence: 0.62,
    state: 'new',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (CUPRA ATP vs Audi entry-level) AND Market (CUPRA NE awareness) as live SIGNAL drivers.',
    trajectory_reasoning: `CUPRA pricing trajectory upward; Audi entry-level under price pressure. Source: ${BRIEF}.`,
    components: [
      {
        name: 'CUPRA_ATP_VS_AUDI_ENTRY',
        description: 'CUPRA average transaction price vs Audi entry-level. Economics SIGNAL driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-02 (Economics SIGNAL — CUPRA ATP vs Audi); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: CUPRA transaction price data by market trending toward €40k.',
        trajectory_reasoning: 'Premium positioning is the brand-building strategy; trajectory consistent with overlap.',
      },
      {
        name: 'CUPRA_BRAND_AWARENESS_NORTHERN_EUROPE',
        description: 'CUPRA brand awareness in Northern Europe. Market SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-02 (Market SIGNAL — CUPRA brand awareness Northern Europe); WNTBT bullet 4`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'CUPRA brand awareness rising via Formula E + esports + design-led marketing.',
        trajectory_reasoning: '60% unaided recall in NE markets by end-2026 directionally consistent.',
      },
      {
        name: 'CUPRA_AUDI_Q4_ETRON_OVERLAP',
        description: 'Performance EV differentiation vs Audi Q4 e-tron. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-02 (Technology — Performance EV differentiation); WNTBT bullet 3`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'CUPRA Tavascan + Audi Q4 e-tron both MEB-based, similar segment.',
        trajectory_reasoning: 'Volatile — depends on whether VWG enforces brand boundaries or allows overlap.',
      },
      {
        name: 'VWG_BRAND_ARCHITECTURE_GOVERNANCE',
        description: 'VW Group brand architecture governance decisions. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-02 (Policy — VWG brand architecture governance); WNTBT bullet 2`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'No public statement on CUPRA-Audi overlap governance as of brief.',
        trajectory_reasoning: 'Volatile — VWG governance decision pending.',
      },
    ],
    claims: [
      { component_name: 'CUPRA_ATP_VS_AUDI_ENTRY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'CUPRA average transaction price exceeds €40,000 by end-2026 overlapping entry-level Audi EQ.',
        claim_basis: `Brief HYP CUP-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40000, threshold_unit: 'EUR',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'ATP threshold is the principal financial confirmation of segment overlap.',
        impact_reasoning: 'Each €1k of ATP rise approaches Audi entry-level pricing.' },
      { component_name: 'CUPRA_AUDI_Q4_ETRON_OVERLAP', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'CUPRA launches a model directly competing with Audi Q4 e-tron in segment and price by 2027.',
        claim_basis: `Brief HYP CUP-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Direct overlap is the structural confirmation of internal competition.',
        impact_reasoning: 'Each direct-overlap model forces VWG to choose pricing/margin allocation.' },
      { component_name: 'CUPRA_BRAND_AWARENESS_NORTHERN_EUROPE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'CUPRA brand awareness in Northern Europe exceeds 60% unaided recall by end-2026.',
        claim_basis: `Brief HYP CUP-02 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 60, threshold_unit: 'pct_unaided_recall',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Brand awareness above 60% breaches the threshold where CUPRA stops being a niche performance play.',
        impact_reasoning: 'Each percentage point of awareness expands competitive overlap with Audi.' },
      { component_name: 'VWG_BRAND_ARCHITECTURE_GOVERNANCE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW Group publicly debates CUPRA long-term brand architecture role by 2026.',
        claim_basis: `Brief HYP CUP-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Public debate confirms boardroom-level recognition of the issue.',
        impact_reasoning: 'Public framing forces resolution within strategic planning cycle.' },
    ],
  },

  // CUP-03 ----------------------------------------------------------------
  {
    name: 'Spain EV manufacturing hub delivers SEAT/CUPRA supply chain independence by 2027',
    strategy_context: `PowerCo Sagunt gigafactory under construction with first cell production targeted before end-2026. Spanish SEAT/CUPRA battery localisation rate target 40%+ of vehicle BOM by end-2027. EU Battery Regulation favours local content. Brief assesses Medium confidence.`,
    brief_description: 'Whether Spain EV manufacturing hub delivers SEAT/CUPRA supply chain independence within VWG by 2027.',
    hypothesis_statement: `Spain's EV manufacturing hub investment will deliver supply chain independence for SEAT and CUPRA within VW Group by 2027. Source: ${BRIEF}, HYP CUP-03.`,
    why_it_matters: 'Battery supply chain localisation, gigafactory ramp intelligence, and Spanish manufacturing cost benchmarks are inputs SEAT/CUPRA\'s operations team needs.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP CUP-03 (H1 · 2-3yr)`,
    decision_threshold: [
      'PowerCo gigafactory in Sagunt achieves first battery cell production before end-2026;',
      'Spanish SEAT/CUPRA battery localisation rate exceeds 40% of vehicle BOM by end-2027;',
      'VW Group does not announce capacity closure affecting Martorell in 2025 or 2026;',
      'EU ESPR or battery regulation favours locally produced cells in public procurement by 2027.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP CUP-03.)',
    ].join(' '),
    baseline_confidence: 0.65,
    current_confidence: 0.65,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (Sagunt cell production) AND Policy (EU Battery Regulation) as live SIGNAL drivers.',
    trajectory_reasoning: `Sagunt gigafactory construction on schedule; PowerCo Salzgitter operational confirms PowerCo execution. Source: ${BRIEF}.`,
    components: [
      {
        name: 'POWERCO_SAGUNT_CELL_PRODUCTION',
        description: 'PowerCo Sagunt gigafactory cell production readiness. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-03 (Technology SIGNAL — Battery cell production at Sagunt); WNTBT bullet 1`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Brief LIVE NOW: PowerCo Sagunt construction milestone updates ongoing.',
        trajectory_reasoning: 'Salzgitter operational pattern (commissioned Dec 2024) replicable at Sagunt.',
      },
      {
        name: 'SEAT_CUPRA_BATTERY_LOCALISATION',
        description: 'Spanish SEAT/CUPRA battery localisation % of BOM. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-03 (Economics — Battery localisation % of BOM); WNTBT bullet 2`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Localisation rate currently low; 40%+ target by end-2027 contingent on Sagunt ramp.',
        trajectory_reasoning: 'Trajectory positive but pace gated by Sagunt commissioning.',
      },
      {
        name: 'EU_BATTERY_REGULATION_LOCAL_CONTENT',
        description: 'EU Battery Regulation local content and subsidy criteria. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP CUP-03 (Policy SIGNAL — EU Battery Regulation local content); WNTBT bullet 4`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'EU Battery Regulation in force; ESPR + procurement preferences tightening.',
        trajectory_reasoning: 'Trajectory favourable for Sagunt-produced cells.',
      },
      {
        name: 'MARTORELL_CAPACITY_PROTECTION',
        description: 'Martorell capacity protection within VW Group restructuring. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CUP-03 (Market — Martorell capacity protection); WNTBT bullet 3`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'No Martorell capacity closure in current VW Group restructuring scope.',
        trajectory_reasoning: 'Stable — Spain hub thesis aligned with VWG CEE consolidation logic.',
      },
    ],
    claims: [
      { component_name: 'POWERCO_SAGUNT_CELL_PRODUCTION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'PowerCo gigafactory in Sagunt achieves first battery cell production before end-2026.',
        claim_basis: `Brief HYP CUP-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cell production milestone is the principal observable confirmation of Spain hub.',
        impact_reasoning: 'Production start enables localisation % to climb.' },
      { component_name: 'SEAT_CUPRA_BATTERY_LOCALISATION', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Spanish SEAT/CUPRA battery localisation rate exceeds 40% of vehicle BOM by end-2027.',
        claim_basis: `Brief HYP CUP-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40, threshold_unit: 'pct_BOM',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Localisation threshold is the operational definition of supply-chain independence.',
        impact_reasoning: 'Each percentage point of localisation reduces import-dependency on East Asian cells.' },
      { component_name: 'EU_BATTERY_REGULATION_LOCAL_CONTENT', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'EU ESPR or battery regulation favours locally produced cells in public procurement by 2027.',
        claim_basis: `Brief HYP CUP-03 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Regulatory preference is the policy lever creating sustainable advantage.',
        impact_reasoning: 'Each procurement preference reinforces the Sagunt cost-competitiveness case.' },
      { component_name: 'MARTORELL_CAPACITY_PROTECTION', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'VW Group announces capacity closure affecting Martorell in 2025 or 2026.',
        claim_basis: `Brief HYP CUP-03 WNTBT condition 3 (inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Closure would directly contradict the Spain-as-hub thesis.',
        impact_reasoning: 'Each Martorell capacity reduction shrinks the Spain hub footprint.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
