// db/population/P5_CNP_hypotheses.mjs
// Source: conocophillips_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'ConocoPhillips'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'conocophillips_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'ConocoPhillips',
  sector: 'energy',
  notes: 'ConocoPhillips — largest US-listed independent E&P after Marathon integration. NYSE:COP. CEO Ryan Lance. v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // CNP-01 ----------------------------------------------------------------
  {
    name: 'COP $7B FCF inflection by 2029 (Willow + 3 LNG projects)',
    strategy_context: `COP 2025: $8.0B earnings + $19.8B CFO. $7B 2029 FCF inflection driven by Willow first oil + NFE first LNG 2026 + Port Arthur Phase 1 + APLNG sustained. $1B annual FCF improvement 2026-2028, $4B improvement 2029. CEO Lance: "resource-rich company in resource-starved world."`,
    brief_description: 'Whether COP delivers the $7B 2029 FCF inflection.',
    hypothesis_statement: `ConocoPhillips delivers the $7B 2029 FCF inflection: Willow first oil on schedule + NFE first LNG 2026 + Port Arthur Phase 1 + APLNG sustained = 2× current FCF and breakeven below $35 WTI. Source: ${BRIEF}, HYP CNP-01.`,
    why_it_matters: 'Willow Alaska execution intelligence + NFE / Port Arthur / APLNG project status are the active scouting categories.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2029,
    time_horizon_source: `${BRIEF} HYP CNP-01 (H2 · 3-5yr)`,
    decision_threshold: 'Willow first oil achieves 2029 target without major slippage; NFE first LNG cargo delivered in 2026 as scheduled; Port Arthur Phase 1 commissioning + APLNG production hold through 2027-2028; Brent / WTI sustained above $60 / $55 through 2027-2029. (WNTBT, brief HYP CNP-01.)',
    baseline_confidence: 0.74, current_confidence: 0.74,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (Willow + LNG FCF) AND Market (Asia + Europe LNG demand) as live SIGNAL drivers.',
    trajectory_reasoning: `Marathon synergies $1B+ realised; Willow construction underway; NFE first LNG 2026 imminent. Source: ${BRIEF}.`,
    components: [
      { name: 'WILLOW_ALASKA_FIRST_OIL_2029', description: 'Willow Alaska North Slope first oil 2029. ~600 MMboe, 30-yr+ asset.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-01 WNTBT bullet 1`, state: 'new', trajectory: 'improving',
        state_reasoning: 'BLM approved 2023; construction underway.', trajectory_reasoning: 'On schedule per Q3 2025.' },
      { name: 'NFE_QATARENERGY_FIRST_LNG_2026', description: 'NFE QatarEnergy partnership; first LNG 2026; COP partner. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-01 (Market SIGNAL); WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'On schedule per Q3 2025; first cargo H1 2026 expected.', trajectory_reasoning: 'QatarEnergy execution track record strong.' },
      { name: 'PORT_ARTHUR_APLNG_PORTFOLIO', description: 'Port Arthur Phase 1 commissioning + APLNG sustained. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-01 (Economics SIGNAL); WNTBT bullet 3`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'APLNG operational; Port Arthur Phase 1 commissioning.', trajectory_reasoning: 'Both projects on schedule.' },
      { name: 'WTI_BRENT_PRICE_FLOOR', description: 'WTI / Brent price floor through 2027-2029.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP CNP-01 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'WTI above $55 throughout 2025; OPEC+ supply discipline.', trajectory_reasoning: 'Stable above breakeven assumption.' },
    ],
    claims: [
      { component_name: 'WILLOW_ALASKA_FIRST_OIL_2029', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Willow first oil achieves 2029 target without major slippage.',
        claim_basis: `Brief HYP CNP-01 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Willow contributes $4B of the $7B 2029 inflection — single-largest driver.', impact_reasoning: 'Each year of slip pushes FCF inflection beyond 2029.' },
      { component_name: 'NFE_QATARENERGY_FIRST_LNG_2026', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'NFE first LNG cargo delivered in 2026 as scheduled.',
        claim_basis: `Brief HYP CNP-01 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'NFE first LNG kicks off the LNG portion of the 2029 inflection.', impact_reasoning: 'Each cargo adds Asia premium-supply EBITDA.' },
      { component_name: 'PORT_ARTHUR_APLNG_PORTFOLIO', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Port Arthur Phase 1 commissioning + APLNG production hold through 2027-2028.',
        claim_basis: `Brief HYP CNP-01 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Combined LNG portfolio underpins ~$3B of the inflection.', impact_reasoning: 'Each project on schedule confirms timing.' },
      { component_name: 'WTI_BRENT_PRICE_FLOOR', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'Brent / WTI sustained above $60 / $55 through 2027-2029 supporting low-cost supply economics.',
        claim_basis: `Brief HYP CNP-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 55, threshold_unit: 'USD_per_bbl_WTI', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Sustained price required for FCF inflection economics.', impact_reasoning: 'Each $5/bbl above breakeven adds material FCF.' },
    ],
  },

  // CNP-02 ----------------------------------------------------------------
  {
    name: 'Marathon synergies + cost discipline reach $2B+ structural savings by end-2026',
    strategy_context: `Marathon $1B+ synergies vs $500M initial target (2× upside). Additional $1B+ cost discipline identified. 2026 capex $12B (-$500M from 2025) with flat-to-2% production growth. Pattern signals durable low-cost-supply identity.`,
    brief_description: 'Whether Marathon synergies + cost discipline reach $2B+ by end-2026.',
    hypothesis_statement: `Marathon synergies + cost discipline reach $2B+ structural annual savings by end-2026, with COP capex falling to $11B+ in 2027 while production grows 2-3%, confirming the integration playbook as best-in-class US E&P M&A. Source: ${BRIEF}, HYP CNP-02.`,
    why_it_matters: 'Shale efficiency benchmarking (vs XOM/CVX/EOG/Diamondback) is the most commercially valuable input as COP defines the capital-discipline frontier.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP CNP-02 (H1 · 1-2yr)`,
    decision_threshold: 'Synergies + cost discipline reach $2B+ annual run-rate by end-2026; 2026 capex achieves $12B target (-$500M from 2025); 2026 production grows flat-to-2% as guided; No material US shale regulatory shock (water, methane) before end-2026. (WNTBT, brief HYP CNP-02.)',
    baseline_confidence: 0.78, current_confidence: 0.78,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (Marathon synergy) AND Technology (combined drilling + completion + workforce optimisation) as live SIGNAL drivers.',
    trajectory_reasoning: `Synergies doubled vs initial estimate; +$1B cost discipline pipeline. Source: ${BRIEF}.`,
    components: [
      { name: 'MARATHON_SYNERGY_RUN_RATE', description: 'Marathon synergy + cost discipline run-rate. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-02 (Economics SIGNAL); WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: '$1B+ synergies + $1B+ additional cost discipline.', trajectory_reasoning: 'Multi-quarter run-rate building.' },
      { name: 'COP_CAPEX_DISCIPLINE_2026', description: '2026 capex $12B (-$500M from 2025) with growth.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-02 WNTBT bullet 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Capex declining while production growing — structural efficiency.', trajectory_reasoning: 'Pattern characteristic of low-cost-supply identity.' },
      { name: 'COMBINED_DRILLING_COMPLETION_OPTIMISATION_COP', description: 'Combined drilling + completion + workforce optimisation post-Marathon.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-02 (Technology SIGNAL)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Combined know-how + acreage = best-in-class.', trajectory_reasoning: 'Each optimisation lifts well economics.' },
      { name: 'US_SHALE_OPERATING_REGIME_COP', description: 'US shale operating regime stability (water, methane, permitting).', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP CNP-02 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No near-term shift; Texas + New Mexico + North Dakota stable.', trajectory_reasoning: 'Stable.' },
    ],
    claims: [
      { component_name: 'MARATHON_SYNERGY_RUN_RATE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Synergies + cost discipline reach $2B+ annual run-rate by end-2026.',
        claim_basis: `Brief HYP CNP-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'USD_billion_annual', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Combined synergy + cost discipline is the principal financial lift from integration.', impact_reasoning: 'Each $B flows to operating cash flow.' },
      { component_name: 'COP_CAPEX_DISCIPLINE_2026', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: '2026 capex achieves $12B target (-$500M from 2025).',
        claim_basis: `Brief HYP CNP-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 12, threshold_unit: 'USD_billion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Capex discipline is the operational confirmation of low-cost identity.', impact_reasoning: 'Each $100M below target adds to FCF.' },
      { component_name: 'COMBINED_DRILLING_COMPLETION_OPTIMISATION_COP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: '2026 production grows flat-to-2% as guided.',
        claim_basis: `Brief HYP CNP-02 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Production growth confirms combined acreage / capability is delivering.', impact_reasoning: 'Each well outperforming pre-acquisition baseline lifts economics.' },
      { component_name: 'US_SHALE_OPERATING_REGIME_COP', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A material US shale regulatory shock (water disposal, methane, permitting) before end-2026.',
        claim_basis: `Brief HYP CNP-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Regulatory shock would constrain 2026 production.', impact_reasoning: 'Each restriction delays well completions.' },
    ],
  },

  // CNP-03 ----------------------------------------------------------------
  {
    name: 'COP achieves low-$30s WTI breakeven by decade-end (lowest-cost US-listed independent)',
    strategy_context: `Management target: breakeven low $30s WTI by decade-end. Among lowest of US-listed independent E&Ps. Long-life asset mix (Willow + APLNG + NFE) plus continued cost discipline.`,
    brief_description: 'Whether COP achieves low-$30s WTI breakeven by decade-end.',
    hypothesis_statement: `COP achieves low-$30s WTI breakeven by decade-end across the integrated portfolio, becoming the lowest-cost US-listed independent E&P and structurally insulated against $40+ price scenarios. Source: ${BRIEF}, HYP CNP-03.`,
    why_it_matters: 'Low-cost-supply benchmarking + scenario stress testing are inputs COP boardroom + investor relations need.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP CNP-03 (H2 · 3-5yr)`,
    decision_threshold: '2027 breakeven discloses below $40 WTI; 2028 below $35 WTI; Long-life asset mix (Willow + APLNG + NFE) consolidates above 35% of total reserve life; No major one-off cost increase (Alaska, Asia LNG) breaks the trajectory; Cost discipline programme remains in place under continued Lance leadership or successor. (WNTBT, brief HYP CNP-03.)',
    baseline_confidence: 0.68, current_confidence: 0.68,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (breakeven trajectory) as live SIGNAL driver. Long-life mix building.',
    trajectory_reasoning: `Cost discipline + long-life asset mix support trajectory. Source: ${BRIEF}.`,
    components: [
      { name: 'COP_BREAKEVEN_TRAJECTORY', description: 'COP breakeven trajectory toward $30s WTI by decade-end. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-03 (Economics SIGNAL); WNTBT bullets 1 + 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Disclosed target low-$30s by decade-end.', trajectory_reasoning: 'Cost discipline building over time.' },
      { name: 'LONG_LIFE_ASSET_MIX', description: 'Long-life asset mix (Willow + APLNG + NFE) consolidating above 35% of reserve life.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-03 WNTBT bullet 3`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Three projects all in build/start-up phase.', trajectory_reasoning: 'Mix shift toward long-life by 2029-2030.' },
      { name: 'WTI_BRENT_PRICE_STRUCTURAL', description: 'WTI / Brent oil price structural backdrop.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP CNP-03 (Market — WTI / Brent oil price structural)`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'OPEC+ supply discipline + EM demand.', trajectory_reasoning: 'Stable above breakeven.' },
      { name: 'US_LEASING_ALASKA_PERMITS', description: 'US offshore + onshore leasing + Alaska permits (Willow). Policy driver.', component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP CNP-03 (Policy)`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'BLM Willow approved; no material reversal indicated.', trajectory_reasoning: 'Stable absent political shift.' },
    ],
    claims: [
      { component_name: 'COP_BREAKEVEN_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: '2027 breakeven discloses below $40 WTI; 2028 below $35 WTI.',
        claim_basis: `Brief HYP CNP-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 40, threshold_unit: 'USD_per_bbl_WTI', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Breakeven disclosure is the principal financial confirmation.', impact_reasoning: 'Each $1 below threshold widens insulation.' },
      { component_name: 'LONG_LIFE_ASSET_MIX', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Long-life asset mix (Willow + APLNG + NFE) consolidates above 35% of total reserve life.',
        claim_basis: `Brief HYP CNP-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 35, threshold_unit: 'pct_reserve_life', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Long-life mix structurally lowers decline rate and breakeven.', impact_reasoning: 'Each percentage point of long-life share lifts portfolio NPV.' },
      { component_name: 'US_LEASING_ALASKA_PERMITS', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A major one-off cost increase (Alaska supply chain, Asia LNG construction overrun) breaks the breakeven trajectory.',
        claim_basis: `Brief HYP CNP-03 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'One-off cost shock could disrupt the disciplined trajectory.', impact_reasoning: 'Each cost overrun adds to per-barrel breakeven.' },
      { component_name: 'WTI_BRENT_PRICE_STRUCTURAL', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'Cost discipline programme remains in place under continued Lance leadership or successor.',
        claim_basis: `Brief HYP CNP-03 WNTBT condition 5. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Leadership continuity is the cultural precondition for sustained discipline.', impact_reasoning: 'Programme inertia compounds over multiple years.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
