// db/population/P5_CON_hypotheses.mjs
// Source: continental_intelligence_brief__1_.html (May 2026 brief).
// PG company: existing 'Continental AG' row (id=10) — populator re-uses via ON CONFLICT (name).

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'continental_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'Continental AG',
  sector: 'mobility',
  notes: 'Continental AG — Hanover-based Tier-1 transforming to pure-play tire manufacturer. ETR:CON. Aumovio (Auto) spun off Sept 2025; OESL sold Feb 2026; ContiTech sale planned 2026. v2 catalogue first-cut hypotheses sourced from May 2026 brief. Re-uses PG id=10.',
};

const initiatives = [
  // CON-01 ----------------------------------------------------------------
  {
    name: 'Continental completes pure-play tire transformation by end-2026 via ContiTech sale',
    strategy_context: `Realignment programme: Aumovio (Automotive) spun off Sept 2025 (~€4.1B Frankfurt listing); OESL sold Feb 2026; ContiTech sale planned 2026 = final step. Post-divestment Continental = pure-play tire manufacturer. Equity ratio 26.3% post-Aumovio.`,
    brief_description: 'Whether Continental completes the pure-play tire transformation by end-2026.',
    hypothesis_statement: `Continental completes its transformation to pure-play tire manufacturer by end-2026 through ContiTech divestment, anchoring a focused FY2027+ profile around Tires + sustained >10% operating margin. Source: ${BRIEF}, HYP CON-01.`,
    why_it_matters: 'ContiTech sale-process tracking is the highest-priority engagement input through 2026.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP CON-01 (H1 · 1-2yr)`,
    decision_threshold: 'ContiTech sale signed by end-2026; No material Aumovio claw-back / unwind risk before end-2026; EU regulatory approvals achieved without material remedies; Post-divestment FY2027+ Tires-only group operates with sustained >10% EBIT margin. (WNTBT, brief HYP CON-01.)',
    baseline_confidence: 0.70, current_confidence: 0.70,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (sale process status) AND Economics (ContiTech valuation) as live SIGNAL drivers; Aumovio + OESL already executed.',
    trajectory_reasoning: `Two-thirds of realignment complete; ContiTech remaining. Source: ${BRIEF}.`,
    components: [
      { name: 'CONTITECH_SALE_PROCESS', description: 'ContiTech sale process status + buyer interest + valuation. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-01 (Market SIGNAL); WNTBT bullet 1; SIG-01`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Sale planned 2026; process timeline ramping.', trajectory_reasoning: 'Industrial-cycle recovery H2 2026 supports valuation.' },
      { name: 'AUMOVIO_POST_SPIN_INDEPENDENCE', description: 'Aumovio post-spin independence (no claw-back / unwind risk).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-01 WNTBT bullet 2; Section 04 Aumovio card`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Aumovio listed Sept 2025 ~€4.1B; no Continental retained stake.', trajectory_reasoning: 'Stable absent governance challenge.' },
      { name: 'EU_REGULATORY_APPROVALS_CON', description: 'EU regulatory approvals for ContiTech divestment without material remedies.', component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-01 WNTBT bullet 3`, state: 'new', trajectory: 'unknown',
        state_reasoning: 'Approvals dependent on buyer + structure.', trajectory_reasoning: 'Outcome contingent on transaction specifics.' },
      { name: 'TIRES_ONLY_OPERATING_MARGIN', description: 'Post-divestment Tires-only group operates with sustained >10% EBIT margin.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-01 WNTBT bullet 4`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q1 2026 Tires margin 14.4%; >10% baseline already established.', trajectory_reasoning: 'Premium-mix supports trajectory.' },
    ],
    claims: [
      { component_name: 'CONTITECH_SALE_PROCESS', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'ContiTech sale signed by end-2026.',
        claim_basis: `Brief HYP CON-01 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'ContiTech sale completion is the principal transformation milestone.', impact_reasoning: 'Each quarter of slip extends realignment overhang.' },
      { component_name: 'AUMOVIO_POST_SPIN_INDEPENDENCE', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'No material Aumovio claw-back / unwind risk before end-2026.',
        claim_basis: `Brief HYP CON-01 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A claw-back would derail the Tier-1-to-tire transformation narrative.', impact_reasoning: 'Each governance challenge disrupts the FY2027+ profile.' },
      { component_name: 'EU_REGULATORY_APPROVALS_CON', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'EU regulatory approvals achieved without material remedies.',
        claim_basis: `Brief HYP CON-01 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'EU approvals are the regulatory precondition for closing.', impact_reasoning: 'Each remedy compromises sale value.' },
      { component_name: 'TIRES_ONLY_OPERATING_MARGIN', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Post-divestment FY2027+ Tires-only group operates with sustained >10% EBIT margin.',
        claim_basis: `Brief HYP CON-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'pct_EBIT_margin', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Sustained >10% margin is the principal financial validation of pure-play model.', impact_reasoning: 'Each percentage point above 10% lifts equity narrative.' },
    ],
  },

  // CON-02 ----------------------------------------------------------------
  {
    name: 'Continental Tires sustains ≥14% adj EBIT margin through FY2026 despite tariffs + FX',
    strategy_context: `Q1 2026 Tires EBIT margin 14.4% — improved YoY despite US tariffs + EUR FX. Premium 18"+ growth + raw material price decline H2 2026 supporting trajectory. FY 2026 group guidance 11.0-12.5% adj EBIT margin (group includes ContiTech).`,
    brief_description: 'Whether Tires sustains ≥14% adj EBIT margin through FY2026.',
    hypothesis_statement: `Continental Tires sustains ≥14% adjusted EBIT margin through FY2026 despite US tariffs + FX headwinds, with premium 18"+ mix shift and raw material price decline H2 2026 supporting the trajectory. Source: ${BRIEF}, HYP CON-02.`,
    why_it_matters: 'Quarterly Tires margin + premium-mix tracking + tariff intelligence is the highest-leverage engagement input.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP CON-02 (H1 · 1-2yr)`,
    decision_threshold: 'FY2026 Tires adj EBIT margin holds ≥14%; Premium 18"+ tire mix continues to grow as share of revenue; Raw material prices decline as guided in H2 2026; No material US tariff escalation that erases margin gains. (WNTBT, brief HYP CON-02.)',
    baseline_confidence: 0.65, current_confidence: 0.65,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (Tires margin) AND Market (premium 18"+ mix) AND Policy (US tariff) as live SIGNAL drivers.',
    trajectory_reasoning: `Q1 2026 14.4% beat; trajectory positive. Source: ${BRIEF}.`,
    components: [
      { name: 'CON_TIRES_EBIT_MARGIN', description: 'Continental Tires adj EBIT margin trajectory (Q1 2026 14.4%; target ≥14% FY2026).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-02 (Economics SIGNAL); WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q1 2026 14.4% above prior-year despite tariffs / FX.', trajectory_reasoning: 'Holding through 2026.' },
      { name: 'PREMIUM_18INCH_MIX_GROWTH', description: 'Premium 18"+ tire mix growth as share of revenue.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-02 (Market SIGNAL); WNTBT bullet 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Primary driver of Q1 margin uplift.', trajectory_reasoning: 'EV-ready tire demand expanding.' },
      { name: 'RAW_MATERIAL_PRICE_DECLINE_H2', description: 'Raw material (rubber, oil-derived) price decline H2 2026 as guided.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP CON-02 WNTBT bullet 3`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Currently elevated; decline expected H2 2026.', trajectory_reasoning: 'Outcome dependent on commodity-cycle.' },
      { name: 'US_TARIFF_ESCALATION_RISK_CON', description: 'US tariff escalation risk that erases margin gains.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP CON-02 (Policy SIGNAL); WNTBT bullet 4`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'US tariff regime uncertain.', trajectory_reasoning: 'High geopolitical volatility.' },
    ],
    claims: [
      { component_name: 'CON_TIRES_EBIT_MARGIN', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2026 Tires adj EBIT margin holds ≥14%.',
        claim_basis: `Brief HYP CON-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 14, threshold_unit: 'pct_EBIT_margin', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Margin sustainability is the principal financial validation.', impact_reasoning: 'Each percentage point compounds annual EBIT.' },
      { component_name: 'PREMIUM_18INCH_MIX_GROWTH', role: 'principal', impact: 'amplifying', criticality: 'high',
        claim_text: 'Premium 18"+ tire mix continues to grow as share of revenue.',
        claim_basis: `Brief HYP CON-02 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Premium mix is the principal margin lever.', impact_reasoning: 'Each percentage point of mix-shift compounds margin.' },
      { component_name: 'RAW_MATERIAL_PRICE_DECLINE_H2', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Raw material prices decline as guided in H2 2026.',
        claim_basis: `Brief HYP CON-02 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Raw material cost is the principal external cost lever.', impact_reasoning: 'Each percentage of raw material decline compounds margin.' },
      { component_name: 'US_TARIFF_ESCALATION_RISK_CON', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'A material US tariff escalation that erases margin gains.',
        claim_basis: `Brief HYP CON-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A tariff escalation could fully erase 2026 margin progress.', impact_reasoning: 'Each tariff round compounds cost.' },
    ],
  },

  // CON-03 ----------------------------------------------------------------
  {
    name: 'Continental delivers ≥mid-single-digit Tires unit growth FY2027 (premium 18"+ + EV-ready + APAC)',
    strategy_context: `Premium 18"+ tire growth + EV-ready demand + APAC expansion are the structural growth pillars. Chinese domestic competition (Linglong, Sailun, Hankook) intense in mass market; Continental positioning targets premium / OE / APAC.`,
    brief_description: 'Whether Continental delivers ≥5% Tires unit growth in FY2027.',
    hypothesis_statement: `Continental delivers ≥mid-single-digit Tires unit growth in FY2027 driven by premium 18"+ + EV-ready + APAC expansion, gaining share against Chinese domestic alternatives in premium / OE segments. Source: ${BRIEF}, HYP CON-03.`,
    why_it_matters: 'EV OE tire design-win tracking + APAC share data is the highest-priority growth-thesis input.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP CON-03 (H1 · 1-2yr)`,
    decision_threshold: 'FY2027 Tires unit growth ≥ 5%; Premium 18"+ tire revenue grows above group average; APAC volume share gains visible in FY2027 reporting; No major Chinese tire premium-segment break-out displaces Continental on EV OE. (WNTBT, brief HYP CON-03.)',
    baseline_confidence: 0.60, current_confidence: 0.60,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (APAC EV / all-season demand) AND Technology (EV-ready roadmap) as live SIGNAL drivers.',
    trajectory_reasoning: `Premium-mix growth driving Q1 2026 results. Source: ${BRIEF}.`,
    components: [
      { name: 'CON_TIRES_UNIT_GROWTH', description: 'Continental Tires unit growth FY2027 (target ≥5%).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-03 WNTBT bullet 1`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Mid-single-digit unit growth target stated.', trajectory_reasoning: 'Path through premium 18"+ + APAC.' },
      { name: 'PREMIUM_18INCH_REVENUE_GROWTH', description: 'Premium 18"+ tire revenue grows above group average.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-03 WNTBT bullet 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Driving Q1 2026 mix-shift.', trajectory_reasoning: 'EV-ready demand compounds.' },
      { name: 'CON_APAC_VOLUME_SHARE_GAIN', description: 'Continental APAC volume share gains visible in FY2027 reporting.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-03 WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Selective APAC deepening underway.', trajectory_reasoning: 'Share gains contested vs Chinese domestic players.' },
      { name: 'CHINESE_TIRE_PREMIUM_BREAKOUT_RISK', description: 'Chinese tire (Linglong, Sailun, Hankook) premium-segment break-out displacing Continental on EV OE.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP CON-03 WNTBT bullet 4; SIG-03`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No major premium break-out to date.', trajectory_reasoning: 'Pressure rising in EV OE segment.' },
    ],
    claims: [
      { component_name: 'CON_TIRES_UNIT_GROWTH', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2027 Tires unit growth ≥ 5%.',
        claim_basis: `Brief HYP CON-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 5, threshold_unit: 'pct_unit_growth', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Unit growth is the principal volume validation.', impact_reasoning: 'Each percentage point compounds revenue + margin operating leverage.' },
      { component_name: 'PREMIUM_18INCH_REVENUE_GROWTH', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Premium 18"+ tire revenue grows above group average.',
        claim_basis: `Brief HYP CON-03 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Premium revenue mix is the principal margin lever.', impact_reasoning: 'Each percentage point of premium share compounds.' },
      { component_name: 'CON_APAC_VOLUME_SHARE_GAIN', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'APAC volume share gains visible in FY2027 reporting.',
        claim_basis: `Brief HYP CON-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'APAC growth is the principal geographical lever.', impact_reasoning: 'Each percentage point of APAC share compounds long-term.' },
      { component_name: 'CHINESE_TIRE_PREMIUM_BREAKOUT_RISK', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'No major Chinese tire premium-segment break-out displaces Continental on EV OE.',
        claim_basis: `Brief HYP CON-03 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A premium break-out would erode Continental EV OE margin.', impact_reasoning: 'Each major loss compounds share-erosion path.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
