// db/population/P5_ENI_hypotheses.mjs
// Source: eni_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'Eni SpA'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'eni_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'Eni SpA',
  sector: 'energy',
  notes: 'Eni SpA — Italian integrated energy major. CEO Claudio Descalzi (since 2014). Borsa Italiana:ENI. Satellite valorisation strategy: Plenitude renewables, Enilive biofuels, Eni CCUS partnerships. v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // ENI-01 ----------------------------------------------------------------
  {
    name: 'Eni satellite valorisation unlocks €15B+ stranded value by end-2027',
    strategy_context: `Eni 2025 satellite valorisation: Ares 20% Plenitude €2B at €12B+ EV; GIP 49.99% in Eni CCUS; Vitol 30% Baleine Côte d'Ivoire €1B. Plenitude added Neoen acquisition (0.76 GW France); 5.8 GW capacity → 10 GW by 2028. Sets up Plenitude IPO 2026-2027 + Enilive valorisation.`,
    brief_description: 'Whether Eni satellite strategy unlocks €15B+ stranded value by end-2027.',
    hypothesis_statement: `Eni's satellite valorisation strategy unlocks more than €15B in stranded value by end-2027 via Plenitude IPO, additional Enilive minority sale, and Eni CCUS + Versalis bio-circular partnerships. Source: ${BRIEF}, HYP ENI-01.`,
    why_it_matters: 'Plenitude IPO timing + Enilive valorisation signals + Eni CCUS commercial pipeline are the active scouting categories.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP ENI-01 (H1 · 1-3yr)`,
    decision_threshold: 'Plenitude IPO completes or formal filing in 2026 at ≥€12B implied EV; Enilive minority stake sale to specialist investor before end-2026 at €5B+ EV; Eni CCUS pipeline reaches at least 2 commercial CCS FIDs through GIP partnership by end-2027; Group net debt declines + dividend / buyback returns sustained through 2026-2027. (WNTBT, brief HYP ENI-01.)',
    baseline_confidence: 0.74, current_confidence: 0.74,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (specialist-capital appetite) AND Market (Plenitude IPO window) as live SIGNAL drivers.',
    trajectory_reasoning: `Plenitude + Eni CCUS + Baleine all closed in 2025 — momentum strong. Source: ${BRIEF}.`,
    components: [
      { name: 'PLENITUDE_IPO_PRECURSOR_ARES', description: 'Plenitude post-Ares structure; €12B+ implied EV; IPO precursor.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-01 (Market SIGNAL — Plenitude IPO window); WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Ares €2B 20% closed 2025 at €12B+ EV.', trajectory_reasoning: 'IPO filing expected 2026.' },
      { name: 'ENILIVE_VALORISATION_PIPELINE', description: 'Enilive next satellite valorisation; biofuels + sustainable mobility.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-01 WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Plenitude playbook applied to Enilive next.', trajectory_reasoning: 'Tripling capacity needs €4-6B; satellite structure spreads.' },
      { name: 'ENI_CCUS_GIP_PARTNERSHIP', description: 'Eni CCUS GIP 49.99% strategic partnership; UK + Italy + Egypt CCS.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-01 WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'GIP partnership closed 2025; commercial pipeline emerging.', trajectory_reasoning: 'HyNet + Bacton + Ravenna in development.' },
      { name: 'GROUP_DEBT_RETURNS_DISCIPLINE', description: 'Group net debt + dividend / buyback returns. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-01 (Economics SIGNAL); Descalzi FY 2025`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Debt declining; returns rising.', trajectory_reasoning: 'Satellite proceeds fund deleveraging.' },
    ],
    claims: [
      { component_name: 'PLENITUDE_IPO_PRECURSOR_ARES', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Plenitude IPO completes or formal filing in 2026 at ≥€12B implied EV (matches Ares mark).',
        claim_basis: `Brief HYP ENI-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 12, threshold_unit: 'EUR_billion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Plenitude IPO is the principal observable confirmation.', impact_reasoning: 'IPO valuation marks the public re-rating of carved-out value.' },
      { component_name: 'ENILIVE_VALORISATION_PIPELINE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Enilive minority stake sale to specialist investor before end-2026 at €5B+ EV.',
        claim_basis: `Brief HYP ENI-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 5, threshold_unit: 'EUR_billion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Enilive valorisation extends the satellite playbook.', impact_reasoning: 'Each satellite re-rates similar carved-outs.' },
      { component_name: 'ENI_CCUS_GIP_PARTNERSHIP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Eni CCUS pipeline reaches at least 2 commercial CCS FIDs through GIP partnership by end-2027.',
        claim_basis: `Brief HYP ENI-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'count', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'CCS commercial scale validates Eni CCUS as a real business not a vehicle.', impact_reasoning: 'Each FID adds to satellite EV underwrite.' },
      { component_name: 'GROUP_DEBT_RETURNS_DISCIPLINE', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'Group net debt declines and dividend / buyback returns sustained through 2026-2027.',
        claim_basis: `Brief HYP ENI-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Capital discipline validates the satellite-as-funding-source thesis.', impact_reasoning: 'Each year of deleveraging widens financial flexibility.' },
    ],
  },

  // ENI-02 ----------------------------------------------------------------
  {
    name: 'Enilive triples biofuel capacity to ~5 MTPA by 2030 (Pengerang + Gela + Venice)',
    strategy_context: `Pengerang biorefinery (650 Ktpa, JV Petronas + Euglena) under construction. Goal: triple Enilive capacity from 1.7 MTPA current to ~5 MTPA by 2030 across Pengerang + existing Gela + Venice + Brazil sites.`,
    brief_description: 'Whether Enilive triples capacity to 5 MTPA by 2030.',
    hypothesis_statement: `Enilive triples biofuel manufacturing capacity from 1.7 to ~5 MTPA by 2030 across Pengerang + existing Gela / Venice / Brazil sites, with Pengerang first cargoes by end-2027 and Enilive emerging as one of three global HVO/SAF leaders. Source: ${BRIEF}, HYP ENI-02.`,
    why_it_matters: 'Renewable feedstock supply intelligence + SAF demand outlook + competitive landscape (Neste, World Energy, Phillips 66) are the inputs Enilive needs.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP ENI-02 (H2 · 3-5yr)`,
    decision_threshold: 'Pengerang biorefinery completes construction + commissioning by end-2027; Renewable feedstock supply contracted for ≥80% of Pengerang capacity through 2028; EU RED III implementation sustained + ICAO CORSIA mandate expansion through 2027; No material technology / cost disruption (synthetic kerosene, PtL) disproves HVO/SAF as primary near-term decarbonisation path. (WNTBT, brief HYP ENI-02.)',
    baseline_confidence: 0.64, current_confidence: 0.64,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (renewable feedstock cost) AND Technology (HVO/SAF capacity ramp) as live SIGNAL drivers.',
    trajectory_reasoning: `Pengerang construction underway; existing Gela + Venice operational; trajectory positive. Source: ${BRIEF}.`,
    components: [
      { name: 'PENGERANG_BIOREFINERY_CONSTRUCTION', description: 'Pengerang biorefinery (Malaysia) construction; 650 Ktpa renewable feedstock processing.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-02 WNTBT bullet 1`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Construction underway; commissioning end-2027 target.', trajectory_reasoning: 'JV partners (Petronas + Euglena) experienced.' },
      { name: 'RENEWABLE_FEEDSTOCK_SUPPLY', description: 'Renewable feedstock supply contracts for Pengerang + Gela + Venice. Economics SIGNAL driver.', component_type: 'ecosystem', vector: 'ecosystem', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-02 (Economics SIGNAL); WNTBT bullet 2`, state: 'new', trajectory: 'volatile',
        state_reasoning: 'Feedstock contracting in flight; Eni in-house origination + 3rd-party.', trajectory_reasoning: 'Volatile until 80% contracted.' },
      { name: 'EU_RED_III_ICAO_CORSIA', description: 'EU RED III + ICAO CORSIA mandates. Policy driver.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP ENI-02 (Policy — RED III + ICAO CORSIA)`, state: 'holding', trajectory: 'improving',
        state_reasoning: 'RED III in force; CORSIA expansion path approved.', trajectory_reasoning: 'Mandate strengthening through 2027.' },
      { name: 'HVO_SAF_TECHNOLOGY_LEADERSHIP', description: 'HVO + SAF capacity ramp. Technology SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-02 (Technology SIGNAL)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Eni Honeywell UOP HEFA technology proven at Gela + Venice.', trajectory_reasoning: 'Each new site reinforces operational learning curve.' },
    ],
    claims: [
      { component_name: 'PENGERANG_BIOREFINERY_CONSTRUCTION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Pengerang biorefinery completes construction + commissioning by end-2027.',
        claim_basis: `Brief HYP ENI-02 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Pengerang is the principal capacity addition needed for the 5 MTPA target.', impact_reasoning: '650 Ktpa adds nearly 40% to current Enilive capacity.' },
      { component_name: 'RENEWABLE_FEEDSTOCK_SUPPLY', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Renewable feedstock supply contracted for ≥80% of Pengerang capacity through 2028.',
        claim_basis: `Brief HYP ENI-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 80, threshold_unit: 'pct', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Without feedstock, the plant runs at low utilisation regardless of capacity.', impact_reasoning: 'Each percentage point of contracted feedstock improves output certainty.' },
      { component_name: 'EU_RED_III_ICAO_CORSIA', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'EU RED III implementation sustained + ICAO CORSIA mandate expansion through 2027.',
        claim_basis: `Brief HYP ENI-02 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Mandates create the demand pull for biofuel volumes.', impact_reasoning: 'Each year of mandate continuity sustains demand-side certainty.' },
      { component_name: 'HVO_SAF_TECHNOLOGY_LEADERSHIP', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A material technology / cost disruption (synthetic kerosene, PtL) emerges that displaces HVO/SAF as primary near-term decarbonisation path.',
        claim_basis: `Brief HYP ENI-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Disruption would strand Enilive capacity additions.', impact_reasoning: 'Each technology breakthrough narrows the HVO/SAF window.' },
    ],
  },

  // ENI-03 ----------------------------------------------------------------
  {
    name: 'Coral North FLNG starts up by end-2028; Eni largest LNG operator in East Africa (8+ MTPA)',
    strategy_context: `Coral North FLNG (Mozambique) FID achieved 2025; second floating LNG after Coral South operational since 2022. T.EN delivers FLNG vessel. Coral South benchmark: ~3.4 MTPA, on-time delivery 2022. Cabo Delgado security primary risk; Total Mozambique LNG remains paused due to security situation.`,
    brief_description: 'Whether Coral North FLNG starts up by end-2028 within ±20% of Coral South benchmark.',
    hypothesis_statement: `Coral North FLNG starts up by end-2028 within ±20% of Coral South benchmark, doubling Eni Mozambique LNG output and consolidating Eni as the largest LNG operator in East Africa with 8+ MTPA installed capacity. Source: ${BRIEF}, HYP ENI-03.`,
    why_it_matters: 'Mozambique security + FLNG construction intelligence + LNG offtake market dynamics are what Eni Upstream + Trading need.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP ENI-03 (H2 · 3-5yr)`,
    decision_threshold: 'Coral North FLNG vessel construction proceeds on schedule (delivery 2027-2028); Mozambique Cabo Delgado security situation does not deteriorate enough to delay vessel installation or commissioning; LNG offtake contracts signed for Coral North output (Asia + Europe demand); Mozambique fiscal regime + PSC framework hold through commissioning. (WNTBT, brief HYP ENI-03.)',
    baseline_confidence: 0.60, current_confidence: 0.60,
    state: 'new', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (Mozambique LNG offtake) AND Policy (Mozambique fiscal + Cabo Delgado security) as live SIGNAL drivers.',
    trajectory_reasoning: `Coral South benchmark proven; FID achieved on Coral North. Source: ${BRIEF} Section 04.`,
    components: [
      { name: 'CORAL_NORTH_FLNG_VESSEL_CONSTRUCTION', description: 'Coral North FLNG vessel construction + delivery (T.EN delivers).', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-03 WNTBT bullet 1`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Construction kickoff post-FID 2025.', trajectory_reasoning: 'Coral South benchmark proves T.EN can deliver on time.' },
      { name: 'CABO_DELGADO_SECURITY_SITUATION', description: 'Mozambique Cabo Delgado security situation + Total LNG status. Policy SIGNAL driver.', component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-03 (Policy SIGNAL); WNTBT bullet 2`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Cabo Delgado security situation remains primary risk; Total LNG paused.', trajectory_reasoning: 'Volatile — depends on Mozambican military + French support.' },
      { name: 'CORAL_NORTH_LNG_OFFTAKE', description: 'LNG offtake contracts for Coral North output. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-03 (Market SIGNAL); WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Offtake contracting in flight; Asia + Europe demand strong.', trajectory_reasoning: 'Demand backdrop favourable per Q3 2025 LNG market.' },
      { name: 'MOZAMBIQUE_FISCAL_PSC_FRAMEWORK', description: 'Mozambique fiscal regime + PSC framework stability.', component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP ENI-03 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'PSC framework holds for Coral South + Coral North.', trajectory_reasoning: 'Stable absent political shock.' },
    ],
    claims: [
      { component_name: 'CORAL_NORTH_FLNG_VESSEL_CONSTRUCTION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Coral North FLNG vessel construction proceeds on schedule (delivery 2027-2028).',
        claim_basis: `Brief HYP ENI-03 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'On-schedule delivery is the principal observable confirmation.', impact_reasoning: 'Each quarter of slip pushes start-up beyond 2028.' },
      { component_name: 'CABO_DELGADO_SECURITY_SITUATION', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'Cabo Delgado security situation deteriorates enough to delay vessel installation or commissioning.',
        claim_basis: `Brief HYP ENI-03 WNTBT condition 2 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Security shock would directly delay or halt construction.', impact_reasoning: 'Each security incident reduces vessel installation feasibility.' },
      { component_name: 'CORAL_NORTH_LNG_OFFTAKE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'LNG offtake contracts signed for Coral North output (Asia + Europe demand).',
        claim_basis: `Brief HYP ENI-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Without offtake, the project economics weaken.', impact_reasoning: 'Each offtake contract de-risks Eni cash flow.' },
      { component_name: 'MOZAMBIQUE_FISCAL_PSC_FRAMEWORK', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Mozambique fiscal regime + PSC framework hold through commissioning.',
        claim_basis: `Brief HYP ENI-03 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'PSC stability is the basic precondition for the project economics.', impact_reasoning: 'Each year of stability protects project IRR.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
