// db/population/P5_JLR_hypotheses.mjs
// Source: jaguar_land_rover_intelligence_brief__1_.html (May 2026 brief).
// PG company: existing 'Jaguar Land Rover' row (id=16) — populator re-uses via ON CONFLICT (name).

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'jaguar_land_rover_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'Jaguar Land Rover',
  sector: 'mobility',
  notes: 'Jaguar Land Rover Automotive plc — UK premium OEM owned by Tata Motors. Reimagine strategy (net-zero 2039). Range Rover Electric 2026; Jaguar Type 00 GT 2027. v2 catalogue first-cut hypotheses sourced from May 2026 brief. Re-uses PG id=16.',
};

const initiatives = [
  // JLR-01 ----------------------------------------------------------------
  {
    name: 'Range Rover Electric launches 2026 on schedule + first volume customer deliveries through FY 2027',
    strategy_context: `Range Rover Electric — first volume battery EV in core Range Rover franchise. Anchor of Reimagine electrification narrative. Customer waitlist open. Critical to FY 2027 revenue recovery vs FY 2026 cyber-/tariff-disrupted base.`,
    brief_description: 'Whether Range Rover Electric launches 2026 on schedule.',
    hypothesis_statement: `Range Rover Electric launches in 2026 on schedule and reaches first volume customer deliveries through FY 2027, anchoring the Reimagine electrification narrative and contributing to FY 2027 revenue recovery. Source: ${BRIEF}, HYP JLR-01.`,
    why_it_matters: 'Range Rover Electric launch milestone tracking is the highest-priority engagement input through 2026.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP JLR-01 (H1 · 1-2yr)`,
    decision_threshold: 'Range Rover Electric SOP achieved in 2026 as planned; First volume customer deliveries through FY 2027; Reservation conversion ≥75% (high reservation-to-order quality); No material technical recall or quality issue post-launch. (WNTBT, brief HYP JLR-01.)',
    baseline_confidence: 0.65, current_confidence: 0.65,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (Range Rover Electric SOP) AND Market (waitlist + reservation conversion) as live SIGNAL drivers.',
    trajectory_reasoning: `Launch on track per JLR public commitments. Source: ${BRIEF}.`,
    components: [
      { name: 'RR_ELECTRIC_SOP_2026', description: 'Range Rover Electric Start of Production 2026.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-01 WNTBT bullet 1; SIG-01`, state: 'new', trajectory: 'improving',
        state_reasoning: '2026 SOP planned per JLR public commitments.', trajectory_reasoning: 'On track.' },
      { name: 'RR_ELECTRIC_RESERVATION_CONVERSION', description: 'Range Rover Electric reservation-to-order conversion (target ≥75%).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-01 WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Customer waitlist open; conversion not yet visible.', trajectory_reasoning: 'Reservation pace strong but conversion outcome TBC.' },
      { name: 'RR_ELECTRIC_FY27_DELIVERIES', description: 'Range Rover Electric first volume customer deliveries through FY 2027.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-01 WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Pre-delivery; outcome dependent on production ramp.', trajectory_reasoning: 'On track absent further disruption.' },
      { name: 'RR_ELECTRIC_QUALITY_RISK', description: 'Range Rover Electric post-launch technical / quality risk.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-01 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No known issues pre-launch.', trajectory_reasoning: 'Stable absent post-launch issues.' },
    ],
    claims: [
      { component_name: 'RR_ELECTRIC_SOP_2026', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Range Rover Electric SOP achieved in 2026 as planned.',
        claim_basis: `Brief HYP JLR-01 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'SOP is the principal technical milestone for the Reimagine narrative.', impact_reasoning: 'Each quarter of slip pushes recovery into 2027.' },
      { component_name: 'RR_ELECTRIC_FY27_DELIVERIES', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'First volume customer deliveries through FY 2027.',
        claim_basis: `Brief HYP JLR-01 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Customer deliveries are the principal commercial validation.', impact_reasoning: 'Each quarter of delivery slip compounds revenue recovery delay.' },
      { component_name: 'RR_ELECTRIC_RESERVATION_CONVERSION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Reservation conversion ≥75% (high reservation-to-order quality).',
        claim_basis: `Brief HYP JLR-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 75, threshold_unit: 'pct_reservation_conversion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Conversion confirms genuine demand vs speculative reservations.', impact_reasoning: 'Each percentage point above 75% compounds revenue.' },
      { component_name: 'RR_ELECTRIC_QUALITY_RISK', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'No material technical recall or quality issue post-launch.',
        claim_basis: `Brief HYP JLR-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A major recall would compromise the Reimagine narrative + customer confidence.', impact_reasoning: 'Each quality issue compounds reputational + financial damage.' },
    ],
  },

  // JLR-02 ----------------------------------------------------------------
  {
    name: 'Jaguar Type 00 GT first 1,000 customer deliveries 2027 with brand-reset commercial traction at $130k+',
    strategy_context: `Jaguar Type 00 GT — tri-motor 1,000hp grand tourer, 800V architecture, 400mi target, $130k+. UK-built. Reveal 2026, orders H2 2026, customer deliveries ~12mo later. Polarising rebrand (designer Gerry McGovern departed). Type 00 GT must justify the brand reset.`,
    brief_description: 'Whether Type 00 GT delivers 1,000 customers 2027 + brand reset gains traction.',
    hypothesis_statement: `Jaguar Type 00 GT customer deliveries reach first 1,000 in 2027 with no further delays, and brand-reset gains commercial traction at $130k+ price point — validating the Reimagine strategy. Source: ${BRIEF}, HYP JLR-02.`,
    why_it_matters: 'Type 00 GT reveal + order book + early reception is the principal Jaguar brand-reset proof-point input.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP JLR-02 (H2 · 3-5yr)`,
    decision_threshold: 'Type 00 GT reveal in 2026 + order book opens H2 2026 as guided; First 1,000 customer deliveries achieved in 2027; No further price escalation beyond $130k+ start point; No major competing premium EV GT (Bentley BEV, Porsche EV) launches that displace Type 00 GT order pace. (WNTBT, brief HYP JLR-02.)',
    baseline_confidence: 0.50, current_confidence: 0.50,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Market (premium luxury EV GT acceptance) AND Brand (rebrand reception) as live SIGNAL drivers; outcome high-risk given polarising rebrand.',
    trajectory_reasoning: `Reveal 2026 imminent; outcome depends on order-book reception. Source: ${BRIEF}.`,
    components: [
      { name: 'TYPE_00_GT_REVEAL_AND_ORDERBOOK', description: 'Type 00 GT reveal 2026 + order book opening H2 2026.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-02 WNTBT bullet 1`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Reveal + order book open imminent.', trajectory_reasoning: 'On track per JLR commitments.' },
      { name: 'TYPE_00_GT_DELIVERIES_2027', description: 'Type 00 GT first 1,000 customer deliveries in 2027.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-02 WNTBT bullet 2`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'Pre-delivery; outcome dependent on production + order pace.', trajectory_reasoning: 'High execution risk.' },
      { name: 'JAGUAR_REBRAND_RECEPTION', description: 'Jaguar rebrand reception + Type 00 GT order pace at $130k+ price point.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-02 (Brand SIGNAL); WNTBT bullet 3`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: '2024 rebrand polarising; designer departed.', trajectory_reasoning: 'Outcome contested.' },
      { name: 'PREMIUM_EV_GT_COMPETITION', description: 'Premium EV GT competition — Bentley BEV, Porsche Taycan, Lucid Air.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-02 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Multiple credible alternatives.', trajectory_reasoning: 'Bentley + Porsche reset launches could compress Type 00 GT pace.' },
    ],
    claims: [
      { component_name: 'TYPE_00_GT_REVEAL_AND_ORDERBOOK', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Type 00 GT reveal in 2026 + order book opens H2 2026 as guided.',
        claim_basis: `Brief HYP JLR-02 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Reveal + order book is the principal near-term execution proof.', impact_reasoning: 'Each quarter of slip compounds brand-reset narrative risk.' },
      { component_name: 'TYPE_00_GT_DELIVERIES_2027', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'First 1,000 customer deliveries achieved in 2027.',
        claim_basis: `Brief HYP JLR-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1000, threshold_unit: 'customer_deliveries', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'First 1,000 deliveries is the principal commercial validation.', impact_reasoning: 'Each quarter of slip compounds brand-reset risk.' },
      { component_name: 'JAGUAR_REBRAND_RECEPTION', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'No further price escalation beyond $130k+ start point.',
        claim_basis: `Brief HYP JLR-02 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Pricing discipline confirms commercial-traction thesis.', impact_reasoning: 'Each price escalation compresses addressable market.' },
      { component_name: 'PREMIUM_EV_GT_COMPETITION', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'No major competing premium EV GT (Bentley BEV, Porsche EV) launches that displace Type 00 GT order pace.',
        claim_basis: `Brief HYP JLR-02 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Premium EV GT competitive intensity is the principal external risk.', impact_reasoning: 'Each major launch compresses Type 00 GT addressable demand.' },
    ],
  },

  // JLR-03 ----------------------------------------------------------------
  {
    name: 'JLR FY 2027 EBIT margin recovers from FY 2026 trough (0-2% guide) to >5%',
    strategy_context: `FY 2026 EBIT guidance 0-2% reflects Q3 cyber incident, US tariffs, legacy Jaguar wind-down. FY 2027 recovery dependent on cyber + insurance + Range Rover Electric mix. £18B (£18B) Reimagine investment plan to FY28.`,
    brief_description: 'Whether FY 2027 EBIT margin recovers to >5%.',
    hypothesis_statement: `JLR FY 2027 EBIT margin recovers from FY 2026 trough (0-2% guide) to >5% as cyber + tariff + Jaguar wind-down headwinds normalise and Range Rover Electric contributes premium mix. Source: ${BRIEF}, HYP JLR-03.`,
    why_it_matters: 'Quarterly EBIT + cyber-recovery + tariff intelligence is the FY 2026-2027 ambient scout for JLR.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP JLR-03 (H1 · 1-2yr)`,
    decision_threshold: 'FY 2026 lands within EBIT 0-2% guidance (no further negative surprises); FY 2027 EBIT margin recovers to >5%; No US tariff escalation that compresses recovery; Cyber-recovery + insurance settlement complete by H1 FY 2027. (WNTBT, brief HYP JLR-03.)',
    baseline_confidence: 0.55, current_confidence: 0.55,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Economics (EBIT trajectory) AND Policy (US tariff) as live SIGNAL drivers; recovery uncertain.',
    trajectory_reasoning: `FY 2026 trough; FY 2027 dependent on multiple normalisation factors. Source: ${BRIEF}.`,
    components: [
      { name: 'JLR_FY26_EBIT_LANDING', description: 'JLR FY 2026 EBIT margin lands within 0-2% guidance (no further surprises).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-03 WNTBT bullet 1`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'YTD EBIT -2.9%; recovery to 0-2% requires Q4.', trajectory_reasoning: 'Outcome dependent on Q4 + insurance.' },
      { name: 'JLR_FY27_EBIT_RECOVERY', description: 'JLR FY 2027 EBIT margin recovery to >5%.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-03 WNTBT bullet 2`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'Pre-FY27; recovery dependent on multiple factors.', trajectory_reasoning: 'Outcome contested.' },
      { name: 'US_TARIFF_ESCALATION_RISK_JLR', description: 'US tariff escalation risk that compresses JLR recovery.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP JLR-03 WNTBT bullet 3`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'US tariff regime uncertain.', trajectory_reasoning: 'High geopolitical volatility.' },
      { name: 'JLR_CYBER_RECOVERY_INSURANCE', description: 'JLR cyber-recovery + insurance settlement complete by H1 FY 2027.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP JLR-03 WNTBT bullet 4`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Recovery in progress.', trajectory_reasoning: 'Insurance settlement timing TBC.' },
    ],
    claims: [
      { component_name: 'JLR_FY26_EBIT_LANDING', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY 2026 lands within EBIT 0-2% guidance (no further negative surprises).',
        claim_basis: `Brief HYP JLR-03 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'FY 2026 outcome is the principal base for FY 2027 trajectory.', impact_reasoning: 'A miss compresses FY 2027 recovery profile.' },
      { component_name: 'JLR_FY27_EBIT_RECOVERY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY 2027 EBIT margin recovers to >5%.',
        claim_basis: `Brief HYP JLR-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 5, threshold_unit: 'pct_EBIT_margin', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'FY 2027 >5% is the principal financial validation of recovery.', impact_reasoning: 'Each percentage point above 5% restores equity narrative.' },
      { component_name: 'US_TARIFF_ESCALATION_RISK_JLR', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No US tariff escalation that compresses recovery.',
        claim_basis: `Brief HYP JLR-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A tariff escalation could fully derail FY 2027 recovery.', impact_reasoning: 'Each tariff round compounds.' },
      { component_name: 'JLR_CYBER_RECOVERY_INSURANCE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Cyber-recovery + insurance settlement complete by H1 FY 2027.',
        claim_basis: `Brief HYP JLR-03 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cyber overhang resolution is the principal precondition for clean FY 2027.', impact_reasoning: 'Each quarter of overhang compounds.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
