// db/population/P5_MBLY_hypotheses.mjs
// Source: mobileye_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'Mobileye'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'mobileye_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'Mobileye',
  sector: 'mobility',
  notes: 'Mobileye Global — Israeli vision-first ADAS / AV stack. NASDAQ:MBLY (Intel majority shareholder). EyeQ + SuperVision + Surround ADAS + Chauffeur + Mobileye Drive. v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // MBLY-01 ----------------------------------------------------------------
  {
    name: 'VW Group E3 1.2 premium architecture reaches SOP 2027 with Mobileye SuperVision + Surround ADAS as primary stack',
    strategy_context: `Cariad-managed E3 1.2 premium architecture (Audi, Bentley, Lamborghini, Porsche). Mobileye SuperVision in C-sample on Porsche + Audi. Surround ADAS B-sample with Valeo, full software Dec 2026. 2nd-gen Mobileye stack ready April 2026 with SOP 2027.`,
    brief_description: 'Whether VW E3 1.2 reaches SOP 2027 with Mobileye stack.',
    hypothesis_statement: `VW Group E3 1.2 premium architecture (Audi, Bentley, Lamborghini, Porsche) reaches SOP 2027 with Mobileye SuperVision + Surround ADAS as the primary stack, anchoring the Cariad relationship and delivering EUR-mid-size revenue stream by FY2028. Source: ${BRIEF}, HYP MBLY-01.`,
    why_it_matters: 'Cariad / VW Group integration tracking + premium-brand model-launch intelligence is the highest-priority engagement input.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP MBLY-01 (H2 · 3-5yr)`,
    decision_threshold: 'Surround ADAS full software implementation by Dec 2026 as guided; SuperVision C-sample passes Cariad acceptance and progresses to D-sample on Audi / Porsche; First E3 1.2 production launch with Mobileye SuperVision in 2027 as planned; No Cariad walk-back to in-house stack on premium-brand vehicles before SOP. (WNTBT, brief HYP MBLY-01.)',
    baseline_confidence: 0.60, current_confidence: 0.60,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (SuperVision C-sample + Surround B-sample) AND Market (VW model launches) as live SIGNAL drivers.',
    trajectory_reasoning: `B/C-sample status visible; Cariad relationship active. Source: ${BRIEF}.`,
    components: [
      { name: 'VW_SURROUND_ADAS_DEC_2026', description: 'VW Surround ADAS full software implementation Dec 2026 (B-sample with Valeo).', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-01 WNTBT bullet 1; Section 04 VW card`, state: 'new', trajectory: 'improving',
        state_reasoning: 'B-samples in 5V5R setup; full sw expected Dec 2026.', trajectory_reasoning: 'On schedule.' },
      { name: 'VW_SUPERVISION_C_TO_D_SAMPLE', description: 'VW SuperVision C-sample → D-sample on Porsche / Audi.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-01 WNTBT bullet 2; Section 04 VW card`, state: 'new', trajectory: 'improving',
        state_reasoning: 'C-sample hardware tests in dozens of Porsche + Audi vehicles.', trajectory_reasoning: 'Progression to D-sample dependent on Cariad acceptance.' },
      { name: 'VW_E3_1_2_FIRST_PRODUCTION_LAUNCH', description: 'First E3 1.2 production launch with Mobileye SuperVision in 2027.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-01 WNTBT bullet 3`, state: 'ambiguous', trajectory: 'improving',
        state_reasoning: 'SOP 2027 planned per disclosure.', trajectory_reasoning: 'Outcome dependent on B/C/D-sample progression.' },
      { name: 'CARIAD_INHOUSE_WALKBACK_RISK', description: 'Cariad walk-back to in-house stack on premium-brand vehicles before SOP.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-01 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Mobileye relationship intact through May 2026 disclosures.', trajectory_reasoning: 'Stable absent change in Cariad strategy.' },
    ],
    claims: [
      { component_name: 'VW_SURROUND_ADAS_DEC_2026', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Surround ADAS full software implementation by Dec 2026 as guided.',
        claim_basis: `Brief HYP MBLY-01 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Surround ADAS Dec 2026 is the principal near-term technical milestone.', impact_reasoning: 'Each milestone slip pushes SOP 2027 out.' },
      { component_name: 'VW_SUPERVISION_C_TO_D_SAMPLE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'SuperVision C-sample passes Cariad acceptance and progresses to D-sample on Audi / Porsche.',
        claim_basis: `Brief HYP MBLY-01 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'C-to-D sample progression is the principal technical validation.', impact_reasoning: 'Each rejection compounds SOP risk.' },
      { component_name: 'VW_E3_1_2_FIRST_PRODUCTION_LAUNCH', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'First E3 1.2 production launch with Mobileye SuperVision in 2027 as planned.',
        claim_basis: `Brief HYP MBLY-01 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Production launch is the principal commercial validation.', impact_reasoning: 'Each year of delay erodes equity narrative.' },
      { component_name: 'CARIAD_INHOUSE_WALKBACK_RISK', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No Cariad walk-back to in-house stack on premium-brand vehicles before SOP.',
        claim_basis: `Brief HYP MBLY-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A Cariad walk-back would falsify the entire VW Group thesis.', impact_reasoning: 'A single walk-back compounds across brands.' },
    ],
  },

  // MBLY-02 ----------------------------------------------------------------
  {
    name: 'Mobileye delivers FY2026 revenue at upper-end of $1.935-2.015B range and grows ≥20% to >$2.4B FY2027',
    strategy_context: `Q1 2026 $558M (+27% YoY); FY 2026 outlook lifted to $1.935-2.015B (+2% midpoint vs prior). EyeQ SoC volumes +28%. 2nd-gen stack ready April 2026 with SOP 2027. Mahindra design wins + Surround 2nd top-10 OEM diversification offsetting concentration risk.`,
    brief_description: 'Whether Mobileye sustains FY2026-2027 growth trajectory.',
    hypothesis_statement: `Mobileye delivers FY2026 revenue at the upper end of $1.935-2.015B range and grows ≥20% in FY2027 to >$2.4B, sustained by EyeQ6 ramp + VW Group Surround ADAS deliveries + Mahindra + Surround 2nd top-10 OEM. Source: ${BRIEF}, HYP MBLY-02.`,
    why_it_matters: 'Quarterly EyeQ + Surround / SuperVision tracking is the FY2026-2027 ambient scout.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP MBLY-02 (H1 · 1-2yr)`,
    decision_threshold: 'FY2026 revenue lands ≥$1.97B (upper-half of guided range); FY2027 revenue grows ≥20% to >$2.4B; EyeQ SoC volumes continue +25%+ YoY through 2027; No Surround ADAS delays at VW + 2nd top-10 OEM. (WNTBT, brief HYP MBLY-02.)',
    baseline_confidence: 0.70, current_confidence: 0.70,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (EyeQ + ADAS demand) AND Economics (ASP + content / vehicle) as live SIGNAL drivers.',
    trajectory_reasoning: `Q1 2026 +27% beat + raised FY guidance + $250M buyback. Source: ${BRIEF}.`,
    components: [
      { name: 'MBLY_FY26_FY27_REVENUE', description: 'Mobileye FY2026 + FY2027 revenue trajectory.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-02 WNTBT bullets 1+2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'FY2026 outlook raised; +27% Q1 beat.', trajectory_reasoning: 'Path to $2.4B FY2027 dependent on EyeQ ramp.' },
      { name: 'EYEQ_SOC_VOLUME_GROWTH', description: 'EyeQ SoC volume growth (+28% Q1 2026; sustained 25%+ YoY through 2027).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-02 WNTBT bullet 3`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: '+28% Q1 2026 volume.', trajectory_reasoning: 'EyeQ6 ramp + 2nd-gen stack.' },
      { name: 'SURROUND_ADAS_OEM_DELIVERIES', description: 'Surround ADAS deliveries at VW + 2nd top-10 OEM (no delays).', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-02 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'On schedule per Q1 2026 disclosures.', trajectory_reasoning: 'Stable absent OEM-side delays.' },
      { name: 'MBLY_OEM_DIVERSIFICATION', description: 'Mobileye OEM diversification (Mahindra + Surround 2nd top-10).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-02 (Section 04 Mahindra + Surround cards)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'New design wins reducing VW concentration risk.', trajectory_reasoning: 'Diversification continuing.' },
    ],
    claims: [
      { component_name: 'MBLY_FY26_FY27_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2026 revenue lands ≥$1.97B (upper-half of guided range).',
        claim_basis: `Brief HYP MBLY-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1.97, threshold_unit: 'USD_billion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'FY2026 attainment is the principal financial validation.', impact_reasoning: 'Each $50M short of upper-half compresses guidance credibility.' },
      { component_name: 'MBLY_FY26_FY27_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2027 revenue grows ≥20% to >$2.4B.',
        claim_basis: `Brief HYP MBLY-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2.4, threshold_unit: 'USD_billion', threshold_direction: 'crossing_validates',
        criticality_reasoning: '>$2.4B FY2027 is the principal multi-year validation.', impact_reasoning: 'Each $100M short erodes equity narrative.' },
      { component_name: 'EYEQ_SOC_VOLUME_GROWTH', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'EyeQ SoC volumes continue +25%+ YoY through 2027.',
        claim_basis: `Brief HYP MBLY-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 25, threshold_unit: 'pct_YoY_volume_growth', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Volume growth is the principal demand signal.', impact_reasoning: 'Each percentage point compounds revenue base.' },
      { component_name: 'SURROUND_ADAS_OEM_DELIVERIES', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'No Surround ADAS delays at VW + 2nd top-10 OEM.',
        claim_basis: `Brief HYP MBLY-02 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'OEM delays are the principal external execution risk.', impact_reasoning: 'Each delay compounds against $2.4B target.' },
    ],
  },

  // MBLY-03 ----------------------------------------------------------------
  {
    name: 'Mobileye Chauffeur L3 + Mobileye Drive achieves first commercial deployment by 2028 (toward 100k AVs by 2033)',
    strategy_context: `Significant milestones in robotaxi technology stack and EyeQ6H-based SuperVision L2++ and Chauffeur L3 programs with VW Group. Mobileye Drive partnership targets 100k AVs by 2033. Tesla FSD + Waymo + Cruise competitive frontier.`,
    brief_description: 'Whether Chauffeur L3 + Mobileye Drive achieves first commercial deployment by 2028.',
    hypothesis_statement: `Mobileye Chauffeur L3 + Mobileye Drive achieves first commercial deployment by 2028 with VW Group, validating the AV stack toward the 100k-AVs-by-2033 target. Source: ${BRIEF}, HYP MBLY-03.`,
    why_it_matters: 'L3 / robotaxi competitive landscape + Mobileye Drive deployment milestones — long-term-thesis scouting input.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP MBLY-03 (H2 · 3-5yr)`,
    decision_threshold: 'Chauffeur L3 stack passes safety case + regulatory clearance in at least one major market by 2027; First commercial Mobileye Drive deployment with VW Group by 2028; VW retains commitment to 100k AVs by 2033 (no walk-back); No major Tesla FSD / Waymo / Cruise expansion that obsoletes Mobileye partnership model. (WNTBT, brief HYP MBLY-03.)',
    baseline_confidence: 0.50, current_confidence: 0.50,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Technology (L3 stack maturity) AND Market (robotaxi commercial timing) as live SIGNAL drivers; outcome high-risk.',
    trajectory_reasoning: `Significant milestones reported but commercialisation timing uncertain. Source: ${BRIEF}.`,
    components: [
      { name: 'CHAUFFEUR_L3_SAFETY_CASE_REG', description: 'Chauffeur L3 safety case + regulatory clearance by 2027.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP MBLY-03 WNTBT bullet 1`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'Stack development underway; regulatory clearance pending.', trajectory_reasoning: 'Region-by-region clearance timeline uncertain.' },
      { name: 'MOBILEYE_DRIVE_FIRST_COMMERCIAL', description: 'First commercial Mobileye Drive deployment with VW Group by 2028.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-03 WNTBT bullet 2`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'VW partnership active; commercial deployment timing TBC.', trajectory_reasoning: 'Outcome depends on safety case + regulatory clearance.' },
      { name: 'VW_100K_AV_BY_2033_COMMITMENT', description: 'VW commitment to 100k AVs by 2033 retained.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-03 WNTBT bullet 3`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Commitment intact through May 2026 disclosures.', trajectory_reasoning: 'Stable absent VW strategy reset.' },
      { name: 'TESLA_FSD_WAYMO_COMPETITION', description: 'Tesla FSD + Waymo + Cruise competitive expansion that obsoletes Mobileye partnership model.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP MBLY-03 WNTBT bullet 4`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'Tesla FSD vision-only validates approach but raises bar.', trajectory_reasoning: 'Competitive intensity rising.' },
    ],
    claims: [
      { component_name: 'CHAUFFEUR_L3_SAFETY_CASE_REG', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Chauffeur L3 stack passes safety case + regulatory clearance in at least one major market by 2027.',
        claim_basis: `Brief HYP MBLY-03 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Regulatory clearance is the principal precondition for commercial deployment.', impact_reasoning: 'Each year of delay pushes 2028 commercial deployment out.' },
      { component_name: 'MOBILEYE_DRIVE_FIRST_COMMERCIAL', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'First commercial Mobileye Drive deployment with VW Group by 2028.',
        claim_basis: `Brief HYP MBLY-03 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'First commercial deployment is the principal AV-stack validation.', impact_reasoning: 'A successful first deployment unlocks scale.' },
      { component_name: 'VW_100K_AV_BY_2033_COMMITMENT', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'VW retains commitment to 100k AVs by 2033 (no walk-back).',
        claim_basis: `Brief HYP MBLY-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'VW commitment underwrites the long-term thesis.', impact_reasoning: 'A walk-back would strand Mobileye Drive investment.' },
      { component_name: 'TESLA_FSD_WAYMO_COMPETITION', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No major Tesla FSD / Waymo / Cruise expansion obsoletes Mobileye partnership model.',
        claim_basis: `Brief HYP MBLY-03 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Vertically integrated AV competition could marginalise Mobileye partnership-based model.', impact_reasoning: 'Each major expansion compounds competitive pressure.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
