// db/population/P5_NXP_hypotheses.mjs
// Source: nxp_intelligence_brief__1_.html (May 2026 brief).
// PG company: existing 'NXP Semiconductors' row (id=53) — populator re-uses via ON CONFLICT (name).

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'nxp_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'NXP Semiconductors',
  sector: 'semiconductors',
  notes: 'NXP Semiconductors N.V. — Eindhoven-based automotive + industrial IDM. NASDAQ:NXPI. v2 catalogue first-cut hypotheses sourced from May 2026 brief. Re-uses existing PG row id=53.',
};

const initiatives = [
  // NXP-01 ----------------------------------------------------------------
  {
    name: 'CoreRide secures first OEM production deployment by 2028 (SDV-platform peer to Snapdragon Ride / SuperVision)',
    strategy_context: `CoreRide computing platform — 48V scalable zonal SDV architectures. 80% optimisation + validation by end-2026; 100% Q1 2027; first OEM production application targeted 2028. 25-30% engineering-efficiency claim cuts new-vehicle development to ~2yr. TTTech strategic stake closes deterministic-Ethernet IP gap.`,
    brief_description: 'Whether CoreRide secures first OEM production deployment by 2028.',
    hypothesis_statement: `CoreRide secures at least one major OEM production deployment by 2028, establishing NXP as a credible SDV-platform peer to Qualcomm Snapdragon Ride and Mobileye SuperVision. Source: ${BRIEF}, HYP NXP-01.`,
    why_it_matters: 'SDV-platform competitive map (NXP / Qualcomm / Mobileye / Renesas) is the highest-priority engagement input for automotive system architects.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP NXP-01 (H2 · 3-5yr)`,
    decision_threshold: 'CoreRide reaches 80% optimisation + validation by end-2026 as guided; CoreRide 100% complete Q1 2027; At least one named major OEM publicly commits to CoreRide by end-2027; First production vehicle launches with CoreRide by 2028. (WNTBT, brief HYP NXP-01.)',
    baseline_confidence: 0.64, current_confidence: 0.64,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (CoreRide validation milestones) AND Market (first OEM commitment) as live SIGNAL drivers.',
    trajectory_reasoning: `Validation profile improving; TTTech stake closes IP gap. Source: ${BRIEF}.`,
    components: [
      { name: 'CORERIDE_PLATFORM_VALIDATION', description: 'CoreRide platform 80% / 100% validation milestones. Technology SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-01 (Technology SIGNAL); WNTBT bullets 1+2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Hardware samples + software layer delivered to selected customers end-March 2026.', trajectory_reasoning: 'Validation profile on track.' },
      { name: 'CORERIDE_FIRST_OEM_COMMIT', description: 'First named major OEM public commitment to CoreRide by end-2027. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-01 (Market SIGNAL); WNTBT bullet 3`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'Pre-public-commitment phase; selected customers engaged.', trajectory_reasoning: 'Outcome not yet decided.' },
      { name: 'TTTECH_DETERMINISTIC_ETHERNET_IP', description: 'NXP-TTTech strategic stake — deterministic-Ethernet IP + TSN integration into CoreRide.', component_type: 'partner', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-01 (Section 04 TTTech card)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Stake closed; IP integration underway.', trajectory_reasoning: 'Closes a core SDV architecture gap.' },
      { name: 'SDV_PLATFORM_COMPETITIVE_FIELD', description: 'SDV-platform competitive field — Qualcomm Snapdragon Ride + Mobileye SuperVision + Renesas R-Car.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-01 (Strategy box); SIG-02`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Qualcomm Ride aggressively winning compute / cockpit deals.', trajectory_reasoning: 'Competitive intensity rising.' },
    ],
    claims: [
      { component_name: 'CORERIDE_PLATFORM_VALIDATION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'CoreRide reaches 80% optimisation + validation by end-2026 as guided; 100% complete Q1 2027.',
        claim_basis: `Brief HYP NXP-01 WNTBT conditions 1+2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Validation milestones are the principal technical precondition.', impact_reasoning: 'Each milestone slip pushes 2028 production out a year.' },
      { component_name: 'CORERIDE_FIRST_OEM_COMMIT', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'At least one named major OEM publicly commits to CoreRide by end-2027.',
        claim_basis: `Brief HYP NXP-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1, threshold_unit: 'named_OEM_commits', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'A named OEM commitment is the principal commercial validation.', impact_reasoning: 'Each named OEM compounds CoreRide credibility.' },
      { component_name: 'CORERIDE_PLATFORM_VALIDATION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'First production vehicle launches with CoreRide by 2028.',
        claim_basis: `Brief HYP NXP-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Production launch is the ultimate validation.', impact_reasoning: 'Initial launch unlocks subsequent volume.' },
      { component_name: 'SDV_PLATFORM_COMPETITIVE_FIELD', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'Qualcomm or Mobileye does NOT capture every contested OEM zonal-SDV pipeline before CoreRide first production.',
        claim_basis: `Brief HYP NXP-01 (Section 02 strategy + SIG-02). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Total competitive shutout would falsify the platform thesis.', impact_reasoning: 'Each OEM zonal-pipeline lost to a competitor compounds CoreRide marginalisation.' },
    ],
  },

  // NXP-02 ----------------------------------------------------------------
  {
    name: 'NXP automotive grows to ~$9.5B by FY2027 at 8-12% CAGR (Analyst Day reaffirmed)',
    strategy_context: `Q1 2026 auto $1.78B (+6% YoY, +10% adj for MEMS sale). Auto = 58% of NXP revenue. Long-term guide: 8-12% CAGR 2024→2027 to ~$9.5B. Reaffirming Analyst Day double-digit growth in 2026 + 2027. Accelerated growth drivers (S32 SDV 20-30%, radar / electrification 15-20%) contributing ~90% of YoY growth.`,
    brief_description: 'Whether auto reaches ~$9.5B by FY2027.',
    hypothesis_statement: `NXP automotive segment grows to ~$9.5B by FY2027 at 8-12% CAGR, sustaining the Analyst Day commitment to double-digit growth in both 2026 and 2027. Source: ${BRIEF}, HYP NXP-02.`,
    why_it_matters: 'Quarterly auto segment tracking + content-per-vehicle benchmarking is the FY2026-2027 ambient scout.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP NXP-02 (H1 · 1-2yr)`,
    decision_threshold: 'FY2026 auto revenue grows ≥10% YoY (double-digit reaffirmation); FY2027 auto revenue reaches ~$9.5B; S32 SDV revenue at 20-30% CAGR; radar / electrification 15-20% CAGR; No major Chinese OEM EV downturn or US-China auto-tariff shock disrupts auto demand through 2027. (WNTBT, brief HYP NXP-02.)',
    baseline_confidence: 0.70, current_confidence: 0.70,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (EV / SDV / radar volume) AND Economics (ASP + content-per-vehicle) as live SIGNAL drivers.',
    trajectory_reasoning: `Q1 2026 +12% YoY beat with stock +26% reaction. Source: ${BRIEF}.`,
    components: [
      { name: 'NXP_AUTO_FY27_REVENUE', description: 'NXP automotive segment revenue trajectory toward ~$9.5B FY2027.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-02 WNTBT bullets 1+2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'On-track per Q1 2026 results.', trajectory_reasoning: 'Double-digit reaffirmation.' },
      { name: 'S32_SDV_RADAR_ELECT_CAGR', description: 'S32 SDV (20-30%) + radar / electrification (15-20%) CAGR growth drivers.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-02 WNTBT bullet 3; Section 02 strategy`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: '~90% of YoY growth from accelerated drivers.', trajectory_reasoning: 'Compounding 2026-2027.' },
      { name: 'EV_SDV_RADAR_PRODUCTION_VOLUME', description: 'Global EV / SDV / radar production volumes + content-per-vehicle ramp.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP NXP-02 (Market SIGNAL)`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Volume ramp on track.', trajectory_reasoning: 'Stable trajectory subject to macro.' },
      { name: 'CHINA_OEM_EV_AND_TARIFFS', description: 'Chinese OEM EV demand + US-China auto-tariff shock risk.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP NXP-02 WNTBT bullet 4`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Tariff regime uncertain; Chinese EV margin pressure.', trajectory_reasoning: 'High geopolitical volatility.' },
    ],
    claims: [
      { component_name: 'NXP_AUTO_FY27_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2026 auto revenue grows ≥10% YoY (double-digit reaffirmation).',
        claim_basis: `Brief HYP NXP-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'pct_YoY_growth', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'FY2026 double-digit is the principal in-year validation.', impact_reasoning: 'Miss would force Analyst Day downgrade.' },
      { component_name: 'NXP_AUTO_FY27_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2027 auto revenue reaches ~$9.5B.',
        claim_basis: `Brief HYP NXP-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 9.5, threshold_unit: 'USD_billion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'FY2027 $9.5B is the principal multi-year validation.', impact_reasoning: 'Each $200M short of target erodes equity narrative.' },
      { component_name: 'S32_SDV_RADAR_ELECT_CAGR', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'S32 SDV revenue grows at 20-30% CAGR; radar / electrification 15-20% CAGR.',
        claim_basis: `Brief HYP NXP-02 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Accelerated drivers are the key growth engines.', impact_reasoning: 'Each percentage point below target compounds against $9.5B.' },
      { component_name: 'CHINA_OEM_EV_AND_TARIFFS', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'A major Chinese OEM EV downturn or US-China auto-tariff shock disrupts auto demand through 2027.',
        claim_basis: `Brief HYP NXP-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Macro / geopolitical shock could derail the trajectory.', impact_reasoning: 'Each major tariff or demand shock pushes auto target out.' },
    ],
  },

  // NXP-03 ----------------------------------------------------------------
  {
    name: 'NXP holds ≥40% global imaging-radar share through 2027',
    strategy_context: `New radar awards for imaging radar solutions Q1 2026. ≥40% target share through 2027. 4D imaging-radar replaces low-resolution radar across L2+ ADAS. Radar / electrification segment growing 15-20% CAGR.`,
    brief_description: 'Whether NXP holds ≥40% imaging-radar share through 2027.',
    hypothesis_statement: `NXP holds ≥40% global imaging-radar share through 2027, sustaining radar / electrification 15-20% CAGR despite Infineon + Renesas competition. Source: ${BRIEF}, HYP NXP-03.`,
    why_it_matters: 'Imaging-radar OEM win-tracking + competitive landscape is the highest-value scouting input for NXP automotive radar BU.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP NXP-03 (H1 · 1-2yr)`,
    decision_threshold: 'NXP wins ≥3 named OEM imaging-radar awards per year through 2027; Imaging-radar market share holds ≥40% globally through 2027; Radar + electrification segment growth holds at 15-20% CAGR; No major imaging-radar architecture shift (silicon-photonics) disrupts NXP roadmap before 2027. (WNTBT, brief HYP NXP-03.)',
    baseline_confidence: 0.65, current_confidence: 0.65,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (4D imaging-radar SoC) AND Market (L2+/L3 ADAS volumes) as live SIGNAL drivers.',
    trajectory_reasoning: `Q1 2026 new radar awards confirm momentum. Source: ${BRIEF}.`,
    components: [
      { name: 'NXP_IMAGING_RADAR_AWARDS', description: 'NXP imaging-radar OEM award flow (≥3 per year target).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-03 WNTBT bullet 1; Section 04 imaging radar card`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q1 2026 new awards.', trajectory_reasoning: 'Pipeline building.' },
      { name: 'NXP_IMAGING_RADAR_SHARE', description: 'NXP imaging-radar global market share (target ≥40% through 2027).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP NXP-03 WNTBT bullet 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Leading position consolidating.', trajectory_reasoning: 'Trajectory holding.' },
      { name: 'L2L3_ADAS_GLOBAL_VOLUMES', description: 'Global L2+/L3 ADAS production volumes. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP NXP-03 (Market SIGNAL)`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'L2+ rollout proceeding broadly.', trajectory_reasoning: 'Stable to improving.' },
      { name: 'RADAR_ARCHITECTURE_DISRUPTION', description: 'Imaging-radar architecture disruption risk (silicon-photonics, lidar / camera shift).', component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP NXP-03 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No imminent architecture shift visible.', trajectory_reasoning: 'Stable through 2027.' },
    ],
    claims: [
      { component_name: 'NXP_IMAGING_RADAR_AWARDS', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'NXP wins ≥3 named OEM imaging-radar awards per year through 2027.',
        claim_basis: `Brief HYP NXP-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 3, threshold_unit: 'awards_per_year', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Award flow is the principal commercial validation.', impact_reasoning: 'Each award compounds share through model-year ramps.' },
      { component_name: 'NXP_IMAGING_RADAR_SHARE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Imaging-radar market share holds ≥40% globally through 2027.',
        claim_basis: `Brief HYP NXP-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40, threshold_unit: 'pct_global_share', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Share leadership is the principal market-position validation.', impact_reasoning: 'Each percentage point of share lost compounds.' },
      { component_name: 'L2L3_ADAS_GLOBAL_VOLUMES', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Radar + electrification segment growth holds at 15-20% CAGR.',
        claim_basis: `Brief HYP NXP-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'CAGR holds the absolute revenue trajectory.', impact_reasoning: 'Each percentage point compounds.' },
      { component_name: 'RADAR_ARCHITECTURE_DISRUPTION', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A major imaging-radar architecture shift (silicon-photonics) disrupts NXP roadmap before 2027.',
        claim_basis: `Brief HYP NXP-03 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Architecture disruption could obsolete current SoC roadmap.', impact_reasoning: 'Each year early shift compounds risk.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
