// db/population/P5_ON_hypotheses.mjs
// Source: onsemi_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'onsemi'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'onsemi_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'onsemi',
  sector: 'mobility',
  notes: 'onsemi (ON Semiconductor Corporation) — Phoenix-based power and sensing IDM. NASDAQ:ON. Treo platform + EliteSiC. v2 catalogue first-cut hypotheses sourced from May 2026 brief. Sector mobility (auto SiC dominant) but cross-cutting AI data center exposure.',
};

const initiatives = [
  // ON-01 ----------------------------------------------------------------
  {
    name: 'Treo platform reaches >$500M run-rate by FY2027 with GM 60-70% (lifts group GM beyond 40% exit-2027)',
    strategy_context: `Treo high-margin analog + mixed-signal family. Q1 2026 +2.5x sequential. GM target 60-70%. Design wins span zonal architectures (10BASE-T1S + SmartFETs), ADAS park assist, humanoid-robotics inductive position sensing. Critical to onsemi GM expansion (now 38.5% Q1, target 40%+ exit-2027).`,
    brief_description: 'Whether Treo platform reaches >$500M run-rate by FY2027.',
    hypothesis_statement: `Treo platform reaches >$500M annual run-rate by FY2027 with segment GM 60-70%, becoming onsemi principal high-margin growth engine and lifting group GM beyond 40% by exit-2027. Source: ${BRIEF}, HYP ON-01.`,
    why_it_matters: 'Treo design-win pipeline + analog mixed-signal competitive map are the highest-priority inputs for onsemi mixed-signal BU.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP ON-01 (H1 · 1-2yr)`,
    decision_threshold: 'Treo annual run-rate reaches ≥$500M by exit-2027; Treo segment GM in 60-70% range as guided; Group GM exits 2027 ≥40%; No major Treo design-win loss to ADI / TI / Microchip alternatives. (WNTBT, brief HYP ON-01.)',
    baseline_confidence: 0.65, current_confidence: 0.65,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (60-70% GM target lifts portfolio mix) AND Market (Treo design-win flow) as live SIGNAL drivers.',
    trajectory_reasoning: `Q1 2026 +2.5x sequential confirms compounding. Source: ${BRIEF}.`,
    components: [
      { name: 'TREO_REVENUE_RUNRATE', description: 'Treo platform annual revenue run-rate. Economics + market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-01 WNTBT bullet 1; Section 04 Treo card`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Q1 2026 +2.5x sequential — early-stage compounding.', trajectory_reasoning: 'Run-rate building toward $500M.' },
      { name: 'TREO_GM_PROFILE', description: 'Treo segment gross margin profile (target 60-70%).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-01 WNTBT bullet 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Disclosed target 60-70%.', trajectory_reasoning: 'Mix lift on track.' },
      { name: 'ON_GROUP_GM', description: 'Group gross margin trajectory (target ≥40% exit-2027).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-01 WNTBT bullet 3`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q1 2026 GM 38.5% (3rd consecutive quarter expansion).', trajectory_reasoning: 'Path to 40% by exit-2027.' },
      { name: 'TREO_COMPETITIVE_FIELD', description: 'Treo competitive field — ADI / TI / Microchip analog mixed-signal alternatives.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-01 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No major design-win losses to date.', trajectory_reasoning: 'Stable competitive intensity.' },
    ],
    claims: [
      { component_name: 'TREO_REVENUE_RUNRATE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Treo annual run-rate reaches ≥$500M by exit-2027.',
        claim_basis: `Brief HYP ON-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 500, threshold_unit: 'USD_million_annual', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Run-rate is the principal financial validation.', impact_reasoning: 'Each $100M short of target erodes the GM uplift.' },
      { component_name: 'TREO_GM_PROFILE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Treo segment GM in 60-70% range as guided.',
        claim_basis: `Brief HYP ON-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 60, threshold_unit: 'pct_GM', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'GM discipline confirms premium positioning.', impact_reasoning: 'Each margin point compounds Treo P&L impact.' },
      { component_name: 'ON_GROUP_GM', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Group GM exits 2027 ≥40%.',
        claim_basis: `Brief HYP ON-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40, threshold_unit: 'pct_GM', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Group GM is the equity-narrative anchor.', impact_reasoning: 'Each percentage point of group GM is material.' },
      { component_name: 'TREO_COMPETITIVE_FIELD', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'No major Treo design-win loss to ADI / TI / Microchip alternatives.',
        claim_basis: `Brief HYP ON-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A major loss would erode Treo positioning.', impact_reasoning: 'Each loss compounds revenue / GM risk.' },
    ],
  },

  // ON-02 ----------------------------------------------------------------
  {
    name: 'onsemi sustains ≥40% SiC share among Chinese new EV platforms through 2027',
    strategy_context: `Q1 2026 ~55% SiC share among new EV models at 2026 Beijing Auto Show. NIO 900V (ES9 flagship), ZEEKR, Vitesco $1.9B LTSA, Magna eDrive — multi-OEM lock-in. Chinese IDM (BYD Semi, CRRC, Sanan) competing on wafer pricing.`,
    brief_description: 'Whether onsemi sustains ≥40% SiC share among Chinese new EV platforms through 2027.',
    hypothesis_statement: `onsemi sustains ≥40% SiC share among Chinese new EV platforms through 2027, with NIO 900V flagship halo + Vitesco / Magna / ZEEKR LTSAs anchoring multi-OEM lock-in. Source: ${BRIEF}, HYP ON-02.`,
    why_it_matters: 'China new-EV SiC pipeline tracking + LTSA delivery monitoring is the highest-priority engagement input.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP ON-02 (H1 · 1-2yr)`,
    decision_threshold: 'onsemi SiC share among Chinese new-EV platforms remains ≥40% through 2027; NIO ES9 + 900V flagship launches on schedule with EliteSiC; No major Chinese IDM (BYD Semi / Sanan / CRRC) replaces onsemi as primary supplier on a flagship Chinese OEM platform before 2027; Vitesco / Magna / ZEEKR LTSAs deliver volume in line with contracted schedules. (WNTBT, brief HYP ON-02.)',
    baseline_confidence: 0.68, current_confidence: 0.68,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (China new-EV SiC content) AND Economics (LTSA pricing discipline) as live SIGNAL drivers.',
    trajectory_reasoning: `~55% Beijing 2026 share + LTSA portfolio. Source: ${BRIEF}.`,
    components: [
      { name: 'ON_CHINA_SIC_SHARE', description: 'onsemi SiC share among Chinese new EV platforms (target ≥40%).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-02 WNTBT bullet 1; Section 04 Beijing card`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: '~55% Beijing 2026 share — well above target.', trajectory_reasoning: 'Holding through 2027.' },
      { name: 'NIO_900V_ES9_LAUNCH', description: 'NIO ES9 + 900V flagship launches on schedule with EliteSiC enhanced M3e.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-02 WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Disclosed at 2026 Beijing Auto Show.', trajectory_reasoning: 'Production ramp through 2026-2027.' },
      { name: 'CHINESE_SIC_IDM_DISPLACEMENT_RISK_ON', description: 'Chinese SiC IDM displacement risk on flagship Chinese OEM platforms.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-02 WNTBT bullet 3; SIG-02`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No major displacement to date.', trajectory_reasoning: 'Pressure rising but not materialised.' },
      { name: 'ON_LTSA_VOLUME_DELIVERY', description: 'Vitesco / Magna / ZEEKR LTSA volume delivery vs contracted schedules.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-02 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'LTSA portfolio active.', trajectory_reasoning: 'Stable absent EU auto destock continuation.' },
    ],
    claims: [
      { component_name: 'ON_CHINA_SIC_SHARE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'onsemi SiC share among Chinese new-EV platforms remains ≥40% through 2027.',
        claim_basis: `Brief HYP ON-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40, threshold_unit: 'pct_china_new_EV_SiC_share', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Share leadership is the principal market-position validation.', impact_reasoning: 'Each percentage point of share-shift compounds.' },
      { component_name: 'NIO_900V_ES9_LAUNCH', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'NIO ES9 + 900V flagship launches on schedule with EliteSiC.',
        claim_basis: `Brief HYP ON-02 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'NIO 900V flagship is the halo proof-point for EliteSiC enhanced M3e.', impact_reasoning: 'Launch validates the technology at scale.' },
      { component_name: 'CHINESE_SIC_IDM_DISPLACEMENT_RISK_ON', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No major Chinese SiC IDM replaces onsemi as primary supplier on a flagship Chinese OEM platform before 2027.',
        claim_basis: `Brief HYP ON-02 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A primary-supplier loss is the principal falsification trigger.', impact_reasoning: 'Each major loss compounds the share-erosion path.' },
      { component_name: 'ON_LTSA_VOLUME_DELIVERY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Vitesco / Magna / ZEEKR LTSAs deliver volume in line with contracted schedules.',
        claim_basis: `Brief HYP ON-02 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'LTSA delivery confirms structural revenue base.', impact_reasoning: 'Each LTSA shortfall erodes contracted volume.' },
    ],
  },

  // ON-03 ----------------------------------------------------------------
  {
    name: 'AI data center revenue scales ~$300M FY2026 → >$700M FY2027 (GaN funnel + Tier-1 PSU wins)',
    strategy_context: `Q1 2026 AI data center +30% QoQ; on track to double YoY. GaN solutions for 48V architectures + AI server PSU. GaN funnel >$1.5B. Hyperscaler 48V architecture refresh underway — onsemi competing with Infineon, STM, Power Integrations.`,
    brief_description: 'Whether AI data center scales >$700M by FY2027.',
    hypothesis_statement: `AI data center revenue scales from ~$300M FY2026 to >$700M FY2027 as GaN funnel converts and onsemi captures Tier-1 hyperscaler 48V PSU slots. Source: ${BRIEF}, HYP ON-03.`,
    why_it_matters: 'Hyperscaler PSU vendor selection + GaN funnel-to-revenue conversion are the highest-leverage scouting inputs for onsemi data center BU.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP ON-03 (H2 · 3-5yr)`,
    decision_threshold: 'AI data center FY2026 revenue ≥ $300M (consistent with doubling YoY trajectory); FY2027 AI data center ≥ $700M; GaN funnel converts ≥30% of $1.5B+ pipeline by end-2027; At least one named Tier-1 hyperscaler 48V PSU win disclosed by end-2026. (WNTBT, brief HYP ON-03.)',
    baseline_confidence: 0.60, current_confidence: 0.60,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (AI server PSU + 48V demand) AND Technology (GaN solutions roadmap) as live SIGNAL drivers.',
    trajectory_reasoning: `Q1 2026 +30% QoQ. Source: ${BRIEF}.`,
    components: [
      { name: 'ON_AI_DATA_CENTER_REVENUE', description: 'onsemi AI data center segment revenue trajectory.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP ON-03 WNTBT bullets 1+2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q1 +30% QoQ; on track to double YoY.', trajectory_reasoning: 'Trajectory toward $700M FY2027.' },
      { name: 'ON_GAN_FUNNEL_CONVERSION', description: 'onsemi GaN funnel conversion (>$1.5B pipeline; target ≥30% by end-2027).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-03 WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Funnel building; conversion in early stages.', trajectory_reasoning: 'Conversion accelerating with hyperscaler 48V refresh.' },
      { name: 'HYPERSCALER_48V_PSU_WIN', description: 'Tier-1 hyperscaler 48V PSU win (target ≥1 named by end-2026).', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP ON-03 WNTBT bullet 4; SIG-03`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'Pre-public-commitment phase.', trajectory_reasoning: 'Outcome contested with Infineon, STM, POWI.' },
      { name: 'AI_PSU_COMPETITIVE_FIELD', description: 'AI server PSU competitive field — Infineon + STM + Power Integrations.', component_type: 'competitor', vector: 'competition', cross_industry: true,
        source_citation: `${BRIEF} HYP ON-03 (Section 03 peer table); SIG-03`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Multiple credible alternatives.', trajectory_reasoning: 'Competitive intensity stable to rising.' },
    ],
    claims: [
      { component_name: 'ON_AI_DATA_CENTER_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'AI data center FY2026 revenue ≥ $300M; FY2027 ≥ $700M.',
        claim_basis: `Brief HYP ON-03 WNTBT conditions 1+2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 700, threshold_unit: 'USD_million_FY2027', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Revenue trajectory is the principal financial validation.', impact_reasoning: 'Each $50M short of target erodes equity narrative.' },
      { component_name: 'ON_GAN_FUNNEL_CONVERSION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'GaN funnel converts ≥30% of $1.5B+ pipeline by end-2027.',
        claim_basis: `Brief HYP ON-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 30, threshold_unit: 'pct_funnel_conversion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Funnel conversion is the principal pipeline validation.', impact_reasoning: 'Each percentage point of conversion compounds revenue.' },
      { component_name: 'HYPERSCALER_48V_PSU_WIN', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'At least one named Tier-1 hyperscaler 48V PSU win disclosed by end-2026.',
        claim_basis: `Brief HYP ON-03 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1, threshold_unit: 'named_hyperscaler_wins', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'A named hyperscaler win de-risks the trajectory.', impact_reasoning: 'Each win compounds segment credibility.' },
      { component_name: 'AI_PSU_COMPETITIVE_FIELD', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'No major hyperscaler 48V PSU contract goes to a competitor before onsemi disclosure.',
        claim_basis: `Brief HYP ON-03 (Section 03 peer table). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A competitive lockout would derail the trajectory.', impact_reasoning: 'Each competitor win compounds the share-erosion risk.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
