// db/population/P5_REN_hypotheses.mjs
// Source: renesas_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'Renesas Electronics'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'renesas_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'Renesas Electronics',
  sector: 'mobility',
  notes: 'Renesas Electronics Corporation — Tokyo-based automotive + industrial / IoT IDM. TYO:6723. v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // REN-01 ----------------------------------------------------------------
  {
    name: 'R-Car Gen 5 / X5H consolidates Renesas as Top-3 SDV-platform contender by 2028',
    strategy_context: `R-Car X5H — industry's first 3nm multi-domain auto SoC (ADAS + IVI + Gateway in one). Centerpiece of Renesas SDV positioning vs NXP CoreRide / Qualcomm Ride / Mobileye SuperVision. End-to-end multi-domain solution platform for OEM zonal architectures.`,
    brief_description: 'Whether R-Car Gen 5 / X5H secures Top-3 SDV positioning by 2028.',
    hypothesis_statement: `R-Car Gen 5 / X5H consolidates Renesas as a Top-3 SDV-platform contender by 2028 alongside NXP CoreRide and Qualcomm Snapdragon Ride, securing at least one major OEM production deployment. Source: ${BRIEF}, HYP REN-01.`,
    why_it_matters: 'SDV-platform competitive map (Renesas / NXP / Qualcomm / Mobileye) + Japanese-OEM intelligence are the highest-priority engagement inputs.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP REN-01 (H2 · 3-5yr)`,
    decision_threshold: 'R-Car X5H ships at volume to first OEM customer by end-2027; At least one major Japanese or European OEM publicly commits to R-Car Gen 5 SDV stack by end-2027; Renesas auto SDV revenue passes 10% of segment by FY2027; No SDV-stack walk-away by major Japanese OEM (Toyota / Honda / Nissan) toward NXP / Qualcomm / Mobileye. (WNTBT, brief HYP REN-01.)',
    baseline_confidence: 0.60, current_confidence: 0.60,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Technology (3nm multi-domain SoC) AND Market (OEM commitments) as live SIGNAL drivers; competitive intensity high.',
    trajectory_reasoning: `R-Car X5H launch but contested OEM pipeline. Source: ${BRIEF}.`,
    components: [
      { name: 'R_CAR_X5H_SOC_3NM', description: 'R-Car X5H — first 3nm multi-domain auto SoC. Technology SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-01 (Technology SIGNAL); Section 04 R-Car card`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Industry-first 3nm multi-domain SoC; ADAS+IVI+Gateway in one.', trajectory_reasoning: 'Volume ramp to first OEM by end-2027.' },
      { name: 'JAPANESE_OEM_SDV_COMMITMENT', description: 'Japanese OEM (Toyota, Honda, Nissan) commitment to R-Car Gen 5 SDV stack. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-01 (Market SIGNAL); WNTBT bullets 2+4`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Pre-public-commitment phase; competitive risk visible.', trajectory_reasoning: 'Outcome contested.' },
      { name: 'SDV_PLATFORM_COMPETITIVE_FIELD_REN', description: 'SDV-platform competitive field — NXP CoreRide + Qualcomm Snapdragon Ride + Mobileye SuperVision.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-01 (Strategy box); SIG-01`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'NXP + Qualcomm aggressive in same OEM pipeline.', trajectory_reasoning: 'Competitive intensity rising.' },
      { name: 'REN_AUTO_SDV_REVENUE_SHARE', description: 'Renesas auto SDV revenue share of total auto segment.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-01 WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Currently small; growth profile dependent on X5H ramp.', trajectory_reasoning: 'Path to >10% by FY2027.' },
    ],
    claims: [
      { component_name: 'R_CAR_X5H_SOC_3NM', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'R-Car X5H ships at volume to first OEM customer by end-2027.',
        claim_basis: `Brief HYP REN-01 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Volume shipping is the principal technical-commercial validation.', impact_reasoning: 'Each year of slip pushes Top-3 contender status out.' },
      { component_name: 'JAPANESE_OEM_SDV_COMMITMENT', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'At least one major Japanese or European OEM publicly commits to R-Car Gen 5 SDV stack by end-2027.',
        claim_basis: `Brief HYP REN-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1, threshold_unit: 'named_OEM_commits', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'A named commitment is the principal commercial validation.', impact_reasoning: 'Each named OEM compounds R-Car platform credibility.' },
      { component_name: 'REN_AUTO_SDV_REVENUE_SHARE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Renesas auto SDV revenue passes 10% of segment by FY2027.',
        claim_basis: `Brief HYP REN-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'pct_auto_segment', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'SDV share confirms platform monetisation underway.', impact_reasoning: 'Each percentage point of share-shift lifts mix.' },
      { component_name: 'SDV_PLATFORM_COMPETITIVE_FIELD_REN', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No SDV-stack walk-away by major Japanese OEM toward NXP / Qualcomm / Mobileye.',
        claim_basis: `Brief HYP REN-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A Japanese-OEM walk-away would falsify the home-field advantage.', impact_reasoning: 'Each major loss erodes the platform thesis.' },
    ],
  },

  // REN-02 ----------------------------------------------------------------
  {
    name: 'Industrial / IoT segment sustains >¥800B run-rate by FY2027 with margin expansion (Altium-amplified)',
    strategy_context: `Q1 2026 industrial / IoT +32% YoY to ¥199B (annualised ~¥800B). Altium A$9.1B Aug 2024 acquisition — PCB design + lifecycle SaaS attaching alongside Renesas IP catalogue. Secular AI / industrial automation tailwinds. Highest-margin segment in mix.`,
    brief_description: 'Whether industrial / IoT sustains >¥800B run-rate with margin expansion through 2027.',
    hypothesis_statement: `Renesas industrial / IoT segment sustains >¥800B run-rate by FY2027 with margin expansion, lifted by Altium SaaS attach and the AI / industrial automation cycle. Source: ${BRIEF}, HYP REN-02.`,
    why_it_matters: 'Industrial / IoT competitive benchmarking + Altium platform-monetisation tracking is the highest-leverage scouting input for industrial business.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP REN-02 (H1 · 1-2yr)`,
    decision_threshold: 'FY2027 industrial / IoT revenue ≥ ¥800B; Altium ARR / subscription growth disclosed at >15% YoY through 2027; Industrial / IoT segment GM holds ≥ 60% non-GAAP through 2027; No major AI / industrial-automation demand reset before end-2027. (WNTBT, brief HYP REN-02.)',
    baseline_confidence: 0.65, current_confidence: 0.65,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (industrial demand +32%) AND Economics (Altium SaaS attach) as live SIGNAL drivers.',
    trajectory_reasoning: `Strong Q1 2026 momentum. Source: ${BRIEF}.`,
    components: [
      { name: 'REN_INDUSTRIAL_IOT_REVENUE', description: 'Renesas industrial / IoT segment revenue trajectory toward ¥800B FY2027.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-02 WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q1 +32% YoY annualised to ~¥800B.', trajectory_reasoning: 'Compounding through 2026-2027.' },
      { name: 'ALTIUM_SAAS_ATTACH', description: 'Altium SaaS / subscription attach + ARPU expansion vs silicon-only mix.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-02 (Economics SIGNAL); WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Aug 2024 close; integration in early stages.', trajectory_reasoning: 'SaaS revenue building.' },
      { name: 'AI_INDUSTRIAL_AUTOMATION_CYCLE', description: 'AI / industrial automation demand cycle. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP REN-02 (Market SIGNAL)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Secular tailwind through 2027.', trajectory_reasoning: 'Compounding demand.' },
      { name: 'INDUSTRIAL_IOT_GM', description: 'Industrial / IoT segment gross margin (target ≥60% non-GAAP).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-02 WNTBT bullet 3`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Q1 2026 group GM 59.2% non-GAAP; segment slightly above.', trajectory_reasoning: 'Stable to improving with SaaS mix.' },
    ],
    claims: [
      { component_name: 'REN_INDUSTRIAL_IOT_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2027 industrial / IoT revenue ≥ ¥800B (annualised run-rate).',
        claim_basis: `Brief HYP REN-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 800, threshold_unit: 'JPY_billion', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Run-rate is the principal financial validation.', impact_reasoning: 'Each ¥50B above target lifts segment profile.' },
      { component_name: 'ALTIUM_SAAS_ATTACH', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Altium ARR / subscription growth disclosed at >15% YoY through 2027.',
        claim_basis: `Brief HYP REN-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 15, threshold_unit: 'pct_YoY_ARR_growth', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Altium ARR confirms platform monetisation thesis.', impact_reasoning: 'Each percentage point of ARR growth compounds attach.' },
      { component_name: 'INDUSTRIAL_IOT_GM', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Industrial / IoT segment GM holds ≥ 60% non-GAAP through 2027.',
        claim_basis: `Brief HYP REN-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 60, threshold_unit: 'pct_GM', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'GM discipline confirms premium positioning.', impact_reasoning: 'Each margin point compounds segment EBIT.' },
      { component_name: 'AI_INDUSTRIAL_AUTOMATION_CYCLE', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'A major AI / industrial-automation demand reset occurs before end-2027.',
        claim_basis: `Brief HYP REN-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A demand reset would derail the run-rate thesis.', impact_reasoning: 'Each quarter of reset compounds against ¥800B target.' },
    ],
  },

  // REN-03 ----------------------------------------------------------------
  {
    name: 'Wolfspeed restructuring delivers Renesas usable SiC capacity at favourable terms by FY2027 (no further write-down)',
    strategy_context: `Pre-petition $2B deposit converted to equity + secured convertible debt; CFIUS clearance Jan 2026; 16.85M Wolfspeed shares to Renesas; Aris Bolisay board designee Feb 2026. Renesas now sits on Wolfspeed cap table — equity-method losses + restructuring execution risk.`,
    brief_description: 'Whether Wolfspeed delivers usable SiC capacity without further write-down through 2026.',
    hypothesis_statement: `Wolfspeed restructuring delivers Renesas usable SiC capacity at favourable terms by FY2027, with no further material write-down on the equity-converted ~$2B deposit through 2026. Source: ${BRIEF}, HYP REN-03.`,
    why_it_matters: 'Wolfspeed quarterly tracking + SiC capacity-allocation intelligence is the highest-risk-adjusted scouting input for power-electronics strategy team.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP REN-03 (H1 · 1-2yr)`,
    decision_threshold: 'No further material write-down on the Wolfspeed equity-converted deposit through end-2026; Wolfspeed Mohawk Valley 200mm reaches commercial-scale utilisation by FY2027; Renesas accesses preferential SiC capacity allocation under restructuring agreement; No further CFIUS / CHIPS Act intervention against the Renesas equity stake. (WNTBT, brief HYP REN-03.)',
    baseline_confidence: 0.55, current_confidence: 0.55,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Economics (mark-to-market) AND Market (SiC pricing + Mohawk Valley utilisation) as live SIGNAL drivers; outcome high-risk.',
    trajectory_reasoning: `Wolfspeed post-emergence trajectory uncertain; restructuring execution dependent. Source: ${BRIEF}.`,
    components: [
      { name: 'WOLFSPEED_EQUITY_MARK_TO_MARKET', description: 'Wolfspeed equity / convertible debt mark-to-market on Renesas balance sheet. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-03 (Economics SIGNAL); WNTBT bullet 1`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: '~$2B deposit converted; Wolfspeed equity volatile post-emergence.', trajectory_reasoning: 'Outcome dependent on Wolfspeed execution.' },
      { name: 'WOLFSPEED_MOHAWK_VALLEY_200MM', description: 'Wolfspeed Mohawk Valley 200mm SiC commercial-scale utilisation. Technology + manufacturing driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-03 WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Mohawk Valley running but pre-bankruptcy yield issues.', trajectory_reasoning: 'Improvement profile post-restructuring.' },
      { name: 'REN_PREFERENTIAL_SIC_ALLOCATION', description: 'Renesas preferential SiC capacity allocation under restructuring agreement.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP REN-03 WNTBT bullet 3`, state: 'new', trajectory: 'unknown',
        state_reasoning: 'Allocation terms not publicly disclosed.', trajectory_reasoning: 'Outcome dependent on restructuring agreement specifics.' },
      { name: 'CFIUS_CHIPS_ACT_INTERVENTION_RISK', description: 'CFIUS + US CHIPS Act intervention risk against Renesas equity stake.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP REN-03 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'CFIUS cleared Jan 2026; CHIPS Act foreign-holder rules applying.', trajectory_reasoning: 'Stable absent further intervention.' },
    ],
    claims: [
      { component_name: 'WOLFSPEED_EQUITY_MARK_TO_MARKET', role: 'principal', impact: 'dampening', criticality: 'critical',
        claim_text: 'No further material write-down on the Wolfspeed equity-converted deposit through end-2026.',
        claim_basis: `Brief HYP REN-03 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'A further write-down is the principal financial risk on Renesas balance sheet.', impact_reasoning: 'Each impairment hits earnings and confidence.' },
      { component_name: 'WOLFSPEED_MOHAWK_VALLEY_200MM', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Wolfspeed Mohawk Valley 200mm reaches commercial-scale utilisation by FY2027.',
        claim_basis: `Brief HYP REN-03 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Mohawk Valley is the principal SiC capacity asset in the Wolfspeed estate.', impact_reasoning: 'Commercial-scale validates capacity for Renesas use.' },
      { component_name: 'REN_PREFERENTIAL_SIC_ALLOCATION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Renesas accesses preferential SiC capacity allocation under restructuring agreement.',
        claim_basis: `Brief HYP REN-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Preferential allocation is the strategic value-capture from the equity stake.', impact_reasoning: 'Each capacity slot validates the deposit-to-stake conversion.' },
      { component_name: 'CFIUS_CHIPS_ACT_INTERVENTION_RISK', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'No further CFIUS / CHIPS Act intervention against the Renesas equity stake.',
        claim_basis: `Brief HYP REN-03 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A further intervention could force divestment.', impact_reasoning: 'Each intervention compounds restructuring risk.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
