// db/population/P5_SLB_hypotheses.mjs
// Source: slb_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'SLB'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'slb_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'SLB',
  sector: 'energy',
  notes: 'SLB (Schlumberger) — world-leading oilfield services group, post-ChampionX. NYSE:SLB. CEO Olivier Le Peuch. Three-leg strategy: core OFS, Production Systems / ChampionX (less-cyclical), Digital & Integration (Lumi + Delfi). v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // SLB-01 ----------------------------------------------------------------
  {
    name: 'ChampionX integration delivers ≥$400M synergies + Production Systems → 35-40% of revenue by 2028',
    strategy_context: `ChampionX deal closed Jul 16 2025 ($7.8B all-stock). Q1 2026: $838M revenue + $199M adj EBITDA contribution. $400M annual pretax synergy target (revenue + cost) within 3 years. Production Systems share lifted from ~28-30% pre-close toward 35-40% target — explicit less-cyclical mix shift thesis.`,
    brief_description: 'Whether ChampionX integration delivers synergy + mix-shift targets.',
    hypothesis_statement: `SLB realises ≥$400M annual pretax ChampionX synergies within 3 years post-close, with Production Systems share of revenue stabilising at 35-40% (vs ~28-30% pre-close), establishing a structurally less-cyclical earnings base. Source: ${BRIEF}, HYP SLB-01.`,
    why_it_matters: 'Production-chemistry benchmarking + artificial-lift competitive positioning are the highest-priority scouting categories.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP SLB-01 (H2 · 3-5yr)`,
    decision_threshold: 'Synergy run-rate ≥ $300M by end-2027 (75% of 3-year target); Production Systems revenue share > 35% of total by FY2028; No material customer attrition in ChampionX legacy book through 2027; EBITDA margin in Production Systems holds > 22% through integration. (WNTBT, brief HYP SLB-01.)',
    baseline_confidence: 0.72, current_confidence: 0.72,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics ($199M ChampionX EBITDA Q1) AND Market (production-chem demand) as live SIGNAL drivers.',
    trajectory_reasoning: `Synergy capture in early stages but execution underway. Source: ${BRIEF}.`,
    components: [
      { name: 'CHAMPIONX_SYNERGY_RUNRATE', description: 'ChampionX synergy run-rate vs $400M 3-year target. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-01 (Economics SIGNAL); WNTBT bullet 1`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Integration just begun (Jul 2025 close); $199M Q1 2026 EBITDA contribution.', trajectory_reasoning: 'Synergy capture ramps over years 1-3.' },
      { name: 'PRODUCTION_SYSTEMS_REV_SHARE', description: 'Production Systems share of SLB revenue (target 35-40% by 2028).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-01 WNTBT bullet 2; Section 02`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'ChampionX close lifts share immediately.', trajectory_reasoning: 'Share trajectory toward 35-40% by 2028 underway.' },
      { name: 'CHAMPIONX_NA_CUSTOMER_BASE', description: 'ChampionX North America customer base unlocks SLB cross-sell.', component_type: 'ecosystem', vector: 'ecosystem', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-01 (Ecosystem driver)`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'NA customer relationships intact through close.', trajectory_reasoning: 'Cross-sell programmes underway.' },
      { name: 'PRODUCTION_CHEMICALS_COMPETITIVE_POSITIONING', description: 'Production chemicals + artificial lift competitive positioning vs HAL / BKR.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-01 (Competition driver)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'HAL / BKR not equivalently positioned in production chemicals scale post-ChampionX.', trajectory_reasoning: 'SLB lead widens with ChampionX integration.' },
    ],
    claims: [
      { component_name: 'CHAMPIONX_SYNERGY_RUNRATE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Synergy run-rate reaches ≥ $300M by end-2027 (75% of 3-year target).',
        claim_basis: `Brief HYP SLB-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 300, threshold_unit: 'USD_million_annual', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Synergy capture is the principal financial validation of the deal thesis.', impact_reasoning: 'Each $50M of synergy lifts group EBITDA.' },
      { component_name: 'PRODUCTION_SYSTEMS_REV_SHARE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Production Systems revenue share > 35% of total by FY2028.',
        claim_basis: `Brief HYP SLB-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 35, threshold_unit: 'pct_revenue', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Mix-shift is the strategic narrative of the deal.', impact_reasoning: 'Each percentage point of share-shift improves earnings quality.' },
      { component_name: 'CHAMPIONX_NA_CUSTOMER_BASE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'No material customer attrition in ChampionX legacy book through 2027.',
        claim_basis: `Brief HYP SLB-01 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Customer retention is the precondition for synergy capture.', impact_reasoning: 'Each major lost account erodes synergy realisation.' },
      { component_name: 'PRODUCTION_CHEMICALS_COMPETITIVE_POSITIONING', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'EBITDA margin in Production Systems holds > 22% through integration.',
        claim_basis: `Brief HYP SLB-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 22, threshold_unit: 'pct_EBITDA_margin', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Margin protection during integration validates competitive positioning.', impact_reasoning: 'Each margin point lost during integration weakens deal economics.' },
    ],
  },

  // SLB-02 ----------------------------------------------------------------
  {
    name: 'Lumi + Delfi + Autonomous Drilling drives Digital & Integration to ≥25% of revenue by 2028',
    strategy_context: `Lumi launched Sep 2024 as AI / data foundation layer integrating with Delfi cognitive E&P. Autonomous Directional Drilling rolled out early 2026 (~30% drilling time reduction). Major win: ONGC enterprise-wide Lumi deployment. Digital is highest-margin SLB segment (>30%); reaching 25% revenue mix would lift group margin meaningfully and re-rate the equity narrative.`,
    brief_description: 'Whether Digital & Integration scales to ≥25% of revenue by 2028.',
    hypothesis_statement: `Lumi platform adoption + Delfi expansion + Autonomous Directional Drilling rollout grows Digital & Integration revenue to ≥25% of group by FY2028, with EBITDA margin holding > 30%. Source: ${BRIEF}, HYP SLB-02.`,
    why_it_matters: 'Track NOC + IOC digital procurement decisions, hyperscaler partnerships, and Autonomous Drilling adoption pace.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP SLB-02 (H2 · 3-5yr)`,
    decision_threshold: 'D&I share rises from current ~13-15% to ≥20% by end-2027 and ≥25% by end-2028; Autonomous Directional Drilling moves from pilot to ≥10 commercial deployments by end-2027; Enterprise Lumi wins continue at ≥3 NOC / IOC announcements per year through 2027; D&I segment EBITDA margin remains > 30%. (WNTBT, brief HYP SLB-02.)',
    baseline_confidence: 0.64, current_confidence: 0.64,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (Autonomous Drilling 30%) AND Market (NOC/IOC digital budgets) as live SIGNAL drivers; Competition flagged as WEAK.',
    trajectory_reasoning: `Lumi enterprise wins (ONGC) + Autonomous Drilling proof point lift trajectory. Source: ${BRIEF}.`,
    components: [
      { name: 'AUTONOMOUS_DIRECTIONAL_DRILLING', description: 'Autonomous Directional Drilling — early 2026 rollout, ~30% drilling time reduction. Technology SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-02 (Technology SIGNAL); Section 04`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Just rolled out 2026; pilot stage moving to commercial.', trajectory_reasoning: '30% time-reduction = compelling economics.' },
      { name: 'LUMI_ENTERPRISE_DEPLOYMENTS', description: 'Lumi platform enterprise deployments (ONGC + future NOC/IOC wins). Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-02 (Market SIGNAL); Section 04`, state: 'new', trajectory: 'improving',
        state_reasoning: 'ONGC enterprise-wide award secured; pipeline building.', trajectory_reasoning: 'NOC + IOC digital procurement budgets compounding.' },
      { name: 'DI_REVENUE_SHARE', description: 'Digital & Integration share of SLB revenue (target ≥25% by 2028).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-02 WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Currently ~13-15%; trajectory underway.', trajectory_reasoning: 'Lumi + Autonomous Drilling adoption to lift share.' },
      { name: 'DIGITAL_OFS_COMPETITION', description: 'HAL iEnergy + BKR Cordant + hyperscaler-direct competition for digital OFS budgets.', component_type: 'competitor', vector: 'competition', cross_industry: true,
        source_citation: `${BRIEF} HYP SLB-02 (Competition WEAK)`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Multiple credible alternatives; hyperscalers also competing for data-platform layer.', trajectory_reasoning: 'Competitive intensity rising.' },
    ],
    claims: [
      { component_name: 'DI_REVENUE_SHARE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'D&I share rises from current ~13-15% to ≥20% by end-2027 and ≥25% by end-2028.',
        claim_basis: `Brief HYP SLB-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 25, threshold_unit: 'pct_revenue', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'D&I revenue share is the principal validation of the platform thesis.', impact_reasoning: 'Each percentage point of share-shift lifts group margin.' },
      { component_name: 'AUTONOMOUS_DIRECTIONAL_DRILLING', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Autonomous Directional Drilling moves from pilot to ≥10 commercial deployments by end-2027.',
        claim_basis: `Brief HYP SLB-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'commercial_deployments', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Commercial adoption is the proof of value capture beyond pilots.', impact_reasoning: 'Each deployment validates the technology and lifts margin profile.' },
      { component_name: 'LUMI_ENTERPRISE_DEPLOYMENTS', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Enterprise Lumi wins continue at ≥3 NOC / IOC announcements per year through 2027.',
        claim_basis: `Brief HYP SLB-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 3, threshold_unit: 'announcements_per_year', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Enterprise wins anchor recurring digital revenue.', impact_reasoning: 'Each enterprise deployment adds multi-year revenue stream.' },
      { component_name: 'DIGITAL_OFS_COMPETITION', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'D&I segment EBITDA margin remains > 30% despite competitive intensity.',
        claim_basis: `Brief HYP SLB-02 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 30, threshold_unit: 'pct_EBITDA_margin', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Margin discipline against competition is the value-capture test.', impact_reasoning: 'Each margin point lost erodes the digital re-rating thesis.' },
    ],
  },

  // SLB-03 ----------------------------------------------------------------
  {
    name: 'Middle East disruption is transient — operations normalise by H2 2026, supporting FY2027 EBITDA growth',
    strategy_context: `Q1 2026 negative EPS preannouncement (6-9¢ hit). Red Sea logistics bottlenecks + NOC tactical project recalibration. SLB demobilised select country operations to safeguard personnel. CEO commentary frames as transient. Aramco 5-yr Jafurah unconventional gas wrap (Dec 2025) anchors long-term Saudi commitment.`,
    brief_description: 'Whether Middle East operations normalise by H2 2026.',
    hypothesis_statement: `Red Sea logistics + NOC project recalibration are tactical / transient — Middle East run-rate revenue normalises by H2 2026, supporting FY2027 group EBITDA growth and reaffirming SLB's structural Middle East advantage. Source: ${BRIEF}, HYP SLB-03.`,
    why_it_matters: 'Middle East operations weekly tracking + NOC contract repacing intelligence is the most time-sensitive scouting category for SLB account team.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP SLB-03 (H1 · 1-2yr)`,
    decision_threshold: 'Middle East revenue stabilises in Q2 2026 and grows sequentially in Q3 + Q4 2026; No further demobilisations announced in H2 2026; Aramco Jafurah project ramps on schedule (visible in 2027); FY2027 group EBITDA grows YoY (vs FY2026 disruption-impaired base). (WNTBT, brief HYP SLB-03.)',
    baseline_confidence: 0.56, current_confidence: 0.56,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Geopolitics (Red Sea + demobilisations) AND Customer (Aramco Jafurah) as competing live SIGNAL drivers; Risk WEAK on escalation.',
    trajectory_reasoning: `Outcome depends on Q2/Q3 2026 trajectory; geopolitical volatility unresolved. Source: ${BRIEF}.`,
    components: [
      { name: 'MIDDLE_EAST_OPERATIONAL_DISRUPTION', description: 'Middle East operational disruption (Red Sea logistics + NOC recalibration). Geopolitics SIGNAL driver.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP SLB-03 (Geopolitics SIGNAL); Section 04`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'Active Q1 2026 disruption with demobilisations.', trajectory_reasoning: 'Trajectory uncertain pending H2 2026 normalisation.' },
      { name: 'ARAMCO_JAFURAH_5YR_WRAP', description: 'Aramco 5-yr Jafurah unconventional gas wrap (Dec 2025). Customer SIGNAL driver.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-03 (Customer SIGNAL); Section 04`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Multi-billion-$ award secured; long-term Saudi commitment intact.', trajectory_reasoning: 'Project ramp begins through 2026-2027.' },
      { name: 'IRAN_HOUTHI_ESCALATION_RISK', description: 'Iran / Houthi escalation risk extending Middle East disruption.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP SLB-03 (Risk WEAK)`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Tactical disruption may become structural if escalation continues.', trajectory_reasoning: 'High-volatility geopolitical input.' },
      { name: 'SLB_FY2027_EBITDA_RECOVERY', description: 'SLB FY2027 group EBITDA recovery vs FY2026 disruption-impaired base.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP SLB-03 WNTBT bullet 4`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'FY2027 trajectory turns on H2 2026 Middle East normalisation.', trajectory_reasoning: 'Outcome unknown pending Q2/Q3 2026 data.' },
    ],
    claims: [
      { component_name: 'MIDDLE_EAST_OPERATIONAL_DISRUPTION', role: 'principal', impact: 'dampening', criticality: 'critical',
        claim_text: 'Middle East revenue stabilises in Q2 2026 and grows sequentially in Q3 + Q4 2026.',
        claim_basis: `Brief HYP SLB-03 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Middle East run-rate is the principal swing factor on FY2026 results.', impact_reasoning: 'Each quarter of continued disruption compounds the FY2027 base risk.' },
      { component_name: 'IRAN_HOUTHI_ESCALATION_RISK', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No further SLB demobilisations announced in H2 2026.',
        claim_basis: `Brief HYP SLB-03 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Further demobilisations would signal structural rather than tactical disruption.', impact_reasoning: 'Each additional demobilisation moves the recovery further out.' },
      { component_name: 'ARAMCO_JAFURAH_5YR_WRAP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Aramco Jafurah project ramps on schedule, with visible progress in 2027.',
        claim_basis: `Brief HYP SLB-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Jafurah ramp is the proof of structural Saudi commitment despite Q1 disruption.', impact_reasoning: 'Each Jafurah milestone validates the 5-yr revenue stream.' },
      { component_name: 'SLB_FY2027_EBITDA_RECOVERY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'FY2027 group EBITDA grows YoY vs FY2026 disruption-impaired base.',
        claim_basis: `Brief HYP SLB-03 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'FY2027 EBITDA growth is the financial validation of the transient-disruption hypothesis.', impact_reasoning: 'Each percentage point of EBITDA growth restores the structural narrative.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
