// db/population/P5_STM_hypotheses.mjs
// Source: stmicroelectronics_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'STMicroelectronics'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'stmicroelectronics_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'STMicroelectronics',
  sector: 'semiconductors',
  notes: 'STMicroelectronics N.V. — Franco-Italian IDM. NYSE:STM, Euronext:STM. Power semis, automotive ICs, MCU, AI infra. v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // STM-01 ----------------------------------------------------------------
  {
    name: 'STM defends ≥30% global automotive SiC share through 2027 via Catania 200mm ramp',
    strategy_context: `Catania €5B (€2B EU Chips Act) fully integrated 200mm SiC fab. First wafers Q4 2025; 15k wfr/wk by 2033. Defends auto SiC share against Chinese IDMs (BYD Semi, CRRC, Sanan) and Infineon. SiC ASP currently <$300 / 200mm-equivalent; Chinese capacity expanding aggressively.`,
    brief_description: 'Whether STM defends ≥30% global automotive SiC share through 2027.',
    hypothesis_statement: `STM defends ≥30% global automotive SiC market share through 2027 by ramping Catania 200mm to design-rule yield, holding ASPs above the Chinese-IDM benchmark via European OEM lock-in. Source: ${BRIEF}, HYP STM-01.`,
    why_it_matters: 'A rigorous SiC competitive landscape — Catania ramp, Chinese-IDM qualification status, OEM dual-source intelligence — is the engagement anchor for STM strategy team.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP STM-01 (H2 · 3-5yr)`,
    decision_threshold: 'Catania 200mm reaches design-rule yield by end-2026 with first OEM-qualified parts shipping in volume; No European OEM dual-sources SiC inverters with a Chinese IDM as primary supplier before 2027; STM SiC ASP holds above $300 / 200mm-equivalent through 2027; EU Chips Act funding remains in force; no reversal of non-China sourcing preferences. (WNTBT, brief HYP STM-01.)',
    baseline_confidence: 0.65, current_confidence: 0.65,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Economics (SiC wafer pricing) AND Market (Chinese + Infineon share) as live SIGNAL drivers; outcome contested.',
    trajectory_reasoning: `Catania ramp early-stage; Chinese capacity expanding; outcome uncertain. Source: ${BRIEF}.`,
    components: [
      { name: 'CATANIA_200MM_SIC_RAMP', description: 'Catania 200mm SiC fab ramp (€5B, first wafers Q4 2025). Technology + manufacturing readiness driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-01 (Tech driver); Section 04 Catania card`, state: 'new', trajectory: 'improving',
        state_reasoning: 'First 200mm wafers Q4 2025 — execution underway.', trajectory_reasoning: 'Yield improvement profile through 2026.' },
      { name: 'CHINESE_SIC_IDM_PRESSURE', description: 'BYD Semi, CRRC, Sanan, Jinko — Chinese SiC IDM 200mm capacity expansion. Market SIGNAL driver.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-01 (Market SIGNAL); SIG-01`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Chinese capacity growing aggressively; share threat building.', trajectory_reasoning: 'Multi-year pressure.' },
      { name: 'STM_SIC_ASP', description: 'STM SiC ASP per 200mm-equivalent vs Chinese IDM benchmark. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-01 (Economics SIGNAL); WNTBT bullet 3`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Pricing under pressure from Chinese supply.', trajectory_reasoning: 'Deteriorating absent Catania cost-curve advantage.' },
      { name: 'EU_CHIPS_ACT_NON_CHINA_SOURCING', description: 'EU Chips Act + non-China sourcing preferences supporting STM auto win-rate. Policy driver.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP STM-01 (Policy); WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'EU Chips Act in force; non-China sourcing preferences intact.', trajectory_reasoning: 'Stable absent reversal.' },
    ],
    claims: [
      { component_name: 'CATANIA_200MM_SIC_RAMP', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Catania 200mm reaches design-rule yield by end-2026 with first OEM-qualified parts shipping in volume.',
        claim_basis: `Brief HYP STM-01 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Catania yield is the principal manufacturing precondition for the share-defence thesis.', impact_reasoning: 'Each yield milestone reduces unit cost vs Chinese benchmark.' },
      { component_name: 'CHINESE_SIC_IDM_PRESSURE', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No European OEM dual-sources SiC inverters with a Chinese IDM as primary supplier before 2027.',
        claim_basis: `Brief HYP STM-01 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A primary-supplier loss to a Chinese IDM is the principal falsification trigger.', impact_reasoning: 'Each lost OEM compounds the share-erosion path.' },
      { component_name: 'STM_SIC_ASP', role: 'principal', impact: 'amplifying', criticality: 'high',
        claim_text: 'STM SiC ASP holds above $300 per 200mm-equivalent through 2027.',
        claim_basis: `Brief HYP STM-01 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 300, threshold_unit: 'USD_per_200mm_equivalent', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'ASP discipline confirms premium positioning vs commodity Chinese supply.', impact_reasoning: 'Each $50 ASP loss erodes gross margin meaningfully.' },
      { component_name: 'EU_CHIPS_ACT_NON_CHINA_SOURCING', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'EU Chips Act funding remains in force; no reversal of non-China sourcing preferences.',
        claim_basis: `Brief HYP STM-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Policy backdrop is the structural support for European OEM lock-in.', impact_reasoning: 'A reversal would re-open the door to Chinese-IDM share gains.' },
    ],
  },

  // STM-02 ----------------------------------------------------------------
  {
    name: 'STM datacenter scales >$500M FY2026 → >$1B FY2027 (AWS-anchored)',
    strategy_context: `STM-AWS multi-year, multi-billion-dollar strategic collaboration announced Feb 2026 — power management, sensing, custom ICs for AWS data centres + edge. Datacenter target: >$500M 2026, >$1B 2027. GaN + SiC power for AI server PSUs + 48V architectures. Highest-margin growth pillar in portfolio.`,
    brief_description: 'Whether datacenter scales >$500M to >$1B as guided.',
    hypothesis_statement: `STM datacenter segment scales from >$500M FY2026 to >$1B FY2027, anchored by the AWS multi-year deal and a second hyperscaler win, becoming the highest-margin growth pillar in the portfolio. Source: ${BRIEF}, HYP STM-02.`,
    why_it_matters: 'Hyperscaler power-platform intelligence (NVIDIA + Microsoft + Google + Meta + Oracle) is the most commercially valuable input for STM datacenter strategy team.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP STM-02 (H1 · 1-2yr)`,
    decision_threshold: 'STM 2026 datacenter revenue confirmed >$500M (in-line with guidance); 2027 datacenter revenue >$1B as guided; At least one second hyperscaler engagement disclosed by end-2026; Datacenter segment gross margin in line with corporate average or above. (WNTBT, brief HYP STM-02.)',
    baseline_confidence: 0.70, current_confidence: 0.70,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (AWS engagement) AND Technology (GaN + SiC AI power) as live SIGNAL drivers.',
    trajectory_reasoning: `AWS deal disclosed Feb 2026; ramp profile improving. Source: ${BRIEF}.`,
    components: [
      { name: 'STM_AWS_MULTIYEAR_DEAL', description: 'STM-AWS multi-year, multi-billion strategic collaboration (Feb 2026). Market SIGNAL driver.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-02 (Market SIGNAL); Section 04 AWS card`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Disclosed Feb 2026; ramp profile begins H2 2026.', trajectory_reasoning: 'Multi-year revenue stream building.' },
      { name: 'STM_DATACENTER_REVENUE', description: 'STM datacenter segment revenue trajectory (target >$500M 2026, >$1B 2027).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-02 WNTBT bullets 1+2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Disclosed targets in management commentary.', trajectory_reasoning: 'Ramp profile underway.' },
      { name: 'GAN_SIC_AI_SERVER_POWER', description: 'GaN + SiC power devices for AI server PSU + 48V architectures. Technology SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP STM-02 (Technology SIGNAL); Section 04 GaN card`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Strong AI infra power-density tailwind.', trajectory_reasoning: 'Each hyperscaler architecture refresh creates demand.' },
      { name: 'HYPERSCALER_FUNNEL_BREADTH', description: 'STM hyperscaler engagement breadth (AWS + 2nd + 3rd anchor accounts).', component_type: 'ecosystem', vector: 'ecosystem', cross_industry: true,
        source_citation: `${BRIEF} HYP STM-02 WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'AWS first; pipeline builds.', trajectory_reasoning: 'Second hyperscaler win expected by end-2026.' },
    ],
    claims: [
      { component_name: 'STM_DATACENTER_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'STM 2026 datacenter revenue confirmed >$500M.',
        claim_basis: `Brief HYP STM-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 500, threshold_unit: 'USD_million', threshold_direction: 'crossing_validates',
        criticality_reasoning: '2026 milestone is the principal validation of the ramp profile.', impact_reasoning: 'Each disclosure quarter validates trajectory toward $1B.' },
      { component_name: 'STM_DATACENTER_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: '2027 datacenter revenue >$1B as guided.',
        claim_basis: `Brief HYP STM-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1000, threshold_unit: 'USD_million', threshold_direction: 'crossing_validates',
        criticality_reasoning: '$1B 2027 is the principal financial validation of the AWS-led platform thesis.', impact_reasoning: 'Doubling YoY would re-rate the equity narrative.' },
      { component_name: 'HYPERSCALER_FUNNEL_BREADTH', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'At least one second hyperscaler engagement disclosed by end-2026.',
        claim_basis: `Brief HYP STM-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1, threshold_unit: 'additional_hyperscaler_accounts', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Concentration risk on AWS is the main downside; second account de-risks the thesis.', impact_reasoning: 'Each additional account compounds revenue and de-risks customer concentration.' },
      { component_name: 'GAN_SIC_AI_SERVER_POWER', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Datacenter segment gross margin in line with corporate average or above.',
        claim_basis: `Brief HYP STM-02 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Margin profile defines whether datacenter is the highest-margin pillar.', impact_reasoning: 'Each margin point above corporate average lifts mix.' },
    ],
  },

  // STM-03 ----------------------------------------------------------------
  {
    name: 'STM gross margin recovers from Q1 2026 trough (33.8%) to ≥38% exit-2026',
    strategy_context: `Q1 2026 GM 33.8% — utilisation pressure + price competition + ~10% unused-capacity charge. Q2 2026 guide 34.8%. $300M cost-savings programme through manufacturing footprint optimisation announced 2025. Industrial channel destocking expected to abate through 2026.`,
    brief_description: 'Whether GM recovers to ≥38% exit-2026.',
    hypothesis_statement: `STM gross margin recovers from the Q1 2026 trough (33.8%) to ≥38% exit-2026, lifted by sequential utilisation improvement, the $300M cost-savings programme and a normalised industrial channel. Source: ${BRIEF}, HYP STM-03.`,
    why_it_matters: 'Quarterly margin + utilisation tracking with peer benchmarking is the FY2026 ambient scout — directly informs CFO + investor relations narrative.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP STM-03 (H1 · 1-2yr)`,
    decision_threshold: 'Q2 2026 GM in line with 34.8% guidance; Q4 2026 GM ≥ 38% confirming the recovery profile; $300M cost-savings programme reaches ≥75% run-rate by end-2026; Industrial book-to-bill above 1.0x by Q3 2026. (WNTBT, brief HYP STM-03.)',
    baseline_confidence: 0.62, current_confidence: 0.62,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Economics (GM trajectory) AND Market (industrial destock + auto design-in) as live SIGNAL drivers; outcome depends on H2 2026 trajectory.',
    trajectory_reasoning: `Q1 2026 trough; sequential improvement guided but execution-dependent. Source: ${BRIEF}.`,
    components: [
      { name: 'STM_GROSS_MARGIN_TRAJECTORY', description: 'STM gross margin trajectory + utilisation rate.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-03 (Economics SIGNAL); WNTBT bullets 1+2`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'Q1 2026 trough at 33.8%; recovery profile guided.', trajectory_reasoning: 'Q2 + Q3 2026 commentary will confirm trajectory.' },
      { name: 'STM_COST_SAVINGS_PROGRAMME', description: '$300M annual cost-savings programme through manufacturing footprint optimisation.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-03 WNTBT bullet 3; Section 04 restructuring card`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Programme announced 2025; realisation in flight.', trajectory_reasoning: 'Run-rate building through 2026.' },
      { name: 'INDUSTRIAL_INVENTORY_DESTOCKING', description: 'Industrial inventory destocking + automotive design-in normalisation. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP STM-03 (Market SIGNAL); WNTBT bullet 4`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'Destocking has stretched into 2026; book-to-bill below 1.0x.', trajectory_reasoning: 'Recovery expected by Q3 2026.' },
      { name: 'STM_AUTOMOTIVE_DESIGN_IN_PIPELINE', description: 'Stellar MCU + ToF / FlightSense automotive design-in pipeline.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP STM-03 (Technology driver); Section 04 Stellar MCU card`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Pipeline rebuilding into 2026-2027 model years.', trajectory_reasoning: 'Each design-in win compounds 2027+ revenue.' },
    ],
    claims: [
      { component_name: 'STM_GROSS_MARGIN_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Q2 2026 GM in line with 34.8% guidance.',
        claim_basis: `Brief HYP STM-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 34.5, threshold_unit: 'pct_GM', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Q2 GM is the first proof point on the recovery profile.', impact_reasoning: 'A miss would push the recovery profile out a quarter.' },
      { component_name: 'STM_GROSS_MARGIN_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Q4 2026 GM ≥ 38% confirming the recovery profile.',
        claim_basis: `Brief HYP STM-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 38, threshold_unit: 'pct_GM', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Exit-2026 GM is the principal financial confirmation.', impact_reasoning: 'Each percentage point above 38% accelerates the recovery narrative.' },
      { component_name: 'STM_COST_SAVINGS_PROGRAMME', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: '$300M cost-savings programme reaches ≥75% run-rate by end-2026.',
        claim_basis: `Brief HYP STM-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 225, threshold_unit: 'USD_million_annual_runrate', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cost programme is the controllable lever; market recovery is not.', impact_reasoning: 'Each $50M run-rate adds to GM exit-2026.' },
      { component_name: 'INDUSTRIAL_INVENTORY_DESTOCKING', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'Industrial book-to-bill above 1.0x by Q3 2026.',
        claim_basis: `Brief HYP STM-03 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1.0, threshold_unit: 'book_to_bill_ratio', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Industrial demand recovery is the principal external precondition.', impact_reasoning: 'Each quarter below 1.0x extends the volume drag.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
