// db/population/P5_TFMC_hypotheses.mjs
// Source: technipfmc_intelligence_brief__1_.html (May 2026 brief).
// Three hypotheses: TFMC-01 deepwater super-cycle peak, TFMC-02 ExxonMobil Guyana exclusivity, TFMC-03 iEPCI margin advantage.
// PG company: NOT yet present — script creates 'TechnipFMC plc'.
//
// Run:
//   node db/population/P5_TFMC_hypotheses.mjs           # dry-run
//   node db/population/P5_TFMC_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'technipfmc_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'TechnipFMC plc',
  sector: 'energy',
  notes: 'TechnipFMC plc — subsea production systems pure-play after Feb 2021 Technip Energies spin-off. NYSE:FTI. v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // TFMC-01 ----------------------------------------------------------------
  {
    name: 'TFMC subsea cycle peak 2026-2028 ($10B 2026 inbound, 17%+ EBITDA margin sustained)',
    strategy_context: `TechnipFMC reported $2.65B Q3 2025 revenue (+9% YoY); subsea $2.32B (88% of group). Total backlog $16.8B (subsea $16.0B); 2027+ phasing $8.6B. Q3 2025 inbound $2.4B. Management initiated 2026 guidance: $10B subsea inbound, $531M adjusted EBITDA ex-FX, $448M FCF. Q3 2025 EBITDA +36% YoY. iEPCI driving sequential growth across Africa, Americas, Australia.`,
    brief_description: 'Whether TFMC subsea cycle peaks 2026-2028 with $10B 2026 inbound + sustained 17%+ EBITDA margin.',
    hypothesis_statement: `TechnipFMC subsea inbound orders exceed $10B in 2026 and the deepwater super-cycle peaks 2026-2028, with TFMC sustaining Subsea EBITDA margin above 17% and growing 2027+ backlog above $10B by end-2026. Source: ${BRIEF}, HYP TFMC-01.`,
    why_it_matters: 'Deepwater capex cycle intelligence + IOC FID pipeline + iEPCI margin economics are the active scouting questions in TFMC strategy.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP TFMC-01 (H2 · 3-5yr)`,
    decision_threshold: [
      '2026 Subsea inbound orders reach or exceed $10B target;',
      '2027+ backlog ($8.6B at Q3 2025) grows above $10B by end-2026;',
      'Subsea operating margin holds above 17% through 2026-2027;',
      'Brent oil price sustained above $60/bbl through 2026-2027 supporting deepwater break-evens.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP TFMC-01.)',
    ].join(' '),
    baseline_confidence: 0.78,
    current_confidence: 0.78,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (Brent floor + deepwater break-even) AND Market (subsea inbound trajectory) as live SIGNAL drivers.',
    trajectory_reasoning: `Q3 2025 inbound $2.4B (~$9.6B annualised) approaching $10B 2026 target; multiple deepwater FIDs in flight. Source: ${BRIEF} Section 02.`,
    components: [
      {
        name: 'TFMC_SUBSEA_INBOUND_TRAJECTORY',
        description: 'TFMC subsea inbound orders trajectory. Market SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-01 (Market SIGNAL — Subsea inbound order trajectory + deepwater FIDs); WNTBT bullet 1`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q3 2025 $2.4B inbound; $10B 2026 target.',
        trajectory_reasoning: 'Multiple Petrobras + ExxonMobil + west Africa awards in flight.',
      },
      {
        name: 'BRENT_DEEPWATER_BREAKEVEN',
        description: 'Brent oil price floor + deepwater break-even economics. Economics SIGNAL driver.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP TFMC-01 (Economics SIGNAL — Brent floor + deepwater break-even); WNTBT bullet 4`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'Brent above $60/bbl throughout 2025; deepwater pencils at $45-55/bbl.',
        trajectory_reasoning: 'OPEC+ supply discipline + EM demand sustain Brent above break-even.',
      },
      {
        name: 'IEPCI_EXECUTION_EFFICIENCY',
        description: 'iEPCI execution efficiency vs traditional EPCI. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-01 (Technology — iEPCI execution efficiency vs traditional EPCI)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'iEPCI driving Q3 2025 sequential growth; standardisation + direct-model gains.',
        trajectory_reasoning: 'Each iEPCI repeat shortens cycle time and lifts margin.',
      },
      {
        name: 'OFFSHORE_LEASING_REGIMES',
        description: 'Offshore leasing regimes (US GOM, Brazil, Guyana, west Africa). Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP TFMC-01 (Policy — Offshore leasing regimes)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'Stable across major TFMC markets; no near-term policy shift.',
        trajectory_reasoning: 'Brazil pre-salt + Guyana access continue; US BOEM lease sales continuing.',
      },
    ],
    claims: [
      { component_name: 'TFMC_SUBSEA_INBOUND_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: '2026 Subsea inbound orders reach or exceed $10B target.',
        claim_basis: `Brief HYP TFMC-01 WNTBT condition 1; Q3 2025 management guidance. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'USD_billion',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Inbound order target is the principal observable confirmation of the cycle peak thesis.',
        impact_reasoning: 'Each $B of inbound orders compounds backlog into 2027+.' },
      { component_name: 'IEPCI_EXECUTION_EFFICIENCY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: '2027+ backlog grows above $10B by end-2026 (from $8.6B at Q3 2025).',
        claim_basis: `Brief HYP TFMC-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'USD_billion',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Long-tail backlog growth shows the cycle has multi-year visibility, not just one peak year.',
        impact_reasoning: 'Above $10B in out-years, TFMC has structural earnings visibility through 2028+.' },
      { component_name: 'BRENT_DEEPWATER_BREAKEVEN', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Brent oil price sustained above $60/bbl through 2026-2027 supporting deepwater break-evens.',
        claim_basis: `Brief HYP TFMC-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 60, threshold_unit: 'USD_per_bbl',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Without sustained oil price, deepwater FIDs slow and TFMC inbound conversion drops.',
        impact_reasoning: 'Each $5/bbl above breakeven raises FID pace.' },
      { component_name: 'OFFSHORE_LEASING_REGIMES', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A major offshore leasing regime change (US BOEM 5-year plan retraction, Brazil PSA reform, Guyana fiscal step-up) before end-2027.',
        claim_basis: `Brief HYP TFMC-01 (Policy driver, inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Policy shift in any of TFMC\'s top-3 markets would dampen inbound conversion.',
        impact_reasoning: 'Each market with regime uncertainty pauses operator FID decisions.' },
    ],
  },

  // TFMC-02 ----------------------------------------------------------------
  {
    name: 'TFMC retains 100% ExxonMobil Guyana subsea exclusivity through end-2027',
    strategy_context: `TFMC has won all 7 of ExxonMobil's Guyana subsea awards since the first contract in 2017 — including Hammerhead (Q3 2025, the 7th). Effective exclusivity on Guyana subsea production systems. SLB acquired OneSubsea (former TFMC JV partner) in 2025 and combined with the Subsea Integration Alliance (SIA) with Subsea7 creates a credible direct-model competitor.`,
    brief_description: 'Whether TFMC retains 100% ExxonMobil Guyana exclusivity through end-2027 against SLB OneSubsea breakthrough threat.',
    hypothesis_statement: `TechnipFMC retains 100% ExxonMobil Guyana exclusivity through end-2027 (8th + 9th + 10th awards), defending against SLB OneSubsea breakthrough until at least the post-Stabroek expansion phase. Source: ${BRIEF}, HYP TFMC-02.`,
    why_it_matters: 'ExxonMobil-side intelligence on selection criteria + competitor (SLB OneSubsea, Subsea7) breakthrough probability is what TFMC needs to defend the position.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP TFMC-02 (H1 · 1-3yr)`,
    decision_threshold: [
      '≥3 additional ExxonMobil Guyana subsea awards through end-2027 — all to TFMC;',
      'No SLB OneSubsea or Subsea7 award announced on Stabroek-block developments before end-2027;',
      'Guyana fiscal regime + ExxonMobil portfolio commitment to Stabroek hold through end-2027.',
      'All three conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP TFMC-02.)',
    ].join(' '),
    baseline_confidence: 0.64,
    current_confidence: 0.64,
    state: 'holding',
    trajectory: 'stable',
    state_reasoning: 'Brief flags Market (ExxonMobil Stabroek next-development award) AND Policy (Guyana fiscal stability) as live SIGNAL drivers.',
    trajectory_reasoning: `7/7 record sustained through Hammerhead award Q3 2025. SLB/OneSubsea integration emerging as new threat factor. Source: ${BRIEF} Section 06 S-01.`,
    components: [
      {
        name: 'EXXONMOBIL_GUYANA_AWARD_PIPELINE',
        description: 'ExxonMobil Stabroek next-development award assignment pipeline. Market SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-02 (Market SIGNAL — ExxonMobil Stabroek next-development award assignment); WNTBT bullet 1`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: '7/7 awards to date; Hammerhead = 7th. Pipeline of additional Stabroek developments ahead.',
        trajectory_reasoning: 'Each award compounds incumbent advantage.',
      },
      {
        name: 'SLB_ONESUBSEA_THREAT',
        description: 'SLB / OneSubsea / Subsea Integration Alliance direct-model threat. Economics driver per brief.',
        component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-02 (Economics — TFMC vs SLB OneSubsea / Subsea7 cost competitiveness); Section 06 S-01`,
        state: 'new', trajectory: 'volatile',
        state_reasoning: 'SLB acquired OneSubsea 2025; SIA with Subsea7 active. Combined direct-model threat to iEPCI emerging.',
        trajectory_reasoning: 'Threat trajectory rising; first ExxonMobil award to SLB-OneSubsea would be the breakthrough.',
      },
      {
        name: 'TFMC_STANDARDISED_CHRISTMAS_TREE',
        description: 'TFMC standardised Christmas tree + flexible pipe technology leadership. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-02 (Technology — Standardised Christmas tree + flexible pipe leadership)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'Standardisation enables short-cycle execution; key iEPCI advantage.',
        trajectory_reasoning: 'Stable; competitor parity slowly closing.',
      },
      {
        name: 'GUYANA_FISCAL_REGIME',
        description: 'Guyana fiscal regime stability + ExxonMobil portfolio commitment. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-02 (Policy SIGNAL — Guyana fiscal regime stability + ExxonMobil portfolio decisions); WNTBT bullet 3`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'Guyana PSC framework stable; ExxonMobil committed to multi-decade Stabroek development.',
        trajectory_reasoning: 'No near-term shift indicated.',
      },
    ],
    claims: [
      { component_name: 'EXXONMOBIL_GUYANA_AWARD_PIPELINE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: '≥3 additional ExxonMobil Guyana subsea awards through end-2027 — all to TFMC.',
        claim_basis: `Brief HYP TFMC-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 3, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Continued exclusivity is the principal confirmation of the customer-lock-in thesis.',
        impact_reasoning: 'Each TFMC win extends the streak; first SLB/OneSubsea win breaks it.' },
      { component_name: 'SLB_ONESUBSEA_THREAT', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No SLB OneSubsea or Subsea7 award announced on Stabroek-block developments before end-2027.',
        claim_basis: `Brief HYP TFMC-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A single competitor breakthrough would disprove the exclusivity thesis.',
        impact_reasoning: 'Each new entrant award erodes TFMC pricing power.' },
      { component_name: 'GUYANA_FISCAL_REGIME', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Guyana fiscal regime + ExxonMobil portfolio commitment to Stabroek hold through end-2027.',
        claim_basis: `Brief HYP TFMC-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Without Guyana stability, the entire pipeline is at risk regardless of TFMC competitive position.',
        impact_reasoning: 'Stability enables continued FID pace; instability halts all subsea awards.' },
      { component_name: 'TFMC_STANDARDISED_CHRISTMAS_TREE', role: 'enabling', impact: 'amplifying', criticality: 'medium',
        claim_text: 'Standardised Christmas tree + flexible pipe technology leadership maintained through 2027.',
        claim_basis: `Brief HYP TFMC-02 (Technology driver). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Technical leadership is the operational basis for short-cycle iEPCI execution.',
        impact_reasoning: 'Each generation of standardisation extends the moat.' },
    ],
  },

  // TFMC-03 ----------------------------------------------------------------
  {
    name: 'iEPCI captures >60% of TFMC subsea inbound by 2027 with sustained +200bps EBITDA margin advantage',
    strategy_context: `TFMC iEPCI integrated direct-model drove Q3 2025 sequential growth. Versus traditional EPCI bidding wars, iEPCI offers single-point accountability + faster cycle time + standardisation. Direct competitors emerging: SLB OneSubsea + Subsea Integration Alliance (Subsea7 + SLB) targeting same direct-model segment.`,
    brief_description: 'Whether iEPCI captures >60% of TFMC subsea inbound and demonstrates sustained 200bps EBITDA margin advantage by 2027.',
    hypothesis_statement: `iEPCI integrated-direct model captures more than 60% of TFMC subsea inbound orders by 2027 and demonstrates a sustained 200bps EBITDA margin advantage over traditional EPCI awards. Source: ${BRIEF}, HYP TFMC-03.`,
    why_it_matters: 'iEPCI vs traditional EPCI margin economics + direct-model competitor trajectory are the strategic questions TFMC commercial team is most focused on.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP TFMC-03 (H2 · 3-5yr)`,
    decision_threshold: [
      'iEPCI share of TFMC inbound orders exceeds 60% in 2026 or 2027;',
      'EBITDA margin on iEPCI awards demonstrates +200bps advantage vs traditional EPCI in disclosed comparisons;',
      'No major IOC reverts to traditional bid-out model after using iEPCI on a previous project;',
      'SLB / Subsea7 direct-model alternatives do not capture >20% of integrated subsea awards through 2027.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP TFMC-03.)',
    ].join(' '),
    baseline_confidence: 0.60,
    current_confidence: 0.60,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (iEPCI EBITDA margin spread) as live SIGNAL driver. Direct-model competitor SLB OneSubsea creates uncertainty.',
    trajectory_reasoning: `iEPCI driving sequential growth Q3 2025; standardisation building. Direct-model competitor threat emerging. Source: ${BRIEF} Section 06 S-01.`,
    components: [
      {
        name: 'IEPCI_EBITDA_MARGIN_SPREAD',
        description: 'iEPCI EBITDA margin spread vs traditional EPCI bid-up. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-03 (Economics SIGNAL — iEPCI EBITDA margin spread vs traditional EPCI); WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'iEPCI growing share; margin disclosure incomplete but Q3 2025 segment margin 17.3% (+10bps).',
        trajectory_reasoning: 'Standardisation + repeatability driving iEPCI margin lift.',
      },
      {
        name: 'IOC_NOC_AWARD_TYPE_PREFERENCE',
        description: 'IOC + NOC project award type preferences (iEPCI vs traditional EPCI). Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-03 (Market — IOC + NOC project award type preferences); WNTBT bullet 3`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'Customers using iEPCI tend to repeat (Petrobras, ExxonMobil). No major reversal observed.',
        trajectory_reasoning: 'Each successful iEPCI delivery reinforces preference.',
      },
      {
        name: 'STANDARDISATION_REPEATABILITY',
        description: 'Standardisation + repeatability of integrated solutions. Technology driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP TFMC-03 (Technology — Standardisation + repeatability of integrated solutions)`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'TFMC standardised tree + flexible pipe + integrated power umbilicals platform.',
        trajectory_reasoning: 'Each generation enables faster cycle and lower per-unit cost.',
      },
      {
        name: 'IRA_CBAM_OFFSHORE_ECONOMICS',
        description: 'IRA + EU CBAM secondary effects on offshore project economics. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP TFMC-03 (Policy — IRA + EU CBAM secondary effects on offshore project economics)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'IRA + CBAM neutral-to-positive for offshore (gas demand sustained).',
        trajectory_reasoning: 'No near-term policy shock to offshore economics.',
      },
    ],
    claims: [
      { component_name: 'IEPCI_EBITDA_MARGIN_SPREAD', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'EBITDA margin on iEPCI awards demonstrates +200bps advantage vs traditional EPCI in disclosed comparisons.',
        claim_basis: `Brief HYP TFMC-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 200, threshold_unit: 'basis_points',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Margin spread is the principal financial confirmation of the iEPCI thesis.',
        impact_reasoning: 'Each bp of advantage compounds across multi-year backlog.' },
      { component_name: 'IOC_NOC_AWARD_TYPE_PREFERENCE', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'iEPCI share of TFMC inbound orders exceeds 60% in 2026 or 2027.',
        claim_basis: `Brief HYP TFMC-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 60, threshold_unit: 'pct',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Volume share confirms market acceptance of the model.',
        impact_reasoning: 'Above 60%, iEPCI is the dominant rather than alternative model.' },
      { component_name: 'STANDARDISATION_REPEATABILITY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'No major IOC reverts to traditional bid-out model after using iEPCI on a previous project.',
        claim_basis: `Brief HYP TFMC-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'No reversal indicates structural acceptance, not temporary procurement preference.',
        impact_reasoning: 'Sticky customer behaviour locks in iEPCI demand.' },
      { component_name: 'IRA_CBAM_OFFSHORE_ECONOMICS', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'SLB / Subsea7 direct-model alternatives capture >20% of integrated subsea awards through 2027.',
        claim_basis: `Brief HYP TFMC-03 WNTBT condition 4 (inverse — competitor breakthrough). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Direct-model competitor breakthrough would erode the iEPCI advantage.',
        impact_reasoning: 'Each percentage point of competitor share at integrated level cuts TFMC pricing power.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
