// db/population/P5_TEN_hypotheses.mjs
// Source: technip_energies_intelligence_brief__1_.html (May 2026 brief).
// Three hypotheses: TEN-01 SnapLNG dominance, TEN-02 energy transition services as 2nd leg, TEN-03 TPS recovery via ethylene cycle.
// PG company: NOT yet present — script creates 'Technip Energies'.
//
// Run:
//   node db/population/P5_TEN_hypotheses.mjs           # dry-run
//   node db/population/P5_TEN_hypotheses.mjs --commit  # write to PG

import { runPopulation } from './_populator_v2.mjs';

const COMMIT = process.argv.includes('--commit');
const BRIEF = 'technip_energies_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'Technip Energies',
  sector: 'energy',
  notes: 'Technip Energies N.V. — French pure-play onshore process EPC + technology licensing. Spun off from TechnipFMC Feb 2021. CEO Arnaud Pieton. Listed Euronext Paris (TE). 105+ Mtpa LNG installed (~20% global). v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // TEN-01 ----------------------------------------------------------------
  {
    name: 'SnapLNG modular liquefaction dominance in next-cycle LNG (>30% post-2025 FOAK FIDs by 2030)',
    strategy_context: `Technip Energies has 105+ Mtpa installed liquefaction capacity (~20% of global LNG infrastructure per company disclosure). SnapLNG by T.EN is their flagship modular electrified 2.5 Mtpa solution. Commonwealth LNG (Louisiana, 6 trains, 9.5 Mtpa) is the FOAK reference. Marsa LNG (Oman) + Ruwais LNG (UAE) showcase electric-driven trains powered by renewable energy — among lowest-carbon-intensity LNG plants globally. CEO Pieton (Q3 2025 earnings) cites 900 Mtpa global liquefaction capacity needed by mid-decade.`,
    brief_description: 'Whether SnapLNG modular technology becomes the dominant new-build LNG technology globally by 2030.',
    hypothesis_statement: `SnapLNG modular liquefaction will become the dominant new-build LNG technology globally by 2030, capturing more than 30% of post-2025 FOAK FIDs and re-baselining T.EN as the reference licensor for the next LNG cycle. Source: ${BRIEF}, HYP TEN-01.`,
    why_it_matters: 'Modular LNG capex economics, SnapLNG vs incumbent stick-built references, and electric-driven liquefaction performance benchmarks are the active scouting categories. Engagement entry on next-cycle LNG technology selection at OEM + IOC + state-NOC level.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP TEN-01 (H2 · 3-5yr)`,
    decision_threshold: [
      'Commonwealth LNG receives full notice to proceed and reaches financial close before end-2026;',
      'At least 2 additional SnapLNG awards by end-2027 outside Commonwealth (validates the template);',
      'SnapLNG capex per Mtpa demonstrates ≥15% advantage vs equivalent stick-built reference at FOAK;',
      'Global LNG demand trajectory toward 900 Mtpa by mid-decade holds without sharp price collapse.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP TEN-01.)',
    ].join(' '),
    baseline_confidence: 0.74,
    current_confidence: 0.74,
    state: 'strengthening',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Market (LNG cycle demand) AND Technology (modular electric liquefaction) as live SIGNAL drivers. Pieton 2025 outlook explicitly bullish.',
    trajectory_reasoning: `Commonwealth LNG limited NTP achieved; Marsa + Ruwais executing; €15B+ backlog (3× annual revenue) provides multi-year visibility. Source: ${BRIEF} Section 02 + 04.`,
    components: [
      {
        name: 'COMMONWEALTH_LNG_FOAK_EXECUTION',
        description: 'Commonwealth LNG (US, Louisiana) — 6-train, 9.5 Mtpa SnapLNG FOAK reference. Limited NTP awarded; awaiting full FID + financial close. Critical reference deployment for next-cycle SnapLNG sales.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} Section 04 Initiatives "Commonwealth LNG" (SnapLNG FOAK); HYP TEN-01 WNTBT bullet 1`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Limited NTP achieved; full FID + financial close pending.',
        trajectory_reasoning: 'Project execution underway — directional indicator improving but not yet locked.',
      },
      {
        name: 'GLOBAL_LNG_DEMAND_900MTPA_TRAJECTORY',
        description: 'Global LNG liquefaction capacity demand trajectory toward 900 Mtpa by mid-decade. Market SIGNAL driver per brief — Pieton Q3 2025 framing.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP TEN-01 (Market driver SIGNAL — LNG cycle next-decade demand); Q3 2025 earnings call Pieton`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'IEA + BNEF + industry consensus on continued LNG demand growth through 2030; Asia-Pacific + European import infrastructure expansion.',
        trajectory_reasoning: 'Multiple LNG project FIDs taken 2024-2025; cycle building.',
      },
      {
        name: 'SNAPLNG_MODULAR_ELECTRIC_LIQUEFACTION',
        description: 'SnapLNG modular electric liquefaction technology — 2.5 Mtpa per train, scalable. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP TEN-01 (Technology driver SIGNAL — Modular electric liquefaction); Section 02 SnapLNG product disclosure`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'SnapLNG operational at Marsa LNG + Ruwais LNG; Commonwealth LNG FOAK at 6-train scale.',
        trajectory_reasoning: 'Technology maturity rising as Marsa + Ruwais commission; cost curve benefits expected at scale.',
      },
      {
        name: 'IMO_EU_CBAM_LNG_IMPORT_RULES',
        description: 'IMO GHG regulations + EU CBAM Phase 2 gas import rules. Policy driver per brief — currently NOT signalled but governs LNG carbon-intensity thresholds.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP TEN-01 (Policy driver — IMO GHG + EU CBAM gas import rules)`,
        state: 'holding', trajectory: 'stable',
        state_reasoning: 'IMO GHG strategy in force; EU CBAM Phase 2 expansion to gas under consultation.',
        trajectory_reasoning: 'Regulation tightening over time but no near-term shock.',
      },
    ],
    claims: [
      { component_name: 'COMMONWEALTH_LNG_FOAK_EXECUTION', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Commonwealth LNG receives full notice to proceed and reaches financial close before end-2026.',
        claim_basis: `Brief HYP TEN-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'FOAK financial close is the principal observable confirmation that SnapLNG is commercially viable at scale.',
        impact_reasoning: 'Full FID unlocks the reference plant template that drives the next-cycle SnapLNG sales pipeline.' },
      { component_name: 'SNAPLNG_MODULAR_ELECTRIC_LIQUEFACTION', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'At least 2 additional SnapLNG awards by end-2027 outside Commonwealth (validates the modular template).',
        claim_basis: `Brief HYP TEN-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Single FOAK is necessary but insufficient — repeat awards prove the template.',
        impact_reasoning: 'Each additional SnapLNG award compounds reference value and reinforces market dominance thesis.' },
      { component_name: 'GLOBAL_LNG_DEMAND_900MTPA_TRAJECTORY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Global LNG demand trajectory toward 900 Mtpa by mid-decade holds without sharp price collapse.',
        claim_basis: `Brief HYP TEN-01 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 900, threshold_unit: 'Mtpa',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Without sustained demand growth, capex cycle peaks and SnapLNG order pipeline thins.',
        impact_reasoning: 'Each Mtpa of new capacity demand adds to potential SnapLNG award pool.' },
      { component_name: 'IMO_EU_CBAM_LNG_IMPORT_RULES', role: 'external_threat', impact: 'amplifying', criticality: 'medium',
        claim_text: 'IMO GHG / EU CBAM rules tighten in a way that favours low-carbon-intensity LNG (electric-driven, CCS-enabled), advantaging SnapLNG vs higher-emission stick-built alternatives.',
        claim_basis: `Brief HYP TEN-01 (Policy driver). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Carbon-intensity discrimination in LNG import markets compounds the SnapLNG value proposition.',
        impact_reasoning: 'Each additional carbon-intensity standard in importing markets pushes new LNG awards toward modular electric.' },
    ],
  },

  // TEN-02 ----------------------------------------------------------------
  {
    name: 'Energy transition services (CCS + low-carbon hydrogen) as second-leg revenue engine by 2028',
    strategy_context: `T.EN's TPS division is positioned for the energy transition: Net Zero Teesside Power (UK, world's first commercial-scale gas-fired power station with CCS, 2 Mtpa CO₂ capture target) is the flagship CCS asset; BlueH₂ by T.EN delivers low-carbon hydrogen with up to 99% CO₂ capture rate; Q1 2025 blue ammonia award in US. Largest green ammonia project globally awarded India 2024. CEO Pieton notes (Q3 2025): "momentum is not a very recurring trend of awards" on green hydrogen — TPS backlog -16% from year start.`,
    brief_description: 'Whether energy transition services become T.EN\'s second revenue engine by 2028.',
    hypothesis_statement: `Energy transition services (CCS + low-carbon hydrogen) becomes T.EN's second-leg revenue engine by 2028, generating €2B+ annual TPS revenue with margin parity to LNG. Source: ${BRIEF}, HYP TEN-02.`,
    why_it_matters: 'Carbon capture engineering services at FOAK commercial scale and BlueH₂ economics vs stand-alone green H₂ are the active scouting questions. Competitive landscape: Sulzer, MHI, Aker Carbon Capture, Honeywell UOP.',
    horizon: 'H2',
    persona: 'strategy',
    time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP TEN-02 (H2 · 3-7yr)`,
    decision_threshold: [
      'Net Zero Teesside Power reaches full FID + EPC execution kickoff before end-2026;',
      'UK CCS CfD framework holds + Track-2 awards announced before mid-2026;',
      '≥2 commercial BlueH₂ by T.EN awards in addition to existing pipeline by end-2027;',
      'TPS revenue recovers above €2.0B annual run-rate in 2026 or 2027.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP TEN-02.)',
    ].join(' '),
    baseline_confidence: 0.58,
    current_confidence: 0.58,
    state: 'ambiguous',
    trajectory: 'volatile',
    state_reasoning: 'Brief flags Market (Net Zero Teesside execution) AND Policy (EU CBAM + UK CCS CfD) as live SIGNAL drivers. But Pieton acknowledges green H₂ pace softer than expected.',
    trajectory_reasoning: `TPS backlog -16% from year start signals near-term softness; Net Zero Teesside FID + UK Track-2 awards = inflection point. Source: ${BRIEF} Section 06 S-04.`,
    components: [
      {
        name: 'NET_ZERO_TEESSIDE_POWER_FID',
        description: 'Net Zero Teesside Power — world\'s first commercial-scale gas-fired power station with CCS, 2 Mtpa CO₂ capture. T.EN delivers Canopy carbon capture (Shell CANSOLV-licensed) and EPC. UK Track-1 anchor.',
        component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} Section 04 Initiatives "Net Zero Teesside Power" (CCS flagship); HYP TEN-02 WNTBT bullet 1`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Project structure in place; FID + EPC execution kickoff pending.',
        trajectory_reasoning: 'UK CCS CfD framework supports execution; political durability needed.',
      },
      {
        name: 'UK_CCS_CFD_TRACK_FRAMEWORK',
        description: 'UK CCS CfD framework + Track-1 / Track-2 cluster awards. Policy SIGNAL driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP TEN-02 (Policy driver SIGNAL — EU CBAM Phase 2 + UK CCS CfD continuation)`,
        state: 'holding', trajectory: 'improving',
        state_reasoning: 'Track-1 in execution; Track-2 announcements pending.',
        trajectory_reasoning: 'CCSA Delivery Plan Dec 2025 supports continued framework expansion.',
      },
      {
        name: 'BLUEH2_COMMERCIAL_PIPELINE',
        description: 'BlueH₂ by T.EN commercial pipeline. Q1 2025 blue ammonia award in US; existing pipeline. Technology driver per brief — currently NOT signalled but tracked.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} Section 02 BlueH₂ by T.EN; HYP TEN-02 WNTBT bullet 3`,
        state: 'new', trajectory: 'unknown',
        state_reasoning: 'Q1 2025 blue ammonia award executed; further pipeline pending.',
        trajectory_reasoning: 'Pace of additional commercial awards uncertain — Pieton notes momentum not recurring.',
      },
      {
        name: 'TPS_BACKLOG_RECOVERY',
        description: 'TPS revenue + backlog trajectory. Currently 2025 tracking lower half €1.8-2.0B guidance; backlog -16% from year start. Economics driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} Section 01 Snapshot (TPS 2025 tracking lower half); Q3 2025 earnings; HYP TEN-02 WNTBT bullet 4`,
        state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'TPS backlog declining; macro headwinds on low-carbon capex awards.',
        trajectory_reasoning: 'Recovery dependent on Net Zero Teesside FID + low-carbon capex restart.',
      },
    ],
    claims: [
      { component_name: 'NET_ZERO_TEESSIDE_POWER_FID', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Net Zero Teesside Power reaches full FID + EPC execution kickoff before end-2026.',
        claim_basis: `Brief HYP TEN-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Net Zero Teesside is the flagship reference for the entire energy-transition-services thesis.',
        impact_reasoning: 'FID + execution start triggers reference value for follow-on CCS awards globally.' },
      { component_name: 'UK_CCS_CFD_TRACK_FRAMEWORK', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'UK CCS CfD framework holds + Track-2 awards announced before mid-2026.',
        claim_basis: `Brief HYP TEN-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Policy continuity is the regulatory precondition for sustained T.EN CCS pipeline in UK.',
        impact_reasoning: 'Track-2 awards open second wave of T.EN-eligible pipeline.' },
      { component_name: 'BLUEH2_COMMERCIAL_PIPELINE', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'At least 2 additional commercial BlueH₂ by T.EN awards by end-2027.',
        claim_basis: `Brief HYP TEN-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'BlueH₂ wins prove the second-leg revenue thesis at scale.',
        impact_reasoning: 'Each commercial BlueH₂ award contributes to TPS revenue rebuild.' },
      { component_name: 'TPS_BACKLOG_RECOVERY', role: 'external_threat', impact: 'amplifying', criticality: 'critical',
        claim_text: 'TPS revenue recovers above €2.0B annual run-rate in 2026 or 2027.',
        claim_basis: `Brief HYP TEN-02 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2.0, threshold_unit: 'EUR_billion',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Without TPS revenue recovery, the second-leg thesis fails its own definition.',
        impact_reasoning: 'Each €100M of TPS revenue above the €1.8-2.0B baseline confirms the segment recovery.' },
    ],
  },

  // TEN-03 ----------------------------------------------------------------
  {
    name: 'TPS rebuilds backlog to ≥€2.0B by end-2026 driven by ethylene cycle re-baseline',
    strategy_context: `TPS 2025 trending lower half of €1.8-2.0B guidance; backlog -16% YTD. Pieton (Q3 2025) anticipates ethylene order intake in 2026, citing "early signs of recovery" with 3-4% per annum growth driver. AM&C acquisition positions T.EN for both traditional and future ethylene growth markets. The recovery is conditional on macro low-carbon capex restart.`,
    brief_description: 'Whether TPS rebuilds backlog above €2.0B by end-2026 via ethylene cycle re-baseline.',
    hypothesis_statement: `TPS rebuilds backlog to ≥€2.0B by end-2026 driven by ethylene cycle re-baseline + AM&C-enabled wins, restoring full €1.8-2.0B revenue range and resuming double-digit segment EBITDA growth. Source: ${BRIEF}, HYP TEN-03.`,
    why_it_matters: 'Ethylene cycle timing intelligence + AM&C synergies + circular feedstock economics are the inputs T.EN\'s TPS team needs to confirm the recovery thesis.',
    horizon: 'H1',
    persona: 'strategy',
    time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP TEN-03 (H1 · 1-2yr)`,
    decision_threshold: [
      'Ethylene order intake materialises Q1-Q2 2026 with at least 1 announced T.EN award;',
      'AM&C integration delivers traditional + future ethylene growth pipeline in 2026;',
      'TPS book-to-bill returns above 1.0 for two consecutive quarters by mid-2026;',
      'No major TPS customer pause in low-carbon capex (recycling, sustainable chemistry) extends beyond Q2 2026.',
      'All four conditions must hold for the hypothesis to confirm. (WNTBT, brief HYP TEN-03.)',
    ].join(' '),
    baseline_confidence: 0.62,
    current_confidence: 0.62,
    state: 'new',
    trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (ethylene capacity utilisation) AND Technology (low-emission furnace + AM&C) as live SIGNAL drivers. Recovery thesis intact but Q1-Q2 2026 awards pending.',
    trajectory_reasoning: `Pieton "early signs of recovery" framing; AM&C acquisition closed; ethylene cycle bottom-of-cycle indicators positive. Source: ${BRIEF} Section 06 S-01 + S-04.`,
    components: [
      {
        name: 'ETHYLENE_ORDER_INTAKE_2026',
        description: 'Ethylene order intake trajectory + 2026 awards. Economics SIGNAL driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP TEN-03 (Economics SIGNAL — Ethylene capacity utilisation + capex cycle); WNTBT bullet 1`,
        state: 'new', trajectory: 'improving',
        state_reasoning: 'Ethylene cycle bottoming; FID announcements expected Q1-Q2 2026 per Pieton.',
        trajectory_reasoning: 'Industry consensus on ethylene 3-4% CAGR rebuild; AM&C acquisition pre-positions T.EN.',
      },
      {
        name: 'TPS_BOOK_TO_BILL_RECOVERY',
        description: 'TPS book-to-bill ratio recovery. Market driver per brief.',
        component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP TEN-03 (Market — TPS backlog rebuild trajectory); WNTBT bullet 3`,
        state: 'weakening', trajectory: 'improving',
        state_reasoning: 'Currently <1.0; need to cross 1.0 for two consecutive quarters by mid-2026.',
        trajectory_reasoning: 'Ethylene + low-carbon capex restart is the gate; momentum building.',
      },
      {
        name: 'LOW_EMISSION_ETHYLENE_FURNACE_AM_C',
        description: 'Low-emission ethylene furnace technology + AM&C acquisition integration. Technology SIGNAL driver per brief.',
        component_type: 'tech', vector: 'tech', cross_industry: true,
        source_citation: `${BRIEF} HYP TEN-03 (Technology SIGNAL — Low-emission ethylene furnace + AM&C integration); WNTBT bullet 2`,
        state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'AM&C integration progressing; covers traditional + future ethylene growth markets.',
        trajectory_reasoning: 'Successful integration multiplies T.EN ethylene addressable market.',
      },
      {
        name: 'PETROCHEM_IRA_CBAM_CAPEX_TIMING',
        description: 'Petrochemical IRA + EU CBAM impact on capex timing. Policy driver per brief.',
        component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP TEN-03 (Policy — Petrochemical IRA / EU CBAM impact on capex timing); WNTBT bullet 4`,
        state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'IRA US + EU CBAM Phase 2 in flux — affects capex timing decisions across petrochemical operators. State ambiguous because direction depends on which policy lever lands first.',
        trajectory_reasoning: 'Policy clarity 2026 will reset capex pause vs restart. Volatile until Q1-Q2 2026.',
      },
    ],
    claims: [
      { component_name: 'ETHYLENE_ORDER_INTAKE_2026', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Ethylene order intake materialises Q1-Q2 2026 with at least 1 announced T.EN award.',
        claim_basis: `Brief HYP TEN-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 0, threshold_unit: 'count',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'First ethylene award is the principal observable confirmation that the cycle has restarted for T.EN specifically.',
        impact_reasoning: 'First win unlocks pipeline visibility for the rest of the cycle.' },
      { component_name: 'LOW_EMISSION_ETHYLENE_FURNACE_AM_C', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'AM&C integration delivers traditional + future ethylene growth pipeline in 2026.',
        claim_basis: `Brief HYP TEN-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'AM&C integration multiplies T.EN ethylene addressable market and competitive position.',
        impact_reasoning: 'Successful integration captures both traditional ethylene and circular/low-emission growth.' },
      { component_name: 'TPS_BOOK_TO_BILL_RECOVERY', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'TPS book-to-bill returns above 1.0 for two consecutive quarters by mid-2026.',
        claim_basis: `Brief HYP TEN-03 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1.0, threshold_unit: 'ratio',
        threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Two consecutive quarters above 1.0 establishes trajectory rather than one-off bounce.',
        impact_reasoning: 'Book-to-bill recovery is the operational confirmation of segment health.' },
      { component_name: 'PETROCHEM_IRA_CBAM_CAPEX_TIMING', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'A major TPS customer pause in low-carbon capex (recycling, sustainable chemistry) extends beyond Q2 2026.',
        claim_basis: `Brief HYP TEN-03 WNTBT condition 4 (inverse). Source: ${BRIEF}.`,
        threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Extended capex pause delays the recovery timeline beyond the H1 horizon window.',
        impact_reasoning: 'Each quarter of pause adds direct revenue softness to TPS.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
