// db/population/P5_vwg_extended.mjs
// Source: vwg_group_extended_brief.html (Oct 2025 / Q1 2026 brief).
// PG company: existing 'Volkswagen Group' row (id=11).
// 5 net-new VWG group-level hypotheses extending the original P2_VWG set
// (VW-01 IG Metall, VW-02 ID. SDV, VW-03 China share decline).
// All 5 use the HYP_VWG_* naming convention from the spec.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'vwg_group_extended_brief.html (Oct 2025 / Q1 2026)';

const company = {
  name: 'Volkswagen Group',
  sector: 'mobility',
  notes: 'Volkswagen Group AG — Wolfsburg-based group OEM. 5 extended VWG-level hypotheses covering software (Rivian/Xpeng/CARIAD), China defence (CMP+Xpeng CEA), German cost reset (€10B), PowerCo battery, and EU BEV demand recovery. Re-uses PG id=11.',
};

const initiatives = [
  // ── HYP_VWG_SW_001 — Software delivery risk ──────────────
  {
    name: 'VWG-SW-01 — Three-architecture software stack (CARIAD + Rivian + Xpeng) delivers by 2028',
    strategy_context: `CARIAD restructured Oct 2025 from developer to integrator. Three-architecture strategy: CARIAD Global + Rivian SDV West (RV Tech JV) + Xpeng SDV East. €12B invested in CARIAD since inception. Rivian JV tensions: Audi Q8 e-tron and A4 e-tron delayed 1+ year to mid-late 2028. Porsche K1 postponed indefinitely. ID.1 targeted as first Rivian-derived software production vehicle (late 2027).`,
    brief_description: 'Whether the three-architecture VWG software strategy delivers a unified Group Software Stack by 2028.',
    hypothesis_statement: `The three-architecture VWG software strategy (CARIAD Global + Rivian SDV West "RV Tech" + Xpeng SDV East) delivers a functional unified Group Software Stack across brands by 2028, with the VW ID.1 as the first production vehicle running Rivian-derived software (target: late 2027). Source: ${BRIEF}, HYP_VWG_SW_001.`,
    why_it_matters: 'Software-stack execution intelligence (CARIAD reorg + Rivian JV milestones + Xpeng CEA progress) is the highest-priority engagement input for VWG strategy team through 2028.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP_VWG_SW_001 (H2 · 3-5yr)`,
    decision_threshold: 'VW ID.1 first production with Rivian-derived software achieved late 2027; Audi Q8/A4 e-tron launch holds for mid-late 2028; CARIAD operates as integrator (not core developer) consistently through 2028; Porsche K1 timing publicly re-committed by end-2027 (no further indefinite postponement); No major Group Software Stack reset announced before end-2027. (WNTBT, brief HYP_VWG_SW_001.)',
    baseline_confidence: 0.45, current_confidence: 0.45,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Three concurrent architecture tracks with CARIAD restructuring + Rivian JV tensions + Xpeng dependency — outcome contested. Brief flags Technology + Partner as live SIGNAL drivers.',
    trajectory_reasoning: `Rivian-driven Audi delays 1+yr; Porsche K1 indefinite; CARIAD reorg ongoing — multi-quarter volatility. Source: ${BRIEF}.`,
    components: [
      { name: 'VWG_ZONAL_E3_ARCHITECTURE', description: 'VWG three-architecture electronic stack: CARIAD Global (E3 1.2) + Rivian RV Tech (West) + Xpeng CEA (East). Tech SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_SW_001 strategy_context; CARIAD Oct 2025 reorg`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Three-track integration in flight; freeze date not public.', trajectory_reasoning: 'CARIAD reorg + Rivian milestones unsettled.' },
      { name: 'VWG_OTA_PLATFORM_GROUP', description: 'Group-wide OTA software-update platform across brands (VW, Audi, Skoda, Porsche, SEAT/CUPRA).', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_SW_001 components list`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Brand-by-brand OTA exists; group-wide unification pending.', trajectory_reasoning: 'Roadmap underway with Rivian-derived stack.' },
      { name: 'VWG_ADAS_STACK_INTEGRATION', description: 'Group ADAS stack integration — Mobileye SuperVision/Surround for Audi/Porsche, Bosch / in-house for VW core. Multi-supplier risk.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_SW_001 components list; Mobileye brief HYP MBLY-01`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Multi-supplier integration risk persists.', trajectory_reasoning: 'Mobileye C-sample progressing but Audi 1+yr delay.' },
      { name: 'RIVIAN_RV_TECH_JV', description: 'Rivian RV Tech JV — software co-development partner for VWG; ID.1 first production target late 2027. Partner SIGNAL driver.', component_type: 'partner', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_SW_001 hypothesis_statement; Audi Q8/A4 e-tron delays`, state: 'new', trajectory: 'volatile',
        state_reasoning: 'JV tensions visible in Audi delays + Porsche K1 postponement.', trajectory_reasoning: 'Rivian milestones the principal swing factor.' },
    ],
    claims: [
      { component_name: 'RIVIAN_RV_TECH_JV', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VW ID.1 ships with Rivian-derived software in production by late 2027.',
        claim_basis: `Brief HYP_VWG_SW_001 hypothesis_statement + WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'ID.1 SOP with Rivian-derived software is the principal proof of three-architecture viability.', impact_reasoning: 'Each quarter of slip pushes the 2028 unified-stack target out.' },
      { component_name: 'VWG_ZONAL_E3_ARCHITECTURE', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'CARIAD operates as integrator (not core developer) consistently through 2028.',
        claim_basis: `Brief HYP_VWG_SW_001 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'CARIAD positioning is the principal organisational precondition for the three-architecture strategy.', impact_reasoning: 'A reversion to CARIAD-as-developer would invalidate the model.' },
      { component_name: 'VWG_OTA_PLATFORM_GROUP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'OTA platform reaches scale across brands by 2028 (no major reset announced before end-2027).',
        claim_basis: `Brief HYP_VWG_SW_001 WNTBT condition 5. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Group-wide OTA is the operational manifestation of unified stack.', impact_reasoning: 'Each brand without OTA at scale erodes the unified-stack thesis.' },
      { component_name: 'VWG_ADAS_STACK_INTEGRATION', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'Audi Q8 e-tron + A4 e-tron launch holds for mid-late 2028 (no further slippage beyond announced 1+yr delay).',
        claim_basis: `Brief HYP_VWG_SW_001 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Further Audi slippage signals deeper integration failure.', impact_reasoning: 'Each additional quarter of delay compounds Audi commercial damage.' },
    ],
  },

  // ── HYP_VWG_CHN_001 — China market defence ──────────────
  {
    name: 'VWG-CHN-01 — China unit sales >2.5M/yr + BEV share recovers >10% by 2027',
    strategy_context: `2024 China sales 2.93M (vs 4.23M peak 2019). BEV deliveries -34.5% YoY H1 2025. China operating margin 4.2% H1 2025. BYD at 34% China EV share. 130 brands competing. 2025 declared "rebuilding year" by VWG China boss. CMP platform (China-only, launch 2026). China Electronic Architecture (CEA) with Xpeng (deploy 2027). Hefei R&D centre operational.`,
    brief_description: 'Whether VWG stabilises China unit sales above 2.5M/year and recovers BEV share above 10% by 2027.',
    hypothesis_statement: `VWG stabilises China unit sales above 2.5M/year and recovers BEV market share above 10% by 2027 via CMP platform (China-only, launch 2026) and China Electronic Architecture (CEA) with Xpeng (deploy 2027). Source: ${BRIEF}, HYP_VWG_CHN_001.`,
    why_it_matters: 'China execution intelligence (CMP launch + Xpeng CEA + JV restructuring + BYD competitive response) is the principal commercial input for VWG China + group capital allocation decisions.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP_VWG_CHN_001 (H2 · 3-5yr)`,
    decision_threshold: 'China unit sales hold ≥2.5M/year through 2027; VWG BEV share in China recovers to ≥10% by FY2027; CMP platform launches 2026 on schedule with at least 2 nameplates; Xpeng CEA deploys 2027 in lead model; China operating margin holds ≥4% through 2026-2027 transition; no further BYD-driven share cliff (>5pp loss in any single year). (WNTBT, brief HYP_VWG_CHN_001.)',
    baseline_confidence: 0.40, current_confidence: 0.40,
    state: 'weakening', trajectory: 'deteriorating',
    state_reasoning: 'Brief flags Market (BEV deliveries -34.5%) AND Competition (BYD 34% share + 130 brands) as deteriorating SIGNAL drivers.',
    trajectory_reasoning: `2024 sales 2.93M vs 4.23M 2019 peak; multi-year decline; H1 2025 BEV cliff. Source: ${BRIEF}.`,
    components: [
      { name: 'CMP_PLATFORM_CHINA', description: 'China Modular Platform (CMP) — China-only, launch 2026. Local cost structure for mass-market competitiveness.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_CHN_001 strategy_context`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Pre-launch; first cars 2026.', trajectory_reasoning: 'Schedule appears intact per VWG China commentary.' },
      { name: 'XPENG_CEA_PARTNERSHIP', description: 'China Electronic Architecture (CEA) with Xpeng — deploy 2027. Tech-stack catch-up vs BYD/NIO/Geely.', component_type: 'partner', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_CHN_001 strategy_context`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Partnership active; CEA in development.', trajectory_reasoning: 'Xpeng track record on SDV strong.' },
      { name: 'CHINA_BEV_MARKET_SHARE_VWG', description: 'VWG BEV market share in China (target ≥10% by FY2027 from sub-7% trough).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_CHN_001 hypothesis_statement; H1 2025 -34.5%`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'Material share loss to BYD + domestic NEV brands.', trajectory_reasoning: 'Recovery profile dependent on CMP + CEA delivery.' },
      { name: 'BYD_DOMESTIC_CHINA_PRESSURE', description: 'BYD + 130 domestic NEV brands competitive pressure on legacy joint ventures.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_CHN_001 strategy_context (BYD 34%)`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'BYD 34% share continues compounding.', trajectory_reasoning: 'Additional Chinese OEM scaling (Geely, Chery).' },
    ],
    claims: [
      { component_name: 'CHINA_BEV_MARKET_SHARE_VWG', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VWG BEV share in China recovers to ≥10% by FY2027.',
        claim_basis: `Brief HYP_VWG_CHN_001 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'pct_china_BEV_share', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'BEV share recovery is the principal validation of CMP+CEA strategy.', impact_reasoning: 'Each percentage point of share-shift compounds.' },
      { component_name: 'CMP_PLATFORM_CHINA', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'CMP platform launches 2026 on schedule with at least 2 nameplates.',
        claim_basis: `Brief HYP_VWG_CHN_001 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2, threshold_unit: 'nameplates_2026', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'CMP is the cost-structure precondition for mass-market competitiveness.', impact_reasoning: 'Each nameplate compounds platform amortisation.' },
      { component_name: 'XPENG_CEA_PARTNERSHIP', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Xpeng CEA deploys 2027 in lead model.',
        claim_basis: `Brief HYP_VWG_CHN_001 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'CEA tech-stack catch-up validates Xpeng partnership thesis.', impact_reasoning: 'Each delay compounds vs domestic SDV pace.' },
      { component_name: 'BYD_DOMESTIC_CHINA_PRESSURE', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No further BYD-driven share cliff (>5pp loss in any single year).',
        claim_basis: `Brief HYP_VWG_CHN_001 WNTBT condition 6. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A further large-step share loss would falsify the recovery hypothesis.', impact_reasoning: 'Each pp lost compounds against the >10% target.' },
    ],
  },

  // ── HYP_VWG_COST_001 — German manufacturing reset ──────────
  {
    name: 'VWG-COST-01 — €10B cost-savings programme by 2027 with maintained ICE + transitioning BEV capacity',
    strategy_context: `€10B group cost-savings programme. Golf/Tiguan Wolfsburg backordered — weekend overtime running. Zwickau/Emden BEV production halted Oct 2025 citing demand slowdown. Workforce restructuring negotiated with IG Metall. MEB platform amortisation across group volume.`,
    brief_description: 'Whether VWG executes €10B cost savings while maintaining ICE capacity and transitioning BEV factories.',
    hypothesis_statement: `VWG executes €10B cost savings programme by 2027 while maintaining ICE capacity (Golf/Tiguan Wolfsburg backordered — weekend overtime running) and transitioning BEV factories (Zwickau/Emden production halted Oct 2025 citing demand slowdown). Source: ${BRIEF}, HYP_VWG_COST_001.`,
    why_it_matters: 'German plant utilisation + ICE/BEV split + IG Metall negotiation status are the key inputs for VWG cost trajectory and labour-relations risk.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP_VWG_COST_001 (H2 · 3-5yr)`,
    decision_threshold: '€10B cost-savings run-rate achieved by end-2027 (≥€7B by end-2026 as 70% milestone); ICE Wolfsburg / Tiguan Wolfsburg / Golf production sustained without further cuts; Zwickau and Emden BEV production restarts and reaches >70% prior utilisation by H2 2026; no major IG Metall industrial action forced in 2026; MEB platform amortisation per-vehicle cost falls ≥15% from 2024 base by 2027. (WNTBT, brief HYP_VWG_COST_001.)',
    baseline_confidence: 0.55, current_confidence: 0.55,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Economics (cost programme + MEB amortisation) AND Market (BEV demand slowdown + ICE backorder) as conflicting SIGNAL drivers.',
    trajectory_reasoning: `Cost programme in execution but BEV transition disrupted. Source: ${BRIEF}.`,
    components: [
      { name: 'GERMAN_PLANT_UTILISATION_VWG', description: 'German plant utilisation across Wolfsburg, Zwickau, Emden, Dresden — ICE/BEV split.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_COST_001 strategy_context`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'ICE plants over-utilised; BEV plants halted Oct 2025.', trajectory_reasoning: 'Outcome contested as 2026 BEV demand evolves.' },
      { name: 'VWG_10B_COST_PROGRAMME', description: '€10B group cost-savings programme by 2027.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_COST_001 hypothesis_statement`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Programme announced + restructuring negotiated.', trajectory_reasoning: 'Run-rate building through 2026-2027.' },
      { name: 'IG_METALL_RESTRUCTURING', description: 'IG Metall workforce restructuring agreement — preserves social peace under cost cuts.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP_VWG_COST_001 components list (workforce restructuring)`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Agreement reached; closure threat avoided.', trajectory_reasoning: 'Subject to 2026 wage-round renegotiation.' },
      { name: 'MEB_PLATFORM_AMORTISATION', description: 'MEB platform cost amortisation across group volume — Audi/Skoda/CUPRA/VW.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_COST_001 components list`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: 'Amortisation depends on BEV volume recovery.', trajectory_reasoning: 'Uncertain absent EU BEV demand recovery.' },
    ],
    claims: [
      { component_name: 'VWG_10B_COST_PROGRAMME', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: '€10B cost-savings run-rate achieved by end-2027 (≥€7B by end-2026 as 70% milestone).',
        claim_basis: `Brief HYP_VWG_COST_001 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 10, threshold_unit: 'EUR_billion_annual_runrate', threshold_direction: 'crossing_validates',
        criticality_reasoning: '€10B is the principal financial validation of the cost reset.', impact_reasoning: 'Each €B short of target erodes group margin restoration narrative.' },
      { component_name: 'GERMAN_PLANT_UTILISATION_VWG', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Zwickau and Emden BEV production restarts and reaches >70% prior utilisation by H2 2026.',
        claim_basis: `Brief HYP_VWG_COST_001 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 70, threshold_unit: 'pct_prior_utilisation', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'BEV plant restart is the principal operational validation.', impact_reasoning: 'Each quarter of halt compounds platform under-amortisation.' },
      { component_name: 'IG_METALL_RESTRUCTURING', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No major IG Metall industrial action forced in 2026.',
        claim_basis: `Brief HYP_VWG_COST_001 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Industrial action would compound production losses.', impact_reasoning: 'Each strike day costs >€100M in production.' },
      { component_name: 'MEB_PLATFORM_AMORTISATION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'MEB platform amortisation per-vehicle cost falls ≥15% from 2024 base by 2027.',
        claim_basis: `Brief HYP_VWG_COST_001 WNTBT condition 5. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 15, threshold_unit: 'pct_cost_reduction', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'MEB amortisation drives per-vehicle EV economics.', impact_reasoning: 'Each percentage point lifts BEV margin.' },
    ],
  },

  // ── HYP_VWG_BAT_001 — PowerCo battery independence ──────────
  {
    name: 'VWG-BAT-01 — PowerCo achieves competitive cell production from Salzgitter by 2028',
    strategy_context: `PowerCo (VWG battery subsidiary) targeting first cells from Salzgitter gigafactory 2025-26. Group target: >200 GWh capacity by early 2030s (Valencia + Salzgitter + Canada). Current ID-family supply: CATL/SK On (ID.4, ID.7). LFP/LMFP chemistry roadmap.`,
    brief_description: 'Whether PowerCo achieves competitive cell production from Salzgitter by 2028.',
    hypothesis_statement: `PowerCo (VWG battery subsidiary) achieves cell production at competitive cost from Salzgitter gigafactory by 2028, reducing dependency on CATL/Samsung SDI for ID-family models. Group targeting >200 GWh capacity by early 2030s (Valencia + Salzgitter + Canada). Source: ${BRIEF}, HYP_VWG_BAT_001.`,
    why_it_matters: 'PowerCo execution + LFP/LMFP chemistry decisions + group battery sourcing strategy are critical inputs for VWG cost competitiveness vs Chinese OEMs.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP_VWG_BAT_001 (H2 · 3-5yr)`,
    decision_threshold: 'PowerCo Salzgitter delivers first commercial cells by end-2026; cell cost-per-kWh within 10% of CATL benchmark by 2028; >200 GWh group capacity profile (Salzgitter + Valencia + Canada) committed and on schedule by 2028; ≥30% of ID-family cells supplied internally (PowerCo) by 2028. (WNTBT, brief HYP_VWG_BAT_001.)',
    baseline_confidence: 0.50, current_confidence: 0.50,
    state: 'new', trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (Salzgitter ramp + chemistry) AND Market (cost-per-kWh) as live SIGNAL drivers; outcome execution-dependent.',
    trajectory_reasoning: `Salzgitter ramp underway; Valencia + Canada committed. Source: ${BRIEF}.`,
    components: [
      { name: 'POWERCO_SALZGITTER_RAMP', description: 'PowerCo Salzgitter gigafactory cell production ramp (first cells 2025-26).', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_BAT_001 strategy_context`, state: 'new', trajectory: 'improving',
        state_reasoning: 'First cells targeted 2025-26; pre-commercial phase.', trajectory_reasoning: 'Construction + commissioning underway.' },
      { name: 'CELL_CHEMISTRY_LFP_LMFP_VWG', description: 'PowerCo cell chemistry roadmap — LFP for entry, LMFP for mid-range, NMC for premium.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_BAT_001 components list`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Multi-chemistry roadmap announced.', trajectory_reasoning: 'LFP/LMFP transition underway across industry.' },
      { name: 'BATTERY_SUPPLY_INDEPENDENCE_VWG', description: 'Group battery supply independence — share of PowerCo cells in ID-family vs CATL/SK On/Samsung SDI.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_BAT_001 hypothesis_statement`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Currently ~0% PowerCo; CATL + SK On dominate ID supply.', trajectory_reasoning: 'Path to ≥30% by 2028 dependent on Salzgitter ramp.' },
      { name: 'CELL_COST_PER_KWH_POWERCO', description: 'PowerCo cell cost-per-kWh vs CATL benchmark — competitive by 2028 thesis.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP_VWG_BAT_001 components list (cost/kWh vs market)`, state: 'ambiguous', trajectory: 'unknown',
        state_reasoning: 'Pre-production; cost not benchmarked.', trajectory_reasoning: 'Outcome dependent on yield + scale + raw materials.' },
    ],
    claims: [
      { component_name: 'POWERCO_SALZGITTER_RAMP', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'PowerCo Salzgitter delivers first commercial cells by end-2026.',
        claim_basis: `Brief HYP_VWG_BAT_001 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'First commercial cells are the principal manufacturing milestone.', impact_reasoning: 'Each quarter of delay compounds vs CATL/SK On dependency.' },
      { component_name: 'CELL_COST_PER_KWH_POWERCO', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'PowerCo cell cost-per-kWh within 10% of CATL benchmark by 2028.',
        claim_basis: `Brief HYP_VWG_BAT_001 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 110, threshold_unit: 'pct_of_CATL_benchmark', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Cost competitiveness is the principal commercial validation.', impact_reasoning: 'Each percentage point above CATL erodes competitive position.' },
      { component_name: 'BATTERY_SUPPLY_INDEPENDENCE_VWG', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: '≥30% of ID-family cells supplied internally (PowerCo) by 2028.',
        claim_basis: `Brief HYP_VWG_BAT_001 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 30, threshold_unit: 'pct_internal_supply', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Internal-supply share is the supply-chain risk reduction proof.', impact_reasoning: 'Each percentage point reduces CATL/SK On bargaining power.' },
      { component_name: 'CELL_CHEMISTRY_LFP_LMFP_VWG', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: '>200 GWh group capacity profile (Salzgitter + Valencia + Canada) committed and on schedule by 2028.',
        claim_basis: `Brief HYP_VWG_BAT_001 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 200, threshold_unit: 'GWh_capacity', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Multi-site capacity is the precondition for ID-family + future SDV scale.', impact_reasoning: 'Each delayed gigafactory compresses 2030 capacity.' },
    ],
  },

  // ── HYP_VWG_EV_001 — European BEV demand recovery ──────────
  {
    name: 'VWG-EV-01 — European BEV share in VWG sales >30% by 2027',
    strategy_context: `MEB factories halted Oct 2025 citing demand slowdown. ICE Golf/Tiguan backordered with weekend overtime. BYD European sales +250% Jan-Aug 2025. EU CO2 fleet regulations 2025 mandate + revised ZEV targets create regulatory pull for BEV demand. €10B+ MEB platform spend awaiting volume amortisation.`,
    brief_description: 'Whether European BEV share in VWG sales reaches >30% by 2027.',
    hypothesis_statement: `European BEV share in VWG European sales reaches >30% by 2027, validating the Zwickau and Emden factory investments and the €10B+ MEB platform spend. Trigger: EU CO2 fleet regulations 2025 mandate and revised ZEV targets. Source: ${BRIEF}, HYP_VWG_EV_001.`,
    why_it_matters: 'EU regulatory pull + MEB factory restart + ID family pricing vs BYD are the principal commercial inputs for VWG European EV strategy.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP_VWG_EV_001 (H2 · 3-5yr)`,
    decision_threshold: 'EU CO2 fleet regulations remain in force without softening through 2027; VWG European BEV share reaches ≥20% by FY2026 as interim milestone, ≥30% by FY2027; ID family pricing held within 5% of BYD Atto 3 / Dolphin / Han equivalents in EU; dealer EV readiness measured (training + servicing + charging) reaches ≥75% of network by FY2026; Zwickau + Emden return to >70% prior utilisation by H2 2026 (linked to VWG-COST-01). (WNTBT, brief HYP_VWG_EV_001.)',
    baseline_confidence: 0.48, current_confidence: 0.48,
    state: 'weakening', trajectory: 'deteriorating',
    state_reasoning: 'Brief flags Market (BEV slowdown + factory halt) AND Competition (BYD +250%) as deteriorating SIGNAL drivers; Policy (EU CO2) supportive.',
    trajectory_reasoning: `MEB factories halted Oct 2025; recovery profile uncertain. Source: ${BRIEF}.`,
    components: [
      { name: 'EU_CO2_FLEET_REG_2025', description: 'EU CO2 fleet regulations 2025 mandate + revised ZEV targets — regulatory pull for BEV demand.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP_VWG_EV_001 hypothesis_statement (trigger)`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Regulation in force; risk of softening flagged but not realised.', trajectory_reasoning: 'Stable absent industry lobbying success.' },
      { name: 'ID_FAMILY_PRICING_EU', description: 'ID family pricing in Europe vs BYD Atto 3 / Dolphin / Han equivalents.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_EV_001 components list`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'BYD price-aggressive; VWG ID pricing premium under pressure.', trajectory_reasoning: 'Pricing-power eroding without CMP-equivalent EU cost structure.' },
      { name: 'BYD_EUROPEAN_RESPONSE', description: 'BYD European competitive response — +250% Jan-Aug 2025; expanding model range + dealer network + plant.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_EV_001 strategy_context`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: 'BYD growth compounding off small base; reaching scale.', trajectory_reasoning: 'Hungary plant + dealer network expansion through 2026.' },
      { name: 'VWG_DEALER_EV_READINESS', description: 'VWG dealer network EV readiness (training + servicing + DC charging integration).', component_type: 'ecosystem', vector: 'ecosystem', cross_industry: false,
        source_citation: `${BRIEF} HYP_VWG_EV_001 components list`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Programme rolling out across European dealers.', trajectory_reasoning: 'Improvement profile through 2026.' },
    ],
    claims: [
      { component_name: 'ID_FAMILY_PRICING_EU', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'VWG European BEV share reaches ≥20% by FY2026 (interim) and ≥30% by FY2027.',
        claim_basis: `Brief HYP_VWG_EV_001 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 30, threshold_unit: 'pct_european_BEV_share', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'BEV share is the principal financial + strategic validation.', impact_reasoning: 'Each percentage point compounds Zwickau/Emden amortisation.' },
      { component_name: 'EU_CO2_FLEET_REG_2025', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'EU CO2 fleet regulations remain in force without softening through 2027.',
        claim_basis: `Brief HYP_VWG_EV_001 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Regulatory pull is the principal external precondition.', impact_reasoning: 'Each softening (e.g. delayed deadlines) erodes BEV demand.' },
      { component_name: 'BYD_EUROPEAN_RESPONSE', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'ID family pricing held within 5% of BYD Atto 3 / Dolphin / Han equivalents in EU.',
        claim_basis: `Brief HYP_VWG_EV_001 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 5, threshold_unit: 'pct_premium_vs_BYD', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Pricing parity is the principal competitive precondition.', impact_reasoning: 'Each 5pp premium loses share at margin.' },
      { component_name: 'VWG_DEALER_EV_READINESS', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Dealer EV readiness reaches ≥75% of network by FY2026.',
        claim_basis: `Brief HYP_VWG_EV_001 WNTBT condition 4. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 75, threshold_unit: 'pct_network_ready', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Dealer readiness is the operational precondition for EV sales.', impact_reasoning: 'Each percentage point of readiness compounds conversion.' },
    ],
  },
];

await runPopulation({ company, initiatives, dryRun: !COMMIT });
