// db/population/P5_WOLF_hypotheses.mjs
// Source: wolfspeed_intelligence_brief__1_.html (May 2026 brief).
// PG company: NOT yet present — script creates 'Wolfspeed'.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'wolfspeed_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'Wolfspeed',
  sector: 'both',
  notes: 'Wolfspeed Inc — sole pure-play SiC IDM. NYSE:WOLF. Emerged from Ch11 29 Sep 2025 (91-day prepack). Renesas equity holder + board designee. v2 catalogue first-cut hypotheses sourced from May 2026 brief. Sector both (auto + grid + AI).',
};

const initiatives = [
  // WOLF-01 ----------------------------------------------------------------
  {
    name: 'Mohawk Valley reaches commercial-scale utilisation by FY2027 with quarterly contribution >$150M',
    strategy_context: `Mohawk Valley $1.2B JV with NY State at SUNY Polytechnic Marcy site. Q1 2026 contribution $97M (+3.1% QoQ, ~2x YoY). Path to commercial-scale utilisation drives gross-margin recovery. Q1 2026 non-GAAP GM -26%; group operating loss $161M; underutilisation drag.`,
    brief_description: 'Whether Mohawk Valley reaches commercial-scale utilisation by FY2027.',
    hypothesis_statement: `Mohawk Valley reaches commercial-scale utilisation by FY2027 with quarterly contribution >$150M, lifting non-GAAP gross margin out of negative territory and confirming the 200mm capacity thesis. Source: ${BRIEF}, HYP WOLF-01.`,
    why_it_matters: 'Mohawk Valley quarterly tracking + cash-runway monitoring is the highest-priority scouting input for Wolfspeed strategy + capital-markets team.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP WOLF-01 (H1 · 1-2yr)`,
    decision_threshold: 'Mohawk Valley quarterly contribution > $150M by FY Q4 2027; Non-GAAP gross margin returns to ≥0% by FY Q4 2027; EV demand recovers from FY2026 trough; aerospace + AI compensate during weakness; No further capital structure adjustment required (cash burn manageable on $926M). (WNTBT, brief HYP WOLF-01.)',
    baseline_confidence: 0.50, current_confidence: 0.50,
    state: 'ambiguous', trajectory: 'volatile',
    state_reasoning: 'Brief flags Economics (Mohawk Valley revenue + utilisation) AND Market (EV recovery + AI/aerospace pull) as live SIGNAL drivers; outcome uncertain.',
    trajectory_reasoning: `Q1 2026 +3.1% QoQ but Q2 guide below consensus. Source: ${BRIEF}.`,
    components: [
      { name: 'MOHAWK_VALLEY_QUARTERLY_REVENUE', description: 'Mohawk Valley quarterly revenue contribution (target >$150M FY Q4 2027).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-01 WNTBT bullet 1; SIG-01`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q1 2026 $97M, +3.1% QoQ, ~2x YoY.', trajectory_reasoning: 'Path to $150M dependent on EV recovery + AI pull.' },
      { name: 'WOLF_NON_GAAP_GM_TRAJECTORY', description: 'Wolfspeed non-GAAP gross margin trajectory back to ≥0%.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-01 WNTBT bullet 2`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'Q1 2026 GM -26% non-GAAP.', trajectory_reasoning: 'Recovery dependent on utilisation + Q2 guide below consensus.' },
      { name: 'EV_DEMAND_RECOVERY_WOLF', description: 'EV demand recovery from FY2026 trough.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP WOLF-01 WNTBT bullet 3; SIG-02`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'Soft EV demand expected through fiscal 2026.', trajectory_reasoning: 'Recovery profile uncertain.' },
      { name: 'WOLF_CASH_RUNWAY', description: 'Wolfspeed $926M cash post-emergence; self-funded plan runway.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-01 WNTBT bullet 4; SIG-04`, state: 'holding', trajectory: 'stable',
        state_reasoning: '$926M cash post-emergence sufficient for self-funded plan.', trajectory_reasoning: 'Burn rate manageable absent revenue shortfall.' },
    ],
    claims: [
      { component_name: 'MOHAWK_VALLEY_QUARTERLY_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Mohawk Valley quarterly contribution > $150M by FY Q4 2027.',
        claim_basis: `Brief HYP WOLF-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 150, threshold_unit: 'USD_million_quarterly', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Mohawk Valley revenue is the principal financial validation.', impact_reasoning: 'Each $20M of additional MV revenue lifts GM materially.' },
      { component_name: 'WOLF_NON_GAAP_GM_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Non-GAAP gross margin returns to ≥0% by FY Q4 2027.',
        claim_basis: `Brief HYP WOLF-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 0, threshold_unit: 'pct_GM', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Non-negative GM is the equity-narrative inflection.', impact_reasoning: 'Crossing zero unlocks investor confidence.' },
      { component_name: 'EV_DEMAND_RECOVERY_WOLF', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'EV demand recovers from FY2026 trough; aerospace + AI compensate during weakness.',
        claim_basis: `Brief HYP WOLF-01 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'EV recovery is the principal market precondition.', impact_reasoning: 'Each quarter of EV softness compounds underutilisation.' },
      { component_name: 'WOLF_CASH_RUNWAY', role: 'external_threat', impact: 'dampening', criticality: 'critical',
        claim_text: 'No further capital structure adjustment required (cash burn manageable on $926M).',
        claim_basis: `Brief HYP WOLF-01 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A further restructuring would severely damage equity value and customer confidence.', impact_reasoning: 'Each quarter of cash burn compresses runway.' },
    ],
  },

  // WOLF-02 ----------------------------------------------------------------
  {
    name: 'Wolfspeed segment mix shifts to ≥40% non-EV (AI / aerospace / ESS) by FY2027',
    strategy_context: `CEO Robert Feurle leading diversification beyond EV. AI data center revenue +50% sequential. Aerospace + energy-storage applications building. Renesas demand pull (auto + industrial) anchored.`,
    brief_description: 'Whether non-EV segment mix reaches ≥40% by FY2027.',
    hypothesis_statement: `Wolfspeed segment mix shifts from EV-dominant to ≥40% non-EV (AI data center + aerospace + energy storage) by FY2027, offsetting EV softness and de-risking the demand profile. Source: ${BRIEF}, HYP WOLF-02.`,
    why_it_matters: 'Non-EV segment-mix tracking + design-win benchmarking is the highest-leverage scouting input.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2027,
    time_horizon_source: `${BRIEF} HYP WOLF-02 (H1 · 1-2yr)`,
    decision_threshold: 'AI data center revenue continues compounding ≥30% sequential through FY2026; Non-EV segment mix reaches ≥40% by FY2027; At least one named aerospace / defence design-win disclosed by end-2026; Renesas demand pull (auto + industrial) materialises in FY2027. (WNTBT, brief HYP WOLF-02.)',
    baseline_confidence: 0.55, current_confidence: 0.55,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Market (AI / aerospace / ESS pull) AND Economics (non-EV ASP / GM) as live SIGNAL drivers.',
    trajectory_reasoning: `+50% AI data center QoQ; pivot underway. Source: ${BRIEF}.`,
    components: [
      { name: 'WOLF_AI_DATA_CENTER_REVENUE', description: 'Wolfspeed AI data center segment revenue (+50% QoQ Q1 2026).', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP WOLF-02 WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: '+50% QoQ; compounding from low base.', trajectory_reasoning: 'Trajectory through FY2027.' },
      { name: 'WOLF_NON_EV_SEGMENT_MIX', description: 'Wolfspeed non-EV segment mix (target ≥40% by FY2027).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-02 WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Currently EV-dominant; mix shifting.', trajectory_reasoning: 'Path to 40% by FY2027 dependent on AI / aerospace traction.' },
      { name: 'AEROSPACE_DEFENCE_DESIGN_WIN', description: 'Aerospace / defence design-win disclosure (target ≥1 named by end-2026).', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-02 WNTBT bullet 3`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Pre-public-commitment phase.', trajectory_reasoning: 'Defence procurement preferences supportive.' },
      { name: 'RENESAS_DEMAND_PULL_WOLF', description: 'Renesas demand pull (auto + industrial) via equity-holder relationship.', component_type: 'partner', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-02 WNTBT bullet 4`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Renesas board designee Feb 2026 + CFIUS clearance.', trajectory_reasoning: 'Strategic relationship building.' },
    ],
    claims: [
      { component_name: 'WOLF_AI_DATA_CENTER_REVENUE', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'AI data center revenue continues compounding ≥30% sequential through FY2026.',
        claim_basis: `Brief HYP WOLF-02 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 30, threshold_unit: 'pct_QoQ_growth', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'AI data center compounding is the principal growth engine.', impact_reasoning: 'Each quarter of >30% growth compounds segment scale.' },
      { component_name: 'WOLF_NON_EV_SEGMENT_MIX', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Non-EV segment mix reaches ≥40% by FY2027.',
        claim_basis: `Brief HYP WOLF-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 40, threshold_unit: 'pct_segment_mix', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Mix shift confirms diversification thesis.', impact_reasoning: 'Each percentage point de-risks EV exposure.' },
      { component_name: 'AEROSPACE_DEFENCE_DESIGN_WIN', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'At least one named aerospace / defence design-win disclosed by end-2026.',
        claim_basis: `Brief HYP WOLF-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1, threshold_unit: 'named_aerospace_wins', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Aerospace / defence wins validate vertical pivot.', impact_reasoning: 'Each design-win compounds vertical credibility.' },
      { component_name: 'RENESAS_DEMAND_PULL_WOLF', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Renesas demand pull (auto + industrial) materialises in FY2027.',
        claim_basis: `Brief HYP WOLF-02 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Renesas relationship is the structural anchor demand.', impact_reasoning: 'Each quarter of demand pull validates the equity stake.' },
    ],
  },

  // WOLF-03 ----------------------------------------------------------------
  {
    name: 'Wolfspeed converts 300mm SiC milestone to commercial samples by FY2028 (long-term cost-curve advantage)',
    strategy_context: `Industry-first single 300mm SiC wafer Jan 2026. Path to commercial samples likely FY2028. Long-term cost-curve advantage vs incumbents stuck at 200mm. Self-funded plan must sustain 300mm capex without further capital raise.`,
    brief_description: 'Whether Wolfspeed reaches commercial 300mm samples by FY2028.',
    hypothesis_statement: `Wolfspeed converts the Jan 2026 single-300mm-wafer milestone into commercial sample shipments to lead customers by FY2028, securing a long-term cost-curve advantage no incumbent can match before 2029. Source: ${BRIEF}, HYP WOLF-03.`,
    why_it_matters: '300mm SiC roadmap tracking + competitive 300mm landscape is the highest-strategic-value scouting input for Wolfspeed long-term thesis.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2028,
    time_horizon_source: `${BRIEF} HYP WOLF-03 (H2 · 3-5yr)`,
    decision_threshold: 'Multi-die 300mm SiC samples to lead customers by FY2028; 300mm yield reaches commercial parity with 200mm by FY2029; No competitor (Infineon, STM, Coherent) ships commercial 300mm SiC before FY2029; Self-funded plan sustains 300mm capex without further capital raise. (WNTBT, brief HYP WOLF-03.)',
    baseline_confidence: 0.50, current_confidence: 0.50,
    state: 'new', trajectory: 'improving',
    state_reasoning: 'Brief flags Technology (300mm yield + reliability) AND Economics (300mm cost-per-die advantage) as live SIGNAL drivers.',
    trajectory_reasoning: `Single-wafer milestone Jan 2026 — early-stage. Source: ${BRIEF}.`,
    components: [
      { name: 'WOLF_300MM_SAMPLE_SHIPMENTS', description: 'Wolfspeed 300mm SiC commercial sample shipments to lead customers (target FY2028).', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-03 WNTBT bullet 1; SIG-03`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Single 300mm wafer Jan 2026; multi-die yielding next.', trajectory_reasoning: 'Path to FY2028 sample shipment dependent on yield improvements.' },
      { name: 'WOLF_300MM_YIELD_PARITY', description: '300mm SiC yield reaches commercial parity with 200mm by FY2029.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-03 WNTBT bullet 2`, state: 'new', trajectory: 'improving',
        state_reasoning: 'Single-wafer milestone; commercial yield far away.', trajectory_reasoning: 'Multi-year improvement profile.' },
      { name: 'COMPETITIVE_300MM_SIC_LANDSCAPE', description: 'Competitive 300mm SiC roadmaps from Infineon, STM, Coherent.', component_type: 'competitor', vector: 'competition', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-03 WNTBT bullet 3`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No competitor at single-wafer stage publicly disclosed.', trajectory_reasoning: 'Wolfspeed leadership intact through 2028.' },
      { name: 'WOLF_300MM_CAPEX_SELF_FUND', description: 'Wolfspeed self-funded plan sustains 300mm capex without further raise.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP WOLF-03 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: '$926M cash; capex slashed during restructuring.', trajectory_reasoning: 'Stable absent revenue shortfall.' },
    ],
    claims: [
      { component_name: 'WOLF_300MM_SAMPLE_SHIPMENTS', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Multi-die 300mm SiC samples to lead customers by FY2028.',
        claim_basis: `Brief HYP WOLF-03 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Sample shipments are the principal commercial validation of 300mm.', impact_reasoning: 'Each milestone validates the long-term cost-curve thesis.' },
      { component_name: 'WOLF_300MM_YIELD_PARITY', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: '300mm yield reaches commercial parity with 200mm by FY2029.',
        claim_basis: `Brief HYP WOLF-03 WNTBT condition 2. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Yield parity is the principal economic validation.', impact_reasoning: 'Each yield milestone reduces cost-per-die.' },
      { component_name: 'COMPETITIVE_300MM_SIC_LANDSCAPE', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'No competitor (Infineon, STM, Coherent) ships commercial 300mm SiC before FY2029.',
        claim_basis: `Brief HYP WOLF-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'A competitor shipping first would erase the cost-curve advantage.', impact_reasoning: 'Each competitor 300mm milestone compresses Wolfspeed lead time.' },
      { component_name: 'WOLF_300MM_CAPEX_SELF_FUND', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Self-funded plan sustains 300mm capex without further capital raise.',
        claim_basis: `Brief HYP WOLF-03 WNTBT condition 4. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Capital structure preservation is the precondition for execution.', impact_reasoning: 'Each quarter without raise validates self-funded model.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
