// db/population/P5_XOM_hypotheses.mjs
// Source: exxonmobil_intelligence_brief__1_.html (May 2026 brief).
// PG company: id=74 (ExxonMobil Corporation) — already exists.

import { runPopulation } from './_populator_v2.mjs';
const COMMIT = process.argv.includes('--commit');
const BRIEF = 'exxonmobil_intelligence_brief__1_.html (May 2026)';

const company = {
  name: 'ExxonMobil Corporation',
  sector: 'energy',
  notes: 'ExxonMobil Corporation — disciplined growth supermajor. NYSE:XOM. Permian + Guyana cash engine + paced low-carbon. v2 catalogue first-cut hypotheses sourced from May 2026 brief.',
};

const initiatives = [
  // XOM-01 ----------------------------------------------------------------
  {
    name: 'XOM 2030 Plan delivery: Permian 2.3M + Guyana 900k+ + cash flow +$35B',
    strategy_context: `XOM raised 2030 Plan in Dec 2025: +$25B earnings growth + $35B cash flow growth vs 2024 at constant price/margin, no capital increase. Q3 2025 record Permian (1.7M boe/d) + Guyana (>700k bpd post Yellowtail). Pioneer synergies $4B/yr (double initial estimates).`,
    brief_description: 'Whether XOM delivers the 2030 Plan: Permian 2.3M + Guyana 900k+ + $35B cash flow growth.',
    hypothesis_statement: `ExxonMobil delivers the 2030 Plan: Permian doubles to 2.3M boe/d, Guyana sustains 900k+ boe/d, and group-level cash flow grows $35B vs 2024 with capital flat — making XOM the highest-cash-flow IOC of the decade. Source: ${BRIEF}, HYP XOM-01.`,
    why_it_matters: 'Permian production scaling + Guyana FPSO sequencing + LNG project execution are the active scouting categories. Engagement entry on capex cycle peak intelligence.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP XOM-01 (H2 · 3-5yr)`,
    decision_threshold: 'Permian production reaches at least 2.0M boe/d by end-2027; Guyana sustained above 900k boe/d through 2027 with at least one additional FPSO online; Pioneer synergies sustain at $4B annual run-rate through 2026 + 2027; Brent above $60/bbl through 2027; no major fiscal regime shock in Permian or Guyana. (WNTBT, brief HYP XOM-01.)',
    baseline_confidence: 0.78, current_confidence: 0.78,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (Permian + Guyana FCF) AND Market (LNG offtake) as live SIGNAL drivers.',
    trajectory_reasoning: `Yellowtail early; Permian record Q3 2025; 2030 Plan raised. Source: ${BRIEF}.`,
    components: [
      { name: 'PERMIAN_PRODUCTION_2_3M_TRAJECTORY', description: 'Permian production trajectory toward 2.3M boe/d by 2030.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-01 (Economics SIGNAL); WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q3 2025 record 1.7M; on path to 2.0M by end-2027.', trajectory_reasoning: 'Pioneer synergy + tier-1 acreage consolidation.' },
      { name: 'GUYANA_900K_BPD_PLATEAU', description: 'Guyana installed capacity past 900k boe/d via Yellowtail + future developments.', component_type: 'ecosystem', vector: 'ecosystem', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-01 (Economics SIGNAL); WNTBT bullet 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Yellowtail (4th) operational; multiple future FPSOs in pipeline.', trajectory_reasoning: 'Stabroek block has multi-decade development runway.' },
      { name: 'GLOBAL_LNG_OFFTAKE_DEMAND', description: 'LNG offtake + global oil demand. Market SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: true,
        source_citation: `${BRIEF} HYP XOM-01 (Market SIGNAL — LNG offtake + global oil demand)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Golden Pass Train 1 first cargoes Q1 2026; Mozambique + PNG starts in 2030 Plan.', trajectory_reasoning: 'LNG demand sustained; multi-source supply.' },
      { name: 'US_PERMIAN_GUYANA_FISCAL_STABILITY', description: 'US Permian + Guyana fiscal regime stability. Policy driver.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP XOM-01 (Policy — US offshore + onshore leasing + Guyana fiscal stability); WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'Stable across Permian + Guyana; no near-term shock.', trajectory_reasoning: 'PSA framework stable in Guyana; US BOEM continuing.' },
    ],
    claims: [
      { component_name: 'PERMIAN_PRODUCTION_2_3M_TRAJECTORY', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Permian production reaches at least 2.0M boe/d by end-2027 (interim milestone toward 2.3M by 2030).',
        claim_basis: `Brief HYP XOM-01 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 2.0, threshold_unit: 'million_boe_per_day', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Permian is the principal cash-flow growth engine in the 2030 Plan.', impact_reasoning: 'Each 100k boe/d adds material cash flow at $60+ Brent.' },
      { component_name: 'GUYANA_900K_BPD_PLATEAU', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Guyana sustained above 900k boe/d through 2027 with at least one additional FPSO online.',
        claim_basis: `Brief HYP XOM-01 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 900, threshold_unit: 'thousand_boe_per_day', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Guyana is the second pillar of the cash-flow doubling thesis.', impact_reasoning: 'Each FPSO adds ~250k boe/d.' },
      { component_name: 'GLOBAL_LNG_OFFTAKE_DEMAND', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'LNG demand sustains; Golden Pass + Mozambique + PNG starts execute on plan.',
        claim_basis: `Brief HYP XOM-01 (Market SIGNAL). Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'LNG portfolio expansion is a key plank of the 2030 Plan.', impact_reasoning: 'Each LNG project at start adds material EBITDA.' },
      { component_name: 'US_PERMIAN_GUYANA_FISCAL_STABILITY', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'A major fiscal regime shock in either Permian or Guyana before end-2027.',
        claim_basis: `Brief HYP XOM-01 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Either market shock derails the 2030 Plan.', impact_reasoning: 'Fiscal step-up or leasing retraction halts FID conversion.' },
    ],
  },

  // XOM-02 ----------------------------------------------------------------
  {
    name: 'XOM low-carbon spend tracks <$20B (vs $30B headline) through 2030 — sustained pace control',
    strategy_context: `Late November 2025: XOM "paced" low-carbon spending citing disappointing customer demand + uncertain government policy. Texas hydrogen hub (Baytown) halted. Denbury CCS network (1,300+ miles) sequencing uncertain. ~$20B realised vs $30B planned likely outcome.`,
    brief_description: 'Whether realised low-carbon spending tracks below $20B vs the $30B headline plan.',
    hypothesis_statement: `Realised low-carbon spending tracks below $20B (vs the headline $30B 2025-2030 plan), driven by sustained pace-control after disappointing customer demand and uncertain US policy. Texas H2 hub stays halted; Denbury network deploys selectively rather than at full design capacity. Source: ${BRIEF}, HYP XOM-02.`,
    why_it_matters: 'Customer demand intelligence (who actually buys low-carbon services and at what price) is the most commercially valuable input for XOM pace-control decisions.',
    horizon: 'H2', persona: 'strategy', time_horizon_year: 2030,
    time_horizon_source: `${BRIEF} HYP XOM-02 (H2 · 4-6yr)`,
    decision_threshold: 'Texas hydrogen hub remains halted through end-2027 (no restart announcement); Annual low-carbon capex tracks below $5B/yr in both 2026 and 2027; Denbury CCS pipeline utilisation stays below 50% of design capacity through 2027; No US 45V / 45Q expansion before mid-2027 that would change customer-demand signal. (WNTBT, brief HYP XOM-02.)',
    baseline_confidence: 0.65, current_confidence: 0.65,
    state: 'strengthening', trajectory: 'deteriorating',
    state_reasoning: 'Brief flags Market (customer demand) AND Policy (IRA 45V/45Q durability) as live SIGNAL drivers. Hub halt is concrete pace evidence.',
    trajectory_reasoning: `Pace-control direction set Nov 2025; reversal would require strong customer demand + policy clarity. Source: ${BRIEF}.`,
    components: [
      { name: 'TEXAS_H2_HUB_HALT_STATUS', description: 'Texas hydrogen hub (Baytown) halt status. Market SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-02 WNTBT bullet 1; Section 04 Texas Hydrogen Hub`, state: 'broken', trajectory: 'deteriorating',
        state_reasoning: 'Halted Nov 2025 citing customer demand + policy. State="broken" reflects formal pause not decline.', trajectory_reasoning: 'No restart signal indicated.' },
      { name: 'XOM_LOW_CARBON_CAPEX_PACE', description: 'XOM annual low-carbon capex pace.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-02 WNTBT bullet 2`, state: 'weakening', trajectory: 'deteriorating',
        state_reasoning: '$30B headline likely revised lower; running well under straight-line amortisation.', trajectory_reasoning: 'Pace-control commentary explicit.' },
      { name: 'DENBURY_CCS_NETWORK_UTILISATION', description: 'Denbury CCS pipeline utilisation vs design.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-02 WNTBT bullet 3`, state: 'weakening', trajectory: 'volatile',
        state_reasoning: 'Customer offtake build-out pace unclear after H2 hub pause.', trajectory_reasoning: 'Denbury depends on industrial CCS customer demand.' },
      { name: 'IRA_45V_45Q_POLICY_DURABILITY', description: 'IRA 45V / 45Q policy durability + government continuity. Policy SIGNAL driver.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP XOM-02 (Policy SIGNAL — IRA 45V/45Q durability); WNTBT bullet 4`, state: 'ambiguous', trajectory: 'volatile',
        state_reasoning: '45V definition contested; 45Q stable but expansion uncertain.', trajectory_reasoning: 'Volatile pending Treasury / IRS final guidance.' },
    ],
    claims: [
      { component_name: 'TEXAS_H2_HUB_HALT_STATUS', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Texas hydrogen hub remains halted through end-2027 (no restart announcement).',
        claim_basis: `Brief HYP XOM-02 WNTBT condition 1. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Hub status is the principal observable confirmation of sustained pace control.', impact_reasoning: 'Restart would invalidate the pace-control thesis.' },
      { component_name: 'XOM_LOW_CARBON_CAPEX_PACE', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Annual low-carbon capex tracks below $5B/yr in both 2026 and 2027.',
        claim_basis: `Brief HYP XOM-02 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 5, threshold_unit: 'USD_billion_annual', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Capex run-rate is the financial confirmation of pace control.', impact_reasoning: 'Each year below $5B widens gap vs $30B headline.' },
      { component_name: 'DENBURY_CCS_NETWORK_UTILISATION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Denbury CCS pipeline utilisation stays below 50% of design capacity through 2027.',
        claim_basis: `Brief HYP XOM-02 WNTBT condition 3. Source: ${BRIEF}.`,
        threshold_op: 'lt', threshold_value_numeric: 50, threshold_unit: 'pct_design_capacity', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Utilisation reflects industrial CCS customer demand absence.', impact_reasoning: 'Low utilisation justifies continued Denbury monetisation pace.' },
      { component_name: 'IRA_45V_45Q_POLICY_DURABILITY', role: 'external_threat', impact: 'dampening', criticality: 'high',
        claim_text: 'A material US 45V or 45Q expansion before mid-2027 reverses the customer-demand softness.',
        claim_basis: `Brief HYP XOM-02 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Policy expansion would unlock customer demand and force XOM to reverse pace-control.', impact_reasoning: 'Each policy step-up changes the cost / subsidy stack for low-carbon offtake.' },
    ],
  },

  // XOM-03 ----------------------------------------------------------------
  {
    name: 'Pioneer integration completes 2026 with $4B+ synergy run-rate; Permian 1.95M+ boe/d 2026',
    strategy_context: `Pioneer synergies $4B/yr (double initial $2B estimate) declared Q3 2025. "Industry-leading performance" per management. Combined XOM tier-1 + Pioneer tier-1 acreage = consolidated dominant Permian position. Q3 2025 Permian record 1.7M boe/d.`,
    brief_description: 'Whether Pioneer integration completes by end-2026 with full $4B synergy run-rate.',
    hypothesis_statement: `Pioneer integration completes by end-2026 with $4B+ annual synergy run-rate fully realised, declared formally complete, and Permian production tracking 1.95M+ boe/d in 2026 — confirming XOM industry-leading Permian unit economics. Source: ${BRIEF}, HYP XOM-03.`,
    why_it_matters: 'Permian competitive intelligence — Chevron, ConocoPhillips, Diamondback, Coterra — is the most commercially valuable input as XOM consolidates dominance.',
    horizon: 'H1', persona: 'strategy', time_horizon_year: 2026,
    time_horizon_source: `${BRIEF} HYP XOM-03 (H1 · 1-2yr)`,
    decision_threshold: '$4B annual synergies sustained through 2026; Permian production exceeds 1.95M boe/d in 2026 calendar year; Pioneer integration declared formally complete in 2026 management commentary; No regulatory or environmental friction (water, methane, permitting) materially constrains 2026 production. (WNTBT, brief HYP XOM-03.)',
    baseline_confidence: 0.80, current_confidence: 0.80,
    state: 'strengthening', trajectory: 'improving',
    state_reasoning: 'Brief flags Economics (Pioneer synergy run-rate) AND Technology (combined drilling + completion + midstream optimisation) as live SIGNAL drivers.',
    trajectory_reasoning: `Synergies doubled vs initial estimate; Q3 2025 Permian record. Source: ${BRIEF}.`,
    components: [
      { name: 'PIONEER_SYNERGY_RUN_RATE_4B', description: 'Pioneer integration synergy run-rate. Economics SIGNAL driver.', component_type: 'market', vector: 'market', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-03 (Economics SIGNAL); WNTBT bullet 1`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q3 2025: $4B/yr declared, double initial.', trajectory_reasoning: 'Multi-quarter run-rate building.' },
      { name: 'PERMIAN_2026_PRODUCTION_TARGET', description: 'Permian production 2026 calendar year run-rate.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-03 WNTBT bullet 2`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Q3 2025 record 1.7M; trajectory consistent with 1.95M 2026.', trajectory_reasoning: 'Production runway clear from 2030 Plan.' },
      { name: 'COMBINED_DRILLING_COMPLETION_OPTIMISATION', description: 'Combined drilling + completion + midstream optimisation. Technology SIGNAL driver.', component_type: 'tech', vector: 'tech', cross_industry: false,
        source_citation: `${BRIEF} HYP XOM-03 (Technology SIGNAL)`, state: 'strengthening', trajectory: 'improving',
        state_reasoning: 'Pioneer + XOM combined know-how + acreage = best-in-class.', trajectory_reasoning: 'Each optimisation generation lifts well productivity.' },
      { name: 'US_PERMIAN_OPERATING_REGIME', description: 'US Permian operating regime stability (water, methane, permitting). Policy driver.', component_type: 'regulation', vector: 'regulation', cross_industry: true,
        source_citation: `${BRIEF} HYP XOM-03 WNTBT bullet 4`, state: 'holding', trajectory: 'stable',
        state_reasoning: 'No near-term shift; Texas + New Mexico stable.', trajectory_reasoning: 'Stable.' },
    ],
    claims: [
      { component_name: 'PIONEER_SYNERGY_RUN_RATE_4B', role: 'principal', impact: 'amplifying', criticality: 'critical',
        claim_text: '$4B annual synergies sustained through 2026 (run-rate disclosed in Q4 2025 / Q1 2026 results).',
        claim_basis: `Brief HYP XOM-03 WNTBT condition 1. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 4, threshold_unit: 'USD_billion_annual', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Synergy run-rate is the principal financial confirmation of integration completion.', impact_reasoning: 'Each $B of synergy flows directly to operating profit.' },
      { component_name: 'PERMIAN_2026_PRODUCTION_TARGET', role: 'enabling', impact: 'amplifying', criticality: 'critical',
        claim_text: 'Permian production exceeds 1.95M boe/d in 2026 calendar year.',
        claim_basis: `Brief HYP XOM-03 WNTBT condition 2. Source: ${BRIEF}.`,
        threshold_op: 'gt', threshold_value_numeric: 1.95, threshold_unit: 'million_boe_per_day', threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Production hitting 2026 milestone validates trajectory to 2.3M by 2030.', impact_reasoning: 'Each 50k boe/d above target compounds 2030 cash flow.' },
      { component_name: 'COMBINED_DRILLING_COMPLETION_OPTIMISATION', role: 'enabling', impact: 'amplifying', criticality: 'high',
        claim_text: 'Pioneer integration declared formally complete in 2026 management commentary.',
        claim_basis: `Brief HYP XOM-03 WNTBT condition 3. Source: ${BRIEF}.`, threshold_direction: 'crossing_validates',
        criticality_reasoning: 'Formal completion is the boardroom-level confirmation.', impact_reasoning: 'Removes integration overhang from forward financial story.' },
      { component_name: 'US_PERMIAN_OPERATING_REGIME', role: 'external_threat', impact: 'dampening', criticality: 'medium',
        claim_text: 'Regulatory or environmental friction (water disposal, methane, permitting) materially constrains 2026 Permian production.',
        claim_basis: `Brief HYP XOM-03 WNTBT condition 4 (inverse). Source: ${BRIEF}.`, threshold_direction: 'crossing_falsifies',
        criticality_reasoning: 'Regulatory shock would slow 2026 production trajectory.', impact_reasoning: 'Each regulatory friction event delays well completions.' },
    ],
  },
];
await runPopulation({ company, initiatives, dryRun: !COMMIT });
