// db/population/shell_phase1.mjs
// Phase 1 Shell catalogue population per /docs/INITIATIVE_METHODOLOGY.md
// Sources: shell_intelligence_brief__4_.html (Section 02 Strategy, Section 04 Initiatives,
// Section 06 Weak Signals, Section HYP Hypothesis Register).
//
// Run:
//   node db/population/shell_phase1.mjs           # dry-run
//   node db/population/shell_phase1.mjs --commit  # insert to PG
//
// All draft_status set per step-10 gate result; nothing enters live signal pipeline.

import { insertAll, reportCatalogueOverlap } from './_runner.mjs';

const COMPANY = 'Shell';

// ===========================================================================
// ENTITIES
// ===========================================================================
// Naming: SCREAMING_SNAKE_CASE, descriptive, sector-anchored for cross-company reuse.

const entities = [
  // --- LNG ---
  {
    id: 'GLOBAL_LNG_DEMAND_TRAJECTORY',
    name: 'Global LNG demand structure and trajectory',
    type: 'market',
    current_state: 'European demand recovered post-Russian-pipeline; Asia-Pacific LNG demand ~270 Mt/yr and growing per IEA; global LNG trade ~400 Mt/yr 2025',
    threshold: 'Global LNG demand maintains >550 Mt/yr trajectory through 2028 with Europe sustaining >150 Mt/yr import dependency',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 02 names LNG as Shell strategic moat (~40% group earnings already). European import infrastructure build expanding capacity locks in offtake. No demand-peak signal yet within window.',
    sources: 'Shell brief Section 02 (Strategy — LNG core engine); Shell brief HYP SH-01',
  },
  {
    id: 'EU_LNG_IMPORT_INFRASTRUCTURE',
    name: 'EU LNG import terminal and FSRU capacity',
    type: 'ecosystem',
    current_state: 'EU LNG import capacity ~190 bcm/yr 2025, expanding through new German FSRU and Mediterranean terminals',
    threshold: '>200 bcm/yr operational by end-2026',
    state: 'holding',
    baseline_state: 'holding',
    note: 'WNTBT bullet from SH-01: capacity build pipeline currently on track. Critical to Shell European re-export trading position.',
    sources: 'Shell brief HYP SH-01 WNTBT',
  },
  {
    id: 'LONG_TERM_LNG_OFFTAKE_AGREEMENTS',
    name: 'Shell long-term LNG supply agreements (10+ year duration)',
    type: 'market',
    current_state: 'Shell signing new 10+ year supply agreements; pipeline of 2-3 in negotiation per Q4 2025 commentary',
    threshold: '>=2 long-term LNG supply agreements (>=10 years) signed by Shell by end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'WNTBT from SH-01. Contracted volumes are EBITDA stabiliser against spot volatility.',
    sources: 'Shell brief HYP SH-01 WNTBT; brief Section 02 LNG strategy',
  },
  {
    id: 'GAS_PRICE_FLOOR_TTF',
    name: 'European TTF gas price floor',
    type: 'market',
    current_state: 'TTF ~$8-12/MMBtu through 2025; spot pricing above floor with material headroom',
    threshold: 'Sustained TTF gas price >$6/MMBtu through end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'WNTBT from SH-01. Below floor LNG netback margin collapses; currently well clear.',
    sources: 'Shell brief HYP SH-01 WNTBT',
  },
  {
    id: 'EU_GAS_REGULATORY_FRAMEWORK',
    name: 'EU gas import and re-export regulatory framework',
    type: 'regulation',
    current_state: 'EU gas market regulation stable; no current restrictions on LNG re-export from EU ports',
    threshold: 'No EU regulatory disruption to LNG re-export operations from EU ports through end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'WNTBT from SH-01. EU gas import regulatory framework is the Policy SIGNAL driver flagged in SH-01. Political risk if energy security politics shift toward import quotas or re-export controls.',
    sources: 'Shell brief HYP SH-01 WNTBT + system drivers',
  },
  {
    id: 'ASIA_PACIFIC_LNG_DEMAND',
    name: 'Asia-Pacific LNG demand (China, India, SEA)',
    type: 'market',
    current_state: 'Asia-Pacific LNG demand ~270 Mt/yr 2025; growth continuing with China, India, SEA economies',
    threshold: 'Asia-Pacific LNG demand sustains >290 Mt/yr through 2028',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 02 names Australia, Qatar, Nigeria, US Gulf supply portfolio targeting AP demand. Demand-side anchor for non-European portion of Shell LNG book.',
    sources: 'Shell brief Section 02 (LNG portfolio scope)',
  },
  {
    id: 'NORTH_AMERICAN_LNG_OVERSUPPLY',
    name: 'US LNG export capacity oversupply trajectory',
    type: 'market',
    current_state: 'US LNG export capacity expanding; >100 Mt/yr operational by 2026; multiple mega-projects in construction or pre-FID',
    threshold: 'US LNG net export additions <30 Mt/yr through 2027 (avoiding flood)',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'If multiple US mega-projects complete simultaneously, supply outpaces demand and gas price floor breaks. Real threat to LNG netback margin but Shell long-term contracts insulate ~50% of book.',
    sources: 'Shell brief Section 02 (peer landscape)',
  },

  // --- CCUS ---
  {
    id: 'INDUSTRIAL_CCUS_CAPTURE_TECH',
    name: 'Industrial CCUS capture chemistry and commercial scale',
    type: 'tech',
    current_state: 'Quest (Alberta) operational since 2015, 8M+ t CO2 captured. Northern Lights operational 2024 as world-first commercial cross-border service. Capture chemistry mature at SMR/refinery scale; less proven on cement/steel.',
    threshold: 'CCUS capture cost <$80/tCO2 at industrial scale (>1 Mt/yr) demonstrated commercially by 2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names Quest as flagship and Northern Lights as JV with Equinor + TotalEnergies. SH-02 names capture chemistry TRL as Technology SIGNAL driver.',
    sources: 'Shell brief Section 04 (Quest, Northern Lights); brief HYP SH-02 system drivers + WNTBT',
  },
  {
    id: 'INDUSTRIAL_DECARBONISATION_SERVICES_DEMAND',
    name: 'Third-party industrial decarbonisation services demand',
    type: 'market',
    current_state: '<3 Tier-1 industrial customers signed commercial CCUS service contracts globally; pipeline emerging via UK and Norway clusters',
    threshold: '>=1 third-party industrial commercial CCUS service contract signed with Shell by end-2026',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'WNTBT from SH-02 + S-04 (Carbon Capture as a Service signal). Shell packaging Quest learnings into commercial offering. Pipeline slow to convert.',
    sources: 'Shell brief Section 04 (Quest commercial template); brief Section 06 S-04; brief HYP SH-02 WNTBT',
  },
  {
    id: 'US_45Q_TAX_CREDIT',
    name: 'US 45Q CCUS tax credit regime',
    type: 'regulation',
    current_state: '45Q regime in force at $85/tCO2 sequestered (post-IRA); subject to 2026 budget reconciliation',
    threshold: '45Q tax credit survives 2026 budget reconciliation intact (or replaced by economically equivalent mechanism)',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'WNTBT from SH-02. Underpins Quest economics and Shell US CCUS pipeline. Political risk in 2026 reconciliation cycle.',
    sources: 'Shell brief HYP SH-02 WNTBT + system drivers',
  },
  {
    id: 'NORTH_SEA_CO2_STORAGE_CAPACITY',
    name: 'North Sea CO2 storage capacity (Northern Lights and adjacent)',
    type: 'ecosystem',
    current_state: 'Northern Lights Phase 1 operational ~1.5 Mt/yr; Phase 2 expansion to 5 Mt/yr planned; broader North Sea storage potential >100 Mt/yr',
    threshold: 'North Sea operational injection capacity >5 Mt/yr by end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names Northern Lights as cross-border first. Storage capacity is the structural bottleneck for European industrial CCUS scaling.',
    sources: 'Shell brief Section 04 (Northern Lights JV)',
  },
  {
    id: 'CCUS_CAPEX_DEPLOYMENT',
    name: 'IOC CCUS cumulative capex deployment',
    type: 'market',
    current_state: 'Shell cumulative CCUS capex ~$700m through 2024; pipeline of $2bn+ disclosed but not committed',
    threshold: 'Shell deploys >$1.5bn cumulative CCUS capex by end-2027',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'WNTBT from SH-02. Internal capital commitment level signals Shell willingness to scale CCUS as service business. Currently lagging stated ambition.',
    sources: 'Shell brief HYP SH-02 WNTBT',
  },

  // --- EV charging / retail energy ---
  {
    id: 'EV_PUBLIC_CHARGING_DEMAND',
    name: 'Public EV charging demand and utilisation rates',
    type: 'market',
    current_state: 'European public DC fast-charging utilisation 8-15% average; growing with BEV penetration; revenue per session improving',
    threshold: 'Average public DC fast-charger utilisation >25% across Shell Recharge sites by end-2028',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names Shell Recharge as retail energy transformation play. Utilisation determines unit economics; currently below break-even threshold for many sites.',
    sources: 'Shell brief Section 04 (Shell Recharge — EV Network)',
  },
  {
    id: 'BEV_FLEET_PENETRATION_EUROPE',
    name: 'European BEV passenger fleet penetration',
    type: 'market',
    current_state: 'BEV new-sale share ~22% Europe 2025; total fleet ~12% BEV',
    threshold: 'BEV fleet share >20% in Shell Recharge primary markets (UK, NL, DE) by end-2028',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Demand-side driver for Shell Recharge unit economics. EU 2035 ICE phase-out underpins trajectory.',
    sources: 'Shell brief Section 02 (Power transition — Shell Recharge)',
  },
  {
    id: 'EV_CHARGING_HARDWARE_CAPEX',
    name: 'DC fast-charger hardware and installation capex',
    type: 'tech',
    current_state: 'DC fast-charger installed capex ~€80-150k per stall depending on power and grid connection',
    threshold: 'DC fast-charger installed capex <€80k per stall at >=150kW by end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Capex trajectory determines whether Shell Recharge can hit EBIT-positive economics at moderate utilisation. Hardware cost-down from manufacturers like ABB, Tritium, Kempower.',
    sources: 'Shell brief Section 04 (Shell Recharge target 500k+ charge points)',
  },

  // --- Brazil deepwater ---
  {
    id: 'BRAZIL_DEEPWATER_REGULATORY_REGIME',
    name: 'Brazilian regulatory regime for deepwater pre-salt operations',
    type: 'regulation',
    current_state: 'ANP licensing stable; pre-salt royalty regime intact; no announced changes to local content or fiscal regime through current concession period',
    threshold: 'No material adverse change in Brazilian fiscal/royalty regime for pre-salt operations through end-2030',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brazilian deepwater fiscal stability underpins Shell\'s Lula-area economics. Political risk varies with electoral cycles but pre-salt has been bipartisan.',
    sources: 'Shell brief Section 04 (Lula Field)',
  },
  {
    id: 'DEEPWATER_PRODUCTION_ECONOMICS',
    name: 'Deepwater pre-salt unit economics ($/bbl)',
    type: 'tech',
    current_state: 'Pre-salt break-even $25-35/bbl; carbon intensity 8-12 kg CO2/bbl (~half conventional onshore average)',
    threshold: 'Lula-area unit economics maintain <$40/bbl break-even through 2030',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names Lula as low-carbon-intensity-per-barrel cash flow pillar. Production sustainability depends on continued reservoir performance and operational efficiency.',
    sources: 'Shell brief Section 04 (Lula Field, 25% stake, low CI/bbl)',
  },
  {
    id: 'OIL_PRICE_BRENT',
    name: 'Brent crude oil benchmark price',
    type: 'market',
    current_state: '2025 average ~$73/bbl; 2026 forward curve $65-78/bbl',
    threshold: 'Brent sustains >$60/bbl through end-2028',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Underpins economics of all Shell upstream initiatives including Brazil, Permian, GoM. Brief outlook scenarios use $50-100/bbl range.',
    sources: 'Shell brief Section 05 (5-Year Outlook scenarios)',
  },

  // --- SAF / biofuels ---
  {
    id: 'EU_SAF_MANDATE',
    name: 'EU SAF blending mandate (ReFuelEU Aviation)',
    type: 'regulation',
    current_state: 'ReFuelEU Aviation in force; 2% SAF blending requirement 2025, scaling to 6% 2030, 20% 2035, 70% 2050',
    threshold: 'EU SAF mandate trajectory maintained at >=6% blending by 2030 without dilution',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names SAF target of 10% of aviation fuel portfolio by 2030, anchored to mandate. Mandate dilution would collapse demand-side economics.',
    sources: 'Shell brief Section 04 (SAF developing initiative); brief HYP SH-03 system drivers',
  },
  {
    id: 'SAF_OFFTAKE_AIRLINE_COMMITMENTS',
    name: 'Airline SAF offtake agreements',
    type: 'market',
    current_state: 'Major airline offtake agreements signed (Lufthansa, Delta, KLM, IAG); volumes still small relative to mandated demand',
    threshold: 'Shell SAF book exceeds 1.5 Mt/yr contracted volume by end-2028',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names Lufthansa and Delta agreements. Airline contracted demand is the load-bearing offtake counterpart.',
    sources: 'Shell brief Section 04 (SAF offtake agreements)',
  },
  {
    id: 'SAF_BLENDING_INFRASTRUCTURE',
    name: 'Refinery SAF blending and HEFA production capacity',
    type: 'tech',
    current_state: 'Shell Pernis renewable fuels project online; Rotterdam HEFA capacity in commissioning',
    threshold: 'Shell operational SAF blending and HEFA capacity >=1 Mt/yr by end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 references blending operations via refinery network. Infrastructure capex is the capital commitment pivot SH-03 hypothesises Shell may exit.',
    sources: 'Shell brief Section 04; brief HYP SH-03 WNTBT (European SAF blending asset for sale signal)',
  },
  {
    id: 'IOC_CAPITAL_DISCIPLINE_PRESSURE',
    name: 'IOC capital discipline pressure on transition assets',
    type: 'market',
    current_state: 'Activist + institutional investor pressure for capital discipline across IOCs; Shell Wael Sawan publicly aligned with "fewer and better" capital allocation',
    threshold: 'Shell maintains "fewer and better" capital discipline mandate at 2026 Capital Markets Day without dilution',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'WNTBT from SH-03. Capital discipline pressure compresses transition asset capex including SAF, EV, hydrogen, threatening return profiles.',
    sources: 'Shell brief Section 02 (Strategy — selective retreat); brief HYP SH-03 WNTBT',
  },

  // --- Hydrogen (industrial blue + green NWE retreat) ---
  {
    id: 'BLUE_HYDROGEN_SMR_CCS_TECH',
    name: 'Blue hydrogen production via SMR with CCS at industrial scale',
    type: 'tech',
    current_state: 'SMR mature; CCS retrofit operating at multiple Shell refineries via Quest and adjacent infrastructure; capture rates 80-90% at integrated facilities',
    threshold: 'Blue H2 production cost <$2/kg at industrial scale (>50 kt/yr) with >=90% CO2 capture rate by 2028',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names Hydrogen as "retaining blue H2 capability". Refinery H2 network already operational; commercial economics depend on capture cost and 45Q-equivalent regimes.',
    sources: 'Shell brief Section 04 (Hydrogen — Industrial Scale)',
  },
  {
    id: 'INDUSTRIAL_H2_HARD_TO_ABATE_DEMAND',
    name: 'Industrial hydrogen demand from hard-to-abate sectors',
    type: 'market',
    current_state: 'Refinery H2 demand stable ~30 Mt/yr globally; ammonia ~35 Mt/yr; methanol ~12 Mt/yr — Shell\'s captive market',
    threshold: 'Hard-to-abate sector industrial H2 demand sustains >=80 Mt/yr globally through 2028',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 04 names "industrial H2 for hard-to-abate sectors remains core". Captive demand is structural, not transition-dependent.',
    sources: 'Shell brief Section 04 (Hydrogen — Industrial Scale)',
  },
  {
    id: 'PEM_ELECTROLYSIS_INDUSTRIAL_SCALE',
    name: 'PEM electrolyser at industrial scale',
    type: 'tech',
    current_state: 'TRL 8-9 component; TRL 7-8 system at >100MW; Holland Hydrogen 1 (200MW) commissioning. Cost-down trajectory tracking 10-20% per doubling per IRENA. Current quotes 1,400-1,800 EUR/kW vs target <1,000 EUR/kW.',
    threshold: 'PEM electrolyser stack CAPEX reaches <€1,000/kW at >100MW scale by 2028',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'Per /docs/WORKED_EXAMPLE_SHELL_H3.md Section 6.2 entity record. Cost trajectory exists but slow vs target. Holland Hydrogen 1 is genuinely commercial-scale but second-of-a-kind unproven.',
    sources: 'IRENA Hydrogen Cost Report 2024 (per worked example); Shell brief Section 04 (Hydrogen — green H2 ambitions scaled back)',
  },
  {
    id: 'EU_HYDROGEN_BANK',
    name: 'EU Hydrogen Bank funding mechanism',
    type: 'regulation',
    current_state: 'Round 1 awarded €720m at <€0.50/kg subsidy 2024; Round 2 announced 2025 at €1.2bn',
    threshold: 'Cumulative >€2bn awarded across Hydrogen Bank rounds by 2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Per worked example Section 7.3. EC framework committed; Round 2 announced. Political risk if EU budget tightens but currently on path.',
    sources: 'European Commission Hydrogen Bank disclosures (per worked example)',
  },
  {
    id: 'NW_EUROPE_INDUSTRIAL_H2_OFFTAKE_FIDS',
    name: 'NW European industrial hydrogen offtake FIDs',
    type: 'market',
    current_state: '<5 binding >50MW offtake agreements signed 2024; refineries lagging because cost gap to grey H2 remains material without sustained subsidy',
    threshold: '>15 offtake FIDs >=50MW each are signed in NW Europe by 2027',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'Per worked example Section 7.3. Offtake commitments lagging announcements; structural-pace concern for green H2 production capacity ramp.',
    sources: 'EU Innovation Fund award lists; Hydrogen Bank Round 1 results (per worked example)',
  },
  {
    id: 'NON_H2_DRI_THREAT',
    name: 'Direct reduced iron (DRI) without hydrogen as steel decarbonisation pathway',
    type: 'tech',
    current_state: 'TRL 5-6; pilot scale; commercial scale 2027-2030 contested. Boston Metal Series C; Electra commercial pilot.',
    threshold: 'Non-H2 DRI does NOT reach commercial scale before 2030',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'Per worked example Section 8.2. If Boston Metal or similar electrolytic iron technology reaches scale, the steel decarbonisation offtake market for green hydrogen narrows materially.',
    sources: 'Boston Metal Series C disclosures; Electra commercial pilot announcements (per worked example)',
  },

  // --- Namibia Orange Basin ---
  {
    id: 'NAMIBIA_ORANGE_BASIN_RESOURCE',
    name: 'Namibia Orange Basin oil resource and appraisal',
    type: 'tech',
    current_state: 'Multiple discoveries in Namibian Orange Basin announced 2022-2024 by TotalEnergies, Shell, Galp; estimated 2B+ boe technical resource per industry consensus',
    threshold: 'Shell+TotalEnergies-operated Orange Basin licence proves >1.5 bn boe commercial resource via FID by end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 06 S-01 names Shell 45% stake in TotalEnergies-operated licence; could be next Guyana for Shell production trajectory.',
    sources: 'Shell brief Section 06 S-01 (Namibia Orange Basin signal)',
  },
  {
    id: 'NAMIBIA_REGULATORY_FRAMEWORK',
    name: 'Namibian upstream regulatory and fiscal framework',
    type: 'regulation',
    current_state: 'Petroleum Act framework stable; ongoing negotiation between operators and government on local content and fiscal terms for major developments',
    threshold: 'Namibian fiscal regime maintains stability for FID-stage development through 2027',
    state: 'ambiguous',
    baseline_state: 'ambiguous',
    note: 'Brief is silent on Namibian regulatory specifics; ambiguous because government has signalled intent to revise local content rules but no major adverse changes published. Open question.',
    sources: 'Shell brief Section 06 S-01 (no specific regulatory commentary)',
  },
  {
    id: 'DEEPWATER_DRILLING_CAPACITY',
    name: 'Frontier deepwater drilling rig and supply chain capacity',
    type: 'ecosystem',
    current_state: 'Drillship day-rates $450-550k for ultra-deepwater 6th-gen rigs 2025; supply chain tightening with multiple frontier basins competing',
    threshold: 'Drillship availability sufficient for Orange Basin 2026-2027 appraisal campaign without >12 month delays',
    state: 'weakening',
    baseline_state: 'weakening',
    note: 'Tight rig market materially affects appraisal pace. Competition from Suriname, Guyana, Mozambique compounds.',
    sources: 'Shell brief Section 06 S-01 (Orange Basin signal context)',
  },

  // --- Chemicals to specialties pivot ---
  {
    id: 'COMMODITY_CRACKER_ECONOMICS',
    name: 'European commodity ethylene cracker economics',
    type: 'market',
    current_state: 'European cracker margins compressed 2024-2025 by feedstock cost (high gas) and weak demand; multiple shutdown announcements industry-wide',
    threshold: 'European cracker margins remain below long-term average through 2027 (sustaining shutdown rationale)',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 06 S-03 names "cracker economics are broken" as driver of Shell\'s pivot. Reverse trajectory would slow the divestment but underlying gas-cost-disadvantage structural.',
    sources: 'Shell brief Section 06 S-03 (Chemicals to Specialties Pivot signal); brief Section 02 (Chemicals pivot)',
  },
  {
    id: 'PERFORMANCE_CHEMICALS_DEMAND',
    name: 'Performance / specialty chemicals end-market demand',
    type: 'market',
    current_state: 'Adhesives, coatings, lubricant additives demand growing 3-5%/yr; margins materially better than commodity petchem',
    threshold: 'Specialty chemicals end-market demand sustains 3%+ growth through 2028 in Shell\'s target categories',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 06 S-03 names performance chemicals (adhesives, coatings, lubricant additives) as Shell\'s pivot target. End-market demand support is the buy-side of the strategic shift.',
    sources: 'Shell brief Section 06 S-03',
  },
  {
    id: 'SHELL_CHEMICALS_CAPITAL_REALLOCATION',
    name: 'Shell Chemicals capital reallocation from commodity to specialty',
    type: 'ecosystem',
    current_state: 'Refinery headcount cuts under way; specific cracker shutdown decisions pending; specialty chemicals capex line being built',
    threshold: 'Shell Chemicals capital allocation shifts >50% to specialty/performance product lines by end-2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Brief Section 02 explicitly names "Shell Chemicals pivoting to performance chemicals from commodity — cutting refinery headcount". Internal capital allocation pivot is the execution risk.',
    sources: 'Shell brief Section 02 (Chemicals strategy)',
  },
  {
    id: 'SPECIALTY_CHEMICALS_M_AND_A_MARKET',
    name: 'Specialty chemicals M&A acquisition market',
    type: 'market',
    current_state: 'Specialty chemicals deal multiples 10-14x EBITDA 2025; deal pipeline active across adhesives, coatings, additives',
    threshold: 'Specialty chemicals M&A deal flow sustains >50 transactions/yr at <12x median EBITDA through 2027',
    state: 'holding',
    baseline_state: 'holding',
    note: 'Bolt-on acquisitions are the natural pace mechanism for Shell\'s specialty pivot. Healthy deal market gives optionality; tight deal market with high multiples slows the pivot.',
    sources: 'Shell brief Section 06 S-03 (Chemicals to Specialties Pivot)',
  },
];

// ===========================================================================
// INITIATIVES
// ===========================================================================
const initiatives = [
  {
    id: 'SHELL_LNG_PORTFOLIO_DOMINANCE',
    name: 'NW European LNG portfolio dominance and EBITDA leadership',
    company: COMPANY,
    segment: 'Integrated Gas',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell's LNG portfolio will deliver more than 45% of group EBITDA by 2028, contingent on European import infrastructure expansion, sustained gas price floor, long-term offtake commitments, and EU regulatory permissibility for re-export operations.",
    time_horizon: '2028',
    decision_window: '2026-2027',
    decision_threshold: '>45% of group EBITDA from Integrated Gas / LNG portfolio in 2028 reporting',
    baseline_confidence: 0.550,
    current_confidence: 0.550,
    notes: "Baseline 0.550 reasoning: principal entity GLOBAL_LNG_DEMAND_TRAJECTORY holding; 4 of 5 enabling links holding; only US LNG oversupply external threat is weakening. Methodology section 9 heuristic 'all gating links holding' shifts toward 0.600; one weakening external threat shifts back ~0.05. Shell brief HYP SH-01 sets analyst confidence High at 76% probability — my baseline is more conservative because the 45% EBITDA target requires both numerator (LNG performance) AND denominator (other segments stable); brief focuses on numerator only. Sources: Shell brief Section 02; HYP SH-01.",
  },
  {
    id: 'SHELL_INDUSTRIAL_CCUS',
    name: 'Industrial CCUS services leadership (Quest + Northern Lights)',
    company: COMPANY,
    segment: 'Renewables & Energy Solutions',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell's selective CCUS investment will position it as the leading IOC in industrial decarbonisation services by 2030, generating more than $2bn annually, contingent on capture chemistry maturation, US/EU policy continuity, third-party customer pipeline conversion, and sustained capital deployment.",
    time_horizon: '2030',
    decision_window: '2026-2028',
    decision_threshold: '>$2bn annual revenue from industrial CCUS services by 2030',
    baseline_confidence: 0.450,
    current_confidence: 0.450,
    notes: "Baseline 0.450 reasoning: principal capture-tech entity holding but two key enabling links weakening (US 45Q political risk, third-party demand conversion lagging, CCUS capex deployment behind schedule). Methodology heuristic 'multiple gating/enabling links weakening → toward 0.400'; one principal holding pulls back to ~0.450. Shell brief HYP SH-02 sets analyst confidence Medium at 47% probability — my baseline aligns. Quest+Northern Lights merged into one initiative per methodology granularity heuristic: same dependency structure (capture tech + storage + customer demand + policy), different geographies. Sources: Shell brief Section 04 (Quest + Northern Lights); HYP SH-02; Section 06 S-04.",
  },
  {
    id: 'SHELL_RECHARGE_EV_NETWORK',
    name: 'Shell Recharge EV charging network as retail energy anchor',
    company: COMPANY,
    segment: 'Mobility',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell's EV charging network (Shell Recharge) will reach EBIT-positive operations across European primary markets by 2028, contingent on BEV fleet penetration, fast-charger utilisation rates, and continued capex cost-down on hardware.",
    time_horizon: '2028',
    decision_window: '2026-2027',
    decision_threshold: 'Shell Recharge European operations turn EBIT-positive at network level by 2028 reporting',
    baseline_confidence: 0.500,
    current_confidence: 0.500,
    notes: "Baseline 0.500 reasoning: all three enabling entities holding; no external threats with material weakening signal at v0; balanced position. Brief Section 04 names Recharge as a retained strategic bet (60% progress, scaling). Shell brief Section 02 distinguishes Recharge as 'genuinely strategic' versus the merchant wind exit. No specific FB hypothesis card on Recharge so falling back to default with mild positive bias for 'genuinely strategic' framing. Sources: Shell brief Section 04 (Shell Recharge — EV Network); Section 02 (Power transition).",
  },
  {
    id: 'SHELL_BRAZIL_DEEPWATER',
    name: 'Brazil deepwater portfolio sustained as cash flow pillar',
    company: COMPANY,
    segment: 'Upstream',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell's Brazilian deepwater portfolio (Lula-area, 25% stake) sustains as a cash flow pillar through 2030, contingent on Brazilian fiscal regime stability, deepwater unit-economics holding, and Brent price support.",
    time_horizon: '2030',
    decision_window: '2027-2028',
    decision_threshold: 'Lula-area share of Shell upstream EBITDA stays >15% through 2028',
    baseline_confidence: 0.600,
    current_confidence: 0.600,
    notes: "Baseline 0.600 reasoning: all three enabling links holding (regulatory stability, deepwater economics, Brent floor). Operationally mature asset (90% progress per brief), low CI/bbl positions it competitively on transition pressure. Methodology heuristic 'all enabling links holding alongside gating links holding' shifts toward 0.650; conservative discount for political/oil-price tail risk lands at 0.600. Sources: Shell brief Section 04 (Lula Field).",
  },
  {
    id: 'SHELL_SAF_PORTFOLIO',
    name: 'Sustainable aviation fuel (SAF) portfolio scaling toward 2030 mandate',
    company: COMPANY,
    segment: 'Mobility / Renewables & Energy Solutions',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell's SAF and biofuels portfolio will reach 10% of aviation fuel volume by 2030, contingent on EU SAF mandate continuity, airline offtake commitment growth, blending infrastructure capex execution, and IOC capital discipline pressure not forcing exit.",
    time_horizon: '2030',
    decision_window: '2026-2027',
    decision_threshold: 'Shell SAF/biofuels reach >=10% of aviation fuel volumes sold by 2030',
    baseline_confidence: 0.400,
    current_confidence: 0.400,
    notes: "Baseline 0.400 reasoning: three enabling links holding but capital-discipline pressure entity is weakening, and SH-03 hypothesis (Confidence High, 73%) is essentially a counter-hypothesis predicting Shell will EXIT biofuels. Methodology section 9 — when one analyst hypothesis directly counters the initiative success, baseline should reflect that asymmetric risk. Shifted from 0.500 default toward 0.400 to reflect the SH-03 counter-pressure. Sources: Shell brief Section 04 (SAF — Sustainable Aviation Fuel); brief HYP SH-03.",
  },
  {
    id: 'SHELL_INDUSTRIAL_BLUE_H2',
    name: 'Industrial blue hydrogen retention for hard-to-abate sectors',
    company: COMPANY,
    segment: 'Renewables & Energy Solutions',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell retains and grows industrial blue hydrogen capability for hard-to-abate sectors through 2030, contingent on SMR-with-CCS economics holding, captive industrial demand persisting, and CCUS-enabling regulation (45Q-style) continuing.",
    time_horizon: '2030',
    decision_window: '2026-2028',
    decision_threshold: 'Shell industrial blue H2 production capacity sustained >=200 kt/yr through 2030',
    baseline_confidence: 0.550,
    current_confidence: 0.550,
    notes: "Baseline 0.550 reasoning: principal blue-H2-tech entity holding; demand-side structural; only 45Q regulatory entity weakening. Aligns with brief framing 'retaining blue H2 capability' (Section 04). Distinct initiative from green H2 NW European retreat (next initiative) per methodology granularity — different dependency structure (CCUS+SMR vs PEM electrolysis). Sources: Shell brief Section 04 (Hydrogen — Industrial Scale); Section 02 (Selective Chemicals & Power Transition).",
  },
  {
    id: 'SHELL_H3_HYDROGEN_NWE',
    name: 'NW European green hydrogen production capacity (managed retreat)',
    company: COMPANY,
    segment: 'Renewables & Energy Solutions',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell's announced 2030 NW European green hydrogen production capacity (Holland Hydrogen 1 + REFHYNE II + NortH2 stake) is delivered within ±50% of stated targets, contingent on PEM electrolyser cost-down, NW European industrial offtake FID density, EU Hydrogen Bank funding, and absence of structural steel-decarbonisation alternative pathway maturation.",
    time_horizon: '2030',
    decision_window: '2027-2028',
    decision_threshold: 'NW European green H2 production capacity at 2030 within ±50% of currently-announced figures (band widened from worked-example ±25% to reflect brief signal of scaling-back ambitions)',
    baseline_confidence: 0.350,
    current_confidence: 0.350,
    notes: "Baseline 0.350 reasoning: three enabling links weakening (PEM cost-down lagging, NW European offtake FIDs sparse, non-H2 DRI threat progressing), only EU Hydrogen Bank holding. Methodology heuristic 'multiple gating links weakening → toward 0.400'; brief signal that Shell is 'scaling back green H2 ambitions' (Section 04) compounds. Worked example /docs/WORKED_EXAMPLE_SHELL_H3.md set baseline 0.450; my read is lower because brief signals retreat post-worked-example date. Decision threshold widened to ±50% from worked example's ±25% to reflect this. Sources: /docs/WORKED_EXAMPLE_SHELL_H3.md (entity records, claim format); Shell brief Section 04 (Hydrogen — green H2 ambitions scaled back).",
  },
  {
    id: 'SHELL_NAMIBIA_ORANGE_BASIN',
    name: 'Namibia Orange Basin commercial development (45% stake)',
    company: COMPANY,
    segment: 'Upstream',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell's 45% stake in Namibian Orange Basin licence reaches commercial FID by end-2027, contingent on resource appraisal validating >1.5 bn boe, Namibian fiscal regime remaining stable, and frontier deepwater rig availability not delaying campaign.",
    time_horizon: '2030',
    decision_window: '2026-2027',
    decision_threshold: 'Orange Basin development reaches FID by end-2027 with first oil targeted 2030',
    baseline_confidence: 0.500,
    current_confidence: 0.500,
    notes: "Baseline 0.500 reasoning: principal resource entity holding (multi-discovery confirmed), regulatory ambiguous (open question), drilling capacity weakening. Mixed picture — exploration-stage initiatives carry inherent uncertainty. Brief Section 06 S-01 ranks signal strength 9/10 with HIGH impact. Sources: Shell brief Section 06 S-01 (Namibia Orange Basin).",
  },
  {
    id: 'SHELL_CHEMICALS_SPECIALTIES',
    name: 'Shell Chemicals pivot from commodity to performance chemicals',
    company: COMPANY,
    segment: 'Chemicals',
    register: 'CLIENT_ACCOUNT',
    hypothesis_statement: "Shell Chemicals pivots capital allocation predominantly toward performance/specialty chemicals by end-2027, contingent on commodity cracker economics remaining unfavourable, specialty end-market demand sustaining, internal capital reallocation execution, and accessible bolt-on M&A market.",
    time_horizon: '2027',
    decision_window: '2025-2026',
    decision_threshold: 'Shell Chemicals capital allocation shifts >50% to specialty/performance product lines by end-2027 reporting',
    baseline_confidence: 0.600,
    current_confidence: 0.600,
    notes: "Baseline 0.600 reasoning: all four enabling links holding (cracker economics broken, specialty demand growing, capital reallocation underway, M&A market healthy). Brief Section 06 S-03 ranks signal strength 7/10 with HIGH impact. The pivot is internally consistent and externally enabled. Methodology heuristic 'all gating links holding' supports >0.500. Sources: Shell brief Section 02 (Chemicals strategy); Section 06 S-03.",
  },
];

// ===========================================================================
// LINKS
// ===========================================================================
function L(initId, entId, role, impact, criticality, claim, claim_basis) {
  return {
    id: `${initId}:${entId}`,
    initiative_id: initId,
    entity_id: entId,
    role, impact, criticality,
    claim, claim_basis,
  };
}

const links = [
  // SHELL_LNG_PORTFOLIO_DOMINANCE
  L('SHELL_LNG_PORTFOLIO_DOMINANCE','GLOBAL_LNG_DEMAND_TRAJECTORY','principal','neutral','gating',
    'Global LNG demand maintains >550 Mt/yr trajectory through 2028 with Europe sustaining >150 Mt/yr import dependency.',
    'The bet is fundamentally about LNG market structure persisting. If global demand peaks earlier than expected, the EBITDA leadership target is unattainable. Brief HYP SH-01 places this as the central system driver. Source: Shell brief Section 02; HYP SH-01.'),
  L('SHELL_LNG_PORTFOLIO_DOMINANCE','EU_LNG_IMPORT_INFRASTRUCTURE','enabling','neutral','gating',
    'EU LNG import capacity exceeds 200 bcm/yr by end-2026.',
    'Direct WNTBT bullet from SH-01. European import infrastructure determines whether Shell can deliver into the demand it has contracted. Gating because production-without-distribution leaves cargoes stranded. Source: brief HYP SH-01 WNTBT.'),
  L('SHELL_LNG_PORTFOLIO_DOMINANCE','LONG_TERM_LNG_OFFTAKE_AGREEMENTS','enabling','neutral','gating',
    '>=2 long-term LNG supply agreements (>=10 years duration) signed by Shell by end-2027.',
    'WNTBT from SH-01. Contracted volumes are the EBITDA stabiliser; without them Shell\'s LNG portfolio is exposed to spot pricing. Gating because the 45% EBITDA target requires growing contract base, not spot beats. Source: brief HYP SH-01 WNTBT.'),
  L('SHELL_LNG_PORTFOLIO_DOMINANCE','GAS_PRICE_FLOOR_TTF','enabling','neutral','enabling',
    'Sustained TTF gas price >$6/MMBtu through end-2027.',
    'WNTBT from SH-01. Material to economics, not gating because Shell LNG cost position is competitive enough to survive temporary dips. Source: brief HYP SH-01 WNTBT.'),
  L('SHELL_LNG_PORTFOLIO_DOMINANCE','EU_GAS_REGULATORY_FRAMEWORK','enabling','neutral','gating',
    'No EU regulatory disruption to Shell LNG re-export operations from EU ports through end-2027.',
    'WNTBT from SH-01. EU LNG re-export underpins Shell trading EBITDA. Loss of regulatory permissibility would force major restructuring. Gating because EU re-export profitability is structural to the trading book. Source: brief HYP SH-01 WNTBT + system drivers.'),
  L('SHELL_LNG_PORTFOLIO_DOMINANCE','ASIA_PACIFIC_LNG_DEMAND','enabling','neutral','enabling',
    'Asia-Pacific LNG demand sustains >290 Mt/yr through 2028.',
    'Half of Shell LNG portfolio targets Asia-Pacific. Demand-side stability matters but trading optionality lets Shell redirect cargoes between basins, so not gating. Source: Shell brief Section 02.'),
  L('SHELL_LNG_PORTFOLIO_DOMINANCE','NORTH_AMERICAN_LNG_OVERSUPPLY','external','threatening','enabling',
    'US LNG net export additions stay below 30 Mt/yr through 2027 (avoiding oversupply flood).',
    'If US LNG over-builds, gas price floor breaks and Shell\'s spot trading EBITDA narrows. Threat is real but not initiative-killing — Shell has long-term contracts insulating ~50% of book; US oversupply hurts but does not kill the EBITDA target. Enabling-criticality not gating per methodology 3.3.3 special-case. Source: Shell brief Section 02 (peer landscape).'),

  // SHELL_INDUSTRIAL_CCUS
  L('SHELL_INDUSTRIAL_CCUS','INDUSTRIAL_CCUS_CAPTURE_TECH','principal','neutral','gating',
    'CCUS capture cost reaches <$80/tCO2 at industrial scale (>1 Mt/yr) demonstrated commercially by 2027.',
    'The bet is fundamentally about industrial CCUS as a packaged service. Capture chemistry economics determine whether the service offering generates margin or eats it. Brief HYP SH-02 names Technology as a SIGNAL driver. Source: brief Section 04 (Quest, Northern Lights); HYP SH-02 system drivers.'),
  L('SHELL_INDUSTRIAL_CCUS','INDUSTRIAL_DECARBONISATION_SERVICES_DEMAND','enabling','neutral','gating',
    '>=1 third-party industrial commercial CCUS service contract signed with Shell by end-2026.',
    'WNTBT from SH-02 + signal S-04 (Carbon Capture as a Service). Demand-side proof point for the services revenue model. Gating because $2bn revenue target requires conversions; current pipeline thin. Source: brief HYP SH-02 WNTBT + Section 06 S-04.'),
  L('SHELL_INDUSTRIAL_CCUS','US_45Q_TAX_CREDIT','enabling','neutral','gating',
    'US 45Q tax credit (or economically equivalent regime) survives 2026 budget reconciliation intact.',
    'WNTBT from SH-02. Underpins Quest economics and Shell US CCUS pipeline. Gating because Shell\'s US CCUS economics depend on the credit; collapse would force re-evaluation of Quest expansion. Source: brief HYP SH-02 WNTBT + system drivers.'),
  L('SHELL_INDUSTRIAL_CCUS','NORTH_SEA_CO2_STORAGE_CAPACITY','enabling','neutral','enabling',
    'North Sea operational CO2 injection capacity exceeds 5 Mt/yr by end-2027.',
    'Storage capacity is the structural bottleneck for European industrial CCUS scaling. Northern Lights expansion underpins Shell\'s European service offering; alternative storage providers exist so not gating. Source: brief Section 04 (Northern Lights JV).'),
  L('SHELL_INDUSTRIAL_CCUS','CCUS_CAPEX_DEPLOYMENT','enabling','neutral','enabling',
    'Shell deploys >$1.5bn cumulative CCUS capex by end-2027.',
    'WNTBT from SH-02. Internal capital commitment signals Shell willingness to scale CCUS as a service business. Currently lagging stated ambition; material to the scaling pace but not a single point of failure. Source: brief HYP SH-02 WNTBT.'),

  // SHELL_RECHARGE_EV_NETWORK
  L('SHELL_RECHARGE_EV_NETWORK','EV_PUBLIC_CHARGING_DEMAND','principal','neutral','gating',
    'Average public DC fast-charger utilisation reaches >25% across Shell Recharge sites by end-2028.',
    'The bet is fundamentally about retail-energy charging economics scaling. Utilisation is the load-bearing variable for unit economics. Source: Shell brief Section 04 (Shell Recharge target 500k+ charge points).'),
  L('SHELL_RECHARGE_EV_NETWORK','BEV_FLEET_PENETRATION_EUROPE','enabling','neutral','enabling',
    'BEV fleet share exceeds 20% in Shell Recharge primary markets (UK, NL, DE) by end-2028.',
    'Demand-side driver for utilisation. EU 2035 ICE phase-out underpins trajectory. Material to economics but not single-point-of-failure as Shell can adjust site density to fleet demand. Source: brief Section 02 (Power transition).'),
  L('SHELL_RECHARGE_EV_NETWORK','EV_CHARGING_HARDWARE_CAPEX','enabling','neutral','enabling',
    'DC fast-charger installed capex falls below €80k per stall at >=150kW by end-2027.',
    'Capex trajectory determines whether Shell Recharge can hit EBIT-positive economics at moderate utilisation. Hardware cost-down depends on competitive supplier market (ABB, Tritium, Kempower). Source: brief Section 04.'),

  // SHELL_BRAZIL_DEEPWATER
  L('SHELL_BRAZIL_DEEPWATER','DEEPWATER_PRODUCTION_ECONOMICS','principal','neutral','gating',
    'Lula-area unit economics maintain <$40/bbl break-even through 2030.',
    'The bet is fundamentally about deepwater pre-salt unit economics holding. If break-even rises materially the cash-flow-pillar framing breaks. Source: Shell brief Section 04 (Lula low CI/bbl).'),
  L('SHELL_BRAZIL_DEEPWATER','BRAZIL_DEEPWATER_REGULATORY_REGIME','enabling','neutral','gating',
    'No material adverse change in Brazilian fiscal/royalty regime for pre-salt operations through end-2030.',
    'Brazilian fiscal regime stability underpins Lula-area economics. Pre-salt has been politically bipartisan but electoral cycle risk persists. Gating because adverse fiscal change would compress the cash flow pillar materially. Source: brief Section 04.'),
  L('SHELL_BRAZIL_DEEPWATER','OIL_PRICE_BRENT','enabling','neutral','enabling',
    'Brent crude price sustains >$60/bbl through end-2028.',
    'Underpins economics across all Shell upstream initiatives. Lula\'s low break-even gives Shell substantial downside cushion so not gating; matters but not load-bearing. Source: brief Section 05 outlook scenarios.'),

  // SHELL_SAF_PORTFOLIO
  L('SHELL_SAF_PORTFOLIO','EU_SAF_MANDATE','principal','neutral','gating',
    'EU SAF mandate trajectory maintained at >=6% blending by 2030 without dilution.',
    'The bet is fundamentally about regulated demand pull. Mandate dilution would collapse offtake economics. Gating per the standard policy-driven-demand pattern. Source: Shell brief Section 04; HYP SH-03 system drivers.'),
  L('SHELL_SAF_PORTFOLIO','SAF_OFFTAKE_AIRLINE_COMMITMENTS','enabling','neutral','gating',
    'Shell SAF book exceeds 1.5 Mt/yr contracted volume by end-2028.',
    'Airline contracted demand is the load-bearing offtake counterpart to regulated mandate. Gating because production capex needs contracted demand to underwrite. Source: brief Section 04 (Lufthansa, Delta agreements).'),
  L('SHELL_SAF_PORTFOLIO','SAF_BLENDING_INFRASTRUCTURE','enabling','neutral','enabling',
    'Shell operational SAF blending and HEFA capacity reaches >=1 Mt/yr by end-2027.',
    'Internal supply infrastructure is execution risk. Brief HYP SH-03 hypothesises Shell may divest blending infrastructure ahead of mandate ramp; this entity is the contested asset. Source: brief Section 04; HYP SH-03 WNTBT.'),
  L('SHELL_SAF_PORTFOLIO','IOC_CAPITAL_DISCIPLINE_PRESSURE','external','threatening','gating',
    'Shell maintains "fewer and better" capital discipline mandate at 2026 Capital Markets Day without dilution-of-SAF-capex.',
    'WNTBT from SH-03 hypothesises capital discipline pressure will force SAF exit. Gating per methodology 3.3.3 — if capital discipline mandates SAF divestment, the initiative ends regardless of demand-side dynamics. External-threatening because the threat is internal-capital-allocation rationale, not SAF-specific. Source: brief HYP SH-03 WNTBT.'),

  // SHELL_INDUSTRIAL_BLUE_H2
  L('SHELL_INDUSTRIAL_BLUE_H2','BLUE_HYDROGEN_SMR_CCS_TECH','principal','neutral','gating',
    'Blue H2 production cost reaches <$2/kg at industrial scale (>50 kt/yr) with >=90% CO2 capture rate by 2028.',
    'The bet is fundamentally about SMR-with-CCS economics being competitive in industrial H2 markets. Source: Shell brief Section 04 (Hydrogen — Industrial Scale).'),
  L('SHELL_INDUSTRIAL_BLUE_H2','INDUSTRIAL_H2_HARD_TO_ABATE_DEMAND','enabling','neutral','gating',
    'Hard-to-abate sector industrial H2 demand sustains >=80 Mt/yr globally through 2028.',
    'Captive-customer demand is structural and gating; without it the blue H2 capability has no commercial home. Source: brief Section 04.'),
  L('SHELL_INDUSTRIAL_BLUE_H2','US_45Q_TAX_CREDIT','enabling','neutral','enabling',
    'US 45Q tax credit (or economically equivalent regime) survives 2026 budget reconciliation intact.',
    'Industrial blue H2 economics in the US depend on capture-side credit. Material but not gating because Shell can prioritise European blue H2 routes if US economics break. Source: shared with SHELL_INDUSTRIAL_CCUS via SH-02.'),
  L('SHELL_INDUSTRIAL_BLUE_H2','INDUSTRIAL_CCUS_CAPTURE_TECH','enabling','neutral','enabling',
    'CCUS capture cost reaches <$80/tCO2 at industrial scale (>1 Mt/yr) demonstrated commercially by 2027.',
    'Blue H2 economics depend on capture cost. Shared dependency with industrial CCUS initiative; entity reused. Source: brief Section 04.'),

  // SHELL_H3_HYDROGEN_NWE
  L('SHELL_H3_HYDROGEN_NWE','PEM_ELECTROLYSIS_INDUSTRIAL_SCALE','principal','neutral','gating',
    'PEM electrolyser stack CAPEX reaches <€1,000/kW at >100MW scale by 2028.',
    'Per worked example Section 9.1. Without this CAPEX trajectory Holland Hydrogen 1 follow-on and REFHYNE II don\'t reach FID. Gating because failure here kills the initiative regardless of policy support. Source: /docs/WORKED_EXAMPLE_SHELL_H3.md; brief Section 04.'),
  L('SHELL_H3_HYDROGEN_NWE','NW_EUROPE_INDUSTRIAL_H2_OFFTAKE_FIDS','enabling','neutral','gating',
    '>15 offtake FIDs >=50MW each are signed in NW Europe by 2027.',
    'Per worked example Section 9.2. Production capacity without offtake is stranded asset. Source: /docs/WORKED_EXAMPLE_SHELL_H3.md.'),
  L('SHELL_H3_HYDROGEN_NWE','EU_HYDROGEN_BANK','enabling','neutral','enabling',
    'Cumulative >€2bn awarded across EU Hydrogen Bank rounds by 2027.',
    'Per worked example Section 9.2. Subsidy closes the cost gap to fossil hydrogen during cost-down period. Material but not single-point-of-failure. Source: /docs/WORKED_EXAMPLE_SHELL_H3.md.'),
  L('SHELL_H3_HYDROGEN_NWE','NON_H2_DRI_THREAT','external','threatening','gating',
    'Non-H2 DRI does NOT reach commercial scale before 2030.',
    'Per worked example Section 9.3. If Boston Metal or similar electrolytic iron technology reaches scale, the steel decarbonisation offtake market for green hydrogen narrows materially. Gating per the special-case external-threatening logic. Source: /docs/WORKED_EXAMPLE_SHELL_H3.md.'),

  // SHELL_NAMIBIA_ORANGE_BASIN
  L('SHELL_NAMIBIA_ORANGE_BASIN','NAMIBIA_ORANGE_BASIN_RESOURCE','principal','neutral','gating',
    'Shell+TotalEnergies-operated Orange Basin licence proves >1.5 bn boe commercial resource via FID by end-2027.',
    'The bet is fundamentally about appraisal validating the discovered resource at commercial scale. Brief Section 06 S-01 ranks signal strength 9/10 with HIGH impact. Source: brief Section 06 S-01.'),
  L('SHELL_NAMIBIA_ORANGE_BASIN','NAMIBIA_REGULATORY_FRAMEWORK','enabling','neutral','enabling',
    'Namibian fiscal regime maintains stability for FID-stage development through 2027.',
    'Brief is silent on Namibian regulatory specifics; ambiguous state recorded. If government revises local content or fiscal terms materially, FID timeline slips. Source: brief Section 06 S-01.'),
  L('SHELL_NAMIBIA_ORANGE_BASIN','OIL_PRICE_BRENT','enabling','neutral','enabling',
    'Brent crude price sustains >$60/bbl through end-2028.',
    'Underpins Orange Basin appraisal economics. Same shared entity as SHELL_BRAZIL_DEEPWATER. Source: brief Section 05 outlook.'),
  L('SHELL_NAMIBIA_ORANGE_BASIN','DEEPWATER_DRILLING_CAPACITY','enabling','neutral','enabling',
    'Drillship availability sufficient for Orange Basin 2026-2027 appraisal campaign without >12 month delays.',
    'Tight rig market materially affects appraisal pace. Competition from Suriname/Guyana/Mozambique compounds. Material to schedule but not initiative-killing. Source: brief Section 06 S-01 context.'),

  // SHELL_CHEMICALS_SPECIALTIES
  L('SHELL_CHEMICALS_SPECIALTIES','SHELL_CHEMICALS_CAPITAL_REALLOCATION','principal','neutral','gating',
    'Shell Chemicals capital allocation shifts >50% to specialty/performance product lines by end-2027.',
    'The bet is fundamentally about internal capital reallocation execution. Brief Section 02 explicitly names the pivot underway. Source: brief Section 02.'),
  L('SHELL_CHEMICALS_SPECIALTIES','COMMODITY_CRACKER_ECONOMICS','enabling','neutral','enabling',
    'European cracker margins remain below long-term average through 2027 (sustaining shutdown rationale).',
    'Brief Section 06 S-03 names "cracker economics are broken" as the structural driver of the pivot. If margins recover, divestment rationale weakens. Source: brief Section 06 S-03.'),
  L('SHELL_CHEMICALS_SPECIALTIES','PERFORMANCE_CHEMICALS_DEMAND','enabling','neutral','enabling',
    'Specialty chemicals end-market demand sustains 3%+ growth through 2028 in Shell\'s target categories.',
    'Buy-side of the strategic shift. Demand growth supports the margin uplift thesis. Source: brief Section 06 S-03.'),
  L('SHELL_CHEMICALS_SPECIALTIES','SPECIALTY_CHEMICALS_M_AND_A_MARKET','enabling','neutral','enabling',
    'Specialty chemicals M&A deal flow sustains >50 transactions/yr at <12x median EBITDA through 2027.',
    'Bolt-on acquisitions are the natural pace mechanism. Tight deal market with high multiples slows pivot. Source: brief Section 06 S-03 context.'),
];

// ===========================================================================
// EXECUTE
// ===========================================================================
const dryRun = !process.argv.includes('--commit');
const overlap = await reportCatalogueOverlap(COMPANY);
console.log(`Catalogue state pre-population: ${overlap.existing_entities} entities`);
console.log(`Population scope: ${initiatives.length} initiatives, ${entities.length} entities, ${links.length} links`);
console.log('');

const result = await insertAll({ initiatives, entities, links, dryRun });

console.log('');
console.log('=== Summary ===');
const passed = result.gateResults.filter((g) => g.pass).length;
console.log(`Initiatives passed step 10: ${passed}/${result.gateResults.length}`);
console.log(`Mode: ${dryRun ? 'DRY-RUN' : 'COMMIT'}`);
